export const siteConfig = {
  name: "LaMadeleine Agadir",
  tagline: "Artisan Bakery & Coffee House",
  description:
    "Handcrafted pastries, artisan bread, and exceptional coffee — an authentic French & Moroccan bakery experience since 2019.",
  phone: "05.28.26.43.44",
  email: "contact@lamadeleine.ma",
  address: "Av. Al Oulfa, Tilila, Agadir 80000",
  social: {
    instagram: "https://instagram.com/lamadeleine.agadir",
    facebook: "https://facebook.com/lamadeleine.agadir",
  },
  hours: [{ day: "Monday — Sunday", time: "6:00 AM — 10:00 PM" }],
};

export const heroSlides = [
  {
    id: 1,
    title: "CHOCO PASTRY",
    subtitle: "Delicious",
    image: "/images/slider/slide-1/slide-1-image.webp",
    bgText: "/images/slider/slide-1/slide-1-bg.webp",
    bgIcon: "/images/slider/slide-1/slide-1-bg-icon.webp",
    products: [
      {
        title: "CHOCOLATE",
        description:
          "Rich dark chocolate pastry with Belgian chocolate and flaky dough.",
        icon: "/images/slider/slide-1/slide-1-product-1.webp",
      },
      {
        title: "SWEET CLASSICS",
        description:
          "Fresh croissants, éclairs, and tarts baked daily with premium ingredients.",
        icon: "/images/slider/slide-1/slide-1-product-2.webp",
      },
    ],
  },
  {
    id: 2,
    title: "NICE BIG BUNS.",
    subtitle: "Delicious",
    image: "/images/slider/slide-2/slide-2-image.webp",
    bgText: "/images/slider/slide-2/slide-2-bg.webp",
    bgIcon: "/images/slider/slide-2/slide-2-bg-icon.webp",
    products: [
      {
        title: "BAKE THE VERY BEST",
        description: "Freshly baked daily with a crisp, golden crust.",
        icon: "/images/slider/slide-2/slide-2-product-1.webp",
      },
      {
        title: "UNSPEAKABLY GOOD",
        description: "Rich, buttery buns with a melt-in-your-mouth texture.",
        icon: "/images/slider/slide-2/slide-2-product-2.webp",
      },
    ],
  },
  {
    id: 3,
    title: "SANDWICHES",
    subtitle: "Delicious",
    image: "/images/slider/slide-3/slide-3-image.webp",
    bgText: "/images/slider/slide-3/slide-3-bg.webp",
    bgIcon: "/images/slider/slide-3/slide-3-bg-icon.webp",
    products: [
      {
        title: "BREAKFAST",
        description: "Savory breakfast sandwiches.",
        icon: "/images/slider/slide-3/slide-3-product-1.webp",
      },
      {
        title: "HEALTHY SNACK",
        description: "Fresh fruit & yogurt parfaits.",
        icon: "/images/slider/slide-3/slide-3-product-2.webp",
      },
    ],
  },
];

export const categories = [
  {
    id: 1,
    name: "Breakfast",
    description: "Start your day the Moroccan way",
    icon: "sunrise",
    image: "/images/cat-breakfast.webp",
  },
  {
    id: 2,
    name: "Artisan Bread",
    description: "Traditional French & Moroccan breads",
    icon: "wheat",
    image: "/images/cat-bread.webp",
  },
  {
    id: 3,
    name: "Desserts",
    description: "Indulgent sweet creations",
    icon: "cherry",
    image: "/images/cat-desserts.webp",
  },
  {
    id: 4,
    name: "Coffee",
    description: "Expertly brewed & roasted",
    icon: "coffee",
    image: "/images/cat-coffee.webp",
  },
  {
    id: 5,
    name: "Pastries",
    description: "Delicate French & Moroccan pâtisserie",
    icon: "cake",
    image: "/images/cat-pastries.webp",
  },
  {
    id: 6,
    name: "Sandwiches",
    description: "Fresh, handmade & delicious",
    icon: "sandwich",
    image: "/images/cat-sandwiches.webp",
  },
];

type TodaysSpecial = {
  id: number;
  name: string;
  category: string;
  description: string;
  price: number;
  image: string;
};

export const todaysSpecials: TodaysSpecial[] = [
  {
    id: 1,
    name: "Pain au Chocolat",
    category: "Pastry",
    description:
      "Buttery, flaky layers wrapped around two bars of premium dark chocolate — the quintessential French breakfast pastry.",
    price: 2.5,
    image: "/images/today-specials/today-3.webp",
  },
  {
    id: 2,
    name: "Butter Croissant",
    category: "Breakfast",
    description:
      "Golden, impossibly light croissant made with 84% fat Norman butter. 72-hour ferment for perfect lamination.",
    price: 2.5,
    image: "/images/today-specials/today-1.webp",
  },
  {
    id: 3,
    name: "Croissant Sandwich",
    category: "Breakfast",
    description:
      "A classic French breakfast pastry filled with a rich, buttery cream and finished with a light dusting of powdered sugar.",
    price: 5,
    image: "/images/today-specials/today-2.webp",
  },
  {
    id: 4,
    name: "Fruit Tart",
    category: "Dessert",
    description:
      "Seasonal fruits arranged on vanilla pastry cream, nestled in a crisp, caramelized tart shell.",
    price: 7,
    image: "/images/today-specials/today-4.webp",
  },
  {
    id: 5,
    name: "Almond Mille-Feuille",
    category: "Dessert",
    description:
      "Three layers of caramelized puff pastry alternating with a light, almond cream, topped with toasted almond flakes and a dusting of powdered sugar.",
    price: 10,
    image: "/images/today-specials/today-5.webp",
  },
  {
    id: 6,
    name: "MadLine Signature Cortado",
    category: "Coffee",
    description:
      "Equal parts intensely rich espresso and perfectly textured steamed milk, dusted with a hint of warm spices.",
    price: 12,
    image: "/images/today-specials/today-6.webp",
  },
];

export const coffeeMenu = [
  {
    id: 1,
    name: "Mocha",
    description: "Espresso combined with chocolate and steamed milk.",
    price: 18.0,
    icon: "Cookie",
  },
  {
    id: 2,
    name: "Cappuccino",
    description: "Espresso topped with equal parts steamed milk and foam.",
    price: 15.0,
    icon: "Milk",
  },
  {
    id: 3,
    name: "Coffee on the Side",
    description: "Espresso served with a separate side of milk.",
    price: 15.0,
    icon: "Coffee",
  },
  {
    id: 4,
    name: "Cortado",
    description: "Equal parts espresso and steamed milk.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 5,
    name: "Cream Coffee",
    description: "Espresso mixed with steamed cream.",
    price: 12.0,
    icon: "Cookie",
  },
  {
    id: 6,
    name: "Double Espresso",
    description: "Two rich shots of intense espresso.",
    price: 18.0,
    icon: "Droplets",
  },
  {
    id: 7,
    name: "Espresso",
    description: "Rich and intense shot of coffee.",
    price: 12.0,
    icon: "Coffee",
  },
  {
    id: 8,
    name: "Flat White",
    description: "Espresso with micro-foamed milk.",
    price: 16.0,
    icon: "Milk",
  },
  {
    id: 9,
    name: "Illy Espresso",
    description: "Premium Italian Illy espresso shot.",
    price: 16.0,
    icon: "Sparkles",
  },
  {
    id: 10,
    name: "Latte Macchiato",
    description: "Steamed milk marked with a shot of espresso.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 11,
    name: "Americano",
    description: "Espresso diluted with hot water.",
    price: 14.0,
    icon: "Coffee",
  },
  {
    id: 12,
    name: "Nespresso Coffee",
    description: "Classic Nespresso brewed coffee.",
    price: 15.0,
    icon: "Coffee",
  },
];

export const menuCategories = [
  "Breakfast & Savory",
  "Pastries & Desserts",
  "Bakery",
  "Hot Drinks",
  "Cold Drinks",
  "Coffees",
  "Juices",
  "Extras",
];

export const menuItems = [
  // BREAKFAST & SAVORY
  {
    id: 1,
    name: "Barley Soup (Hesewa)",
    category: "Breakfast & Savory",
    description:
      "Warm and comforting traditional Moroccan barley and milk soup.",
    price: 7.0,
    popular: false,
    image: "/images/menu/Soup.webp",
  },
  {
    id: 2,
    name: "Cheese Omelet",
    category: "Breakfast & Savory",
    description:
      "Fluffy omelet loaded with melted cheese, served with olives and olive oil.",
    price: 16.0,
    popular: true,
    image: "/images/menu/Omelet.webp",
  },
  {
    id: 3,
    name: "Continental Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, cheese omelet, olive oil, olives, cheese, bread, yogurt, and water.",
    price: 35.0,
    popular: false,
    image: "/images/menu/breakfast.webp",
  },
  {
    id: 4,
    name: "Deli Meat Omelet",
    category: "Breakfast & Savory",
    description:
      "Omelet packed with cold cuts, served with olives and olive oil.",
    price: 17.0,
    popular: false,
    image: "/images/menu/Omelet.webp",
  },
  {
    id: 5,
    name: "Express Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, pastries, yogurt, and mineral water.",
    price: 26.0,
    popular: true,
    image: "/images/menu/breakfast.webp",
  },
  {
    id: 6,
    name: "Fassi Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, dried meat omelet, olive oil, olives, cheese, bread, yogurt, and water.",
    price: 37.0,
    popular: true,
    image: "/images/menu/breakfast.webp",
  },
  {
    id: 7,
    name: "Gourmet Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, olive oil, Amlou, olives, honey, bread, yogurt, and water.",
    price: 26.0,
    popular: false,
    image: "/images/menu/breakfast.webp",
  },
  {
    id: 8,
    name: "Harira Soup",
    category: "Breakfast & Savory",
    description:
      "Traditional hearty Moroccan tomato, lentil, and chickpea soup.",
    price: 10.0,
    popular: false,
    image: "/images/menu/Soup.webp",
  },
  {
    id: 9,
    name: "Khlii Omelet",
    category: "Breakfast & Savory",
    description:
      "Traditional omelet with Moroccan preserved meat, served with olives and olive oil.",
    price: 24.0,
    popular: true,
    image: "/images/menu/Omelet.webp",
  },
  {
    id: 10,
    name: "Kids Breakfast",
    category: "Breakfast & Savory",
    description:
      "Chocolate milk, orange juice, chocolate bread, vanilla cake, yogurt, and water.",
    price: 25.0,
    popular: false,
    image: "/images/menu/breakfast.webp",
  },
  {
    id: 11,
    name: "La Madeleine Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, choice of omelet, olive oil, olives, honey, cheese, Amlou, bread, crepe, chocolate, cake, yogurt, and water.",
    price: 55.0,
    popular: true,
    image: "/images/menu/breakfast.webp",
  },
  {
    id: 12,
    name: "Plain Omelet",
    category: "Breakfast & Savory",
    description: "Simple, fluffy egg omelet served with olives and olive oil.",
    price: 13.0,
    popular: true,
    image: "/images/menu/Omelet.webp",
  },
  {
    id: 13,
    name: "Soussi Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, Amlou, olive oil, cheese, olives, honey, jam, and water.",
    price: 38.0,
    popular: true,
    image: "/images/menu/breakfast.webp",
  },
  {
    id: 14,
    name: "Tomato Omelet",
    category: "Breakfast & Savory",
    description:
      "Fluffy omelet with fresh tomatoes, served with olives and olive oil.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Omelet.webp",
  },
  {
    id: 15,
    name: "Traditional Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, Moroccan pancakes, Harcha, honey, fresh cheese, and water.",
    price: 28.0,
    popular: true,
    image: "/images/menu/breakfast.webp",
  },

  // PASTRIES & DESSERTS
  {
    id: 16,
    name: "Seafood Cigar",
    category: "Pastries & Desserts",
    description: "Crispy rolled pastry filled with savory mixed seafood.",
    price: 12.0,
    popular: false,
    image: "/images/menu/Cigar.webp",
  },
  {
    id: 17,
    name: "Seafood Pastilla",
    category: "Pastries & Desserts",
    description:
      "Flaky savory pie filled with seasoned mixed seafood and vermicelli.",
    price: 12.0,
    popular: false,
    image: "/images/menu/pastilla.webp",
  },
  {
    id: 18,
    name: "Sandwich",
    category: "Pastries & Desserts",
    description: "Freshly made savory sandwich.",
    price: 8.0,
    popular: false,
    image: "/images/menu/sandwich.webp",
  },
  {
    id: 19,
    name: "Mini Pizza",
    category: "Pastries & Desserts",
    description:
      "Personal-sized savory pizza topped with cheese and tomato sauce.",
    price: 6.0,
    popular: false,
    image: "/images/menu/pizza.webp",
  },
  {
    id: 20,
    name: "Hot Dog Pastry",
    category: "Pastries & Desserts",
    description: "Savory sausage wrapped and baked in soft dough.",
    price: 9.0,
    popular: false,
    image: "/images/menu/hot-dog.webp",
  },
  {
    id: 21,
    name: "Chicken Pastilla",
    category: "Pastries & Desserts",
    description:
      "Sweet and savory pie filled with spiced chicken and toasted almonds.",
    price: 10.0,
    popular: false,
    image: "/images/menu/pastilla.webp",
  },
  {
    id: 22,
    name: "Cheese Briouat",
    category: "Pastries & Desserts",
    description: "Crispy Moroccan pastry triangles filled with savory cheese.",
    price: 7.0,
    popular: false,
    image: "/images/menu/Briouat.webp",
  },
  {
    id: 23,
    name: "Almond Tart",
    category: "Pastries & Desserts",
    description: "Crisp sweet pastry shell filled with dense almond cream.",
    price: 10.0,
    popular: false,
    image: "/images/menu/Tart.webp",
  },
  {
    id: 24,
    name: "Amlou Pancakes",
    category: "Pastries & Desserts",
    description: "Fluffy pancakes topped with traditional Moroccan Amlou.",
    price: 17.0,
    popular: false,
    image: "/images/menu/Pancakes.webp",
  },
  {
    id: 25,
    name: "Apple Turnover",
    category: "Pastries & Desserts",
    description: "Flaky puff pastry filled with sweet spiced apple compote.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Apple-Turnover.webp",
  },
  {
    id: 26,
    name: "Caramel Crepe",
    category: "Pastries & Desserts",
    description: "Thin French crepe folded with sweet caramel.",
    price: 16.0,
    popular: false,
    image: "/images/menu/crepe.webp",
  },
  {
    id: 27,
    name: "Caramel Waffle",
    category: "Pastries & Desserts",
    description: "Golden waffle topped with rich caramel sauce.",
    price: 16.0,
    popular: false,
    image: "/images/menu/waffle.webp",
  },
  {
    id: 28,
    name: "Chocolate Basbousa",
    category: "Pastries & Desserts",
    description: "Sweet semolina cake flavored with rich chocolate.",
    price: 8.0,
    popular: false,
    image: "/images/menu/basbousa.webp",
  },
  {
    id: 29,
    name: "Chocolate Madeleine",
    category: "Pastries & Desserts",
    description: "Small, shell-shaped sponge cake flavored with chocolate.",
    price: 2.5,
    popular: false,
    image: "/images/menu/madeleine.webp",
  },
  {
    id: 30,
    name: "Classic Crepe",
    category: "Pastries & Desserts",
    description: "Simple, thin, and soft French crepe.",
    price: 4.0,
    popular: false,
    image: "/images/menu/crepe.webp",
  },
  {
    id: 31,
    name: "Cream Cake Slice (10)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 10.0,
    popular: false,
    image: "/images/menu/strawberry-cake.webp",
  },
  {
    id: 32,
    name: "Cream Cake Slice (12)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 12.0,
    popular: false,
    image: "/images/menu/strawberry-cake.webp",
  },
  {
    id: 33,
    name: "Cream Cake Slice (13)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 13.0,
    popular: false,
    image: "/images/menu/strawberry-cake.webp",
  },
  {
    id: 34,
    name: "Cream Cake Slice (14)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 14.0,
    popular: false,
    image: "/images/menu/strawberry-cake.webp",
  },
  {
    id: 35,
    name: "Cream Cake Slice (15)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 15.0,
    popular: false,
    image: "/images/menu/strawberry-cake.webp",
  },
  {
    id: 36,
    name: "Cream Cake Slice (17)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 17.0,
    popular: false,
    image: "/images/menu/strawberry-cake.webp",
  },
  {
    id: 37,
    name: "Cream Cake Slice (18)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 18.0,
    popular: false,
    image: "/images/menu/strawberry-cake.webp",
  },
  {
    id: 38,
    name: "Donut",
    category: "Pastries & Desserts",
    description: "Soft, sweet, and classic fried dough ring.",
    price: 4.0,
    popular: false,
    image: "/images/menu/donut.webp",
  },
  {
    id: 39,
    name: "Frangipane Tart",
    category: "Pastries & Desserts",
    description: "Sweet pastry tart filled with rich almond cream.",
    price: 8.0,
    popular: false,
    image: "/images/menu/tart.webp",
  },
  {
    id: 40,
    name: "Fruit Pithiviers",
    category: "Pastries & Desserts",
    description: "Puff pastry pie filled with sweet fruit compote.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Pithiviers.webp",
  },
  {
    id: 41,
    name: "Fruit Salad with Orange Juice",
    category: "Pastries & Desserts",
    description: "Fresh seasonal fruits steeped in fresh orange juice.",
    price: 19.0,
    popular: false,
    image: "/images/menu/fruit-salad.webp",
  },
  {
    id: 42,
    name: "Fruit Salad with Yogurt",
    category: "Pastries & Desserts",
    description: "Fresh seasonal fruits mixed with creamy yogurt.",
    price: 18.0,
    popular: false,
    image: "/images/menu/fruit-salad.webp",
  },
  {
    id: 43,
    name: "Fruit Tartlet",
    category: "Pastries & Desserts",
    description: "Small, sweet tart crust filled with custard and fresh fruit.",
    price: 7.0,
    popular: false,
    image: "/images/menu/tartlet.webp",
  },
  {
    id: 44,
    name: "Honey Pancakes",
    category: "Pastries & Desserts",
    description: "Fluffy pancakes drizzled with pure honey.",
    price: 16.0,
    popular: false,
    image: "/images/menu/pancakes.webp",
  },
  {
    id: 45,
    name: "Large Pound Cake",
    category: "Pastries & Desserts",
    description: "Generously sized, buttery, and moist pound cake.",
    price: 30.0,
    popular: false,
    image: "/images/menu/pound-cake.webp",
  },
  {
    id: 46,
    name: "Medium Pound Cake",
    category: "Pastries & Desserts",
    description: "Classic moist and sweet pound cake.",
    price: 20.0,
    popular: false,
    image: "/images/menu/pound-cake.webp",
  },
  {
    id: 47,
    name: "Mille-Feuille",
    category: "Pastries & Desserts",
    description:
      "Classic French pastry with layers of puff pastry and vanilla cream.",
    price: 8.0,
    popular: false,
    image: "/images/menu/millefeuille.webp",
  },
  {
    id: 48,
    name: "Mini Cake",
    category: "Pastries & Desserts",
    description: "Small, moist, and sweet personal cake.",
    price: 7.0,
    popular: false,
    image: "/images/menu/minicake.webp",
  },
  {
    id: 49,
    name: "Mini Cupcake",
    category: "Pastries & Desserts",
    description: "Bite-sized fluffy cake with sweet frosting.",
    price: 4.0,
    popular: false,
    image: "/images/menu/cupcake.webp",
  },
  {
    id: 50,
    name: "Nutella & Banana Crepe",
    category: "Pastries & Desserts",
    description: "Crepe filled with Nutella and sliced bananas.",
    price: 23.0,
    popular: true,
    image: "/images/menu/crepe.webp",
  },
  {
    id: 51,
    name: "Nutella & Banana Pancakes",
    category: "Pastries & Desserts",
    description: "Pancakes served with Nutella and fresh bananas.",
    price: 26.0,
    popular: true,
    image: "/images/menu/pancakes.webp",
  },
  {
    id: 52,
    name: "Nutella & Banana Waffle",
    category: "Pastries & Desserts",
    description: "Waffle topped with Nutella and fresh banana slices.",
    price: 22.0,
    popular: true,
    image: "/images/menu/waffle.webp",
  },
  {
    id: 53,
    name: "Nutella & Oreo Crepe",
    category: "Pastries & Desserts",
    description: "Crepe filled with Nutella and crushed Oreo cookies.",
    price: 25.0,
    popular: true,
    image: "/images/menu/crepe.webp",
  },
  {
    id: 54,
    name: "Nutella & Seasonal Fruits Crepe",
    category: "Pastries & Desserts",
    description: "Crepe filled with Nutella and fresh seasonal fruits.",
    price: 29.0,
    popular: false,
    image: "/images/menu/crepe.webp",
  },
  {
    id: 55,
    name: "Nutella & Seasonal Fruits Waffle",
    category: "Pastries & Desserts",
    description: "Waffle with Nutella and fresh seasonal fruits.",
    price: 27.0,
    popular: false,
    image: "/images/menu/waffle.webp",
  },
  {
    id: 56,
    name: "Nutella Crepe",
    category: "Pastries & Desserts",
    description: "Classic thin crepe filled with warm Nutella.",
    price: 19.0,
    popular: true,
    image: "/images/menu/crepe.webp",
  },
  {
    id: 57,
    name: "Nutella Pancakes",
    category: "Pastries & Desserts",
    description: "Stack of fluffy pancakes layered with Nutella.",
    price: 21.0,
    popular: true,
    image: "/images/menu/pancakes.webp",
  },
  {
    id: 58,
    name: "Nutella Waffle",
    category: "Pastries & Desserts",
    description: "Golden waffle generously topped with Nutella.",
    price: 19.0,
    popular: true,
    image: "/images/menu/waffle.webp",
  },
  {
    id: 59,
    name: "Pithiviers",
    category: "Pastries & Desserts",
    description:
      "Round, enclosed pie made of puff pastry with a sweet filling.",
    price: 5.0,
    popular: false,
    image: "/images/menu/Pithiviers.webp",
  },
  {
    id: 60,
    name: "Raspberry Mini Cake",
    category: "Pastries & Desserts",
    description: "Small cake infused with sweet raspberry flavor.",
    price: 8.0,
    popular: false,
    image: "/images/menu/minicake.webp",
  },
  {
    id: 61,
    name: "Small Pound Cake",
    category: "Pastries & Desserts",
    description: "Personal-sized slice of moist pound cake.",
    price: 15.0,
    popular: false,
    image: "/images/menu/pound-cake.webp",
  },
  {
    id: 62,
    name: "Vanilla Basbousa",
    category: "Pastries & Desserts",
    description: "Classic sweet semolina cake soaked in vanilla syrup.",
    price: 6.0,
    popular: false,
    image: "/images/menu/basbousa.webp",
  },
  {
    id: 63,
    name: "Vanilla Madeleine",
    category: "Pastries & Desserts",
    description: "Classic, buttery, shell-shaped French sponge cake.",
    price: 1.5,
    popular: false,
    image: "/images/menu/madeleine.webp",
  },
  {
    id: 64,
    name: "Almond Croissant",
    category: "Pastries & Desserts",
    description:
      "Flaky croissant filled with almond cream and topped with sliced almonds.",
    price: 5.0,
    popular: false,
    image: "/images/menu/croissant.webp",
  },
  {
    id: 65,
    name: "Almond Triangle",
    category: "Pastries & Desserts",
    description:
      "Flaky, triangle-shaped pastry filled with sweet almond paste.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Triangle.webp",
  },
  {
    id: 66,
    name: "Chocolate Danish",
    category: "Pastries & Desserts",
    description: "Flaky Danish pastry swirled with rich chocolate.",
    price: 4.0,
    popular: false,
    image: "/images/menu/Danish.webp",
  },
  {
    id: 67,
    name: "Danish Pastry",
    category: "Pastries & Desserts",
    description: "Flaky, buttery, and sweet traditional Danish pastry.",
    price: 3.5,
    popular: false,
    image: "/images/menu/Danish.webp",
  },
  {
    id: 68,
    name: "Harcha",
    category: "Pastries & Desserts",
    description: "Traditional Moroccan pan-fried semolina flatbread.",
    price: 2.5,
    popular: false,
    image: "/images/menu/harcha.webp",
  },
  {
    id: 69,
    name: "Msemmen",
    category: "Pastries & Desserts",
    description: "Traditional Moroccan flaky, layered square flatbread.",
    price: 4.0,
    popular: false,
    image: "/images/menu/msemmen.webp",
  },
  {
    id: 70,
    name: "Olive Oil Harcha",
    category: "Pastries & Desserts",
    description: "Savory semolina flatbread prepared with rich olive oil.",
    price: 3.5,
    popular: false,
    image: "/images/menu/harcha.webp",
  },
  {
    id: 71,
    name: "Pain Suisse",
    category: "Pastries & Desserts",
    description:
      "Flaky pastry rolled with vanilla custard and chocolate chips.",
    price: 3.0,
    popular: false,
    image: "/images/menu/pain-suisse.webp",
  },
  {
    id: 72,
    name: "Pain au Chocolat / Croissant",
    category: "Pastries & Desserts",
    description: "Classic flaky and buttery French breakfast pastry.",
    price: 2.5,
    popular: false,
    image: "/images/menu/croissant.webp",
  },

  // BAKERY
  {
    id: 73,
    name: "Barley Bread",
    category: "Bakery",
    description: "Hearty and healthy Moroccan barley bread.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 74,
    name: "Batbout",
    category: "Bakery",
    description: "Moroccan soft and chewy pan-cooked flatbread.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 75,
    name: "Chocolate Brioche",
    category: "Bakery",
    description: "Soft and fluffy sweet bread filled with chocolate chips.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 76,
    name: "Classic Baguette",
    category: "Bakery",
    description: "Traditional crusty and soft French baguette.",
    price: 1.5,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 77,
    name: "Classic Bread",
    category: "Bakery",
    description: "Traditional Moroccan soft white round bread.",
    price: 1.5,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 78,
    name: "Classic Brioche",
    category: "Bakery",
    description: "Buttery, soft, and fluffy traditional sweet bread.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 79,
    name: "Corn Bread",
    category: "Bakery",
    description: "Rustic and flavorful Moroccan cornmeal bread.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 80,
    name: "Gingerbread",
    category: "Bakery",
    description: "Traditional French spiced bread with honey and anise.",
    price: 24.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 81,
    name: "Multigrain Baguette",
    category: "Bakery",
    description:
      "Crusty baguette baked with a blend of wholesome seeds and grains.",
    price: 4.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 82,
    name: "Olive Baguette",
    category: "Bakery",
    description: "Savory baguette baked with pieces of black and green olives.",
    price: 5.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 83,
    name: "Olive Bread",
    category: "Bakery",
    description: "Soft traditional round bread baked with savory olives.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 84,
    name: "Salt-Free Wheat Bread",
    category: "Bakery",
    description: "Healthy whole wheat bread prepared without added salt.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 85,
    name: "Semolina Baguette",
    category: "Bakery",
    description: "Baguette made with semolina flour for a rustic crunch.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 86,
    name: "Semolina Bread",
    category: "Bakery",
    description: "Traditional Moroccan round bread made with semolina.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 87,
    name: "Sesame Baguette",
    category: "Bakery",
    description:
      "Freshly baked crusty French baguette topped with sesame seeds.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 88,
    name: "Sesame Roll",
    category: "Bakery",
    description: "Soft bread roll generously topped with sesame seeds.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 89,
    name: "Viennese Baguette",
    category: "Bakery",
    description: "Soft, slightly sweet, and rich Viennese-style bread.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 90,
    name: "Whole Wheat Baguette",
    category: "Bakery",
    description: "Healthy and hearty whole wheat French baguette.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 91,
    name: "Whole Wheat Bread",
    category: "Bakery",
    description: "Nutritious traditional Moroccan whole wheat round bread.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.webp",
  },
  {
    id: 92,
    name: "Whole Wheat Roll",
    category: "Bakery",
    description: "Healthy and soft whole wheat bread roll.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.webp",
  },

  // HOT DRINKS
  {
    id: 93,
    name: "Black Tea (Lipton)",
    category: "Hot Drinks",
    description: "Classic Lipton black tea.",
    price: 12.0,
    popular: false,
    image: "/images/menu/tea.webp",
  },
  {
    id: 94,
    name: "Hot Chocolate",
    category: "Hot Drinks",
    description: "Warm and comforting milk with rich chocolate.",
    price: 12.0,
    popular: true,
    image: "/images/menu/hot-chocolate.webp",
  },
  {
    id: 95,
    name: "Hot Milk",
    category: "Hot Drinks",
    description: "Simple, comforting steamed milk.",
    price: 12.0,
    popular: false,
    image: "/images/menu/hot-milk.webp",
  },
  {
    id: 96,
    name: "Lemon Verbena Tea",
    category: "Hot Drinks",
    description: "Herbal tea made with natural lemon verbena leaves.",
    price: 12.0,
    popular: false,
    image: "/images/menu/tea.webp",
  },
  {
    id: 97,
    name: "Milk Tea (Lipton)",
    category: "Hot Drinks",
    description: "Classic Lipton black tea brewed with milk.",
    price: 12.0,
    popular: false,
    image: "/images/menu/milk-tea.webp",
  },
  {
    id: 98,
    name: "Milk with Lemon Verbena",
    category: "Hot Drinks",
    description: "Warm milk infused with soothing lemon verbena.",
    price: 12.0,
    popular: false,
    image: "/images/menu/milk-tea.webp",
  },
  {
    id: 99,
    name: "Milk with Syrup",
    category: "Hot Drinks",
    description: "Cold or warm milk flavored with sweet syrup.",
    price: 11.0,
    popular: false,
    image: "/images/menu/hot-milk.webp",
  },
  {
    id: 100,
    name: "Moroccan Mint Tea",
    category: "Hot Drinks",
    description: "Traditional green tea brewed with fresh mint.",
    price: 11.0,
    popular: true,
    image: "/images/menu/teapot.webp",
  },

  // COLD DRINKS
  {
    id: 101,
    name: "Affogato",
    category: "Cold Drinks",
    description: "A scoop of vanilla ice cream drowned in hot espresso.",
    price: 18.0,
    popular: false,
    image: "/images/menu/Affogato.webp",
  },
  {
    id: 102,
    name: "Banana Milkshake",
    category: "Cold Drinks",
    description: "Sweet and creamy banana shake.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milk-shake.webp",
  },
  {
    id: 103,
    name: "Banana Smoothie",
    category: "Cold Drinks",
    description: "Creamy blended banana smoothie.",
    price: 23.0,
    popular: false,
    image: "/images/menu/Smoothie.webp",
  },
  {
    id: 104,
    name: "Blue Mojito",
    category: "Cold Drinks",
    description: "Citrus and mint mocktail with blue curaçao syrup.",
    price: 22.0,
    popular: false,
    image: "/images/menu/Mojito.webp",
  },
  {
    id: 105,
    name: "Choice of Soda (35cl)",
    category: "Cold Drinks",
    description: "Selection of refreshing carbonated beverages.",
    price: 12.0,
    popular: true,
    image: "/images/menu/Soda.webp",
  },
  {
    id: 106,
    name: "Chocolate Milkshake",
    category: "Cold Drinks",
    description: "Rich and creamy chocolate shake.",
    price: 23.0,
    popular: true,
    image: "/images/menu/milk-shake.webp",
  },
  {
    id: 107,
    name: "Exotic Cocktail",
    category: "Cold Drinks",
    description: "Blended mango, orange, and pineapple.",
    price: 21.0,
    popular: true,
    image: "/images/menu/Cocktail.webp",
  },
  {
    id: 108,
    name: "Exotic Smoothie",
    category: "Cold Drinks",
    description: "Refreshing blend of tropical fruits.",
    price: 26.0,
    popular: false,
    image: "/images/menu/Smoothie.webp",
  },
  {
    id: 109,
    name: "Iced Caramel Macchiato",
    category: "Cold Drinks",
    description: "Iced milk and espresso, flavored with vanilla and caramel.",
    price: 21.0,
    popular: true,
    image: "/images/menu/iced-caramel.webp",
  },
  {
    id: 110,
    name: "Iced Coffee",
    category: "Cold Drinks",
    description: "Chilled coffee over ice with choice of flavor.",
    price: 18.0,
    popular: false,
    image: "/images/menu/iced-coffee.webp",
  },
  {
    id: 111,
    name: "Iced Frappuccino",
    category: "Cold Drinks",
    description:
      "Blended iced coffee drink with choice of vanilla, chocolate, or caramel.",
    price: 21.0,
    popular: true,
    image: "/images/menu/iced-frappuccino.webp",
  },
  {
    id: 112,
    name: "Iced Latte",
    category: "Cold Drinks",
    description: "Espresso and chilled milk over ice.",
    price: 19.0,
    popular: true,
    image: "/images/menu/Iced-Latte.webp",
  },
  {
    id: 113,
    name: "Iced Mocha",
    category: "Cold Drinks",
    description: "Iced espresso with chocolate and milk.",
    price: 19.0,
    popular: true,
    image: "/images/menu/iced-mocha.webp",
  },
  {
    id: 114,
    name: "Mango Smoothie",
    category: "Cold Drinks",
    description: "Tropical blended mango smoothie.",
    price: 23.0,
    popular: true,
    image: "/images/menu/smoothie.webp",
  },
  {
    id: 115,
    name: "Mineral Water (33cl)",
    category: "Cold Drinks",
    description: "Small bottle of still mineral water.",
    price: 5.0,
    popular: false,
    image: "/images/menu/Water.webp",
  },
  {
    id: 116,
    name: "Mineral Water (50cl)",
    category: "Cold Drinks",
    description: "Medium bottle of still mineral water.",
    price: 7.0,
    popular: true,
    image: "/images/menu/Water.webp",
  },
  {
    id: 117,
    name: "Oreo Milkshake",
    category: "Cold Drinks",
    description: "Creamy vanilla shake blended with Oreo cookies.",
    price: 26.0,
    popular: true,
    image: "/images/menu/milk-shake.webp",
  },
  {
    id: 118,
    name: "Oriental Cocktail",
    category: "Cold Drinks",
    description: "Blended banana, apple, and orange.",
    price: 20.0,
    popular: false,
    image: "/images/menu/Cocktail.webp",
  },
  {
    id: 119,
    name: "Red Mojito",
    category: "Cold Drinks",
    description: "Fruity red berry mocktail with mint and lime.",
    price: 22.0,
    popular: false,
    image: "/images/menu/Mojito.webp",
  },
  {
    id: 120,
    name: "Strawberry Milkshake",
    category: "Cold Drinks",
    description: "Sweet and creamy strawberry shake.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milk-shake.webp",
  },
  {
    id: 121,
    name: "Strawberry Smoothie",
    category: "Cold Drinks",
    description: "Blended fresh strawberries and yogurt.",
    price: 23.0,
    popular: true,
    image: "/images/menu/Smoothie.webp",
  },
  {
    id: 122,
    name: "Tropical Cocktail",
    category: "Cold Drinks",
    description: "Blended mango, kiwi, and pineapple.",
    price: 21.0,
    popular: false,
    image: "/images/menu/Cocktail.webp",
  },
  {
    id: 123,
    name: "Vanilla Milkshake",
    category: "Cold Drinks",
    description: "Classic creamy vanilla shake.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milk-shake.webp",
  },
  {
    id: 124,
    name: "Virgin Mojito",
    category: "Cold Drinks",
    description: "Refreshing lime and mint mocktail.",
    price: 19.0,
    popular: true,
    image: "/images/menu/Mojito.webp",
  },

  // COFFEES
  {
    id: 125,
    name: "Americano",
    category: "Coffees",
    description: "Espresso diluted with hot water.",
    price: 14.0,
    popular: false,
    image: "/images/menu/Americano.webp",
  },
  {
    id: 126,
    name: "Cappuccino",
    category: "Coffees",
    description: "Espresso topped with equal parts steamed milk and foam.",
    price: 15.0,
    popular: true,
    image: "/images/menu/Cappuccino.webp",
  },
  {
    id: 127,
    name: "Coffee on the Side",
    category: "Coffees",
    description: "Espresso served with a separate side of milk.",
    price: 15.0,
    popular: false,
    image: "/images/menu/coffee-milk.webp",
  },
  {
    id: 128,
    name: "Cortado",
    category: "Coffees",
    description: "Equal parts espresso and steamed milk.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Cortado.webp",
  },
  {
    id: 129,
    name: "Cream Coffee",
    category: "Coffees",
    description: "Espresso mixed with steamed cream.",
    price: 12.0,
    popular: true,
    image: "/images/menu/Cream-Coffee.webp",
  },
  {
    id: 130,
    name: "Double Espresso",
    category: "Coffees",
    description: "Two rich shots of intense espresso.",
    price: 18.0,
    popular: true,
    image: "/images/menu/double-espresso.webp",
  },
  {
    id: 131,
    name: "Espresso",
    category: "Coffees",
    description: "Rich and intense shot of coffee.",
    price: 12.0,
    popular: true,
    image: "/images/menu/Espresso.webp",
  },
  {
    id: 132,
    name: "Flat White",
    category: "Coffees",
    description: "Espresso with micro-foamed milk.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Flat-White.webp",
  },
  {
    id: 133,
    name: "Illy Espresso",
    category: "Coffees",
    description: "Premium Italian Illy espresso shot.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Illy-Espresso.webp",
  },
  {
    id: 134,
    name: "Latte Macchiato",
    category: "Coffees",
    description: "Steamed milk marked with a shot of espresso.",
    price: 16.0,
    popular: true,
    image: "/images/menu/Latte-Macchiato.webp",
  },
  {
    id: 135,
    name: "Mocha",
    category: "Coffees",
    description: "Espresso combined with chocolate and steamed milk.",
    price: 18.0,
    popular: false,
    image: "/images/menu/mocha.webp",
  },
  {
    id: 136,
    name: "Nespresso Coffee",
    category: "Coffees",
    description: "Classic Nespresso brewed coffee.",
    price: 15.0,
    popular: false,
    image: "/images/menu/Nespresso.webp",
  },
  {
    id: 137,
    name: "Viennese Chocolate",
    category: "Coffees",
    description: "Hot chocolate topped with whipped cream.",
    price: 16.0,
    popular: true,
    image: "/images/menu/Viennese-Chocolate.webp",
  },

  // JUICES
  {
    id: 138,
    name: "Apple Juice",
    category: "Juices",
    description: "Freshly pressed apple juice.",
    price: 16.0,
    popular: false,
    image: "/images/menu/juices.webp",
  },
  {
    id: 139,
    name: "Avocado Juice",
    category: "Juices",
    description: "Rich and creamy blended avocado juice.",
    price: 18.0,
    popular: true,
    image: "/images/menu/juices.webp",
  },
  {
    id: 140,
    name: "Avocado Juice with Dried Fruits",
    category: "Juices",
    description: "Creamy avocado juice blended with mixed dried fruits.",
    price: 23.0,
    popular: true,
    image: "/images/menu/juices.webp",
  },
  {
    id: 141,
    name: "Banana Juice",
    category: "Juices",
    description: "Freshly blended banana juice.",
    price: 16.0,
    popular: false,
    image: "/images/menu/juices.webp",
  },
  {
    id: 142,
    name: "Mango Juice",
    category: "Juices",
    description: "Fresh tropical mango juice.",
    price: 20.0,
    popular: false,
    image: "/images/menu/juices.webp",
  },
  {
    id: 143,
    name: "Mixed Fruit Juice with Milk",
    category: "Juices",
    description: "Blend of mixed fruits with milk.",
    price: 18.0,
    popular: true,
    image: "/images/menu/juices.webp",
  },
  {
    id: 144,
    name: "Mixed Fruit Juice with Orange",
    category: "Juices",
    description: "Blend of mixed fruits with orange juice.",
    price: 23.0,
    popular: false,
    image: "/images/menu/juices.webp",
  },
  {
    id: 145,
    name: "Orange Juice",
    category: "Juices",
    description: "Freshly squeezed orange juice.",
    price: 16.0,
    popular: true,
    image: "/images/menu/juices.webp",
  },
  {
    id: 146,
    name: "Pineapple Juice",
    category: "Juices",
    description: "Fresh sweet pineapple juice.",
    price: 23.0,
    popular: false,
    image: "/images/menu/juices.webp",
  },
  {
    id: 147,
    name: "Strawberry Juice",
    category: "Juices",
    description: "Freshly blended strawberry juice.",
    price: 18.0,
    popular: true,
    image: "/images/menu/juices.webp",
  },

  // EXTRAS
  {
    id: 148,
    name: "Almond Amlou",
    category: "Extras",
    description:
      "Premium Amlou made with extra roasted almonds. Served with bread.",
    price: 12.0,
    popular: false,
    image: "/images/menu/Almond.webp",
  },
  {
    id: 149,
    name: "Argan oil Amlou",
    category: "Extras",
    description:
      "Traditional almond, honey, and argan oil dip. Served with bread.",
    price: 8.0,
    popular: true,
    image: "/images/menu/argan.webp",
  },
  {
    id: 150,
    name: "Black and Green Olives",
    category: "Extras",
    description: "Mixed marinated olives. Served with bread.",
    price: 5.0,
    popular: false,
    image: "/images/menu/olive.webp",
  },
  {
    id: 151,
    name: "Cheese Spread",
    category: "Extras",
    description: "Portion of spreadable cheese. Served with bread.",
    price: 3.0,
    popular: true,
    image: "/images/menu/cheese.webp",
  },
  {
    id: 152,
    name: "Fresh Cheese (Jben)",
    category: "Extras",
    description:
      "Portion of traditional Moroccan fresh cheese. Served with bread.",
    price: 8.0,
    popular: true,
    image: "/images/menu/Fresh-Cheese.webp",
  },
  {
    id: 153,
    name: "Honey",
    category: "Extras",
    description: "Portion of pure honey. Served with bread.",
    price: 6.0,
    popular: true,
    image: "/images/menu/Honey.webp",
  },
  {
    id: 154,
    name: "Jam",
    category: "Extras",
    description: "Portion of fruit jam. Served with bread.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Jam.webp",
  },
  {
    id: 155,
    name: "Nutella",
    category: "Extras",
    description: "Portion of rich hazelnut cocoa spread. Served with bread.",
    price: 10.0,
    popular: true,
    image: "/images/menu/Nutella.webp",
  },
  {
    id: 156,
    name: "Olive Oil",
    category: "Extras",
    description:
      "Portion of high-quality extra virgin olive oil. Served with bread.",
    price: 8.0,
    popular: true,
    image: "/images/menu/Olive-Oil.webp",
  },
];

export const shopProducts = [
  // BREAKFAST & SAVORY
  {
    id: 1,
    name: "Barley Soup (Hesewa)",
    category: "Breakfast & Savory",
    description:
      "Warm and comforting traditional Moroccan barley and milk soup.",
    price: 7.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Hesewa.webp",
  },
  {
    id: 2,
    name: "Cheese Omelet",
    category: "Breakfast & Savory",
    description:
      "Fluffy omelet loaded with melted cheese, served with olives and olive oil.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Omelet.webp",
  },
  {
    id: 3,
    name: "Continental Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, cheese omelet, olive oil, olives, cheese, bread, yogurt, and water.",
    price: 35.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 4,
    name: "Deli Meat Omelet",
    category: "Breakfast & Savory",
    description:
      "Omelet packed with cold cuts, served with olives and olive oil.",
    price: 17.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/Omelet.webp",
  },
  {
    id: 5,
    name: "Express Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, pastries, yogurt, and mineral water.",
    price: 26.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 6,
    name: "Fassi Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, dried meat omelet, olive oil, olives, cheese, bread, yogurt, and water.",
    price: 37.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 7,
    name: "Gourmet Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, olive oil, Amlou, olives, honey, bread, yogurt, and water.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 8,
    name: "Harira Soup",
    category: "Breakfast & Savory",
    description:
      "Traditional hearty Moroccan tomato, lentil, and chickpea soup.",
    price: 10.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Soup.webp",
  },
  {
    id: 9,
    name: "Khlii Omelet",
    category: "Breakfast & Savory",
    description:
      "Traditional omelet with Moroccan preserved meat, served with olives and olive oil.",
    price: 24.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Omelet.webp",
  },
  {
    id: 10,
    name: "Kids Breakfast",
    category: "Breakfast & Savory",
    description:
      "Chocolate milk, orange juice, chocolate bread, vanilla cake, yogurt, and water.",
    price: 25.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 11,
    name: "La Madeleine Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, choice of omelet, olive oil, olives, honey, cheese, Amlou, bread, crepe, chocolate, cake, yogurt, and water.",
    price: 55.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 12,
    name: "Plain Omelet",
    category: "Breakfast & Savory",
    description: "Simple, fluffy egg omelet served with olives and olive oil.",
    price: 13.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/Omelet.webp",
  },
  {
    id: 13,
    name: "Soussi Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, Amlou, olive oil, cheese, olives, honey, jam, and water.",
    price: 38.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 14,
    name: "Tomato Omelet",
    category: "Breakfast & Savory",
    description:
      "Fluffy omelet with fresh tomatoes, served with olives and olive oil.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Omelet.webp",
  },
  {
    id: 15,
    name: "Traditional Breakfast",
    category: "Breakfast & Savory",
    description:
      "Barley soup, hot drink, orange juice, Moroccan pancakes, Harcha, honey, fresh cheese, and water.",
    price: 28.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.webp",
  },

  // PASTRIES & DESSERTS
  {
    id: 16,
    name: "Seafood Cigar",
    category: "Pastries & Desserts",
    description: "Crispy rolled pastry filled with savory mixed seafood.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Cigar.webp",
  },
  {
    id: 17,
    name: "Seafood Pastilla",
    category: "Pastries & Desserts",
    description:
      "Flaky savory pie filled with seasoned mixed seafood and vermicelli.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pastilla.webp",
  },
  {
    id: 18,
    name: "Sandwich",
    category: "Pastries & Desserts",
    description: "Freshly made savory sandwich.",
    price: 8.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/sandwich.webp",
  },
  {
    id: 19,
    name: "Mini Pizza",
    category: "Pastries & Desserts",
    description:
      "Personal-sized savory pizza topped with cheese and tomato sauce.",
    price: 6.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/pizza.webp",
  },
  {
    id: 20,
    name: "Hot Dog Pastry",
    category: "Pastries & Desserts",
    description: "Savory sausage wrapped and baked in soft dough.",
    price: 9.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/hot-dog.webp",
  },
  {
    id: 21,
    name: "Chicken Pastilla",
    category: "Pastries & Desserts",
    description:
      "Sweet and savory pie filled with spiced chicken and toasted almonds.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pastilla.webp",
  },
  {
    id: 22,
    name: "Cheese Briouat",
    category: "Pastries & Desserts",
    description: "Crispy Moroccan pastry triangles filled with savory cheese.",
    price: 7.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Briouat.webp",
  },
  {
    id: 23,
    name: "Almond Tart",
    category: "Pastries & Desserts",
    description: "Crisp sweet pastry shell filled with dense almond cream.",
    price: 10.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Tart.webp",
  },
  {
    id: 24,
    name: "Amlou Pancakes",
    category: "Pastries & Desserts",
    description: "Fluffy pancakes topped with traditional Moroccan Amlou.",
    price: 17.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Pancakes.webp",
  },
  {
    id: 25,
    name: "Apple Turnover",
    category: "Pastries & Desserts",
    description: "Flaky puff pastry filled with sweet spiced apple compote.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Apple-Turnover.webp",
  },
  {
    id: 26,
    name: "Caramel Crepe",
    category: "Pastries & Desserts",
    description: "Thin French crepe folded with sweet caramel.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 27,
    name: "Caramel Waffle",
    category: "Pastries & Desserts",
    description: "Golden waffle topped with rich caramel sauce.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 28,
    name: "Chocolate Basbousa",
    category: "Pastries & Desserts",
    description: "Sweet semolina cake flavored with rich chocolate.",
    price: 8.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.webp",
  },
  {
    id: 29,
    name: "Chocolate Madeleine",
    category: "Pastries & Desserts",
    description: "Small, shell-shaped sponge cake flavored with chocolate.",
    price: 2.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.webp",
  },
  {
    id: 30,
    name: "Classic Crepe",
    category: "Pastries & Desserts",
    description: "Simple, thin, and soft French crepe.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 31,
    name: "Cream Cake Slice (10)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 10.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 32,
    name: "Cream Cake Slice (12)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 33,
    name: "Cream Cake Slice (13)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 13.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 34,
    name: "Cream Cake Slice (14)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 14.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 35,
    name: "Cream Cake Slice (15)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 36,
    name: "Cream Cake Slice (17)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 17.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 37,
    name: "Cream Cake Slice (18)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 38,
    name: "Donut",
    category: "Pastries & Desserts",
    description: "Soft, sweet, and classic fried dough ring.",
    price: 4.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/donut.webp",
  },
  {
    id: 39,
    name: "Frangipane Tart",
    category: "Pastries & Desserts",
    description: "Sweet pastry tart filled with rich almond cream.",
    price: 8.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Frangipane-Tart.webp",
  },
  {
    id: 40,
    name: "Fruit Pithiviers",
    category: "Pastries & Desserts",
    description: "Puff pastry pie filled with sweet fruit compote.",
    price: 6.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Pithiviers.webp",
  },
  {
    id: 41,
    name: "Fruit Salad with Orange Juice",
    category: "Pastries & Desserts",
    description: "Fresh seasonal fruits steeped in fresh orange juice.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/fruit-salad.webp",
  },
  {
    id: 42,
    name: "Fruit Salad with Yogurt",
    category: "Pastries & Desserts",
    description: "Fresh seasonal fruits mixed with creamy yogurt.",
    price: 18.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/fruit-salad.webp",
  },
  {
    id: 43,
    name: "Fruit Tartlet",
    category: "Pastries & Desserts",
    description: "Small, sweet tart crust filled with custard and fresh fruit.",
    price: 7.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Fruit-Tartlet.webp",
  },
  {
    id: 44,
    name: "Honey Pancakes",
    category: "Pastries & Desserts",
    description: "Fluffy pancakes drizzled with pure honey.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 45,
    name: "Large Pound Cake",
    category: "Pastries & Desserts",
    description: "Generously sized, buttery, and moist pound cake.",
    price: 30.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 46,
    name: "Medium Pound Cake",
    category: "Pastries & Desserts",
    description: "Classic moist and sweet pound cake.",
    price: 20.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 47,
    name: "Mille-Feuille",
    category: "Pastries & Desserts",
    description:
      "Classic French pastry with layers of puff pastry and vanilla cream.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/millefeuille.webp",
  },
  {
    id: 48,
    name: "Mini Cake",
    category: "Pastries & Desserts",
    description: "Small, moist, and sweet personal cake.",
    price: 7.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/minicake.webp",
  },
  {
    id: 49,
    name: "Mini Cupcake",
    category: "Pastries & Desserts",
    description: "Bite-sized fluffy cake with sweet frosting.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cupcake.webp",
  },
  {
    id: 50,
    name: "Nutella & Banana Crepe",
    category: "Pastries & Desserts",
    description: "Crepe filled with Nutella and sliced bananas.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 51,
    name: "Nutella & Banana Pancakes",
    category: "Pastries & Desserts",
    description: "Pancakes served with Nutella and fresh bananas.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 52,
    name: "Nutella & Banana Waffle",
    category: "Pastries & Desserts",
    description: "Waffle topped with Nutella and fresh banana slices.",
    price: 22.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 53,
    name: "Nutella & Oreo Crepe",
    category: "Pastries & Desserts",
    description: "Crepe filled with Nutella and crushed Oreo cookies.",
    price: 25.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 54,
    name: "Nutella & Seasonal Fruits Crepe",
    category: "Pastries & Desserts",
    description: "Crepe filled with Nutella and fresh seasonal fruits.",
    price: 29.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 55,
    name: "Nutella & Seasonal Fruits Waffle",
    category: "Pastries & Desserts",
    description: "Waffle with Nutella and fresh seasonal fruits.",
    price: 27.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 56,
    name: "Nutella Crepe",
    category: "Pastries & Desserts",
    description: "Classic thin crepe filled with warm Nutella.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 57,
    name: "Nutella Pancakes",
    category: "Pastries & Desserts",
    description: "Stack of fluffy pancakes layered with Nutella.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 58,
    name: "Nutella Waffle",
    category: "Pastries & Desserts",
    description: "Golden waffle generously topped with Nutella.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 59,
    name: "Pithiviers",
    category: "Pastries & Desserts",
    description:
      "Round, enclosed pie made of puff pastry with a sweet filling.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Pithiviers.webp",
  },
  {
    id: 60,
    name: "Raspberry Mini Cake",
    category: "Pastries & Desserts",
    description: "Small cake infused with sweet raspberry flavor.",
    price: 8.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/minicake.webp",
  },
  {
    id: 61,
    name: "Small Pound Cake",
    category: "Pastries & Desserts",
    description: "Personal-sized slice of moist pound cake.",
    price: 15.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 62,
    name: "Vanilla Basbousa",
    category: "Pastries & Desserts",
    description: "Classic sweet semolina cake soaked in vanilla syrup.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.webp",
  },
  {
    id: 63,
    name: "Vanilla Madeleine",
    category: "Pastries & Desserts",
    description: "Classic, buttery, shell-shaped French sponge cake.",
    price: 1.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.webp",
  },
  {
    id: 64,
    name: "Almond Croissant",
    category: "Pastries & Desserts",
    description:
      "Flaky croissant filled with almond cream and topped with sliced almonds.",
    price: 5.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/croissant.webp",
  },
  {
    id: 65,
    name: "Almond Triangle",
    category: "Pastries & Desserts",
    description:
      "Flaky, triangle-shaped pastry filled with sweet almond paste.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Triangle.webp",
  },
  {
    id: 66,
    name: "Chocolate Danish",
    category: "Pastries & Desserts",
    description: "Flaky Danish pastry swirled with rich chocolate.",
    price: 4.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Danish.webp",
  },
  {
    id: 67,
    name: "Danish Pastry",
    category: "Pastries & Desserts",
    description: "Flaky, buttery, and sweet traditional Danish pastry.",
    price: 3.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Danish.webp",
  },
  {
    id: 68,
    name: "Harcha",
    category: "Pastries & Desserts",
    description: "Traditional Moroccan pan-fried semolina flatbread.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/harcha.webp",
  },
  {
    id: 69,
    name: "Msemmen",
    category: "Pastries & Desserts",
    description: "Traditional Moroccan flaky, layered square flatbread.",
    price: 4.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/msemmen.webp",
  },
  {
    id: 70,
    name: "Olive Oil Harcha",
    category: "Pastries & Desserts",
    description: "Savory semolina flatbread prepared with rich olive oil.",
    price: 3.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Oil-Harcha.webp",
  },
  {
    id: 71,
    name: "Pain Suisse",
    category: "Pastries & Desserts",
    description:
      "Flaky pastry rolled with vanilla custard and chocolate chips.",
    price: 3.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pain-suisse.webp",
  },
  {
    id: 72,
    name: "Pain au Chocolat / Croissant",
    category: "Pastries & Desserts",
    description: "Classic flaky and buttery French breakfast pastry.",
    price: 2.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Pain-au-Chocolat.webp",
  },

  // BAKERY
  {
    id: 73,
    name: "Barley Bread",
    category: "Bakery",
    description: "Hearty and healthy Moroccan barley bread.",
    price: 2.5,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 74,
    name: "Batbout",
    category: "Bakery",
    description: "Moroccan soft and chewy pan-cooked flatbread.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 75,
    name: "Chocolate Brioche",
    category: "Bakery",
    description: "Soft and fluffy sweet bread filled with chocolate chips.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 76,
    name: "Classic Baguette",
    category: "Bakery",
    description: "Traditional crusty and soft French baguette.",
    price: 1.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/bread.webp",
  },
  {
    id: 77,
    name: "Classic Bread",
    category: "Bakery",
    description: "Traditional Moroccan soft white round bread.",
    price: 1.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 78,
    name: "Classic Brioche",
    category: "Bakery",
    description: "Buttery, soft, and fluffy traditional sweet bread.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 79,
    name: "Corn Bread",
    category: "Bakery",
    description: "Rustic and flavorful Moroccan cornmeal bread.",
    price: 2.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },
  {
    id: 80,
    name: "Gingerbread",
    category: "Bakery",
    description: "Traditional French spiced bread with honey and anise.",
    price: 2.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 81,
    name: "Multigrain Baguette",
    category: "Bakery",
    description:
      "Crusty baguette baked with a blend of wholesome seeds and grains.",
    price: 4.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 82,
    name: "Olive Baguette",
    category: "Bakery",
    description: "Savory baguette baked with pieces of black and green olives.",
    price: 5.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 83,
    name: "Olive Bread",
    category: "Bakery",
    description: "Soft traditional round bread baked with savory olives.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 84,
    name: "Salt-Free Wheat Bread",
    category: "Bakery",
    description: "Healthy whole wheat bread prepared without added salt.",
    price: 3.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/bread.webp",
  },
  {
    id: 85,
    name: "Semolina Baguette",
    category: "Bakery",
    description: "Baguette made with semolina flour for a rustic crunch.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 86,
    name: "Semolina Bread",
    category: "Bakery",
    description: "Traditional Moroccan round bread made with semolina.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 87,
    name: "Sesame Baguette",
    category: "Bakery",
    description:
      "Freshly baked crusty French baguette topped with sesame seeds.",
    price: 2.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 88,
    name: "Sesame Roll",
    category: "Bakery",
    description: "Soft bread roll generously topped with sesame seeds.",
    price: 3.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },
  {
    id: 89,
    name: "Viennese Baguette",
    category: "Bakery",
    description: "Soft, slightly sweet, and rich Viennese-style bread.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 90,
    name: "Whole Wheat Baguette",
    category: "Bakery",
    description: "Healthy and hearty whole wheat French baguette.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 91,
    name: "Whole Wheat Bread",
    category: "Bakery",
    description: "Nutritious traditional Moroccan whole wheat round bread.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 92,
    name: "Whole Wheat Roll",
    category: "Bakery",
    description: "Healthy and soft whole wheat bread roll.",
    price: 2.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },

  // HOT DRINKS
  {
    id: 93,
    name: "Black Tea (Lipton)",
    category: "Hot Drinks",
    description: "Classic Lipton black tea.",
    price: 12.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/Lipton.webp",
  },
  {
    id: 94,
    name: "Hot Chocolate",
    category: "Hot Drinks",
    description: "Warm and comforting milk with rich chocolate.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/hot-chocolate.webp",
  },
  {
    id: 95,
    name: "Hot Milk",
    category: "Hot Drinks",
    description: "Simple, comforting steamed milk.",
    price: 12.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/hot-milk.webp",
  },
  {
    id: 96,
    name: "Lemon Verbena Tea",
    category: "Hot Drinks",
    description: "Herbal tea made with natural lemon verbena leaves.",
    price: 12.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Lemon-Verbena-Tea.webp",
  },
  {
    id: 97,
    name: "Milk Tea (Lipton)",
    category: "Hot Drinks",
    description: "Classic Lipton black tea brewed with milk.",
    price: 12.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Milk-Tea.webp",
  },
  {
    id: 98,
    name: "Milk with Lemon Verbena",
    category: "Hot Drinks",
    description: "Warm milk infused with soothing lemon verbena.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-tea.webp",
  },
  {
    id: 99,
    name: "Milk with Syrup",
    category: "Hot Drinks",
    description: "Cold or warm milk flavored with sweet syrup.",
    price: 11.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/Milk-Syrup.webp",
  },
  {
    id: 100,
    name: "Moroccan Mint Tea",
    category: "Hot Drinks",
    description: "Traditional green tea brewed with fresh mint.",
    price: 11.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Moroccan-Tea.webp",
  },

  // COLD DRINKS
  {
    id: 101,
    name: "Affogato",
    category: "Cold Drinks",
    description: "A scoop of vanilla ice cream drowned in hot espresso.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Affogato.webp",
  },
  {
    id: 102,
    name: "Banana Milkshake",
    category: "Cold Drinks",
    description: "Sweet and creamy banana shake.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 103,
    name: "Banana Smoothie",
    category: "Cold Drinks",
    description: "Creamy blended banana smoothie.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Smoothie.webp",
  },
  {
    id: 104,
    name: "Blue Mojito",
    category: "Cold Drinks",
    description: "Citrus and mint mocktail with blue curaçao syrup.",
    price: 22.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Mojito.webp",
  },
  {
    id: 105,
    name: "Choice of Soda (35cl)",
    category: "Cold Drinks",
    description: "Selection of refreshing carbonated beverages.",
    price: 12.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/Soda.webp",
  },
  {
    id: 106,
    name: "Chocolate Milkshake",
    category: "Cold Drinks",
    description: "Rich and creamy chocolate shake.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 107,
    name: "Exotic Cocktail",
    category: "Cold Drinks",
    description: "Blended mango, orange, and pineapple.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Cocktail.webp",
  },
  {
    id: 108,
    name: "Exotic Smoothie",
    category: "Cold Drinks",
    description: "Refreshing blend of tropical fruits.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Smoothie.webp",
  },
  {
    id: 109,
    name: "Iced Caramel Macchiato",
    category: "Cold Drinks",
    description: "Iced milk and espresso, flavored with vanilla and caramel.",
    price: 21.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/iced-caramel.webp",
  },
  {
    id: 110,
    name: "Iced Coffee",
    category: "Cold Drinks",
    description: "Chilled coffee over ice with choice of flavor.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/iced-coffee.webp",
  },
  {
    id: 111,
    name: "Iced Frappuccino",
    category: "Cold Drinks",
    description:
      "Blended iced coffee drink with choice of vanilla, chocolate, or caramel.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-frappuccino.webp",
  },
  {
    id: 112,
    name: "Iced Latte",
    category: "Cold Drinks",
    description: "Espresso and chilled milk over ice.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Iced-Latte.webp",
  },
  {
    id: 113,
    name: "Iced Mocha",
    category: "Cold Drinks",
    description: "Iced espresso with chocolate and milk.",
    price: 19.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-mocha.webp",
  },
  {
    id: 114,
    name: "Mango Smoothie",
    category: "Cold Drinks",
    description: "Tropical blended mango smoothie.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 115,
    name: "Mineral Water (33cl)",
    category: "Cold Drinks",
    description: "Small bottle of still mineral water.",
    price: 5.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/Water.webp",
  },
  {
    id: 116,
    name: "Mineral Water (50cl)",
    category: "Cold Drinks",
    description: "Medium bottle of still mineral water.",
    price: 7.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/Water.webp",
  },
  {
    id: 117,
    name: "Oreo Milkshake",
    category: "Cold Drinks",
    description: "Creamy vanilla shake blended with Oreo cookies.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 118,
    name: "Oriental Cocktail",
    category: "Cold Drinks",
    description: "Blended banana, apple, and orange.",
    price: 20.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cocktail.webp",
  },
  {
    id: 119,
    name: "Red Mojito",
    category: "Cold Drinks",
    description: "Fruity red berry mocktail with mint and lime.",
    price: 22.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Mojito.webp",
  },
  {
    id: 120,
    name: "Strawberry Milkshake",
    category: "Cold Drinks",
    description: "Sweet and creamy strawberry shake.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 121,
    name: "Strawberry Smoothie",
    category: "Cold Drinks",
    description: "Blended fresh strawberries and yogurt.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Smoothie.webp",
  },
  {
    id: 122,
    name: "Tropical Cocktail",
    category: "Cold Drinks",
    description: "Blended mango, kiwi, and pineapple.",
    price: 21.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Cocktail.webp",
  },
  {
    id: 123,
    name: "Vanilla Milkshake",
    category: "Cold Drinks",
    description: "Classic creamy vanilla shake.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 124,
    name: "Virgin Mojito",
    category: "Cold Drinks",
    description: "Refreshing lime and mint mocktail.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Mojito.webp",
  },

  // COFFEES
  {
    id: 125,
    name: "Americano",
    category: "Coffees",
    description: "Espresso diluted with hot water.",
    price: 14.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/Americano.webp",
  },
  {
    id: 126,
    name: "Cappuccino",
    category: "Coffees",
    description: "Espresso topped with equal parts steamed milk and foam.",
    price: 15.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Cappuccino.webp",
  },
  {
    id: 127,
    name: "Coffee on the Side",
    category: "Coffees",
    description: "Espresso served with a separate side of milk.",
    price: 15.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/coffee-milk.webp",
  },
  {
    id: 128,
    name: "Cortado",
    category: "Coffees",
    description: "Equal parts espresso and steamed milk.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Cortado.webp",
  },
  {
    id: 129,
    name: "Cream Coffee",
    category: "Coffees",
    description: "Espresso mixed with steamed cream.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cream-Coffee.webp",
  },
  {
    id: 130,
    name: "Double Espresso",
    category: "Coffees",
    description: "Two rich shots of intense espresso.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/double-espresso.webp",
  },
  {
    id: 131,
    name: "Espresso",
    category: "Coffees",
    description: "Rich and intense shot of coffee.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Espresso.webp",
  },
  {
    id: 132,
    name: "Flat White",
    category: "Coffees",
    description: "Espresso with micro-foamed milk.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Flat-White.webp",
  },
  {
    id: 133,
    name: "Illy Espresso",
    category: "Coffees",
    description: "Premium Italian Illy espresso shot.",
    price: 16.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Illy-Espresso.webp",
  },
  {
    id: 134,
    name: "Latte Macchiato",
    category: "Coffees",
    description: "Steamed milk marked with a shot of espresso.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Latte-Macchiato.webp",
  },
  {
    id: 135,
    name: "Mocha",
    category: "Coffees",
    description: "Espresso combined with chocolate and steamed milk.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/mocha.webp",
  },
  {
    id: 136,
    name: "Nespresso Coffee",
    category: "Coffees",
    description: "Classic Nespresso brewed coffee.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Nespresso.webp",
  },
  {
    id: 137,
    name: "Viennese Chocolate",
    category: "Coffees",
    description: "Hot chocolate topped with whipped cream.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Viennese-Chocolate.webp",
  },

  // JUICES
  {
    id: 138,
    name: "Apple Juice",
    category: "Juices",
    description: "Freshly pressed apple juice.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Apple-Juice.webp",
  },
  {
    id: 139,
    name: "Avocado Juice",
    category: "Juices",
    description: "Rich and creamy blended avocado juice.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Avocado-Juice.webp",
  },
  {
    id: 140,
    name: "Avocado Juice with Dried Fruits",
    category: "Juices",
    description: "Creamy avocado juice blended with mixed dried fruits.",
    price: 23.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Avocado-Juice-with-Dried-Fruits.webp",
  },
  {
    id: 141,
    name: "Banana Juice",
    category: "Juices",
    description: "Freshly blended banana juice.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Banana-Juice.webp",
  },
  {
    id: 142,
    name: "Mango Juice",
    category: "Juices",
    description: "Fresh tropical mango juice.",
    price: 20.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Mango-Juice.webp",
  },
  {
    id: 143,
    name: "Mixed Fruit Juice with Milk",
    category: "Juices",
    description: "Blend of mixed fruits with milk.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Mixed-Fruit-Juice-with-Milk.webp",
  },
  {
    id: 144,
    name: "Mixed Fruit Juice with Orange",
    category: "Juices",
    description: "Blend of mixed fruits with orange juice.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Mixed-Fruit-Juice-with-Orange.webp",
  },
  {
    id: 145,
    name: "Orange Juice",
    category: "Juices",
    description: "Freshly squeezed orange juice.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Orange-Juice.webp",
  },
  {
    id: 146,
    name: "Pineapple Juice",
    category: "Juices",
    description: "Fresh sweet pineapple juice.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Pineapple-Juice.webp",
  },
  {
    id: 147,
    name: "Strawberry Juice",
    category: "Juices",
    description: "Freshly blended strawberry juice.",
    price: 18.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Strawberry-Juice.webp",
  },

  // EXTRAS
  {
    id: 148,
    name: "Almond Amlou",
    category: "Extras",
    description:
      "Premium Amlou made with extra roasted almonds. Served with bread.",
    price: 12.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Almond.webp",
  },
  {
    id: 149,
    name: "Argan Oil Amlou",
    category: "Extras",
    description:
      "Traditional almond, honey, and argan oil dip. Served with bread.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/argan.webp",
  },
  {
    id: 150,
    name: "Black and Green Olives",
    category: "Extras",
    description: "Mixed marinated olives. Served with bread.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/olive.webp",
  },
  {
    id: 151,
    name: "Cheese Spread",
    category: "Extras",
    description: "Portion of spreadable cheese. Served with bread.",
    price: 3.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cheese.webp",
  },
  {
    id: 152,
    name: "Fresh Cheese (Jben)",
    category: "Extras",
    description:
      "Portion of traditional Moroccan fresh cheese. Served with bread.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Fresh-Cheese.webp",
  },
  {
    id: 153,
    name: "Honey",
    category: "Extras",
    description: "Portion of pure honey. Served with bread.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Honey.webp",
  },
  {
    id: 154,
    name: "Jam",
    category: "Extras",
    description: "Portion of fruit jam. Served with bread.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Jam.webp",
  },
  {
    id: 155,
    name: "Nutella",
    category: "Extras",
    description: "Portion of rich hazelnut cocoa spread. Served with bread.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Nutella.webp",
  },
  {
    id: 156,
    name: "Olive Oil",
    category: "Extras",
    description:
      "Portion of high-quality extra virgin olive oil. Served with bread.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Olive-Oil.webp",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Ryu Zaki",
    role: "Regular Customer",
    quote:
      "A lovely tea room serving very good baked goods and pastries. The fruit juices are excellent.",
    rating: 5,
  },
  {
    id: 2,
    name: "Halima Elmkiess",
    role: "Regular Customer",
    quote:
      "A great place where you can find everything you want. The staff is wonderful 😊 Very clean establishment. The food is absolutely delicious. I really, really love it. Thank you so much for your service! ☺️",
    rating: 5,
  },
  {
    id: 3,
    name: "Soufiane Driver",
    role: "Regular Customer",
    quote: "A very calm place with good service and friendly people !",
    rating: 4,
  },
];

export const locations = [
  {
    id: 1,
    name: "La Madeleine — Tilila",
    address: "Av. Al Oulfa, Tilila, Agadir 80000",
    phone: "05.28.26.43.44",
    hours: "Mon–Sun 6am–10pm",
    mapUrl: "https://maps.app.goo.gl/Z5memQUhJrBtShyx7",
  },
];

export const faqData = [
  {
    id: 1,
    category: "General",
    question: "What are your opening hours?",
    answer: "We're open Monday to Sunday from 6:00 AM to 10:00 PM.",
  },
  {
    id: 2,
    category: "General",
    question: "Do you offer dine-in or is it takeaway only?",
    answer:
      "Both! We have a beautiful seating area with indoor and outdoor tables. Enjoy your freshly baked pastries and coffee in our warm, inviting space.",
  },
  {
    id: 3,
    category: "Products",
    question: "Are your products made with organic ingredients?",
    answer:
      "We source the finest ingredients available. While not everything is certified organic, we prioritize quality, sustainability.",
  },
  {
    id: 4,
    category: "Ordering",
    question: "What payment methods do you accept?",
    answer: "We currently accept cash payments only.",
  },
  {
    id: 5,
    category: "Ordering",
    question: "Can I place an order for delivery?",
    answer:
      "At the moment, we do not offer delivery or online ordering. To place an order, simply call us directly or visit our bakery, and our team will be happy to assist you.",
  },
  {
    id: 6,
    category: "Ordering",
    question: "Do you cater for events and weddings?",
    answer:
      "We'd love to be part of your special day! We offer bespoke catering packages for weddings, corporate events, and private parties. Contact us at least one week in advance for custom orders.",
  },
  {
    id: 7,
    category: "General",
    question: "Is parking available near your bakery?",
    answer:
      "Parking is available nearby, and our bakery is easily accessible by public transport or car.",
  },
];
