export const siteConfig = {
  name: "LaMadeleine Agadir",
  tagline: "مخبز حرفي ومقهى",
  description:
    "معجنات مصنوعة يدوياً، خبز حرفي، وقهوة استثنائية — تجربة أصيلة للمخبزة الفرنسية والمغربية منذ 2019.",
  phone: "05.28.26.43.44",
  email: "contact@lamadeleine.ma",
  address: "شارع الألفة، تيليلا، أكادير 80000",
  social: {
    instagram: "https://instagram.com/lamadeleine.agadir",
    facebook: "https://facebook.com/lamadeleine.agadir",
  },
  hours: [{ day: "الإثنين — الأحد", time: "6:00 صباحاً — 10:00 مساءً" }],
};

export const heroSlides = [
  {
    id: 1,
    title: "معجنات بالشوكولاتة",
    subtitle: "لذيذة",
    image: "/images/slider/slide-1/slide-1-image.png",
    bgText: "/images/slider/slide-1/slide-1-bg.png",
    bgIcon: "/images/slider/slide-1/slide-1-bg-icon.png",
    products: [
      {
        title: "شوكولاتة",
        description:
          "معجنات غنية بالشوكولاتة الداكنة مع الشوكولاتة البلجيكية وعجينة مورقة.",
        icon: "/images/slider/slide-1/slide-1-product-1.png",
      },
      {
        title: "كلاسيكيات حلوة",
        description:
          "كرواسون طازج، إكلير، وتارت تُخبز يومياً بمكونات عالية الجودة.",
        icon: "/images/slider/slide-1/slide-1-product-2.png",
      },
    ],
  },
  {
    id: 2,
    title: "خبز رائع وكبير.",
    subtitle: "لذيذ",
    image: "/images/slider/slide-2/slide-2-image.png",
    bgText: "/images/slider/slide-2/slide-2-bg.png",
    bgIcon: "/images/slider/slide-2/slide-2-bg-icon.png",
    products: [
      {
        title: "نخبز الأفضل",
        description: "مخبوزات طازجة يومياً بقشرة ذهبية ومقرمشة.",
        icon: "/images/slider/slide-2/slide-2-product-1.png",
      },
      {
        title: "مذاق لا يُوصف",
        description: "خبز غني بالزبدة بقوام يذوب في الفم.",
        icon: "/images/slider/slide-2/slide-2-product-2.png",
      },
    ],
  },
  {
    id: 3,
    title: "سندويشات",
    subtitle: "لذيذة",
    image: "/images/slider/slide-3/slide-3-image.png",
    bgText: "/images/slider/slide-3/slide-3-bg.png",
    bgIcon: "/images/slider/slide-3/slide-3-bg-icon.png",
    products: [
      {
        title: "فطور",
        description: "سندويشات فطور مالحة ولذيذة.",
        icon: "/images/slider/slide-3/slide-3-product-1.png",
      },
      {
        title: "وجبة خفيفة صحية",
        description: "أكواب الفواكه الطازجة مع الزبادي.",
        icon: "/images/slider/slide-3/slide-3-product-2.png",
      },
    ],
  },
];

export const categories = [
  {
    id: 1,
    name: "فطور",
    description: "ابدأ يومك على الطريقة المغربية",
    icon: "sunrise",
    image: "/images/cat-breakfast.jpg",
  },
  {
    id: 2,
    name: "خبز حرفي",
    description: "مخبوزات فرنسية ومغربية تقليدية",
    icon: "wheat",
    image: "/images/cat-bread.jpg",
  },
  {
    id: 3,
    name: "حلويات",
    description: "إبداعات حلوة لا تُقاوم",
    icon: "cherry",
    image: "/images/cat-desserts.jpg",
  },
  {
    id: 4,
    name: "قهوة",
    description: "مُحضرة ومحمصة بخبرة",
    icon: "coffee",
    image: "/images/cat-coffee.jpg",
  },
  {
    id: 5,
    name: "معجنات",
    description: "معجنات فرنسية ومغربية راقية",
    icon: "cake",
    image: "/images/cat-pastries.jpg",
  },
  {
    id: 6,
    name: "سندويشات",
    description: "طازجة، محضرة يدوياً ولذيذة",
    icon: "sandwich",
    image: "/images/cat-sandwiches.jpg",
  },
];

type TodaysSpecial = {
  id: number;
  name: string;
  category: string;
  description: string;
  price: number;
  image: string;
};

export const todaysSpecials: TodaysSpecial[] = [
  {
    id: 1,
    name: "بان أو شوكولا",
    category: "معجنات",
    description:
      "طبقات مورقة بالزبدة ملفوفة حول قطعتين من الشوكولاتة الداكنة الفاخرة — معجنات الفطور الفرنسية الكلاسيكية.",
    price: 2.5,
    image: "/images/today-specials/today-3.jpg",
  },
  {
    id: 2,
    name: "كرواسون بالزبدة",
    category: "فطور",
    description:
      "كرواسون ذهبي وخفيف جداً، مصنوع من زبدة نورماندي بنسبة دسم 84%. تخمير لمدة 72 ساعة لطبقات مثالية.",
    price: 2.5,
    image: "/images/today-specials/today-1.jpg",
  },
  {
    id: 3,
    name: "سندويش كرواسون",
    category: "فطور",
    description:
      "معجنات فطور فرنسية كلاسيكية محشوة بكريمة غنية بالزبدة ومزينة برشة خفيفة من السكر الناعم.",
    price: 5,
    image: "/images/today-specials/today-2.jpg",
  },
  {
    id: 4,
    name: "تارت الفواكه",
    category: "حلويات",
    description:
      "فواكه موسمية مرتبة فوق كريمة الفانيليا، موضوعة في عجينة تارت مقرمشة ومكرملة.",
    price: 7,
    image: "/images/today-specials/today-4.jpg",
  },
  {
    id: 5,
    name: "ميل فوي باللوز",
    category: "حلويات",
    description:
      "ثلاث طبقات من العجينة المورقة المكرملة تتناوب مع كريمة اللوز الخفيفة، مغطاة بشرائح اللوز المحمص ورشة من السكر الناعم.",
    price: 10,
    image: "/images/today-specials/today-5.jpg",
  },
  {
    id: 6,
    name: "كورتادو مادلاين المميز",
    category: "قهوة",
    description:
      "مقادير متساوية من الإسبريسو الغني جداً والحليب المبخر بقوام مثالي، مزين برشة من التوابل الدافئة.",
    price: 12,
    image: "/images/today-specials/today-6.jpg",
  },
];

export const coffeeMenu = [
  {
    id: 1,
    name: "موكا",
    description: "إسبريسو ممزوج مع الشوكولاتة والحليب المبخر.",
    price: 18.0,
    icon: "Cookie",
  },
  {
    id: 2,
    name: "كابتشينو",
    description: "إسبريسو مغطى بمقادير متساوية من الحليب المبخر والرغوة.",
    price: 15.0,
    icon: "Milk",
  },
  {
    id: 3,
    name: "قهوة مع حليب جانبي",
    description: "إسبريسو يُقدم مع حليب جانبي منفصل.",
    price: 15.0,
    icon: "Coffee",
  },
  {
    id: 4,
    name: "كورتادو",
    description: "مقادير متساوية من الإسبريسو والحليب المبخر.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 5,
    name: "قهوة بالكريمة",
    description: "إسبريسو ممزوج بالكريمة المبخرة.",
    price: 12.0,
    icon: "Cookie",
  },
  {
    id: 6,
    name: "إسبريسو مزدوج",
    description: "جرعتان غنيتان من الإسبريسو المركز.",
    price: 18.0,
    icon: "Droplets",
  },
  {
    id: 7,
    name: "إسبريسو",
    description: "جرعة غنية ومركزة من القهوة.",
    price: 12.0,
    icon: "Coffee",
  },
  {
    id: 8,
    name: "فلات وايت",
    description: "إسبريسو مع حليب برغوة دقيقة.",
    price: 16.0,
    icon: "Milk",
  },
  {
    id: 9,
    name: "إسبريسو إيلي",
    description: "جرعة إسبريسو إيطالية فاخرة من إيلي.",
    price: 16.0,
    icon: "Sparkles",
  },
  {
    id: 10,
    name: "لاتيه ماكياتو",
    description: "حليب مبخر مضاف إليه جرعة من الإسبريسو.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 11,
    name: "أمريكانو",
    description: "إسبريسو مخفف بالماء الساخن.",
    price: 14.0,
    icon: "Coffee",
  },
  {
    id: 12,
    name: "قهوة نسبريسو",
    description: "قهوة نسبريسو كلاسيكية.",
    price: 15.0,
    icon: "Coffee",
  },
];

export const menuCategories = [
  "فطور ومملحات",
  "معجنات وحلويات",
  "مخبزة",
  "مشروبات ساخنة",
  "مشروبات باردة",
  "قهوة",
  "عصائر",
  "إضافات",
];

export const menuItems = [
  // BREAKFAST & SAVORY
  {
    id: 1,
    name: "حساء الشعير (حسوة)",
    category: "فطور ومملحات",
    description:
      "حساء الشعير والحليب المغربي التقليدي الدافئ والمريح.",
    price: 7.0,
    popular: false,
    image: "/images/menu/Soup.png",
  },
  {
    id: 2,
    name: "أومليت بالجبن",
    category: "فطور ومملحات",
    description:
      "أومليت هشة محشوة بالجبن الذائب، تُقدم مع الزيتون وزيت الزيتون.",
    price: 16.0,
    popular: true,
    image: "/images/menu/Omelet.png",
  },
  {
    id: 3,
    name: "فطور كونتيننتال",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، أومليت بالجبن، زيت زيتون، زيتون، جبن، خبز، زبادي، وماء.",
    price: 35.0,
    popular: false,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 4,
    name: "أومليت باللحم البارد (كاشير)",
    category: "فطور ومملحات",
    description:
      "أومليت محشوة باللحم البارد، تُقدم مع الزيتون وزيت الزيتون.",
    price: 17.0,
    popular: false,
    image: "/images/menu/Omelet.png",
  },
  {
    id: 5,
    name: "فطور إكسبريس",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، معجنات، زبادي، وماء معدني.",
    price: 26.0,
    popular: true,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 6,
    name: "فطور فاسي",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، أومليت باللحم المجفف (القديد)، زيت زيتون، زيتون، جبن، خبز، زبادي، وماء.",
    price: 37.0,
    popular: true,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 7,
    name: "فطور الذواقة",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، زيت زيتون، أملو، زيتون، عسل، خبز، زبادي، وماء.",
    price: 26.0,
    popular: false,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 8,
    name: "حريرة",
    category: "فطور ومملحات",
    description:
      "الحساء المغربي التقليدي الغني بالطماطم، العدس، والحمص.",
    price: 10.0,
    popular: false,
    image: "/images/menu/Soup.png",
  },
  {
    id: 9,
    name: "أومليت بالخليع",
    category: "فطور ومملحات",
    description:
      "أومليت تقليدية مع اللحم المغربي المحفوظ (الخليع)، تُقدم مع الزيتون وزيت الزيتون.",
    price: 24.0,
    popular: true,
    image: "/images/menu/Omelet.png",
  },
  {
    id: 10,
    name: "فطور الأطفال",
    category: "فطور ومملحات",
    description:
      "حليب بالشوكولاتة، عصير برتقال، خبز بالشوكولاتة، كيك بالفانيليا، زبادي، وماء.",
    price: 25.0,
    popular: false,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 11,
    name: "فطور لامادلين",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، اختيارك من الأومليت، زيت زيتون، زيتون، عسل، جبن، أملو، خبز، كريب، شوكولاتة، كيك، زبادي، وماء.",
    price: 55.0,
    popular: true,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 12,
    name: "أومليت عادية",
    category: "فطور ومملحات",
    description: "أومليت بيض بسيطة وهشة تُقدم مع الزيتون وزيت الزيتون.",
    price: 13.0,
    popular: true,
    image: "/images/menu/Omelet.png",
  },
  {
    id: 13,
    name: "فطور سوسي",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، أملو، زيت زيتون، جبن، زيتون، عسل، مربى، وماء.",
    price: 38.0,
    popular: true,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 14,
    name: "أومليت بالطماطم",
    category: "فطور ومملحات",
    description:
      "أومليت هشة مع طماطم طازجة، تُقدم مع الزيتون وزيت الزيتون.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Omelet.png",
  },
  {
    id: 15,
    name: "فطور تقليدي",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، بغرير، حرشة، عسل، جبن طازج، وماء.",
    price: 28.0,
    popular: true,
    image: "/images/menu/breakfast.png",
  },

  // PASTRIES & DESSERTS
  {
    id: 16,
    name: "سيجار فواكه البحر",
    category: "معجنات وحلويات",
    description: "لفائف مقرمشة محشوة بتشكيلة لذيذة من فواكه البحر.",
    price: 12.0,
    popular: false,
    image: "/images/menu/Cigar.png",
  },
  {
    id: 17,
    name: "بسطيلة فواكه البحر",
    category: "معجنات وحلويات",
    description:
      "فطيرة مالحة مورقة محشوة بفواكه البحر المتبلة والشعيرية.",
    price: 12.0,
    popular: false,
    image: "/images/menu/pastilla.png",
  },
  {
    id: 18,
    name: "سندويش",
    category: "معجنات وحلويات",
    description: "سندويش مالح محضر طازجاً.",
    price: 8.0,
    popular: false,
    image: "/images/menu/sandwich.png",
  },
  {
    id: 19,
    name: "ميني بيتزا",
    category: "معجنات وحلويات",
    description:
      "بيتزا مالحة بحجم صغير مغطاة بالجبن وصلصة الطماطم.",
    price: 6.0,
    popular: false,
    image: "/images/menu/pizza.png",
  },
  {
    id: 20,
    name: "هوت دوج بعجينة مورقة",
    category: "معجنات وحلويات",
    description: "نقانق مالحة ملفوفة ومخبوزة في عجينة طرية.",
    price: 9.0,
    popular: false,
    image: "/images/menu/hot-dog.png",
  },
  {
    id: 21,
    name: "بسطيلة بالدجاج",
    category: "معجنات وحلويات",
    description:
      "فطيرة حلوة ومالحة محشوة بالدجاج المتبل واللوز المحمص.",
    price: 10.0,
    popular: false,
    image: "/images/menu/pastilla.png",
  },
  {
    id: 22,
    name: "بريوات بالجبن",
    category: "معجنات وحلويات",
    description: "مثلثات معجنات مغربية مقرمشة محشوة بالجبن المالح.",
    price: 7.0,
    popular: false,
    image: "/images/menu/Briouat.png",
  },
  {
    id: 23,
    name: "تارت اللوز",
    category: "معجنات وحلويات",
    description: "قشرة معجنات حلوة ومقرمشة محشوة بكريمة اللوز الكثيفة.",
    price: 10.0,
    popular: false,
    image: "/images/menu/Tart.png",
  },
  {
    id: 24,
    name: "بان كيك أملو",
    category: "معجنات وحلويات",
    description: "بان كيك هش مغطى بالأملو المغربي التقليدي.",
    price: 17.0,
    popular: false,
    image: "/images/menu/Pancakes.png",
  },
  {
    id: 25,
    name: "شوسون بالتفاح",
    category: "معجنات وحلويات",
    description: "عجينة مورقة محشوة بكومبوت التفاح الحلو المتبل.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Apple-Turnover.png",
  },
  {
    id: 26,
    name: "كريب بالكراميل",
    category: "معجنات وحلويات",
    description: "كريب فرنسي رقيق مطوي مع الكراميل الحلو.",
    price: 16.0,
    popular: false,
    image: "/images/menu/crepe.png",
  },
  {
    id: 27,
    name: "وافل بالكراميل",
    category: "معجنات وحلويات",
    description: "وافل ذهبي مغطى بصلصة الكراميل الغنية.",
    price: 16.0,
    popular: false,
    image: "/images/menu/waffle.png",
  },
  {
    id: 28,
    name: "بسبوسة بالشوكولاتة",
    category: "معجنات وحلويات",
    description: "كيكة سميد حلوة بنكهة الشوكولاتة الغنية.",
    price: 8.0,
    popular: false,
    image: "/images/menu/basbousa.png",
  },
  {
    id: 29,
    name: "مادلين بالشوكولاتة",
    category: "معجنات وحلويات",
    description: "كيكة إسفنجية صغيرة على شكل صدفة بنكهة الشوكولاتة.",
    price: 2.5,
    popular: false,
    image: "/images/menu/madeleine.png",
  },
  {
    id: 30,
    name: "كريب كلاسيكي",
    category: "معجنات وحلويات",
    description: "كريب فرنسي بسيط ورقيق وطري.",
    price: 4.0,
    popular: false,
    image: "/images/menu/crepe.png",
  },
  {
    id: 31,
    name: "شريحة كيك بالكريمة (10)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 10.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 32,
    name: "شريحة كيك بالكريمة (12)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 12.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 33,
    name: "شريحة كيك بالكريمة (13)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 13.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 34,
    name: "شريحة كيك بالكريمة (14)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 14.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 35,
    name: "شريحة كيك بالكريمة (15)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 15.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 36,
    name: "شريحة كيك بالكريمة (17)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 17.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 37,
    name: "شريحة كيك بالكريمة (18)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 18.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 38,
    name: "دونات",
    category: "معجنات وحلويات",
    description: "دونات كلاسيكية مقلية طرية وحلوة.",
    price: 4.0,
    popular: false,
    image: "/images/menu/donut.png",
  },
  {
    id: 39,
    name: "تارت الفرانجيبان",
    category: "معجنات وحلويات",
    description: "تارت معجنات حلوة محشوة بكريمة اللوز الغنية.",
    price: 8.0,
    popular: false,
    image: "/images/menu/tart.png",
  },
  {
    id: 40,
    name: "بيثيفييه فواكه",
    category: "معجنات وحلويات",
    description: "فطيرة من العجين المورق محشوة بكومبوت الفواكه الحلو.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Pithiviers.png",
  },
  {
    id: 41,
    name: "سلطة فواكه مع عصير برتقال",
    category: "معجنات وحلويات",
    description: "فواكه موسمية طازجة منقوعة في عصير برتقال طازج.",
    price: 19.0,
    popular: false,
    image: "/images/menu/fruit-salad.png",
  },
  {
    id: 42,
    name: "سلطة فواكه مع زبادي",
    category: "معجنات وحلويات",
    description: "فواكه موسمية طازجة ممزوجة بزبادي كريمي.",
    price: 18.0,
    popular: false,
    image: "/images/menu/fruit-salad.png",
  },
  {
    id: 43,
    name: "تارتليت بالفواكه",
    category: "معجنات وحلويات",
    description: "قشرة تارت حلوة صغيرة محشوة بالكاسترد والفواكه الطازجة.",
    price: 7.0,
    popular: false,
    image: "/images/menu/tartlet.png",
  },
  {
    id: 44,
    name: "بان كيك بالعسل",
    category: "معجنات وحلويات",
    description: "بان كيك هش مغطى بعسل نقي.",
    price: 16.0,
    popular: false,
    image: "/images/menu/pancakes.png",
  },
  {
    id: 45,
    name: "باوند كيك كبير",
    category: "معجنات وحلويات",
    description: "كيكة بحجم كبير، غنية بالزبدة وطرية.",
    price: 30.0,
    popular: false,
    image: "/images/menu/pound-cake.png",
  },
  {
    id: 46,
    name: "باوند كيك وسط",
    category: "معجنات وحلويات",
    description: "كيكة كلاسيكية طرية وحلوة.",
    price: 20.0,
    popular: false,
    image: "/images/menu/pound-cake.png",
  },
  {
    id: 47,
    name: "ميل فوي",
    category: "معجنات وحلويات",
    description:
      "معجنات فرنسية كلاسيكية بطبقات من العجينة المورقة وكريمة الفانيليا.",
    price: 8.0,
    popular: false,
    image: "/images/menu/millefeuille.png",
  },
  {
    id: 48,
    name: "ميني كيك",
    category: "معجنات وحلويات",
    description: "كيكة صغيرة شخصية، طرية وحلوة.",
    price: 7.0,
    popular: false,
    image: "/images/menu/minicake.png",
  },
  {
    id: 49,
    name: "ميني كب كيك",
    category: "معجنات وحلويات",
    description: "كيكة صغيرة هشة بحجم لقمة مع كريمة تزيين حلوة.",
    price: 4.0,
    popular: false,
    image: "/images/menu/cupcake.png",
  },
  {
    id: 50,
    name: "كريب نوتيلا وموز",
    category: "معجنات وحلويات",
    description: "كريب محشو بالنوتيلا وشرائح الموز.",
    price: 23.0,
    popular: true,
    image: "/images/menu/crepe.png",
  },
  {
    id: 51,
    name: "بان كيك نوتيلا وموز",
    category: "معجنات وحلويات",
    description: "بان كيك يُقدم مع النوتيلا والموز الطازج.",
    price: 26.0,
    popular: true,
    image: "/images/menu/pancakes.png",
  },
  {
    id: 52,
    name: "وافل نوتيلا وموز",
    category: "معجنات وحلويات",
    description: "وافل مغطى بالنوتيلا وشرائح الموز الطازجة.",
    price: 22.0,
    popular: true,
    image: "/images/menu/waffle.png",
  },
  {
    id: 53,
    name: "كريب نوتيلا وأوريو",
    category: "معجنات وحلويات",
    description: "كريب محشو بالنوتيلا وبسكويت الأوريو المطحون.",
    price: 25.0,
    popular: true,
    image: "/images/menu/crepe.png",
  },
  {
    id: 54,
    name: "كريب نوتيلا وفواكه موسمية",
    category: "معجنات وحلويات",
    description: "كريب محشو بالنوتيلا والفواكه الموسمية الطازجة.",
    price: 29.0,
    popular: false,
    image: "/images/menu/crepe.png",
  },
  {
    id: 55,
    name: "وافل نوتيلا وفواكه موسمية",
    category: "معجنات وحلويات",
    description: "وافل مع النوتيلا والفواكه الموسمية الطازجة.",
    price: 27.0,
    popular: false,
    image: "/images/menu/waffle.png",
  },
  {
    id: 56,
    name: "كريب نوتيلا",
    category: "معجنات وحلويات",
    description: "كريب رقيق كلاسيكي محشو بالنوتيلا الدافئة.",
    price: 19.0,
    popular: true,
    image: "/images/menu/crepe.png",
  },
  {
    id: 57,
    name: "بان كيك نوتيلا",
    category: "معجنات وحلويات",
    description: "طبقات من البان كيك الهش يتخللها النوتيلا.",
    price: 21.0,
    popular: true,
    image: "/images/menu/pancakes.png",
  },
  {
    id: 58,
    name: "وافل نوتيلا",
    category: "معجنات وحلويات",
    description: "وافل ذهبي مغطى بسخاء بالنوتيلا.",
    price: 19.0,
    popular: true,
    image: "/images/menu/waffle.png",
  },
  {
    id: 59,
    name: "بيثيفييه",
    category: "معجنات وحلويات",
    description:
      "فطيرة دائرية مغلقة مصنوعة من العجين المورق مع حشوة حلوة.",
    price: 5.0,
    popular: false,
    image: "/images/menu/Pithiviers.png",
  },
  {
    id: 60,
    name: "ميني كيك بالتوت",
    category: "معجنات وحلويات",
    description: "كيكة صغيرة بنكهة التوت الحلو.",
    price: 8.0,
    popular: false,
    image: "/images/menu/minicake.png",
  },
  {
    id: 61,
    name: "شريحة باوند كيك",
    category: "معجنات وحلويات",
    description: "شريحة شخصية من الباوند كيك الطري.",
    price: 15.0,
    popular: false,
    image: "/images/menu/pound-cake.png",
  },
  {
    id: 62,
    name: "بسبوسة بالفانيليا",
    category: "معجنات وحلويات",
    description: "كيكة سميد حلوة كلاسيكية مشربة بشراب الفانيليا.",
    price: 6.0,
    popular: false,
    image: "/images/menu/basbousa.png",
  },
  {
    id: 63,
    name: "مادلين بالفانيليا",
    category: "معجنات وحلويات",
    description: "كيكة إسفنجية فرنسية كلاسيكية غنية بالزبدة على شكل صدفة.",
    price: 1.5,
    popular: false,
    image: "/images/menu/madeleine.png",
  },
  {
    id: 64,
    name: "كرواسون باللوز",
    category: "معجنات وحلويات",
    description:
      "كرواسون مورق محشو بكريمة اللوز ومغطى بشرائح اللوز.",
    price: 5.0,
    popular: false,
    image: "/images/menu/croissant.png",
  },
  {
    id: 65,
    name: "مثلث اللوز",
    category: "معجنات وحلويات",
    description:
      "معجنات مورقة على شكل مثلث محشوة بعجينة اللوز الحلوة.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Triangle.png",
  },
  {
    id: 66,
    name: "دانيش بالشوكولاتة",
    category: "معجنات وحلويات",
    description: "معجنات دانيش مورقة متداخلة مع الشوكولاتة الغنية.",
    price: 4.0,
    popular: false,
    image: "/images/menu/Danish.webp",
  },
  {
    id: 67,
    name: "معجنات دانيش",
    category: "معجنات وحلويات",
    description: "معجنات دانيش تقليدية مورقة، غنية بالزبدة وحلوة.",
    price: 3.5,
    popular: false,
    image: "/images/menu/Danish.webp",
  },
  {
    id: 68,
    name: "حرشة",
    category: "معجنات وحلويات",
    description: "خبز سميد مغربي تقليدي مقلي بالمقلاة.",
    price: 2.5,
    popular: false,
    image: "/images/menu/harcha.png",
  },
  {
    id: 69,
    name: "مسمن",
    category: "معجنات وحلويات",
    description: "خبز مسطح مغربي تقليدي مورق ومربع الشكل.",
    price: 4.0,
    popular: false,
    image: "/images/menu/msemmen.png",
  },
  {
    id: 70,
    name: "حرشة بزيت الزيتون",
    category: "معجنات وحلويات",
    description: "خبز سميد مالح محضر بزيت الزيتون الغني.",
    price: 3.5,
    popular: false,
    image: "/images/menu/harcha.png",
  },
  {
    id: 71,
    name: "بان سويس",
    category: "معجنات وحلويات",
    description:
      "معجنات مورقة ملفوفة مع كاسترد الفانيليا ورقائق الشوكولاتة.",
    price: 3.0,
    popular: false,
    image: "/images/menu/pain-suisse.png",
  },
  {
    id: 72,
    name: "بان أو شوكولا / كرواسون",
    category: "معجنات وحلويات",
    description: "معجنات فطور فرنسية كلاسيكية مورقة وغنية بالزبدة.",
    price: 2.5,
    popular: false,
    image: "/images/menu/croissant.png",
  },

  // BAKERY
  {
    id: 73,
    name: "خبز الشعير",
    category: "مخبزة",
    description: "خبز شعير مغربي صحي ومشبع.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 74,
    name: "بطبوط",
    category: "مخبزة",
    description: "خبز مغربي طري مطبوخ في المقلاة.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 75,
    name: "بريوش بالشوكولاتة",
    category: "مخبزة",
    description: "خبز حلو طري وهش محشو برقائق الشوكولاتة.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 76,
    name: "باجيت كلاسيكي",
    category: "مخبزة",
    description: "باجيت فرنسي تقليدي مقرمش وطري من الداخل.",
    price: 1.5,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 77,
    name: "خبز كلاسيكي",
    category: "مخبزة",
    description: "خبز مغربي تقليدي دائري وطري.",
    price: 1.5,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 78,
    name: "بريوش كلاسيكي",
    category: "مخبزة",
    description: "خبز حلو تقليدي غني بالزبدة، طري وهش.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 79,
    name: "خبز الذرة",
    category: "مخبزة",
    description: "خبز دقيق الذرة المغربي الريفي واللذيذ.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 80,
    name: "خبز الزنجبيل (بان ديبس)",
    category: "مخبزة",
    description: "خبز التوابل الفرنسي التقليدي بالعسل واليانسون.",
    price: 24.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 81,
    name: "باجيت متعدد الحبوب",
    category: "مخبزة",
    description:
      "باجيت مقرمش مخبوز بمزيج من البذور والحبوب الصحية.",
    price: 4.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 82,
    name: "باجيت بالزيتون",
    category: "مخبزة",
    description: "باجيت مالح مخبوز مع قطع من الزيتون الأسود والأخضر.",
    price: 5.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 83,
    name: "خبز بالزيتون",
    category: "مخبزة",
    description: "خبز دائري تقليدي طري مخبوز مع زيتون مالح.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 84,
    name: "خبز قمح بدون ملح",
    category: "مخبزة",
    description: "خبز قمح كامل صحي محضر بدون ملح مضاف.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 85,
    name: "باجيت سميد",
    category: "مخبزة",
    description: "باجيت مصنوع من دقيق السميد لقرمشة ريفية.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 86,
    name: "خبز سميد",
    category: "مخبزة",
    description: "خبز دائري مغربي تقليدي مصنوع من السميد.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 87,
    name: "باجيت بالسمسم",
    category: "مخبزة",
    description:
      "باجيت فرنسي مقرمش طازج مزين ببذور السمسم.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 88,
    name: "لفافة بالسمسم",
    category: "مخبزة",
    description: "لفافة خبز طرية مغطاة بسخاء ببذور السمسم.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 89,
    name: "باجيت فيينوا",
    category: "مخبزة",
    description: "خبز على طراز فيينا، طري وحلو قليلاً وغني.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 90,
    name: "باجيت قمح كامل",
    category: "مخبزة",
    description: "باجيت فرنسي صحي ومشبع من القمح الكامل.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 91,
    name: "خبز قمح كامل",
    category: "مخبزة",
    description: "خبز دائري مغربي تقليدي مغذي من القمح الكامل.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 92,
    name: "لفافة قمح كامل",
    category: "مخبزة",
    description: "لفافة خبز صحية وطرية من القمح الكامل.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.png",
  },

  // HOT DRINKS
  {
    id: 93,
    name: "شاي أسود (ليبتون)",
    category: "مشروبات ساخنة",
    description: "شاي ليبتون الأسود الكلاسيكي.",
    price: 12.0,
    popular: false,
    image: "/images/menu/tea.png",
  },
  {
    id: 94,
    name: "شوكولاتة ساخنة",
    category: "مشروبات ساخنة",
    description: "حليب دافئ ومريح مع الشوكولاتة الغنية.",
    price: 12.0,
    popular: true,
    image: "/images/menu/hot-chocolate.png",
  },
  {
    id: 95,
    name: "حليب ساخن",
    category: "مشروبات ساخنة",
    description: "حليب مبخر بسيط ومريح.",
    price: 12.0,
    popular: false,
    image: "/images/menu/hot-milk.png",
  },
  {
    id: 96,
    name: "شاي لويزة",
    category: "مشروبات ساخنة",
    description: "شاي أعشاب محضر من أوراق اللويزة الطبيعية.",
    price: 12.0,
    popular: false,
    image: "/images/menu/tea.png",
  },
  {
    id: 97,
    name: "شاي بالحليب (ليبتون)",
    category: "مشروبات ساخنة",
    description: "شاي ليبتون الأسود الكلاسيكي محضر مع الحليب.",
    price: 12.0,
    popular: false,
    image: "/images/menu/milk-tea.png",
  },
  {
    id: 98,
    name: "حليب باللويزة",
    category: "مشروبات ساخنة",
    description: "حليب دافئ منقوع باللويزة المهدئة.",
    price: 12.0,
    popular: false,
    image: "/images/menu/milk-tea.png",
  },
  {
    id: 99,
    name: "حليب بالسيرو (الشراب)",
    category: "مشروبات ساخنة",
    description: "حليب بارد أو دافئ بنكهة الشراب الحلو.",
    price: 11.0,
    popular: false,
    image: "/images/menu/hot-milk.png",
  },
  {
    id: 100,
    name: "شاي مغربي بالنعناع",
    category: "مشروبات ساخنة",
    description: "شاي أخضر تقليدي محضر مع النعناع الطازج.",
    price: 11.0,
    popular: true,
    image: "/images/menu/teapot.png",
  },

  // COLD DRINKS
  {
    id: 101,
    name: "أفوغاتو",
    category: "مشروبات باردة",
    description: "كرة من آيس كريم الفانيليا غارقة في إسبريسو ساخن.",
    price: 18.0,
    popular: false,
    image: "/images/menu/Affogato.png",
  },
  {
    id: 102,
    name: "ميلك شيك موز",
    category: "مشروبات باردة",
    description: "مخفوق الموز الحلو والكريمي.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milk-shake.png",
  },
  {
    id: 103,
    name: "سموثي موز",
    category: "مشروبات باردة",
    description: "سموثي موز ممزوج وكريمي.",
    price: 23.0,
    popular: false,
    image: "/images/menu/Smoothie.png",
  },
  {
    id: 104,
    name: "موهيتو أزرق",
    category: "مشروبات باردة",
    description: "مشروب حمضيات ونعناع مع شراب الكوراكاو الأزرق.",
    price: 22.0,
    popular: false,
    image: "/images/menu/Mojito.png",
  },
  {
    id: 105,
    name: "مشروب غازي (35 سل)",
    category: "مشروبات باردة",
    description: "تشكيلة من المشروبات الغازية المنعشة.",
    price: 12.0,
    popular: true,
    image: "/images/menu/Soda.png",
  },
  {
    id: 106,
    name: "ميلك شيك شوكولاتة",
    category: "مشروبات باردة",
    description: "مخفوق الشوكولاتة الغني والكريمي.",
    price: 23.0,
    popular: true,
    image: "/images/menu/milk-shake.png",
  },
  {
    id: 107,
    name: "كوكتيل استوائي",
    category: "مشروبات باردة",
    description: "مزيج المانجو، البرتقال، والأناناس.",
    price: 21.0,
    popular: true,
    image: "/images/menu/Cocktail.png",
  },
  {
    id: 108,
    name: "سموثي استوائي",
    category: "مشروبات باردة",
    description: "مزيج منعش من الفواكه الاستوائية.",
    price: 26.0,
    popular: false,
    image: "/images/menu/Smoothie.png",
  },
  {
    id: 109,
    name: "مكياتو كراميل مثلج",
    category: "مشروبات باردة",
    description: "حليب وإسبريسو مثلج، بنكهة الفانيليا والكراميل.",
    price: 21.0,
    popular: true,
    image: "/images/menu/iced-caramel.png",
  },
  {
    id: 110,
    name: "قهوة مثلجة",
    category: "مشروبات باردة",
    description: "قهوة مبردة بالثلج مع اختيار النكهة.",
    price: 18.0,
    popular: false,
    image: "/images/menu/iced-coffee.png",
  },
  {
    id: 111,
    name: "فرابتشينو مثلج",
    category: "مشروبات باردة",
    description:
      "مشروب قهوة مثلج ممزوج مع اختيار الفانيليا، الشوكولاتة، أو الكراميل.",
    price: 21.0,
    popular: true,
    image: "/images/menu/iced-frappuccino.png",
  },
  {
    id: 112,
    name: "لاتيه مثلج",
    category: "مشروبات باردة",
    description: "إسبريسو وحليب مبرد على الثلج.",
    price: 19.0,
    popular: true,
    image: "/images/menu/Iced-Latte.png",
  },
  {
    id: 113,
    name: "موكا مثلج",
    category: "مشروبات باردة",
    description: "إسبريسو مثلج مع الشوكولاتة والحليب.",
    price: 19.0,
    popular: true,
    image: "/images/menu/iced-mocha.png",
  },
  {
    id: 114,
    name: "سموثي مانجو",
    category: "مشروبات باردة",
    description: "سموثي مانجو استوائي ممزوج.",
    price: 23.0,
    popular: true,
    image: "/images/menu/smoothie.png",
  },
  {
    id: 115,
    name: "مياه معدنية (33 سل)",
    category: "مشروبات باردة",
    description: "قنينة صغيرة من المياه المعدنية بدون غاز.",
    price: 5.0,
    popular: false,
    image: "/images/menu/Water.png",
  },
  {
    id: 116,
    name: "مياه معدنية (50 سل)",
    category: "مشروبات باردة",
    description: "قنينة متوسطة من المياه المعدنية بدون غاز.",
    price: 7.0,
    popular: true,
    image: "/images/menu/Water.png",
  },
  {
    id: 117,
    name: "ميلك شيك أوريو",
    category: "مشروبات باردة",
    description: "مخفوق فانيليا كريمي ممزوج ببسكويت الأوريو.",
    price: 26.0,
    popular: true,
    image: "/images/menu/milk-shake.png",
  },
  {
    id: 118,
    name: "كوكتيل شرقي",
    category: "مشروبات باردة",
    description: "مزيج الموز، التفاح، والبرتقال.",
    price: 20.0,
    popular: false,
    image: "/images/menu/Cocktail.png",
  },
  {
    id: 119,
    name: "موهيتو أحمر",
    category: "مشروبات باردة",
    description: "مشروب توت أحمر فاكهي مع نعناع وليمون.",
    price: 22.0,
    popular: false,
    image: "/images/menu/Mojito.png",
  },
  {
    id: 120,
    name: "ميلك شيك فراولة",
    category: "مشروبات باردة",
    description: "مخفوق الفراولة الحلو والكريمي.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milk-shake.png",
  },
  {
    id: 121,
    name: "سموثي فراولة",
    category: "مشروبات باردة",
    description: "فراولة طازجة ممزوجة مع الزبادي.",
    price: 23.0,
    popular: true,
    image: "/images/menu/Smoothie.png",
  },
  {
    id: 122,
    name: "كوكتيل استوائي",
    category: "مشروبات باردة",
    description: "مزيج المانجو، الكيوي، والأناناس.",
    price: 21.0,
    popular: false,
    image: "/images/menu/Cocktail.png",
  },
  {
    id: 123,
    name: "ميلك شيك فانيليا",
    category: "مشروبات باردة",
    description: "مخفوق الفانيليا الكلاسيكي الكريمي.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milk-shake.png",
  },
  {
    id: 124,
    name: "فيرجن موهيتو",
    category: "مشروبات باردة",
    description: "مشروب الليمون والنعناع المنعش.",
    price: 19.0,
    popular: true,
    image: "/images/menu/Mojito.png",
  },

  // COFFEES
  {
    id: 125,
    name: "أمريكانو",
    category: "قهوة",
    description: "إسبريسو مخفف بالماء الساخن.",
    price: 14.0,
    popular: false,
    image: "/images/menu/Americano.png",
  },
  {
    id: 126,
    name: "كابتشينو",
    category: "قهوة",
    description: "إسبريسو مغطى بمقادير متساوية من الحليب المبخر والرغوة.",
    price: 15.0,
    popular: true,
    image: "/images/menu/Cappuccino.png",
  },
  {
    id: 127,
    name: "قهوة مع حليب جانبي",
    category: "قهوة",
    description: "إسبريسو يُقدم مع حليب جانبي منفصل.",
    price: 15.0,
    popular: false,
    image: "/images/menu/coffee-milk.png",
  },
  {
    id: 128,
    name: "كورتادو",
    category: "قهوة",
    description: "مقادير متساوية من الإسبريسو والحليب المبخر.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Cortado.png",
  },
  {
    id: 129,
    name: "قهوة بالكريمة",
    category: "قهوة",
    description: "إسبريسو ممزوج بالكريمة المبخرة.",
    price: 12.0,
    popular: true,
    image: "/images/menu/Cream-Coffee.png",
  },
  {
    id: 130,
    name: "إسبريسو مزدوج",
    category: "قهوة",
    description: "جرعتان غنيتان من الإسبريسو المركز.",
    price: 18.0,
    popular: true,
    image: "/images/menu/double-espresso.png",
  },
  {
    id: 131,
    name: "إسبريسو",
    category: "قهوة",
    description: "جرعة غنية ومركزة من القهوة.",
    price: 12.0,
    popular: true,
    image: "/images/menu/Espresso.png",
  },
  {
    id: 132,
    name: "فلات وايت",
    category: "قهوة",
    description: "إسبريسو مع حليب برغوة دقيقة.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Flat-White.png",
  },
  {
    id: 133,
    name: "إسبريسو إيلي",
    category: "قهوة",
    description: "جرعة إسبريسو إيطالية فاخرة من إيلي.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Illy-Espresso.png",
  },
  {
    id: 134,
    name: "لاتيه ماكياتو",
    category: "قهوة",
    description: "حليب مبخر مضاف إليه جرعة من الإسبريسو.",
    price: 16.0,
    popular: true,
    image: "/images/menu/Latte-Macchiato.png",
  },
  {
    id: 135,
    name: "موكا",
    category: "قهوة",
    description: "إسبريسو ممزوج مع الشوكولاتة والحليب المبخر.",
    price: 18.0,
    popular: false,
    image: "/images/menu/mocha.png",
  },
  {
    id: 136,
    name: "قهوة نسبريسو",
    category: "قهوة",
    description: "قهوة نسبريسو كلاسيكية.",
    price: 15.0,
    popular: false,
    image: "/images/menu/Nespresso.png",
  },
  {
    id: 137,
    name: "شوكولاتة فيينوا",
    category: "قهوة",
    description: "شوكولاتة ساخنة مغطاة بكريمة مخفوقة.",
    price: 16.0,
    popular: true,
    image: "/images/menu/Viennese-Chocolate.png",
  },

  // JUICES
  {
    id: 138,
    name: "عصير تفاح",
    category: "عصائر",
    description: "عصير تفاح معصور طازجاً.",
    price: 16.0,
    popular: false,
    image: "/images/menu/juices.png",
  },
  {
    id: 139,
    name: "عصير أفوكادو",
    category: "عصائر",
    description: "عصير أفوكادو ممزوج، غني وكريمي.",
    price: 18.0,
    popular: true,
    image: "/images/menu/juices.png",
  },
  {
    id: 140,
    name: "عصير أفوكادو بالفواكه الجافة",
    category: "عصائر",
    description: "عصير أفوكادو كريمي ممزوج بمزيج من الفواكه الجافة.",
    price: 23.0,
    popular: true,
    image: "/images/menu/juices.png",
  },
  {
    id: 141,
    name: "عصير موز",
    category: "عصائر",
    description: "عصير موز ممزوج طازجاً.",
    price: 16.0,
    popular: false,
    image: "/images/menu/juices.png",
  },
  {
    id: 142,
    name: "عصير مانجو",
    category: "عصائر",
    description: "عصير مانجو استوائي طازج.",
    price: 20.0,
    popular: false,
    image: "/images/menu/juices.png",
  },
  {
    id: 143,
    name: "عصير فواكه مشكلة بالحليب",
    category: "عصائر",
    description: "مزيج من الفواكه المشكلة مع الحليب.",
    price: 18.0,
    popular: true,
    image: "/images/menu/juices.png",
  },
  {
    id: 144,
    name: "عصير فواكه مشكلة بالبرتقال",
    category: "عصائر",
    description: "مزيج من الفواكه المشكلة مع عصير البرتقال.",
    price: 23.0,
    popular: false,
    image: "/images/menu/juices.png",
  },
  {
    id: 145,
    name: "عصير برتقال",
    category: "عصائر",
    description: "عصير برتقال معصور طازجاً.",
    price: 16.0,
    popular: true,
    image: "/images/menu/juices.png",
  },
  {
    id: 146,
    name: "عصير أناناس",
    category: "عصائر",
    description: "عصير أناناس حلو وطازج.",
    price: 23.0,
    popular: false,
    image: "/images/menu/juices.png",
  },
  {
    id: 147,
    name: "عصير فراولة",
    category: "عصائر",
    description: "عصير فراولة ممزوج طازجاً.",
    price: 18.0,
    popular: true,
    image: "/images/menu/juices.png",
  },

  // EXTRAS
  {
    id: 148,
    name: "أملو باللوز",
    category: "إضافات",
    description:
      "أملو فاخر محضر بلوز محمص إضافي. يُقدم مع الخبز.",
    price: 12.0,
    popular: false,
    image: "/images/menu/Almond.png",
  },
  {
    id: 149,
    name: "أملو بزيت الأركان",
    category: "إضافات",
    description:
      "تغميسة تقليدية من اللوز والعسل وزيت الأركان. تُقدم مع الخبز.",
    price: 8.0,
    popular: true,
    image: "/images/menu/argan.png",
  },
  {
    id: 150,
    name: "زيتون أسود وأخضر",
    category: "إضافات",
    description: "زيتون مشكل متبل. يُقدم مع الخبز.",
    price: 5.0,
    popular: false,
    image: "/images/menu/olive.png",
  },
  {
    id: 151,
    name: "جبن للدهن",
    category: "إضافات",
    description: "حصة من الجبن القابل للدهن. تُقدم مع الخبز.",
    price: 3.0,
    popular: true,
    image: "/images/menu/cheese.png",
  },
  {
    id: 152,
    name: "جبن طازج (جُبن)",
    category: "إضافات",
    description:
      "حصة من الجبن المغربي الطازج التقليدي. تُقدم مع الخبز.",
    price: 8.0,
    popular: true,
    image: "/images/menu/Fresh-Cheese.png",
  },
  {
    id: 153,
    name: "عسل",
    category: "إضافات",
    description: "حصة من العسل النقي. تُقدم مع الخبز.",
    price: 6.0,
    popular: true,
    image: "/images/menu/Honey.png",
  },
  {
    id: 154,
    name: "مربى",
    category: "إضافات",
    description: "حصة من مربى الفواكه. تُقدم مع الخبز.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Jam.png",
  },
  {
    id: 155,
    name: "نوتيلا",
    category: "إضافات",
    description: "حصة من دهن البندق والكاكاو الغني. تُقدم مع الخبز.",
    price: 10.0,
    popular: true,
    image: "/images/menu/Nutella.png",
  },
  {
    id: 156,
    name: "زيت زيتون",
    category: "إضافات",
    description:
      "حصة من زيت الزيتون البكر الممتاز عالي الجودة. تُقدم مع الخبز.",
    price: 8.0,
    popular: true,
    image: "/images/menu/Olive-Oil.png",
  },
];

export const shopProducts = [
  // BREAKFAST & SAVORY
  {
    id: 1,
    name: "حساء الشعير (حسوة)",
    category: "فطور ومملحات",
    description:
      "حساء الشعير والحليب المغربي التقليدي الدافئ والمريح.",
    price: 7.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Hesewa.jpg",
  },
  {
    id: 2,
    name: "أومليت بالجبن",
    category: "فطور ومملحات",
    description:
      "أومليت هشة محشوة بالجبن الذائب، تُقدم مع الزيتون وزيت الزيتون.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Omelet.jpg",
  },
  {
    id: 3,
    name: "فطور كونتيننتال",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، أومليت بالجبن، زيت زيتون، زيتون، جبن، خبز، زبادي، وماء.",
    price: 35.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 4,
    name: "أومليت باللحم البارد (كاشير)",
    category: "فطور ومملحات",
    description:
      "أومليت محشوة باللحم البارد، تُقدم مع الزيتون وزيت الزيتون.",
    price: 17.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/Omelet.jpg",
  },
  {
    id: 5,
    name: "فطور إكسبريس",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، معجنات، زبادي، وماء معدني.",
    price: 26.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 6,
    name: "فطور فاسي",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، أومليت باللحم المجفف (القديد)، زيت زيتون، زيتون، جبن، خبز، زبادي، وماء.",
    price: 37.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 7,
    name: "فطور الذواقة",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، زيت زيتون، أملو، زيتون، عسل، خبز، زبادي، وماء.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 8,
    name: "حريرة",
    category: "فطور ومملحات",
    description:
      "الحساء المغربي التقليدي الغني بالطماطم، العدس، والحمص.",
    price: 10.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Soup.jpg",
  },
  {
    id: 9,
    name: "أومليت بالخليع",
    category: "فطور ومملحات",
    description:
      "أومليت تقليدية مع اللحم المغربي المحفوظ (الخليع)، تُقدم مع الزيتون وزيت الزيتون.",
    price: 24.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Omelet.jpg",
  },
  {
    id: 10,
    name: "فطور الأطفال",
    category: "فطور ومملحات",
    description:
      "حليب بالشوكولاتة، عصير برتقال، خبز بالشوكولاتة، كيك بالفانيليا، زبادي، وماء.",
    price: 25.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 11,
    name: "فطور لامادلين",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، اختيارك من الأومليت، زيت زيتون، زيتون، عسل، جبن، أملو، خبز، كريب، شوكولاتة، كيك، زبادي، وماء.",
    price: 55.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 12,
    name: "أومليت عادية",
    category: "فطور ومملحات",
    description: "أومليت بيض بسيطة وهشة تُقدم مع الزيتون وزيت الزيتون.",
    price: 13.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/Omelet.jpg",
  },
  {
    id: 13,
    name: "فطور سوسي",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، أملو، زيت زيتون، جبن، زيتون، عسل، مربى، وماء.",
    price: 38.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 14,
    name: "أومليت بالطماطم",
    category: "فطور ومملحات",
    description:
      "أومليت هشة مع طماطم طازجة، تُقدم مع الزيتون وزيت الزيتون.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Omelet.jpg",
  },
  {
    id: 15,
    name: "فطور تقليدي",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، بغرير، حرشة، عسل، جبن طازج، وماء.",
    price: 28.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.jpg",
  },

  // PASTRIES & DESSERTS
  {
    id: 16,
    name: "سيجار فواكه البحر",
    category: "معجنات وحلويات",
    description: "لفائف مقرمشة محشوة بتشكيلة لذيذة من فواكه البحر.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Cigar.webp",
  },
  {
    id: 17,
    name: "بسطيلة فواكه البحر",
    category: "معجنات وحلويات",
    description:
      "فطيرة مالحة مورقة محشوة بفواكه البحر المتبلة والشعيرية.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pastilla.png",
  },
  {
    id: 18,
    name: "سندويش",
    category: "معجنات وحلويات",
    description: "سندويش مالح محضر طازجاً.",
    price: 8.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/sandwich.jpg",
  },
  {
    id: 19,
    name: "ميني بيتزا",
    category: "معجنات وحلويات",
    description:
      "بيتزا مالحة بحجم صغير مغطاة بالجبن وصلصة الطماطم.",
    price: 6.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/pizza.jpeg",
  },
  {
    id: 20,
    name: "هوت دوج بعجينة مورقة",
    category: "معجنات وحلويات",
    description: "نقانق مالحة ملفوفة ومخبوزة في عجينة طرية.",
    price: 9.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/hot-dog.jpg",
  },
  {
    id: 21,
    name: "بسطيلة بالدجاج",
    category: "معجنات وحلويات",
    description:
      "فطيرة حلوة ومالحة محشوة بالدجاج المتبل واللوز المحمص.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pastilla.png",
  },
  {
    id: 22,
    name: "بريوات بالجبن",
    category: "معجنات وحلويات",
    description: "مثلثات معجنات مغربية مقرمشة محشوة بالجبن المالح.",
    price: 7.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Briouat.jpeg",
  },
  {
    id: 23,
    name: "تارت اللوز",
    category: "معجنات وحلويات",
    description: "قشرة معجنات حلوة ومقرمشة محشوة بكريمة اللوز الكثيفة.",
    price: 10.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Tart.jpg",
  },
  {
    id: 24,
    name: "بان كيك أملو",
    category: "معجنات وحلويات",
    description: "بان كيك هش مغطى بالأملو المغربي التقليدي.",
    price: 17.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Pancakes.jpg",
  },
  {
    id: 25,
    name: "شوسون بالتفاح",
    category: "معجنات وحلويات",
    description: "عجينة مورقة محشوة بكومبوت التفاح الحلو المتبل.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Apple-Turnover.jpg",
  },
  {
    id: 26,
    name: "كريب بالكراميل",
    category: "معجنات وحلويات",
    description: "كريب فرنسي رقيق مطوي مع الكراميل الحلو.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 27,
    name: "وافل بالكراميل",
    category: "معجنات وحلويات",
    description: "وافل ذهبي مغطى بصلصة الكراميل الغنية.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/waffle.jpg",
  },
  {
    id: 28,
    name: "بسبوسة بالشوكولاتة",
    category: "معجنات وحلويات",
    description: "كيكة سميد حلوة بنكهة الشوكولاتة الغنية.",
    price: 8.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.jpg",
  },
  {
    id: 29,
    name: "مادلين بالشوكولاتة",
    category: "معجنات وحلويات",
    description: "كيكة إسفنجية صغيرة على شكل صدفة بنكهة الشوكولاتة.",
    price: 2.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.jpg",
  },
  {
    id: 30,
    name: "كريب كلاسيكي",
    category: "معجنات وحلويات",
    description: "كريب فرنسي بسيط ورقيق وطري.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 31,
    name: "شريحة كيك بالكريمة (10)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 10.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 32,
    name: "شريحة كيك بالكريمة (12)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 33,
    name: "شريحة كيك بالكريمة (13)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 13.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 34,
    name: "شريحة كيك بالكريمة (14)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 14.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 35,
    name: "شريحة كيك بالكريمة (15)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 36,
    name: "شريحة كيك بالكريمة (17)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 17.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 37,
    name: "شريحة كيك بالكريمة (18)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 38,
    name: "دونات",
    category: "معجنات وحلويات",
    description: "دونات كلاسيكية مقلية طرية وحلوة.",
    price: 4.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/donut.jpg",
  },
  {
    id: 39,
    name: "تارت الفرانجيبان",
    category: "معجنات وحلويات",
    description: "تارت معجنات حلوة محشوة بكريمة اللوز الغنية.",
    price: 8.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Frangipane-Tart.jpg",
  },
  {
    id: 40,
    name: "بيثيفييه فواكه",
    category: "معجنات وحلويات",
    description: "فطيرة من العجين المورق محشوة بكومبوت الفواكه الحلو.",
    price: 6.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Pithiviers.jpg",
  },
  {
    id: 41,
    name: "سلطة فواكه مع عصير برتقال",
    category: "معجنات وحلويات",
    description: "فواكه موسمية طازجة منقوعة في عصير برتقال طازج.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/fruit-salad.jpeg",
  },
  {
    id: 42,
    name: "سلطة فواكه مع زبادي",
    category: "معجنات وحلويات",
    description: "فواكه موسمية طازجة ممزوجة بزبادي كريمي.",
    price: 18.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/fruit-salad.jpeg",
  },
  {
    id: 43,
    name: "تارتليت بالفواكه",
    category: "معجنات وحلويات",
    description: "قشرة تارت حلوة صغيرة محشوة بالكاسترد والفواكه الطازجة.",
    price: 7.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Fruit-Tartlet.jpg",
  },
  {
    id: 44,
    name: "بان كيك بالعسل",
    category: "معجنات وحلويات",
    description: "بان كيك هش مغطى بعسل نقي.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pancakes.jpg",
  },
  {
    id: 45,
    name: "باوند كيك كبير",
    category: "معجنات وحلويات",
    description: "كيكة بحجم كبير، غنية بالزبدة وطرية.",
    price: 30.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pound-cake.jpg",
  },
  {
    id: 46,
    name: "باوند كيك وسط",
    category: "معجنات وحلويات",
    description: "كيكة كلاسيكية طرية وحلوة.",
    price: 20.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pound-cake.jpg",
  },
  {
    id: 47,
    name: "ميل فوي",
    category: "معجنات وحلويات",
    description:
      "معجنات فرنسية كلاسيكية بطبقات من العجينة المورقة وكريمة الفانيليا.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/millefeuille.jpg",
  },
  {
    id: 48,
    name: "ميني كيك",
    category: "معجنات وحلويات",
    description: "كيكة صغيرة شخصية، طرية وحلوة.",
    price: 7.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/minicake.png",
  },
  {
    id: 49,
    name: "ميني كب كيك",
    category: "معجنات وحلويات",
    description: "كيكة صغيرة هشة بحجم لقمة مع كريمة تزيين حلوة.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cupcake.png",
  },
  {
    id: 50,
    name: "كريب نوتيلا وموز",
    category: "معجنات وحلويات",
    description: "كريب محشو بالنوتيلا والموز.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 51,
    name: "بان كيك نوتيلا وموز",
    category: "معجنات وحلويات",
    description: "بان كيك يُقدم مع النوتيلا والموز الطازج.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pancakes.jpg",
  },
  {
    id: 52,
    name: "وافل نوتيلا وموز",
    category: "معجنات وحلويات",
    description: "وافل مغطى بالنوتيلا وشرائح الموز الطازجة.",
    price: 22.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.jpg",
  },
  {
    id: 53,
    name: "كريب نوتيلا وأوريو",
    category: "معجنات وحلويات",
    description: "كريب محشو بالنوتيلا وبسكويت الأوريو المطحون.",
    price: 25.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 54,
    name: "كريب نوتيلا وفواكه موسمية",
    category: "معجنات وحلويات",
    description: "كريب محشو بالنوتيلا والفواكه الموسمية الطازجة.",
    price: 29.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 55,
    name: "وافل نوتيلا وفواكه موسمية",
    category: "معجنات وحلويات",
    description: "وافل مع النوتيلا والفواكه الموسمية الطازجة.",
    price: 27.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.jpg",
  },
  {
    id: 56,
    name: "كريب نوتيلا",
    category: "معجنات وحلويات",
    description: "كريب رقيق كلاسيكي محشو بالنوتيلا الدافئة.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 57,
    name: "بان كيك نوتيلا",
    category: "معجنات وحلويات",
    description: "طبقات من البان كيك الهش يتخللها النوتيلا.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pancakes.jpg",
  },
  {
    id: 58,
    name: "وافل نوتيلا",
    category: "معجنات وحلويات",
    description: "وافل ذهبي مغطى بسخاء بالنوتيلا.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/waffle.jpg",
  },
  {
    id: 59,
    name: "بيثيفييه",
    category: "معجنات وحلويات",
    description:
      "فطيرة دائرية مغلقة مصنوعة من العجين المورق مع حشوة حلوة.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Pithiviers.jpg",
  },
  {
    id: 60,
    name: "ميني كيك بالتوت",
    category: "معجنات وحلويات",
    description: "كيكة صغيرة بنكهة التوت الحلو.",
    price: 8.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/minicake.png",
  },
  {
    id: 61,
    name: "شريحة باوند كيك",
    category: "معجنات وحلويات",
    description: "شريحة شخصية من الباوند كيك الطري.",
    price: 15.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pound-cake.jpg",
  },
  {
    id: 62,
    name: "بسبوسة بالفانيليا",
    category: "معجنات وحلويات",
    description: "كيكة سميد حلوة كلاسيكية مشربة بشراب الفانيليا.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.jpg",
  },
  {
    id: 63,
    name: "مادلين بالفانيليا",
    category: "معجنات وحلويات",
    description: "كيكة إسفنجية فرنسية كلاسيكية غنية بالزبدة على شكل صدفة.",
    price: 1.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.jpg",
  },
  {
    id: 64,
    name: "كرواسون باللوز",
    category: "معجنات وحلويات",
    description:
      "كرواسون مورق محشو بكريمة اللوز ومغطى بشرائح اللوز.",
    price: 5.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/croissant.jpg",
  },
  {
    id: 65,
    name: "مثلث اللوز",
    category: "معجنات وحلويات",
    description:
      "معجنات مورقة على شكل مثلث محشوة بعجينة اللوز الحلوة.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Triangle.jpg",
  },
  {
    id: 66,
    name: "دانيش بالشوكولاتة",
    category: "معجنات وحلويات",
    description: "معجنات دانيش مورقة متداخلة مع الشوكولاتة الغنية.",
    price: 4.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Danish.jpg",
  },
  {
    id: 67,
    name: "معجنات دانيش",
    category: "معجنات وحلويات",
    description: "معجنات دانيش تقليدية مورقة، غنية بالزبدة وحلوة.",
    price: 3.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Danish.jpg",
  },
  {
    id: 68,
    name: "حرشة",
    category: "معجنات وحلويات",
    description: "خبز سميد مغربي تقليدي مقلي بالمقلاة.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/harcha.jpg",
  },
  {
    id: 69,
    name: "مسمن",
    category: "معجنات وحلويات",
    description: "خبز مسطح مغربي تقليدي مورق ومربع الشكل.",
    price: 4.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/msemmen.jpg",
  },
  {
    id: 70,
    name: "حرشة بزيت الزيتون",
    category: "معجنات وحلويات",
    description: "خبز سميد مالح محضر بزيت الزيتون الغني.",
    price: 3.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Oil-Harcha.jpg",
  },
  {
    id: 71,
    name: "بان سويس",
    category: "معجنات وحلويات",
    description:
      "معجنات مورقة ملفوفة مع كاسترد الفانيليا ورقائق الشوكولاتة.",
    price: 3.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pain-suisse.jpg",
  },
  {
    id: 72,
    name: "بان أو شوكولا / كرواسون",
    category: "معجنات وحلويات",
    description: "معجنات فطور فرنسية كلاسيكية مورقة وغنية بالزبدة.",
    price: 2.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Pain-au-Chocolat.jpg",
  },

  // BAKERY
  {
    id: 73,
    name: "خبز الشعير",
    category: "مخبزة",
    description: "خبز شعير مغربي صحي ومشبع.",
    price: 2.5,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 74,
    name: "بطبوط",
    category: "مخبزة",
    description: "خبز مغربي طري مطبوخ في المقلاة.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 75,
    name: "بريوش بالشوكولاتة",
    category: "مخبزة",
    description: "خبز حلو طري وهش محشو برقائق الشوكولاتة.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 76,
    name: "باجيت كلاسيكي",
    category: "مخبزة",
    description: "باجيت فرنسي تقليدي مقرمش وطري من الداخل.",
    price: 1.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 77,
    name: "خبز كلاسيكي",
    category: "مخبزة",
    description: "خبز مغربي تقليدي دائري وطري.",
    price: 1.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 78,
    name: "بريوش كلاسيكي",
    category: "مخبزة",
    description: "خبز حلو تقليدي غني بالزبدة، طري وهش.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 79,
    name: "خبز الذرة",
    category: "مخبزة",
    description: "خبز دقيق الذرة المغربي الريفي واللذيذ.",
    price: 2.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 80,
    name: "خبز الزنجبيل (بان ديبس)",
    category: "مخبزة",
    description: "خبز التوابل الفرنسي التقليدي بالعسل واليانسون.",
    price: 24.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 81,
    name: "باجيت متعدد الحبوب",
    category: "مخبزة",
    description:
      "باجيت مقرمش مخبوز بمزيج من البذور والحبوب الصحية.",
    price: 4.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 82,
    name: "باجيت بالزيتون",
    category: "مخبزة",
    description: "باجيت مالح مخبوز مع قطع من الزيتون الأسود والأخضر.",
    price: 5.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 83,
    name: "خبز بالزيتون",
    category: "مخبزة",
    description: "خبز دائري تقليدي طري مخبوز مع زيتون مالح.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 84,
    name: "خبز قمح بدون ملح",
    category: "مخبزة",
    description: "خبز قمح كامل صحي محضر بدون ملح مضاف.",
    price: 3.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 85,
    name: "باجيت سميد",
    category: "مخبزة",
    description: "باجيت مصنوع من دقيق السميد لقرمشة ريفية.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 86,
    name: "خبز سميد",
    category: "مخبزة",
    description: "خبز دائري مغربي تقليدي مصنوع من السميد.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 87,
    name: "باجيت بالسمسم",
    category: "مخبزة",
    description:
      "باجيت فرنسي مقرمش طازج مزين ببذور السمسم.",
    price: 2.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 88,
    name: "لفافة بالسمسم",
    category: "مخبزة",
    description: "لفافة خبز طرية مغطاة بسخاء ببذور السمسم.",
    price: 3.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 89,
    name: "باجيت فيينوا",
    category: "مخبزة",
    description: "خبز على طراز فيينا، طري وحلو قليلاً وغني.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 90,
    name: "باجيت قمح كامل",
    category: "مخبزة",
    description: "باجيت فرنسي صحي ومشبع من القمح الكامل.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 91,
    name: "خبز قمح كامل",
    category: "مخبزة",
    description: "خبز دائري مغربي تقليدي مغذي من القمح الكامل.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 92,
    name: "لفافة قمح كامل",
    category: "مخبزة",
    description: "لفافة خبز صحية وطرية من القمح الكامل.",
    price: 2.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.jpg",
  },

  // HOT DRINKS
  {
    id: 93,
    name: "شاي أسود (ليبتون)",
    category: "مشروبات ساخنة",
    description: "شاي ليبتون الأسود الكلاسيكي.",
    price: 12.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/Lipton.jpg",
  },
  {
    id: 94,
    name: "شوكولاتة ساخنة",
    category: "مشروبات ساخنة",
    description: "حليب دافئ ومريح مع الشوكولاتة الغنية.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/hot-chocolate.jpg",
  },
  {
    id: 95,
    name: "حليب ساخن",
    category: "مشروبات ساخنة",
    description: "حليب مبخر بسيط ومريح.",
    price: 12.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/hot-milk.webp",
  },
  {
    id: 96,
    name: "شاي لويزة",
    category: "مشروبات ساخنة",
    description: "شاي أعشاب محضر من أوراق اللويزة الطبيعية.",
    price: 12.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Lemon-Verbena-Tea.jpg",
  },
  {
    id: 97,
    name: "شاي بالحليب (ليبتون)",
    category: "مشروبات ساخنة",
    description: "شاي ليبتون الأسود الكلاسيكي محضر مع الحليب.",
    price: 12.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Milk-Tea.jpg",
  },
  {
    id: 98,
    name: "حليب باللويزة",
    category: "مشروبات ساخنة",
    description: "حليب دافئ منقوع باللويزة المهدئة.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-tea.jpg",
  },
  {
    id: 99,
    name: "حليب بالسيرو (الشراب)",
    category: "مشروبات ساخنة",
    description: "حليب بارد أو دافئ بنكهة الشراب الحلو.",
    price: 11.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/Milk-Syrup.jpg",
  },
  {
    id: 100,
    name: "شاي مغربي بالنعناع",
    category: "مشروبات ساخنة",
    description: "شاي أخضر تقليدي محضر مع النعناع الطازج.",
    price: 11.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Moroccan-Tea.jpg",
  },

  // COLD DRINKS
  {
    id: 101,
    name: "أفوغاتو",
    category: "مشروبات باردة",
    description: "كرة من آيس كريم الفانيليا غارقة في إسبريسو ساخن.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Affogato.jpg",
  },
  {
    id: 102,
    name: "ميلك شيك موز",
    category: "مشروبات باردة",
    description: "مخفوق الموز الحلو والكريمي.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-shake.jpg",
  },
  {
    id: 103,
    name: "سموثي موز",
    category: "مشروبات باردة",
    description: "سموثي موز ممزوج وكريمي.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Smoothie.jpg",
  },
  {
    id: 104,
    name: "موهيتو أزرق",
    category: "مشروبات باردة",
    description: "مشروب حمضيات ونعناع مع شراب الكوراكاو الأزرق.",
    price: 22.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Mojito.jpg",
  },
  {
    id: 105,
    name: "مشروب غازي (35 سل)",
    category: "مشروبات باردة",
    description: "تشكيلة من المشروبات الغازية المنعشة.",
    price: 12.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/Soda.jpg",
  },
  {
    id: 106,
    name: "ميلك شيك شوكولاتة",
    category: "مشروبات باردة",
    description: "مخفوق الشوكولاتة الغني والكريمي.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/milk-shake.jpg",
  },
  {
    id: 107,
    name: "كوكتيل استوائي",
    category: "مشروبات باردة",
    description: "مزيج المانجو، البرتقال، والأناناس.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Cocktail.jpg",
  },
  {
    id: 108,
    name: "سموثي استوائي",
    category: "مشروبات باردة",
    description: "مزيج منعش من الفواكه الاستوائية.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Smoothie.jpg",
  },
  {
    id: 109,
    name: "مكياتو كراميل مثلج",
    category: "مشروبات باردة",
    description: "حليب وإسبريسو مثلج، بنكهة الفانيليا والكراميل.",
    price: 21.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/iced-caramel.jpg",
  },
  {
    id: 110,
    name: "قهوة مثلجة",
    category: "مشروبات باردة",
    description: "قهوة مبردة بالثلج مع اختيار النكهة.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/iced-coffee.jpg",
  },
  {
    id: 111,
    name: "فرابتشينو مثلج",
    category: "مشروبات باردة",
    description:
      "مشروب قهوة مثلج ممزوج مع اختيار الفانيليا، الشوكولاتة، أو الكراميل.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-frappuccino.jpg",
  },
  {
    id: 112,
    name: "لاتيه مثلج",
    category: "مشروبات باردة",
    description: "إسبريسو وحليب مبرد على الثلج.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Iced-Latte.jpg",
  },
  {
    id: 113,
    name: "موكا مثلج",
    category: "مشروبات باردة",
    description: "إسبريسو مثلج مع الشوكولاتة والحليب.",
    price: 19.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-mocha.jpg",
  },
  {
    id: 114,
    name: "سموثي مانجو",
    category: "مشروبات باردة",
    description: "سموثي مانجو استوائي ممزوج.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/smoothie.jpg",
  },
  {
    id: 115,
    name: "مياه معدنية (33 سل)",
    category: "مشروبات باردة",
    description: "قنينة صغيرة من المياه المعدنية بدون غاز.",
    price: 5.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/Water.webp",
  },
  {
    id: 116,
    name: "مياه معدنية (50 سل)",
    category: "مشروبات باردة",
    description: "قنينة متوسطة من المياه المعدنية بدون غاز.",
    price: 7.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/Water.webp",
  },
  {
    id: 117,
    name: "ميلك شيك أوريو",
    category: "مشروبات باردة",
    description: "مخفوق فانيليا كريمي ممزوج ببسكويت الأوريو.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/milk-shake.jpg",
  },
  {
    id: 118,
    name: "كوكتيل شرقي",
    category: "مشروبات باردة",
    description: "مزيج الموز، التفاح، والبرتقال.",
    price: 20.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cocktail.jpg",
  },
  {
    id: 119,
    name: "موهيتو أحمر",
    category: "مشروبات باردة",
    description: "مشروب توت أحمر فاكهي مع نعناع وليمون.",
    price: 22.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Mojito.jpg",
  },
  {
    id: 120,
    name: "ميلك شيك فراولة",
    category: "مشروبات باردة",
    description: "مخفوق الفراولة الحلو والكريمي.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/milk-shake.jpg",
  },
  {
    id: 121,
    name: "سموثي فراولة",
    category: "مشروبات باردة",
    description: "فراولة طازجة ممزوجة مع الزبادي.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Smoothie.jpg",
  },
  {
    id: 122,
    name: "كوكتيل استوائي",
    category: "مشروبات باردة",
    description: "مزيج المانجو، الكيوي، والأناناس.",
    price: 21.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Cocktail.jpg",
  },
  {
    id: 123,
    name: "ميلك شيك فانيليا",
    category: "مشروبات باردة",
    description: "مخفوق الفانيليا الكلاسيكي الكريمي.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/milk-shake.jpg",
  },
  {
    id: 124,
    name: "فيرجن موهيتو",
    category: "مشروبات باردة",
    description: "مشروب الليمون والنعناع المنعش.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Mojito.jpg",
  },

  // COFFEES
  {
    id: 125,
    name: "أمريكانو",
    category: "قهوة",
    description: "إسبريسو مخفف بالماء الساخن.",
    price: 14.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/Americano.jpg",
  },
  {
    id: 126,
    name: "كابتشينو",
    category: "قهوة",
    description: "إسبريسو مغطى بمقادير متساوية من الحليب المبخر والرغوة.",
    price: 15.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Cappuccino.jpg",
  },
  {
    id: 127,
    name: "قهوة مع حليب جانبي",
    category: "قهوة",
    description: "إسبريسو يُقدم مع حليب جانبي منفصل.",
    price: 15.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/coffee-milk.jpg",
  },
  {
    id: 128,
    name: "كورتادو",
    category: "قهوة",
    description: "مقادير متساوية من الإسبريسو والحليب المبخر.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Cortado.jpg",
  },
  {
    id: 129,
    name: "قهوة بالكريمة",
    category: "قهوة",
    description: "إسبريسو ممزوج بالكريمة المبخرة.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cream-Coffee.jpg",
  },
  {
    id: 130,
    name: "إسبريسو مزدوج",
    category: "قهوة",
    description: "جرعتان غنيتان من الإسبريسو المركز.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/double-espresso.jpg",
  },
  {
    id: 131,
    name: "إسبريسو",
    category: "قهوة",
    description: "جرعة غنية ومركزة من القهوة.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Espresso.jpg",
  },
  {
    id: 132,
    name: "فلات وايت",
    category: "قهوة",
    description: "إسبريسو مع حليب برغوة دقيقة.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Flat-White.png",
  },
  {
    id: 133,
    name: "إسبريسو إيلي",
    category: "قهوة",
    description: "جرعة إسبريسو إيطالية فاخرة من إيلي.",
    price: 16.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Illy-Espresso.jpg",
  },
  {
    id: 134,
    name: "لاتيه ماكياتو",
    category: "قهوة",
    description: "حليب مبخر مضاف إليه جرعة من الإسبريسو.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Latte-Macchiato.jpg",
  },
  {
    id: 135,
    name: "موكا",
    category: "قهوة",
    description: "إسبريسو ممزوج مع الشوكولاتة والحليب المبخر.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/mocha.png",
  },
  {
    id: 136,
    name: "قهوة نسبريسو",
    category: "قهوة",
    description: "قهوة نسبريسو كلاسيكية.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Nespresso.jpg",
  },
  {
    id: 137,
    name: "شوكولاتة فيينوا",
    category: "قهوة",
    description: "شوكولاتة ساخنة مغطاة بكريمة مخفوقة.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Viennese-Chocolate.jpg",
  },

  // JUICES
  {
    id: 138,
    name: "عصير تفاح",
    category: "عصائر",
    description: "عصير تفاح معصور طازجاً.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Apple-Juice.jpg",
  },
  {
    id: 139,
    name: "عصير أفوكادو",
    category: "عصائر",
    description: "عصير أفوكادو ممزوج، غني وكريمي.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Avocado-Juice.jpg",
  },
  {
    id: 140,
    name: "عصير أفوكادو بالفواكه الجافة",
    category: "عصائر",
    description: "عصير أفوكادو كريمي ممزوج بمزيج من الفواكه الجافة.",
    price: 23.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Avocado-Juice-with-Dried-Fruits.jpg",
  },
  {
    id: 141,
    name: "عصير موز",
    category: "عصائر",
    description: "عصير موز ممزوج طازجاً.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Banana-Juice.jpg",
  },
  {
    id: 142,
    name: "عصير مانجو",
    category: "عصائر",
    description: "عصير مانجو استوائي طازج.",
    price: 20.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Mango-Juice.jpg",
  },
  {
    id: 143,
    name: "عصير فواكه مشكلة بالحليب",
    category: "عصائر",
    description: "مزيج من الفواكه المشكلة مع الحليب.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Mixed-Fruit-Juice-with-Milk.jpg",
  },
  {
    id: 144,
    name: "عصير فواكه مشكلة بالبرتقال",
    category: "عصائر",
    description: "مزيج من الفواكه المشكلة مع عصير البرتقال.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Mixed-Fruit-Juice-with-Orange.jpg",
  },
  {
    id: 145,
    name: "عصير برتقال",
    category: "عصائر",
    description: "عصير برتقال معصور طازجاً.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Orange-Juice.jpg",
  },
  {
    id: 146,
    name: "عصير أناناس",
    category: "عصائر",
    description: "عصير أناناس حلو وطازج.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Pineapple-Juice.jpg",
  },
  {
    id: 147,
    name: "عصير فراولة",
    category: "عصائر",
    description: "عصير فراولة ممزوج طازجاً.",
    price: 18.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Strawberry-Juice.jpg",
  },

  // EXTRAS
  {
    id: 148,
    name: "أملو باللوز",
    category: "إضافات",
    description:
      "أملو فاخر محضر بلوز محمص إضافي. يُقدم مع الخبز.",
    price: 12.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Almond.jpeg",
  },
  {
    id: 149,
    name: "أملو بزيت الأركان",
    category: "إضافات",
    description:
      "تغميسة تقليدية من اللوز والعسل وزيت الأركان. تُقدم مع الخبز.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/argan.jpg",
  },
  {
    id: 150,
    name: "زيتون أسود وأخضر",
    category: "إضافات",
    description: "زيتون مشكل متبل. يُقدم مع الخبز.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/olive.jpg",
  },
  {
    id: 151,
    name: "جبن للدهن",
    category: "إضافات",
    description: "حصة من الجبن القابل للدهن. تُقدم مع الخبز.",
    price: 3.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cheese.jpg",
  },
  {
    id: 152,
    name: "جبن طازج (جُبن)",
    category: "إضافات",
    description:
      "حصة من الجبن المغربي الطازج التقليدي. تُقدم مع الخبز.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Fresh-Cheese.jpg",
  },
  {
    id: 153,
    name: "عسل",
    category: "إضافات",
    description: "حصة من العسل النقي. تُقدم مع الخبز.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Honey.jpg",
  },
  {
    id: 154,
    name: "مربى",
    category: "إضافات",
    description: "حصة من مربى الفواكه. تُقدم مع الخبز.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Jam.jpg",
  },
  {
    id: 155,
    name: "نوتيلا",
    category: "إضافات",
    description: "حصة من دهن البندق والكاكاو الغني. تُقدم مع الخبز.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Nutella.jpg",
  },
  {
    id: 156,
    name: "زيت زيتون",
    category: "إضافات",
    description:
      "حصة من زيت الزيتون البكر الممتاز عالي الجودة. تُقدم مع الخبز.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Olive-Oil.jpg",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Ryu Zaki",
    role: "زبون دائم",
    quote:
      "مقهى جميل يقدم مخبوزات ومعجنات جيدة جداً. عصائر الفواكه ممتازة.",
    rating: 5,
  },
  {
    id: 2,
    name: "Halima Elmkiess",
    role: "زبونة دائمة",
    quote:
      "مكان رائع حيث يمكنك العثور على كل ما تريد. الموظفون رائعون 😊 مؤسسة نظيفة جداً. الطعام لذيذ تماماً. أنا حقاً، حقاً أحبه. شكراً جزيلاً لخدمتكم! ☺️",
    rating: 5,
  },
  {
    id: 3,
    name: "Soufiane Driver",
    role: "زبون دائم",
    quote: "مكان هادئ جداً مع خدمة جيدة وأشخاص ودودين!",
    rating: 4,
  },
];

export const locations = [
  {
    id: 1,
    name: "لامادلين — تيليلا",
    address: "شارع الألفة، تيليلا، أكادير 80000",
    phone: "05.28.26.43.44",
    hours: "الإثنين–الأحد 6ص–10م",
    mapUrl: "https://maps.app.goo.gl/Z5memQUhJrBtShyx7",
  },
];

export const faqData = [
  {
    id: 1,
    category: "عام",
    question: "ما هي أوقات العمل الخاصة بكم؟",
    answer: "نحن نفتح من الإثنين إلى الأحد من الساعة 6:00 صباحاً حتى 10:00 مساءً.",
  },
  {
    id: 2,
    category: "عام",
    question: "هل تقدمون خدمة الأكل في المكان أم للطلبات الخارجية فقط؟",
    answer:
      "كلاهما! لدينا منطقة جلوس جميلة مع طاولات داخلية وخارجية. استمتع بالمعجنات المخبوزة طازجاً والقهوة في مساحتنا الدافئة والمرحبة.",
  },
  {
    id: 3,
    category: "المنتجات",
    question: "هل منتجاتكم مصنوعة من مكونات عضوية؟",
    answer:
      "نحن نستورد أفضل المكونات المتاحة. في حين أن ليس كل شيء عضوي معتمد، فإننا نعطي الأولوية للجودة والاستدامة.",
  },
  {
    id: 4,
    category: "الطلبات",
    question: "ما هي طرق الدفع التي تقبلونها؟",
    answer: "نحن نقبل الدفع نقداً فقط في الوقت الحالي.",
  },
  {
    id: 5,
    category: "الطلبات",
    question: "هل يمكنني تقديم طلب للتوصيل؟",
    answer:
      "في الوقت الحالي، لا نقدم خدمة التوصيل أو الطلب عبر الإنترنت. لتقديم طلب، ما عليك سوى الاتصال بنا مباشرة أو زيارة المخبزة، وسيكون فريقنا سعيداً بمساعدتك.",
  },
  {
    id: 6,
    category: "الطلبات",
    question: "هل توفرون خدمة تقديم الطعام (الكاترينج) للمناسبات وحفلات الزفاف؟",
    answer:
      "يسعدنا أن نكون جزءاً من يومك المميز! نقدم باقات تقديم طعام مخصصة لحفلات الزفاف، فعاليات الشركات، والحفلات الخاصة. اتصل بنا قبل أسبوع على الأقل للطلبات المخصصة.",
  },
  {
    id: 7,
    category: "عام",
    question: "هل يتوفر موقف سيارات بالقرب من مخبزتكم؟",
    answer:
      "تتوفر مواقف للسيارات في الجوار، ويمكن الوصول إلى مخبزتنا بسهولة عن طريق وسائل النقل العام أو السيارة.",
  },
];