export const siteConfig = {
  name: "LaMadeleine Agadir",
  tagline: "Artisan Bakery & Coffee House",
  description:
    "Handcrafted pastries, artisan bread, and exceptional coffee — an authentic French & Moroccan bakery experience since 2018.",
  phone: "05.28.26.43.44",
  email: "contact@lamadeleine.ma",
  address: "Av. Al Oulfa, Tilila, Agadir 80000",
  social: {
    instagram: "https://instagram.com/lamadeleine.agadir",
    facebook: "https://facebook.com/lamadeleine.agadir",
  },
  hours: [{ day: "Monday — Sunday", time: "6:00 AM — 10:00 PM" }],
  science: 2018,
  mapLink: "https://maps.app.goo.gl/Z5memQUhJrBtShyx7",
};

type TodaysSpecial = {
  id: number;
  name: string;
  category: string;
  description: string;
  price: number;
  image: string;
};

export const todaysSpecials: TodaysSpecial[] = [
  {
    id: 1,
    name: "Pain au Chocolat",
    category: "Pastry",
    description:
      "Buttery, flaky layers wrapped around two bars of premium dark chocolate — the quintessential French breakfast pastry.",
    price: 2.5,
    image: "/images/today-specials/today-3.webp",
  },
  {
    id: 2,
    name: "Butter Croissant",
    category: "Breakfast",
    description:
      "Golden, impossibly light croissant made with 84% fat Norman butter. 72-hour ferment for perfect lamination.",
    price: 2.5,
    image: "/images/today-specials/today-1.webp",
  },
  {
    id: 3,
    name: "Croissant Sandwich",
    category: "Breakfast",
    description:
      "A classic French breakfast pastry filled with a rich, buttery cream and finished with a light dusting of powdered sugar.",
    price: 5,
    image: "/images/today-specials/today-2.webp",
  },
  {
    id: 4,
    name: "Fruit Tart",
    category: "Dessert",
    description:
      "Seasonal fruits arranged on vanilla pastry cream, nestled in a crisp, caramelized tart shell.",
    price: 7,
    image: "/images/today-specials/today-4.webp",
  },
  {
    id: 5,
    name: "Almond Mille-Feuille",
    category: "Dessert",
    description:
      "Three layers of caramelized puff pastry alternating with a light, almond cream, topped with toasted almond flakes and a dusting of powdered sugar.",
    price: 10,
    image: "/images/today-specials/today-5.webp",
  },
  {
    id: 6,
    name: "MadLine Signature Cortado",
    category: "Coffee",
    description:
      "Equal parts intensely rich espresso and perfectly textured steamed milk, dusted with a hint of warm spices.",
    price: 12,
    image: "/images/today-specials/today-6.webp",
  },
];

export const coffeeMenu = [
  {
    id: 1,
    name: "Mocha",
    description: "Espresso combined with chocolate and steamed milk.",
    price: 18.0,
    icon: "Cookie",
  },
  {
    id: 2,
    name: "Cappuccino",
    description: "Espresso topped with equal parts steamed milk and foam.",
    price: 15.0,
    icon: "Milk",
  },
  {
    id: 3,
    name: "Coffee on the Side",
    description: "Espresso served with a separate side of milk.",
    price: 15.0,
    icon: "Coffee",
  },
  {
    id: 4,
    name: "Cortado",
    description: "Equal parts espresso and steamed milk.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 5,
    name: "Cream Coffee",
    description: "Espresso mixed with steamed cream.",
    price: 12.0,
    icon: "Cookie",
  },
  {
    id: 6,
    name: "Double Espresso",
    description: "Two rich shots of intense espresso.",
    price: 18.0,
    icon: "Droplets",
  },
  {
    id: 7,
    name: "Espresso",
    description: "Rich and intense shot of coffee.",
    price: 12.0,
    icon: "Coffee",
  },
  {
    id: 8,
    name: "Flat White",
    description: "Espresso with micro-foamed milk.",
    price: 16.0,
    icon: "Milk",
  },
  {
    id: 9,
    name: "Illy Espresso",
    description: "Premium Italian Illy espresso shot.",
    price: 16.0,
    icon: "Sparkles",
  },
  {
    id: 10,
    name: "Americano",
    description: "Espresso diluted with hot water.",
    price: 14.0,
    icon: "Coffee",
  },
  {
    id: 11,
    name: "Latte Macchiato",
    description: "Steamed milk marked with a shot of espresso.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 12,
    name: "Nespresso Coffee",
    description: "Classic Nespresso brewed coffee.",
    price: 15.0,
    icon: "Coffee",
  },
];

export const menuCategories = [
  "Breakfast",
  "Pastry",
  "Coffee",
  "Milk & Tea",
  "Cold Drinks",
];

export const menuItems = [
  {
    id: 1,
    name: "Express Breakfast",
    category: "Breakfast",
    description:
      "Hssoua, a hot drink, fresh orange juice, a basket of viennoiseries, yogurt, and mineral water.",
    price: 26.0,
    popular: false,
    image: "/images/menu/breakfast-express.webp",
  },
  {
    id: 2,
    name: "Beldi Breakfast",
    category: "Breakfast",
    description:
      "Hssoua, a hot drink, fresh orange juice, msemen or meloui, harcha, honey, jben cheese, and mineral water.",
    price: 28.0,
    popular: false,
    image: "/images/menu/breakfast-beldi.webp",
  },
  {
    id: 3,
    name: "Continental Breakfast",
    category: "Breakfast",
    description:
      "Hssoua, a hot drink, fresh orange juice, cheese omelet, olive oil, olives, jben cheese, a bread basket, mineral water, and yogurt.",
    price: 35.0,
    popular: false,
    image: "/images/menu/breakfast-continental.webp",
  },
  {
    id: 4,
    name: "Fassi Breakfast",
    category: "Breakfast",
    description:
      "Hssoua, a hot drink, fresh orange juice, dried-beef (khliî) omelet, olive oil, olives, jben cheese, a bread basket, mineral water, and yogurt.",
    price: 37.0,
    popular: false,
    image: "/images/menu/breakfast-fassi.webp",
  },
  {
    id: 5,
    name: "Soussi Breakfast",
    category: "Breakfast",
    description:
      "Hssoua, a hot drink, fresh orange juice, amlou, olive oil, jben cheese, black and green olives, honey, jam, and mineral water.",
    price: 38.0,
    popular: true,
    image: "/images/menu/breakfast-soussi.webp",
  },
  {
    id: 6,
    name: "Gourmand Breakfast",
    category: "Breakfast",
    description:
      "Hssoua, a hot drink, fresh orange juice, olive oil, amlou, black olives, honey, a bread basket, yogurt, and mineral water.",
    price: 26.0,
    popular: false,
    image: "/images/menu/breakfast-gourmand.webp",
  },
  {
    id: 7,
    name: "La Madeleine Breakfast",
    category: "Breakfast",
    description:
      "Our signature spread: hssoua, a hot drink, fresh orange juice, omelet (cheese / charcuterie / tomato), olive oil, olives, honey, jben cheese, amlou, a bread basket, crepe, chocolate spread, American cake, mineral water, and yogurt.",
    price: 55.0,
    popular: true,
    image: "/images/menu/breakfast-la-madeleine.webp",
  },
  {
    id: 8,
    name: "Kids Breakfast",
    category: "Breakfast",
    description:
      "Chocolate milk, fresh orange juice, a bread roll, vanilla cake, mineral water, and yogurt.",
    price: 25.0,
    popular: false,
    image: "/images/menu/breakfast-kids.webp",
  },
  {
    id: 9,
    name: "Plain Omelet (2 eggs)",
    category: "Omelets",
    description: "Simple two-egg omelet, served with olives and olive oil.",
    price: 13.0,
    popular: false,
    image: "/images/menu/omelet-nature.webp",
  },
  {
    id: 10,
    name: "Plain Omelet (4 eggs)",
    category: "Omelets",
    description: "Hearty four-egg omelet, served with olives and olive oil.",
    price: 18.0,
    popular: false,
    image: "/images/menu/omelet-nature.webp",
  },
  {
    id: 11,
    name: "Tomato Omelet (2 eggs)",
    category: "Omelets",
    description:
      "Two-egg omelet with fresh tomato, served with olives and olive oil.",
    price: 16.0,
    popular: false,
    image: "/images/menu/omelet-tomato.webp",
  },
  {
    id: 12,
    name: "Tomato Omelet (4 eggs)",
    category: "Omelets",
    description:
      "Four-egg omelet with fresh tomato, served with olives and olive oil.",
    price: 20.0,
    popular: false,
    image: "/images/menu/omelet-tomato.webp",
  },
  {
    id: 13,
    name: "Cheese Omelet (2 eggs)",
    category: "Omelets",
    description:
      "Fluffy two-egg omelet loaded with melted cheese, served with olives and olive oil.",
    price: 16.0,
    popular: true,
    image: "/images/menu/omelet-cheese.webp",
  },
  {
    id: 14,
    name: "Cheese Omelet (4 eggs)",
    category: "Omelets",
    description:
      "Fluffy four-egg omelet loaded with melted cheese, served with olives and olive oil.",
    price: 22.0,
    popular: false,
    image: "/images/menu/omelet-cheese.webp",
  },
  {
    id: 15,
    name: "Dried Beef Omelet (Khliî, 2 eggs)",
    category: "Omelets",
    description:
      "Two-egg omelet with khliî (Moroccan spiced dried beef), served with olives and olive oil.",
    price: 18.0,
    popular: false,
    image: "/images/menu/omelet-khlii.webp",
  },
  {
    id: 16,
    name: "Dried Beef Omelet (Khliî, 4 eggs)",
    category: "Omelets",
    description:
      "Four-egg omelet with khliî (Moroccan spiced dried beef), served with olives and olive oil.",
    price: 24.0,
    popular: false,
    image: "/images/menu/omelet-khlii.webp",
  },
  {
    id: 17,
    name: "Charcuterie Omelet (2 eggs)",
    category: "Omelets",
    description:
      "Two-egg omelet with charcuterie, served with olives and olive oil.",
    price: 17.0,
    popular: false,
    image: "/images/menu/omelet-charcuterie.webp",
  },
  {
    id: 18,
    name: "Charcuterie Omelet (4 eggs)",
    category: "Omelets",
    description:
      "Four-egg omelet with charcuterie, served with olives and olive oil.",
    price: 23.0,
    popular: false,
    image: "/images/menu/omelet-charcuterie.webp",
  },
  {
    id: 19,
    name: "Amlou",
    category: "Extras",
    description:
      "Traditional almond, argan oil and honey spread, served with bread.",
    price: 8.0,
    popular: false,
    image: "/images/menu/amlou.webp",
  },
  {
    id: 20,
    name: "Amlou with Almonds",
    category: "Extras",
    description:
      "Amlou spread topped with extra whole almonds, served with bread.",
    price: 12.0,
    popular: false,
    image: "/images/menu/amlou-almonds.webp",
  },
  {
    id: 21,
    name: "Honey",
    category: "Extras",
    description: "Natural honey, served with bread.",
    price: 6.0,
    popular: false,
    image: "/images/menu/honey.webp",
  },
  {
    id: 22,
    name: "Jam",
    category: "Extras",
    description: "Fruit jam, served with bread.",
    price: 6.0,
    popular: false,
    image: "/images/menu/jam.webp",
  },
  {
    id: 23,
    name: "Jben (Fresh Cheese)",
    category: "Extras",
    description: "Traditional Moroccan fresh cheese, served with bread.",
    price: 8.0,
    popular: false,
    image: "/images/menu/jben.webp",
  },
  {
    id: 24,
    name: "Cheese",
    category: "Extras",
    description: "A portion of cheese, served with bread.",
    price: 3.0,
    popular: false,
    image: "/images/menu/cheese.webp",
  },
  {
    id: 25,
    name: "Olive Oil",
    category: "Extras",
    description: "Extra portion of olive oil, served with bread.",
    price: 8.0,
    popular: false,
    image: "/images/menu/olive-oil.webp",
  },
  {
    id: 26,
    name: "Black & Green Olives",
    category: "Extras",
    description: "A mix of black and green olives, served with bread.",
    price: 5.0,
    popular: false,
    image: "/images/menu/olives.webp",
  },
  {
    id: 27,
    name: "Nutella",
    category: "Extras",
    description: "A generous portion of Nutella, served with bread.",
    price: 10.0,
    popular: false,
    image: "/images/menu/nutella-side.webp",
  },

  // ---------- Soup ----------
  {
    id: 28,
    name: "Barley Soup (Hesewa)",
    category: "Soup",
    description:
      "Warm and comforting traditional Moroccan barley and milk soup.",
    price: 7.0,
    popular: false,
    image: "/images/menu/hesewa.webp",
  },
  {
    id: 29,
    name: "Harira Soup",
    category: "Soup",
    description:
      "Traditional hearty Moroccan tomato, lentil, and chickpea soup.",
    price: 10.0,
    popular: false,
    image: "/images/menu/soup.webp",
  },

  // ---------- Coffee ----------
  {
    id: 30,
    name: "Espresso",
    category: "Coffee",
    description: "Classic short shot of rich Italian-style espresso.",
    price: 12.0,
    popular: false,
    image: "/images/menu/espresso.webp",
  },
  {
    id: 31,
    name: "Espresso illy",
    category: "Coffee",
    description: "Premium espresso made with illy coffee beans.",
    price: 16.0,
    popular: false,
    image: "/images/menu/espresso-illy.webp",
  },
  {
    id: 32,
    name: "Café Crème",
    category: "Coffee",
    description: "Espresso topped with warm, creamy milk foam.",
    price: 12.0,
    popular: false,
    image: "/images/menu/cafe-creme.webp",
  },
  {
    id: 33,
    name: "Nespresso Coffee",
    category: "Coffee",
    description: "Smooth coffee brewed from Nespresso capsules.",
    price: 15.0,
    popular: false,
    image: "/images/menu/cafe-nespresso.webp",
  },
  {
    id: 34,
    name: "Café Américain",
    category: "Coffee",
    description: "Espresso lengthened with hot water for a milder cup.",
    price: 14.0,
    popular: false,
    image: "/images/menu/cafe-americain.webp",
  },
  {
    id: 35,
    name: "Café Séparé",
    category: "Coffee",
    description: "Espresso served separately with steamed milk on the side.",
    price: 15.0,
    popular: false,
    image: "/images/menu/cafe-separe.webp",
  },
  {
    id: 36,
    name: "Double Espresso",
    category: "Coffee",
    description: "A double shot of concentrated espresso.",
    price: 18.0,
    popular: false,
    image: "/images/menu/double-espresso.webp",
  },
  {
    id: 37,
    name: "Cappuccino",
    category: "Coffee",
    description: "Espresso with steamed milk and a thick layer of milk foam.",
    price: 15.0,
    popular: true,
    image: "/images/menu/cappuccino.webp",
  },
  {
    id: 38,
    name: "Morcha",
    category: "Coffee",
    description: "Traditional strong Moroccan-style black coffee.",
    price: 18.0,
    popular: false,
    image: "/images/menu/morcha.webp",
  },
  {
    id: 39,
    name: "Cortado",
    category: "Coffee",
    description: "Espresso cut with a small amount of warm milk.",
    price: 16.0,
    popular: false,
    image: "/images/menu/cortado.webp",
  },
  {
    id: 40,
    name: "Latte Macchiato",
    category: "Coffee",
    description: "Steamed milk lightly marked with a shot of espresso.",
    price: 16.0,
    popular: false,
    image: "/images/menu/latte-macchiato.webp",
  },
  {
    id: 41,
    name: "Flat White",
    category: "Coffee",
    description: "Espresso with a thin layer of velvety micro-foam milk.",
    price: 16.0,
    popular: false,
    image: "/images/menu/flat-white.webp",
  },
  {
    id: 42,
    name: "Chocolat Viennois",
    category: "Coffee",
    description: "Rich hot chocolate topped with whipped cream.",
    price: 16.0,
    popular: false,
    image: "/images/menu/chocolat-viennois.webp",
  },

  // ---------- Iced Coffee ----------
  {
    id: 43,
    name: "Café Affogato",
    category: "Iced Coffee",
    description: "A scoop of ice cream “drowned” in a hot shot of espresso.",
    price: 18.0,
    popular: false,
    image: "/images/menu/affogato.webp",
  },
  {
    id: 44,
    name: "Iced Mocha",
    category: "Iced Coffee",
    description: "Chilled espresso blended with chocolate and cold milk.",
    price: 19.0,
    popular: false,
    image: "/images/menu/iced-mocha.webp",
  },
  {
    id: 45,
    name: "Iced Caramel Macchiato",
    category: "Iced Coffee",
    description: "Cold milk and espresso layered with sweet caramel drizzle.",
    price: 21.0,
    popular: false,
    image: "/images/menu/iced-caramel-macchiato.webp",
  },
  {
    id: 46,
    name: "Iced Frappuccino",
    category: "Iced Coffee",
    description:
      "Blended iced coffee drink, available in vanilla, chocolate or caramel.",
    price: 21.0,
    popular: true,
    image: "/images/menu/iced-frappuccino.webp",
  },
  {
    id: 47,
    name: "Iced Coffee",
    category: "Iced Coffee",
    description:
      "Chilled coffee over ice, available nature, vanilla, chocolate, caramel or hazelnut.",
    price: 18.0,
    popular: false,
    image: "/images/menu/iced-coffee.webp",
  },
  {
    id: 48,
    name: "Iced Latte",
    category: "Iced Coffee",
    description:
      "Espresso and cold milk over ice, available nature, vanilla, chocolate, caramel or hazelnut.",
    price: 19.0,
    popular: false,
    image: "/images/menu/iced-latte.webp",
  },

  // ---------- Milk & Tea ----------
  {
    id: 49,
    name: "Chocolate Milk",
    category: "Milk & Tea",
    description: "Warm milk blended with rich chocolate.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-chocolat.webp",
  },
  {
    id: 50,
    name: "Hot Milk",
    category: "Milk & Tea",
    description: "A simple glass of warm milk.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-chaud.webp",
  },
  {
    id: 51,
    name: "Verbena Milk",
    category: "Milk & Tea",
    description: "Warm milk infused with fragrant verbena.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-verveine.webp",
  },
  {
    id: 52,
    name: "Milk with Syrup",
    category: "Milk & Tea",
    description: "Warm milk sweetened with flavored syrup.",
    price: 11.0,
    popular: false,
    image: "/images/menu/lait-sirop.webp",
  },
  {
    id: 53,
    name: "Lipton Milk",
    category: "Milk & Tea",
    description: "Warm milk infused with Lipton tea.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-lipton.webp",
  },
  {
    id: 54,
    name: "Verbena Tea",
    category: "Milk & Tea",
    description: "Soothing infusion of natural verbena leaves.",
    price: 11.0,
    popular: false,
    image: "/images/menu/verveine-nature.webp",
  },
  {
    id: 55,
    name: "Lipton Tea",
    category: "Milk & Tea",
    description: "Classic Lipton black tea.",
    price: 11.0,
    popular: false,
    image: "/images/menu/lipton-nature.webp",
  },
  {
    id: 56,
    name: "Moroccan Mint Tea",
    category: "Milk & Tea",
    description: "Traditional sweet green tea with fresh mint.",
    price: 11.0,
    popular: true,
    image: "/images/menu/the-marocain.webp",
  },

  // ---------- Waffles, Crepes & Pancakes ----------
  {
    id: 57,
    name: "Caramel Waffle",
    category: "Waffles, Crepes & Pancakes",
    description: "Crisp golden waffle drizzled with caramel sauce.",
    price: 16.0,
    popular: false,
    image: "/images/menu/waffle-caramel.webp",
  },
  {
    id: 58,
    name: "Nutella Waffle",
    category: "Waffles, Crepes & Pancakes",
    description: "Crisp golden waffle generously topped with Nutella.",
    price: 19.0,
    popular: true,
    image: "/images/menu/waffle-nutella.webp",
  },
  {
    id: 59,
    name: "Nutella Banana Waffle",
    category: "Waffles, Crepes & Pancakes",
    description: "Golden waffle topped with Nutella and fresh banana slices.",
    price: 22.0,
    popular: false,
    image: "/images/menu/waffle-nutella-banane.webp",
  },
  {
    id: 60,
    name: "Nutella Seasonal Fruit Waffle",
    category: "Waffles, Crepes & Pancakes",
    description: "Golden waffle topped with Nutella and fresh seasonal fruit.",
    price: 27.0,
    popular: false,
    image: "/images/menu/waffle-nutella-fruits.webp",
  },
  {
    id: 61,
    name: "Caramel Crepe",
    category: "Waffles, Crepes & Pancakes",
    description: "Thin crepe folded with sweet caramel sauce.",
    price: 16.0,
    popular: false,
    image: "/images/menu/crepe-caramel.webp",
  },
  {
    id: 62,
    name: "Nutella Crepe",
    category: "Waffles, Crepes & Pancakes",
    description: "Thin crepe filled with melted Nutella.",
    price: 19.0,
    popular: false,
    image: "/images/menu/crepe-nutella.webp",
  },
  {
    id: 63,
    name: "Nutella Banana Crepe",
    category: "Waffles, Crepes & Pancakes",
    description: "Thin crepe filled with Nutella and fresh banana.",
    price: 23.0,
    popular: false,
    image: "/images/menu/crepe-nutella-banane.webp",
  },
  {
    id: 64,
    name: "Nutella Oreo Crepe",
    category: "Waffles, Crepes & Pancakes",
    description: "Thin crepe filled with Nutella and crushed Oreo cookies.",
    price: 25.0,
    popular: false,
    image: "/images/menu/crepe-nutella-oreo.webp",
  },
  {
    id: 65,
    name: "Nutella Seasonal Fruit Crepe",
    category: "Waffles, Crepes & Pancakes",
    description: "Thin crepe filled with Nutella and fresh seasonal fruit.",
    price: 29.0,
    popular: false,
    image: "/images/menu/crepe-nutella-fruits.webp",
  },
  {
    id: 66,
    name: "Honey Pancakes",
    category: "Waffles, Crepes & Pancakes",
    description: "Fluffy stacked pancakes drizzled with honey.",
    price: 16.0,
    popular: false,
    image: "/images/menu/pancakes-miel.webp",
  },
  {
    id: 67,
    name: "Amlou Pancakes",
    category: "Waffles, Crepes & Pancakes",
    description: "Fluffy stacked pancakes topped with traditional amlou.",
    price: 17.0,
    popular: false,
    image: "/images/menu/pancakes-amlou.webp",
  },
  {
    id: 68,
    name: "Nutella Pancakes",
    category: "Waffles, Crepes & Pancakes",
    description: "Fluffy stacked pancakes topped with Nutella.",
    price: 21.0,
    popular: false,
    image: "/images/menu/pancakes-nutella.webp",
  },
  {
    id: 69,
    name: "Nutella Banana Pancakes",
    category: "Waffles, Crepes & Pancakes",
    description: "Fluffy stacked pancakes topped with Nutella and banana.",
    price: 26.0,
    popular: false,
    image: "/images/menu/pancakes-nutella-banane.webp",
  },

  // ---------- Pastries & Desserts -----------
  {
    id: 70,
    name: "Seafood Cigar",
    category: "Pastries & Desserts",
    description: "Crispy rolled pastry filled with savory mixed seafood.",
    price: 12.0,
    popular: false,
    image: "/images/menu/cigar.webp",
  },
  {
    id: 71,
    name: "Seafood Pastilla",
    category: "Pastries & Desserts",
    description:
      "Flaky savory pie filled with seasoned mixed seafood and vermicelli.",
    price: 12.0,
    popular: false,
    image: "/images/menu/pastilla.webp",
  },
  {
    id: 72,
    name: "Sandwich",
    category: "Pastries & Desserts",
    description: "Freshly made savory sandwich.",
    price: 8.0,
    popular: false,
    image: "/images/menu/sandwich.webp",
  },
  {
    id: 73,
    name: "Mini Pizza",
    category: "Pastries & Desserts",
    description:
      "Personal-sized savory pizza topped with cheese and tomato sauce.",
    price: 6.0,
    popular: false,
    image: "/images/menu/pizza.webp",
  },
  {
    id: 74,
    name: "Hot Dog Pastry",
    category: "Pastries & Desserts",
    description: "Savory sausage wrapped and baked in soft dough.",
    price: 9.0,
    popular: false,
    image: "/images/menu/hot-dog.webp",
  },
  {
    id: 75,
    name: "Chicken Pastilla",
    category: "Pastries & Desserts",
    description:
      "Sweet and savory pie filled with spiced chicken and toasted almonds.",
    price: 10.0,
    popular: false,
    image: "/images/menu/pastilla.webp",
  },
  {
    id: 76,
    name: "Cheese Briouat",
    category: "Pastries & Desserts",
    description: "Crispy Moroccan pastry triangles filled with savory cheese.",
    price: 7.0,
    popular: false,
    image: "/images/menu/briouat.webp",
  },
  {
    id: 77,
    name: "Almond Tart",
    category: "Pastries & Desserts",
    description: "Crisp sweet pastry shell filled with dense almond cream.",
    price: 10.0,
    popular: false,
    image: "/images/menu/tart.webp",
  },
  {
    id: 78,
    name: "Apple Turnover",
    category: "Pastries & Desserts",
    description: "Flaky puff pastry filled with sweet spiced apple compote.",
    price: 6.0,
    popular: false,
    image: "/images/menu/apple-turnover.webp",
  },
  {
    id: 79,
    name: "Chocolate Basbousa",
    category: "Pastries & Desserts",
    description: "Sweet semolina cake flavored with rich chocolate.",
    price: 8.0,
    popular: false,
    image: "/images/menu/basbousa.webp",
  },
  {
    id: 80,
    name: "Chocolate Madeleine",
    category: "Pastries & Desserts",
    description: "Small, shell-shaped sponge cake flavored with chocolate.",
    price: 2.5,
    popular: false,
    image: "/images/menu/madeleine.webp",
  },
  {
    id: 81,
    name: "Donut",
    category: "Pastries & Desserts",
    description: "Soft, sweet, and classic fried dough ring.",
    price: 4.0,
    popular: false,
    image: "/images/menu/donut.webp",
  },
  {
    id: 82,
    name: "Frangipane Tart",
    category: "Pastries & Desserts",
    description: "Sweet pastry tart filled with rich almond cream.",
    price: 8.0,
    popular: false,
    image: "/images/menu/frangipane-tart.webp",
  },
  {
    id: 83,
    name: "Fruit Pithiviers",
    category: "Pastries & Desserts",
    description: "Puff pastry pie filled with sweet fruit compote.",
    price: 6.0,
    popular: false,
    image: "/images/menu/pithiviers.webp",
  },
  {
    id: 84,
    name: "Fruit Tartlet",
    category: "Pastries & Desserts",
    description: "Small, sweet tart crust filled with custard and fresh fruit.",
    price: 7.0,
    popular: false,
    image: "/images/menu/fruit-tartlet.webp",
  },
  {
    id: 85,
    name: "Vanilla Basbousa",
    category: "Pastries & Desserts",
    description: "Classic sweet semolina cake soaked in vanilla syrup.",
    price: 6.0,
    popular: false,
    image: "/images/menu/basbousa.webp",
  },
  {
    id: 86,
    name: "Vanilla Madeleine",
    category: "Pastries & Desserts",
    description: "Classic, buttery, shell-shaped French sponge cake.",
    price: 1.5,
    popular: false,
    image: "/images/menu/madeleine.webp",
  },
  {
    id: 87,
    name: "Almond Croissant",
    category: "Pastries & Desserts",
    description:
      "Flaky croissant filled with almond cream and topped with sliced almonds.",
    price: 5.0,
    popular: false,
    image: "/images/menu/croissant.webp",
  },
  {
    id: 88,
    name: "Almond Triangle",
    category: "Pastries & Desserts",
    description:
      "Flaky, triangle-shaped pastry filled with sweet almond paste.",
    price: 6.0,
    popular: false,
    image: "/images/menu/triangle.webp",
  },
  {
    id: 89,
    name: "Chocolate Danish",
    category: "Pastries & Desserts",
    description: "Flaky Danish pastry swirled with rich chocolate.",
    price: 4.0,
    popular: false,
    image: "/images/menu/danish.webp",
  },
  {
    id: 90,
    name: "Danish Pastry",
    category: "Pastries & Desserts",
    description: "Flaky, buttery, and sweet traditional Danish pastry.",
    price: 3.5,
    popular: false,
    image: "/images/menu/danish.webp",
  },
  {
    id: 91,
    name: "Harcha",
    category: "Pastries & Desserts",
    description: "Traditional Moroccan pan-fried semolina flatbread.",
    price: 2.5,
    popular: false,
    image: "/images/menu/harcha.webp",
  },
  {
    id: 92,
    name: "Msemmen",
    category: "Pastries & Desserts",
    description: "Traditional Moroccan flaky, layered square flatbread.",
    price: 4.0,
    popular: false,
    image: "/images/menu/msemmen.webp",
  },
  {
    id: 93,
    name: "Olive Oil Harcha",
    category: "Pastries & Desserts",
    description: "Savory semolina flatbread prepared with rich olive oil.",
    price: 3.5,
    popular: false,
    image: "/images/menu/oil-harcha.webp",
  },
  {
    id: 94,
    name: "Pain Suisse",
    category: "Pastries & Desserts",
    description:
      "Flaky pastry rolled with vanilla custard and chocolate chips.",
    price: 3.0,
    popular: false,
    image: "/images/menu/pain-suisse.webp",
  },
  {
    id: 95,
    name: "Pain au Chocolat / Croissant",
    category: "Pastries & Desserts",
    description: "Classic flaky and buttery French breakfast pastry.",
    price: 2.5,
    popular: false,
    image: "/images/menu/pain-au-chocolat.webp",
  },
  {
    id: 96,
    name: "Pithiviers",
    category: "Pastries & Desserts",
    description:
      "Round, enclosed pie made of puff pastry with a sweet filling.",
    price: 5.0,
    popular: false,
    image: "/images/menu/pithiviers.webp",
  },
  {
    id: 97,
    name: "Raspberry Mini Cake",
    category: "Pastries & Desserts",
    description: "Small cake infused with sweet raspberry flavor.",
    price: 8.0,
    popular: false,
    image: "/images/menu/minicake.webp",
  },
  {
    id: 98,
    name: "Mille-Feuille",
    category: "Pastries & Desserts",
    description:
      "Classic French pastry with layers of puff pastry and vanilla cream.",
    price: 8.0,
    popular: false,
    image: "/images/menu/millefeuille.webp",
  },
  {
    id: 99,
    name: "Mini Cake",
    category: "Pastries & Desserts",
    description: "Small, moist, and sweet personal cake.",
    price: 7.0,
    popular: false,
    image: "/images/menu/minicake.webp",
  },
  {
    id: 100,
    name: "Mini Cupcake",
    category: "Pastries & Desserts",
    description: "Bite-sized fluffy cake with sweet frosting.",
    price: 4.0,
    popular: false,
    image: "/images/menu/cupcake.webp",
  },

  // ---------- Smoothies & Milkshakes ----------
  {
    id: 101,
    name: "Strawberry Smoothie",
    category: "Smoothies & Milkshakes",
    description: "Fresh strawberries blended into a smooth, fruity drink.",
    price: 23.0,
    popular: true,
    image: "/images/menu/smoothie-fraise.webp",
  },
  {
    id: 102,
    name: "Banana Smoothie",
    category: "Smoothies & Milkshakes",
    description: "Creamy blended smoothie made with ripe banana.",
    price: 23.0,
    popular: false,
    image: "/images/menu/smoothie-banane.webp",
  },
  {
    id: 103,
    name: "Mango Smoothie",
    category: "Smoothies & Milkshakes",
    description: "Smooth and tropical blended mango smoothie.",
    price: 23.0,
    popular: false,
    image: "/images/menu/smoothie-mangue.webp",
  },
  {
    id: 104,
    name: "Exotic Smoothie",
    category: "Smoothies & Milkshakes",
    description: "A blend of exotic fruits for a refreshing tropical smoothie.",
    price: 26.0,
    popular: false,
    image: "/images/menu/smoothie-exotique.webp",
  },
  {
    id: 105,
    name: "Chocolate Milkshake",
    category: "Smoothies & Milkshakes",
    description: "Thick and creamy chocolate milkshake.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milkshake-choco.webp",
  },
  {
    id: 106,
    name: "Vanilla Milkshake",
    category: "Smoothies & Milkshakes",
    description: "Thick and creamy vanilla milkshake.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milkshake-vanille.webp",
  },
  {
    id: 107,
    name: "Banana Milkshake",
    category: "Smoothies & Milkshakes",
    description: "Thick and creamy banana milkshake.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milkshake-banane.webp",
  },
  {
    id: 108,
    name: "Strawberry Milkshake",
    category: "Smoothies & Milkshakes",
    description: "Thick and creamy strawberry milkshake.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milkshake-fraise.webp",
  },
  {
    id: 109,
    name: "Oreo Milkshake",
    category: "Smoothies & Milkshakes",
    description: "Creamy milkshake blended with crushed Oreo cookies.",
    price: 26.0,
    popular: false,
    image: "/images/menu/milkshake-oreo.webp",
  },

  // ---------- Mojito ----------
  {
    id: 110,
    name: "Virgin Mojito",
    category: "Mojito",
    description: "Refreshing alcohol-free mojito with lime and mint.",
    price: 19.0,
    popular: false,
    image: "/images/menu/mojito-virgin.webp",
  },
  {
    id: 111,
    name: "Blue Mojito",
    category: "Mojito",
    description: "Refreshing blue-hued mojito with lime and mint.",
    price: 22.0,
    popular: false,
    image: "/images/menu/mojito-blue.webp",
  },
  {
    id: 112,
    name: "Rose Mojito",
    category: "Mojito",
    description: "Refreshing rose-flavored mojito with lime and mint.",
    price: 22.0,
    popular: false,
    image: "/images/menu/mojito-roso.webp",
  },

  // ---------- Juices ----------
  {
    id: 113,
    name: "Orange Juice",
    category: "Juices",
    description: "Freshly squeezed orange juice.",
    price: 16.0,
    popular: false,
    image: "/images/menu/jus-orange.webp",
  },
  {
    id: 114,
    name: "Banana Juice",
    category: "Juices",
    description: "Freshly blended banana juice.",
    price: 16.0,
    popular: false,
    image: "/images/menu/jus-banane.webp",
  },
  {
    id: 115,
    name: "Apple Juice",
    category: "Juices",
    description: "Freshly pressed apple juice.",
    price: 16.0,
    popular: false,
    image: "/images/menu/jus-pomme.webp",
  },
  {
    id: 116,
    name: "Avocado Juice",
    category: "Juices",
    description: "Creamy blended avocado juice.",
    price: 18.0,
    popular: false,
    image: "/images/menu/jus-avocat.webp",
  },
  {
    id: 117,
    name: "Strawberry Juice",
    category: "Juices",
    description: "Freshly blended strawberry juice.",
    price: 18.0,
    popular: false,
    image: "/images/menu/jus-fraise.webp",
  },
  {
    id: 118,
    name: "Mango Juice",
    category: "Juices",
    description: "Freshly blended mango juice.",
    price: 20.0,
    popular: false,
    image: "/images/menu/jus-mangue.webp",
  },
  {
    id: 119,
    name: "Pineapple Juice",
    category: "Juices",
    description: "Freshly blended pineapple juice.",
    price: 23.0,
    popular: false,
    image: "/images/menu/jus-ananas.webp",
  },
  {
    id: 120,
    name: "Mixed Juice with Milk",
    category: "Juices",
    description: "Blended fruit juice mixed with milk.",
    price: 18.0,
    popular: false,
    image: "/images/menu/jus-panache-lait.webp",
  },
  {
    id: 121,
    name: "Mixed Juice with Orange",
    category: "Juices",
    description: "Blended fruit juice mixed with fresh orange juice.",
    price: 23.0,
    popular: true,
    image: "/images/menu/jus-panache-orange.webp",
  },
  {
    id: 122,
    name: "Avocado Juice with Dried Fruits",
    category: "Juices",
    description: "Creamy avocado juice topped with a mix of dried fruits.",
    price: 23.0,
    popular: false,
    image: "/images/menu/jus-avocat-fruits-secs.webp",
  },

  // ---------- Cocktails & Fruit Salads ----------
  {
    id: 123,
    name: "Fruit Salad with Yogurt",
    category: "Cocktails & Fruit Salads",
    description: "Fresh mixed fruit salad served on a yogurt base.",
    price: 18.0,
    popular: false,
    image: "/images/menu/salade-fruits-yaourt.webp",
  },
  {
    id: 124,
    name: "Fruit Salad with Orange",
    category: "Cocktails & Fruit Salads",
    description: "Fresh mixed fruit salad served in orange juice.",
    price: 19.0,
    popular: false,
    image: "/images/menu/salade-fruits-orange.webp",
  },
  {
    id: 125,
    name: "Tropical Cocktail",
    category: "Cocktails & Fruit Salads",
    description: "A blend of mango, kiwi and pineapple.",
    price: 21.0,
    popular: false,
    image: "/images/menu/cocktail-tropical.webp",
  },
  {
    id: 126,
    name: "Oriental Cocktail",
    category: "Cocktails & Fruit Salads",
    description: "A blend of banana, apple and orange.",
    price: 20.0,
    popular: false,
    image: "/images/menu/cocktail-oriental.webp",
  },
  {
    id: 127,
    name: "Exotic Cocktail",
    category: "Cocktails & Fruit Salads",
    description: "A blend of mango, orange and pineapple.",
    price: 21.0,
    popular: false,
    image: "/images/menu/cocktail-exotique.webp",
  },

  // ---------- Soft Drinks ----------
  {
    id: 128,
    name: "Soda (35cl)",
    category: "Soft Drinks",
    description: "Choice of chilled soft drink, 35cl.",
    price: 12.0,
    popular: false,
    image: "/images/menu/soda.webp",
  },
  {
    id: 129,
    name: "Mineral Water (33cl)",
    category: "Soft Drinks",
    description: "Small bottle of still or sparkling mineral water.",
    price: 5.0,
    popular: false,
    image: "/images/menu/eau-minerale-33.webp",
  },
  {
    id: 130,
    name: "Mineral Water (50cl)",
    category: "Soft Drinks",
    description: "Large bottle of still or sparkling mineral water.",
    price: 7.0,
    popular: false,
    image: "/images/menu/eau-minerale-50.webp",
  },
];

export const shopProducts = [
  // Breakfast
  {
    id: 1,
    name: "Barley Soup (Hesewa)",
    category: "Breakfast",
    description:
      "Warm and comforting traditional Moroccan barley and milk soup.",
    price: 7.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/hesewa.webp",
  },
  {
    id: 2,
    name: "Cheese Omelet",
    category: "Breakfast",
    description:
      "Fluffy omelet loaded with melted cheese, served with olives and olive oil.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 3,
    name: "Continental Breakfast",
    category: "Breakfast",
    description:
      "Barley soup, hot drink, orange juice, cheese omelet, olive oil, olives, cheese, bread, yogurt, and water.",
    price: 35.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 4,
    name: "Deli Meat Omelet",
    category: "Breakfast",
    description:
      "Omelet packed with cold cuts, served with olives and olive oil.",
    price: 17.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 5,
    name: "Express Breakfast",
    category: "Breakfast",
    description:
      "Barley soup, hot drink, orange juice, pastries, yogurt, and mineral water.",
    price: 26.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 6,
    name: "Fassi Breakfast",
    category: "Breakfast",
    description:
      "Barley soup, hot drink, orange juice, dried meat omelet, olive oil, olives, cheese, bread, yogurt, and water.",
    price: 37.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 7,
    name: "Gourmet Breakfast",
    category: "Breakfast",
    description:
      "Barley soup, hot drink, orange juice, olive oil, Amlou, olives, honey, bread, yogurt, and water.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 8,
    name: "Harira Soup",
    category: "Breakfast",
    description:
      "Traditional hearty Moroccan tomato, lentil, and chickpea soup.",
    price: 10.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/soup.webp",
  },
  {
    id: 9,
    name: "Khlii Omelet",
    category: "Breakfast",
    description:
      "Traditional omelet with Moroccan preserved meat, served with olives and olive oil.",
    price: 24.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 10,
    name: "Kids Breakfast",
    category: "Breakfast",
    description:
      "Chocolate milk, orange juice, chocolate bread, vanilla cake, yogurt, and water.",
    price: 25.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 11,
    name: "La Madeleine Breakfast",
    category: "Breakfast",
    description:
      "Barley soup, hot drink, orange juice, choice of omelet, olive oil, olives, honey, cheese, Amlou, bread, crepe, chocolate, cake, yogurt, and water.",
    price: 55.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 12,
    name: "Plain Omelet",
    category: "Breakfast",
    description: "Simple, fluffy egg omelet served with olives and olive oil.",
    price: 13.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 13,
    name: "Soussi Breakfast",
    category: "Breakfast",
    description:
      "Barley soup, hot drink, orange juice, Amlou, olive oil, cheese, olives, honey, jam, and water.",
    price: 38.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 14,
    name: "Tomato Omelet",
    category: "Breakfast",
    description:
      "Fluffy omelet with fresh tomatoes, served with olives and olive oil.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 15,
    name: "Traditional Breakfast",
    category: "Breakfast",
    description:
      "Barley soup, hot drink, orange juice, Moroccan pancakes, Harcha, honey, fresh cheese, and water.",
    price: 28.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.webp",
  },

  // PASTRIES & DESSERTS
  {
    id: 16,
    name: "Seafood Cigar",
    category: "Pastries & Desserts",
    description: "Crispy rolled pastry filled with savory mixed seafood.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/cigar.webp",
  },
  {
    id: 17,
    name: "Seafood Pastilla",
    category: "Pastries & Desserts",
    description:
      "Flaky savory pie filled with seasoned mixed seafood and vermicelli.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pastilla.webp",
  },
  {
    id: 18,
    name: "Sandwich",
    category: "Pastries & Desserts",
    description: "Freshly made savory sandwich.",
    price: 8.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/sandwich.webp",
  },
  {
    id: 19,
    name: "Mini Pizza",
    category: "Pastries & Desserts",
    description:
      "Personal-sized savory pizza topped with cheese and tomato sauce.",
    price: 6.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/pizza.webp",
  },
  {
    id: 20,
    name: "Hot Dog Pastry",
    category: "Pastries & Desserts",
    description: "Savory sausage wrapped and baked in soft dough.",
    price: 9.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/hot-dog.webp",
  },
  {
    id: 21,
    name: "Chicken Pastilla",
    category: "Pastries & Desserts",
    description:
      "Sweet and savory pie filled with spiced chicken and toasted almonds.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pastilla.webp",
  },
  {
    id: 22,
    name: "Cheese Briouat",
    category: "Pastries & Desserts",
    description: "Crispy Moroccan pastry triangles filled with savory cheese.",
    price: 7.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/briouat.webp",
  },
  {
    id: 23,
    name: "Almond Tart",
    category: "Pastries & Desserts",
    description: "Crisp sweet pastry shell filled with dense almond cream.",
    price: 10.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/tart.webp",
  },
  {
    id: 24,
    name: "Amlou Pancakes",
    category: "Pastries & Desserts",
    description: "Fluffy pancakes topped with traditional Moroccan Amlou.",
    price: 17.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 25,
    name: "Apple Turnover",
    category: "Pastries & Desserts",
    description: "Flaky puff pastry filled with sweet spiced apple compote.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/apple-turnover.webp",
  },
  {
    id: 26,
    name: "Caramel Crepe",
    category: "Pastries & Desserts",
    description: "Thin French crepe folded with sweet caramel.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 27,
    name: "Caramel Waffle",
    category: "Pastries & Desserts",
    description: "Golden waffle topped with rich caramel sauce.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 28,
    name: "Chocolate Basbousa",
    category: "Pastries & Desserts",
    description: "Sweet semolina cake flavored with rich chocolate.",
    price: 8.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.webp",
  },
  {
    id: 29,
    name: "Chocolate Madeleine",
    category: "Pastries & Desserts",
    description: "Small, shell-shaped sponge cake flavored with chocolate.",
    price: 2.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.webp",
  },
  {
    id: 30,
    name: "Classic Crepe",
    category: "Pastries & Desserts",
    description: "Simple, thin, and soft French crepe.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 31,
    name: "Cream Cake Slice (10)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 10.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 32,
    name: "Cream Cake Slice (12)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 33,
    name: "Cream Cake Slice (13)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 13.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 34,
    name: "Cream Cake Slice (14)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 14.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 35,
    name: "Cream Cake Slice (15)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 36,
    name: "Cream Cake Slice (17)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 17.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 37,
    name: "Cream Cake Slice (18)",
    category: "Pastries & Desserts",
    description: "Delicious slice of cream-filled layer cake.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 38,
    name: "Donut",
    category: "Pastries & Desserts",
    description: "Soft, sweet, and classic fried dough ring.",
    price: 4.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/donut.webp",
  },
  {
    id: 39,
    name: "Frangipane Tart",
    category: "Pastries & Desserts",
    description: "Sweet pastry tart filled with rich almond cream.",
    price: 8.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/frangipane-tart.webp",
  },
  {
    id: 40,
    name: "Fruit Pithiviers",
    category: "Pastries & Desserts",
    description: "Puff pastry pie filled with sweet fruit compote.",
    price: 6.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pithiviers.webp",
  },
  {
    id: 41,
    name: "Fruit Salad with Orange Juice",
    category: "Pastries & Desserts",
    description: "Fresh seasonal fruits steeped in fresh orange juice.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/fruit-salad.webp",
  },
  {
    id: 42,
    name: "Fruit Salad with Yogurt",
    category: "Pastries & Desserts",
    description: "Fresh seasonal fruits mixed with creamy yogurt.",
    price: 18.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/fruit-salad.webp",
  },
  {
    id: 43,
    name: "Fruit Tartlet",
    category: "Pastries & Desserts",
    description: "Small, sweet tart crust filled with custard and fresh fruit.",
    price: 7.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/fruit-tartlet.webp",
  },
  {
    id: 44,
    name: "Honey Pancakes",
    category: "Pastries & Desserts",
    description: "Fluffy pancakes drizzled with pure honey.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 45,
    name: "Large Pound Cake",
    category: "Pastries & Desserts",
    description: "Generously sized, buttery, and moist pound cake.",
    price: 30.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 46,
    name: "Medium Pound Cake",
    category: "Pastries & Desserts",
    description: "Classic moist and sweet pound cake.",
    price: 20.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 47,
    name: "Mille-Feuille",
    category: "Pastries & Desserts",
    description:
      "Classic French pastry with layers of puff pastry and vanilla cream.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/millefeuille.webp",
  },
  {
    id: 48,
    name: "Mini Cake",
    category: "Pastries & Desserts",
    description: "Small, moist, and sweet personal cake.",
    price: 7.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/minicake.webp",
  },
  {
    id: 49,
    name: "Mini Cupcake",
    category: "Pastries & Desserts",
    description: "Bite-sized fluffy cake with sweet frosting.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cupcake.webp",
  },
  {
    id: 50,
    name: "Nutella & Banana Crepe",
    category: "Pastries & Desserts",
    description: "Crepe filled with Nutella and sliced bananas.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 51,
    name: "Nutella & Banana Pancakes",
    category: "Pastries & Desserts",
    description: "Pancakes served with Nutella and fresh bananas.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 52,
    name: "Nutella & Banana Waffle",
    category: "Pastries & Desserts",
    description: "Waffle topped with Nutella and fresh banana slices.",
    price: 22.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 53,
    name: "Nutella & Oreo Crepe",
    category: "Pastries & Desserts",
    description: "Crepe filled with Nutella and crushed Oreo cookies.",
    price: 25.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 54,
    name: "Nutella & Seasonal Fruits Crepe",
    category: "Pastries & Desserts",
    description: "Crepe filled with Nutella and fresh seasonal fruits.",
    price: 29.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 55,
    name: "Nutella & Seasonal Fruits Waffle",
    category: "Pastries & Desserts",
    description: "Waffle with Nutella and fresh seasonal fruits.",
    price: 27.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 56,
    name: "Nutella Crepe",
    category: "Pastries & Desserts",
    description: "Classic thin crepe filled with warm Nutella.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 57,
    name: "Nutella Pancakes",
    category: "Pastries & Desserts",
    description: "Stack of fluffy pancakes layered with Nutella.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 58,
    name: "Nutella Waffle",
    category: "Pastries & Desserts",
    description: "Golden waffle generously topped with Nutella.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 59,
    name: "Pithiviers",
    category: "Pastries & Desserts",
    description:
      "Round, enclosed pie made of puff pastry with a sweet filling.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pithiviers.webp",
  },
  {
    id: 60,
    name: "Raspberry Mini Cake",
    category: "Pastries & Desserts",
    description: "Small cake infused with sweet raspberry flavor.",
    price: 8.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/minicake.webp",
  },
  {
    id: 61,
    name: "Small Pound Cake",
    category: "Pastries & Desserts",
    description: "Personal-sized slice of moist pound cake.",
    price: 15.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 62,
    name: "Vanilla Basbousa",
    category: "Pastries & Desserts",
    description: "Classic sweet semolina cake soaked in vanilla syrup.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.webp",
  },
  {
    id: 63,
    name: "Vanilla Madeleine",
    category: "Pastries & Desserts",
    description: "Classic, buttery, shell-shaped French sponge cake.",
    price: 1.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.webp",
  },
  {
    id: 64,
    name: "Almond Croissant",
    category: "Pastries & Desserts",
    description:
      "Flaky croissant filled with almond cream and topped with sliced almonds.",
    price: 5.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/croissant.webp",
  },
  {
    id: 65,
    name: "Almond Triangle",
    category: "Pastries & Desserts",
    description:
      "Flaky, triangle-shaped pastry filled with sweet almond paste.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/triangle.webp",
  },
  {
    id: 66,
    name: "Chocolate Danish",
    category: "Pastries & Desserts",
    description: "Flaky Danish pastry swirled with rich chocolate.",
    price: 4.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/danish.webp",
  },
  {
    id: 67,
    name: "Danish Pastry",
    category: "Pastries & Desserts",
    description: "Flaky, buttery, and sweet traditional Danish pastry.",
    price: 3.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/danish.webp",
  },
  {
    id: 68,
    name: "Harcha",
    category: "Pastries & Desserts",
    description: "Traditional Moroccan pan-fried semolina flatbread.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/harcha.webp",
  },
  {
    id: 69,
    name: "Msemmen",
    category: "Pastries & Desserts",
    description: "Traditional Moroccan flaky, layered square flatbread.",
    price: 4.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/msemmen.webp",
  },
  {
    id: 70,
    name: "Olive Oil Harcha",
    category: "Pastries & Desserts",
    description: "Savory semolina flatbread prepared with rich olive oil.",
    price: 3.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/oil-harcha.webp",
  },
  {
    id: 71,
    name: "Pain Suisse",
    category: "Pastries & Desserts",
    description:
      "Flaky pastry rolled with vanilla custard and chocolate chips.",
    price: 3.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pain-suisse.webp",
  },
  {
    id: 72,
    name: "Pain au Chocolat / Croissant",
    category: "Pastries & Desserts",
    description: "Classic flaky and buttery French breakfast pastry.",
    price: 2.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pain-au-chocolat.webp",
  },

  // BAKERY
  {
    id: 73,
    name: "Barley Bread",
    category: "Bakery",
    description: "Hearty and healthy Moroccan barley bread.",
    price: 2.5,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 74,
    name: "Batbout",
    category: "Bakery",
    description: "Moroccan soft and chewy pan-cooked flatbread.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 75,
    name: "Chocolate Brioche",
    category: "Bakery",
    description: "Soft and fluffy sweet bread filled with chocolate chips.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 76,
    name: "Classic Baguette",
    category: "Bakery",
    description: "Traditional crusty and soft French baguette.",
    price: 1.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/bread.webp",
  },
  {
    id: 77,
    name: "Classic Bread",
    category: "Bakery",
    description: "Traditional Moroccan soft white round bread.",
    price: 1.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 78,
    name: "Classic Brioche",
    category: "Bakery",
    description: "Buttery, soft, and fluffy traditional sweet bread.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 79,
    name: "Corn Bread",
    category: "Bakery",
    description: "Rustic and flavorful Moroccan cornmeal bread.",
    price: 2.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },
  {
    id: 80,
    name: "Gingerbread",
    category: "Bakery",
    description: "Traditional French spiced bread with honey and anise.",
    price: 2.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 81,
    name: "Multigrain Baguette",
    category: "Bakery",
    description:
      "Crusty baguette baked with a blend of wholesome seeds and grains.",
    price: 4.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 82,
    name: "Olive Baguette",
    category: "Bakery",
    description: "Savory baguette baked with pieces of black and green olives.",
    price: 5.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 83,
    name: "Olive Bread",
    category: "Bakery",
    description: "Soft traditional round bread baked with savory olives.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 84,
    name: "Salt-Free Wheat Bread",
    category: "Bakery",
    description: "Healthy whole wheat bread prepared without added salt.",
    price: 3.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/bread.webp",
  },
  {
    id: 85,
    name: "Semolina Baguette",
    category: "Bakery",
    description: "Baguette made with semolina flour for a rustic crunch.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 86,
    name: "Semolina Bread",
    category: "Bakery",
    description: "Traditional Moroccan round bread made with semolina.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 87,
    name: "Sesame Baguette",
    category: "Bakery",
    description:
      "Freshly baked crusty French baguette topped with sesame seeds.",
    price: 2.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 88,
    name: "Sesame Roll",
    category: "Bakery",
    description: "Soft bread roll generously topped with sesame seeds.",
    price: 3.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },
  {
    id: 89,
    name: "Viennese Baguette",
    category: "Bakery",
    description: "Soft, slightly sweet, and rich Viennese-style bread.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 90,
    name: "Whole Wheat Baguette",
    category: "Bakery",
    description: "Healthy and hearty whole wheat French baguette.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 91,
    name: "Whole Wheat Bread",
    category: "Bakery",
    description: "Nutritious traditional Moroccan whole wheat round bread.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 92,
    name: "Whole Wheat Roll",
    category: "Bakery",
    description: "Healthy and soft whole wheat bread roll.",
    price: 2.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },

  // HOT DRINKS
  {
    id: 93,
    name: "Black Tea (Lipton)",
    category: "Hot Drinks",
    description: "Classic Lipton black tea.",
    price: 11.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/lipton.webp",
  },
  {
    id: 94,
    name: "Hot Chocolate",
    category: "Hot Drinks",
    description: "Warm and comforting milk with rich chocolate.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/hot-chocolate.webp",
  },
  {
    id: 95,
    name: "Hot Milk",
    category: "Hot Drinks",
    description: "Simple, comforting steamed milk.",
    price: 12.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/hot-milk.webp",
  },
  {
    id: 96,
    name: "Lemon Verbena Tea",
    category: "Hot Drinks",
    description: "Herbal tea made with natural lemon verbena leaves.",
    price: 11.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/lemon-verbena-tea.webp",
  },
  {
    id: 97,
    name: "Milk Tea (Lipton)",
    category: "Hot Drinks",
    description: "Classic Lipton black tea brewed with milk.",
    price: 12.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/milk-tea.webp",
  },
  {
    id: 98,
    name: "Milk with Lemon Verbena",
    category: "Hot Drinks",
    description: "Warm milk infused with soothing lemon verbena.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-tea.webp",
  },
  {
    id: 99,
    name: "Milk with Syrup",
    category: "Hot Drinks",
    description: "Cold or warm milk flavored with sweet syrup.",
    price: 11.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/milk-syrup.webp",
  },
  {
    id: 100,
    name: "Moroccan Mint Tea",
    category: "Hot Drinks",
    description: "Traditional green tea brewed with fresh mint.",
    price: 11.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/moroccan-tea.webp",
  },

  // COLD DRINKS
  {
    id: 101,
    name: "Affogato",
    category: "Cold Drinks",
    description: "A scoop of vanilla ice cream drowned in hot espresso.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/affogato.webp",
  },
  {
    id: 102,
    name: "Banana Milkshake",
    category: "Cold Drinks",
    description: "Sweet and creamy banana shake.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 103,
    name: "Banana Smoothie",
    category: "Cold Drinks",
    description: "Creamy blended banana smoothie.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 104,
    name: "Blue Mojito",
    category: "Cold Drinks",
    description: "Citrus and mint mocktail with blue curaçao syrup.",
    price: 22.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/mojito.webp",
  },
  {
    id: 105,
    name: "Choice of Soda (35cl)",
    category: "Cold Drinks",
    description: "Selection of refreshing carbonated beverages.",
    price: 12.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/soda.webp",
  },
  {
    id: 106,
    name: "Chocolate Milkshake",
    category: "Cold Drinks",
    description: "Rich and creamy chocolate shake.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 107,
    name: "Exotic Cocktail",
    category: "Cold Drinks",
    description: "Blended mango, orange, and pineapple.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/cocktail.webp",
  },
  {
    id: 108,
    name: "Exotic Smoothie",
    category: "Cold Drinks",
    description: "Refreshing blend of tropical fruits.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 109,
    name: "Iced Caramel Macchiato",
    category: "Cold Drinks",
    description: "Iced milk and espresso, flavored with vanilla and caramel.",
    price: 21.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/iced-caramel.webp",
  },
  {
    id: 110,
    name: "Iced Coffee",
    category: "Cold Drinks",
    description: "Chilled coffee over ice with choice of flavor.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/iced-coffee.webp",
  },
  {
    id: 111,
    name: "Iced Frappuccino",
    category: "Cold Drinks",
    description:
      "Blended iced coffee drink with choice of vanilla, chocolate, or caramel.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-frappuccino.webp",
  },
  {
    id: 112,
    name: "Iced Latte",
    category: "Cold Drinks",
    description: "Espresso and chilled milk over ice.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/iced-latte.webp",
  },
  {
    id: 113,
    name: "Iced Mocha",
    category: "Cold Drinks",
    description: "Iced espresso with chocolate and milk.",
    price: 19.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-mocha.webp",
  },
  {
    id: 114,
    name: "Mango Smoothie",
    category: "Cold Drinks",
    description: "Tropical blended mango smoothie.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 115,
    name: "Mineral Water (33cl)",
    category: "Cold Drinks",
    description: "Small bottle of still mineral water.",
    price: 5.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/water.webp",
  },
  {
    id: 116,
    name: "Mineral Water (50cl)",
    category: "Cold Drinks",
    description: "Medium bottle of still mineral water.",
    price: 7.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/water.webp",
  },
  {
    id: 117,
    name: "Oreo Milkshake",
    category: "Cold Drinks",
    description: "Creamy vanilla shake blended with Oreo cookies.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 118,
    name: "Oriental Cocktail",
    category: "Cold Drinks",
    description: "Blended banana, apple, and orange.",
    price: 20.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cocktail.webp",
  },
  {
    id: 119,
    name: "Red Mojito",
    category: "Cold Drinks",
    description: "Fruity red berry mocktail with mint and lime.",
    price: 22.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/mojito.webp",
  },
  {
    id: 120,
    name: "Strawberry Milkshake",
    category: "Cold Drinks",
    description: "Sweet and creamy strawberry shake.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 121,
    name: "Strawberry Smoothie",
    category: "Cold Drinks",
    description: "Blended fresh strawberries and yogurt.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 122,
    name: "Tropical Cocktail",
    category: "Cold Drinks",
    description: "Blended mango, kiwi, and pineapple.",
    price: 21.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/cocktail.webp",
  },
  {
    id: 123,
    name: "Vanilla Milkshake",
    category: "Cold Drinks",
    description: "Classic creamy vanilla shake.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 124,
    name: "Virgin Mojito",
    category: "Cold Drinks",
    description: "Refreshing lime and mint mocktail.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/mojito.webp",
  },

  // COFFEES
  {
    id: 125,
    name: "Americano",
    category: "Coffees",
    description: "Espresso diluted with hot water.",
    price: 14.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/americano.webp",
  },
  {
    id: 126,
    name: "Cappuccino",
    category: "Coffees",
    description: "Espresso topped with equal parts steamed milk and foam.",
    price: 15.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/cappuccino.webp",
  },
  {
    id: 127,
    name: "Coffee on the Side",
    category: "Coffees",
    description: "Espresso served with a separate side of milk.",
    price: 15.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/coffee-milk.webp",
  },
  {
    id: 128,
    name: "Cortado",
    category: "Coffees",
    description: "Equal parts espresso and steamed milk.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/cortado.webp",
  },
  {
    id: 129,
    name: "Cream Coffee",
    category: "Coffees",
    description: "Espresso mixed with steamed cream.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cream-coffee.webp",
  },
  {
    id: 130,
    name: "Double Espresso",
    category: "Coffees",
    description: "Two rich shots of intense espresso.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/double-espresso.webp",
  },
  {
    id: 131,
    name: "Espresso",
    category: "Coffees",
    description: "Rich and intense shot of coffee.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/espresso.webp",
  },
  {
    id: 132,
    name: "Flat White",
    category: "Coffees",
    description: "Espresso with micro-foamed milk.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/flat-white.webp",
  },
  {
    id: 133,
    name: "Illy Espresso",
    category: "Coffees",
    description: "Premium Italian Illy espresso shot.",
    price: 16.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/illy-espresso.webp",
  },
  {
    id: 134,
    name: "Latte Macchiato",
    category: "Coffees",
    description: "Steamed milk marked with a shot of espresso.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/latte-macchiato.webp",
  },
  {
    id: 135,
    name: "Mocha",
    category: "Coffees",
    description: "Espresso combined with chocolate and steamed milk.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/mocha.webp",
  },
  {
    id: 136,
    name: "Nespresso Coffee",
    category: "Coffees",
    description: "Classic Nespresso brewed coffee.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/nespresso.webp",
  },
  {
    id: 137,
    name: "Viennese Chocolate",
    category: "Coffees",
    description: "Hot chocolate topped with whipped cream.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/viennese-chocolate.webp",
  },

  // JUICES
  {
    id: 138,
    name: "Apple Juice",
    category: "Juices",
    description: "Freshly pressed apple juice.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/apple-juice.webp",
  },
  {
    id: 139,
    name: "Avocado Juice",
    category: "Juices",
    description: "Rich and creamy blended avocado juice.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/avocado-juice.webp",
  },
  {
    id: 140,
    name: "Avocado Juice with Dried Fruits",
    category: "Juices",
    description: "Creamy avocado juice blended with mixed dried fruits.",
    price: 23.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/avocado-juice-with-dried-fruits.webp",
  },
  {
    id: 141,
    name: "Banana Juice",
    category: "Juices",
    description: "Freshly blended banana juice.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/banana-juice.webp",
  },
  {
    id: 142,
    name: "Mango Juice",
    category: "Juices",
    description: "Fresh tropical mango juice.",
    price: 20.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/mango-juice.webp",
  },
  {
    id: 143,
    name: "Mixed Fruit Juice with Milk",
    category: "Juices",
    description: "Blend of mixed fruits with milk.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/mixed-fruit-juice-with-milk.webp",
  },
  {
    id: 144,
    name: "Mixed Fruit Juice with Orange",
    category: "Juices",
    description: "Blend of mixed fruits with orange juice.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/mixed-fruit-juice-with-orange.webp",
  },
  {
    id: 145,
    name: "Orange Juice",
    category: "Juices",
    description: "Freshly squeezed orange juice.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/orange-juice.webp",
  },
  {
    id: 146,
    name: "Pineapple Juice",
    category: "Juices",
    description: "Fresh sweet pineapple juice.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pineapple-juice.webp",
  },
  {
    id: 147,
    name: "Strawberry Juice",
    category: "Juices",
    description: "Freshly blended strawberry juice.",
    price: 18.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/strawberry-juice.webp",
  },

  // EXTRAS
  {
    id: 148,
    name: "Almond Amlou",
    category: "Extras",
    description:
      "Premium Amlou made with extra roasted almonds. Served with bread.",
    price: 12.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/almond.webp",
  },
  {
    id: 149,
    name: "Argan Oil Amlou",
    category: "Extras",
    description:
      "Traditional almond, honey, and argan oil dip. Served with bread.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/argan.webp",
  },
  {
    id: 150,
    name: "Black and Green Olives",
    category: "Extras",
    description: "Mixed marinated olives. Served with bread.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/olive.webp",
  },
  {
    id: 151,
    name: "Cheese Spread",
    category: "Extras",
    description: "Portion of spreadable cheese. Served with bread.",
    price: 3.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cheese.webp",
  },
  {
    id: 152,
    name: "Fresh Cheese (Jben)",
    category: "Extras",
    description:
      "Portion of traditional Moroccan fresh cheese. Served with bread.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/fresh-cheese.webp",
  },
  {
    id: 153,
    name: "Honey",
    category: "Extras",
    description: "Portion of pure honey. Served with bread.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/honey.webp",
  },
  {
    id: 154,
    name: "Jam",
    category: "Extras",
    description: "Portion of fruit jam. Served with bread.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/jam.webp",
  },
  {
    id: 155,
    name: "Nutella",
    category: "Extras",
    description: "Portion of rich hazelnut cocoa spread. Served with bread.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/nutella.webp",
  },
  {
    id: 156,
    name: "Olive Oil",
    category: "Extras",
    description:
      "Portion of high-quality extra virgin olive oil. Served with bread.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/olive-oil.webp",
  },
];