export const siteConfig = {
  name: "لامادلين أكادير",
  tagline: "مخبز حرفي ومقهى",
  description:
    "معجنات مصنوعة يدوياً، خبز حرفي، وقهوة استثنائية — تجربة أصيلة للمخبزة الفرنسية والمغربية منذ 2018.",
  phone: "05.28.26.43.44",
  email: "contact@lamadeleine.ma",
  address: "شارع الألفة، تيليلا، أكادير 80000",
  social: {
    instagram: "https://instagram.com/lamadeleine.agadir",
    facebook: "https://facebook.com/lamadeleine.agadir",
  },
  hours: [{ day: "الإثنين — الأحد", time: "6:00 صباحاً — 10:00 مساءً" }],
  science: 2018,
  mapLink: "https://maps.app.goo.gl/Z5memQUhJrBtShyx7",
};

type TodaysSpecial = {
  id: number;
  name: string;
  category: string;
  description: string;
  price: number;
  image: string;
};

export const todaysSpecials: TodaysSpecial[] = [
  {
    id: 1,
    name: "بان أو شوكولا",
    category: "معجنات",
    description:
      "طبقات مورقة بالزبدة ملفوفة حول قطعتين من الشوكولاتة الداكنة الفاخرة — معجنات الفطور الفرنسية الكلاسيكية.",
    price: 2.5,
    image: "/images/today-specials/today-3.webp",
  },
  {
    id: 2,
    name: "كرواسون بالزبدة",
    category: "فطور",
    description:
      "كرواسون ذهبي وخفيف جداً، مصنوع من زبدة نورماندي بنسبة دسم 84%. تخمير لمدة 72 ساعة لطبقات مثالية.",
    price: 2.5,
    image: "/images/today-specials/today-1.webp",
  },
  {
    id: 3,
    name: "سندويش كرواسون",
    category: "فطور",
    description:
      "معجنات فطور فرنسية كلاسيكية محشوة بكريمة غنية بالزبدة ومزينة برشة خفيفة من السكر الناعم.",
    price: 5,
    image: "/images/today-specials/today-2.webp",
  },
  {
    id: 4,
    name: "تارت الفواكه",
    category: "حلويات",
    description:
      "فواكه موسمية مرتبة فوق كريمة الفانيليا، موضوعة في عجينة تارت مقرمشة ومكرملة.",
    price: 7,
    image: "/images/today-specials/today-4.webp",
  },
  {
    id: 5,
    name: "ميل فوي باللوز",
    category: "حلويات",
    description:
      "ثلاث طبقات من العجينة المورقة المكرملة تتناوب مع كريمة اللوز الخفيفة، مغطاة بشرائح اللوز المحمص ورشة من السكر الناعم.",
    price: 10,
    image: "/images/today-specials/today-5.webp",
  },
  {
    id: 6,
    name: "كورتادو مادلاين المميز",
    category: "قهوة",
    description:
      "مقادير متساوية من الإسبريسو الغني جداً والحليب المبخر بقوام مثالي، مزين برشة من التوابل الدافئة.",
    price: 12,
    image: "/images/today-specials/today-6.webp",
  },
];

export const coffeeMenu = [
  {
    id: 1,
    name: "موكا",
    description: "إسبريسو ممزوج مع الشوكولاتة والحليب المبخر.",
    price: 18.0,
    icon: "Cookie",
  },
  {
    id: 2,
    name: "كابتشينو",
    description: "إسبريسو مغطى بمقادير متساوية من الحليب المبخر والرغوة.",
    price: 15.0,
    icon: "Milk",
  },
  {
    id: 3,
    name: "قهوة مع حليب جانبي",
    description: "إسبريسو يُقدم مع حليب جانبي منفصل.",
    price: 15.0,
    icon: "Coffee",
  },
  {
    id: 4,
    name: "كورتادو",
    description: "مقادير متساوية من الإسبريسو والحليب المبخر.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 5,
    name: "قهوة بالكريمة",
    description: "إسبريسو ممزوج بالكريمة المبخرة.",
    price: 12.0,
    icon: "Cookie",
  },
  {
    id: 6,
    name: "إسبريسو مزدوج",
    description: "جرعتان غنيتان من الإسبريسو المركز.",
    price: 18.0,
    icon: "Droplets",
  },
  {
    id: 7,
    name: "إسبريسو",
    description: "جرعة غنية ومركزة من القهوة.",
    price: 12.0,
    icon: "Coffee",
  },
  {
    id: 8,
    name: "فلات وايت",
    description: "إسبريسو مع حليب برغوة دقيقة.",
    price: 16.0,
    icon: "Milk",
  },
  {
    id: 9,
    name: "إسبريسو إيلي",
    description: "جرعة إسبريسو إيطالية فاخرة من إيلي.",
    price: 16.0,
    icon: "Sparkles",
  },
  {
    id: 10,
    name: "أمريكانو",
    description: "إسبريسو مخفف بالماء الساخن.",
    price: 14.0,
    icon: "Coffee",
  },
  {
    id: 11,
    name: "لاتيه ماكياتو",
    description: "حليب مبخر مضاف إليه جرعة من الإسبريسو.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 12,
    name: "قهوة نسبريسو",
    description: "قهوة نسبريسو كلاسيكية.",
    price: 15.0,
    icon: "Coffee",
  },
];

export const menuCategories = [
  "وجبات الفطور",
  "المعجنات والحلويات",
  "القهوة",
  "الحليب والشاي",
  "المشروبات الباردة",
];

export const menuItems = [
  {
    id: 1,
    name: "فطور إكسبريس",
    category: "وجبات الفطور",
    description:
      "حسوة، مشروب ساخن، عصير برتقال طازج، سلة معجنات، زبادي، وماء معدني.",
    price: 26.0,
    popular: false,
    image: "/images/menu/breakfast-express.webp",
  },
  {
    id: 2,
    name: "فطور بلدي",
    category: "وجبات الفطور",
    description:
      "حسوة، مشروب ساخن، عصير برتقال طازج، مسمن أو ملوي، حرشة، عسل، جبن بلدي، وماء معدني.",
    price: 28.0,
    popular: false,
    image: "/images/menu/breakfast-beldi.webp",
  },
  {
    id: 3,
    name: "فطور كونتيننتال",
    category: "وجبات الفطور",
    description:
      "حسوة، مشروب ساخن، عصير برتقال طازج، أومليت بالجبن، زيت زيتون، زيتون، جبن بلدي، سلة خبز، ماء معدني، وزبادي.",
    price: 35.0,
    popular: false,
    image: "/images/menu/breakfast-continental.webp",
  },
  {
    id: 4,
    name: "فطور فاسي",
    category: "وجبات الفطور",
    description:
      "حسوة، مشروب ساخن، عصير برتقال طازج، أومليت بالخليع، زيت زيتون، زيتون، جبن بلدي، سلة خبز، ماء معدني، وزبادي.",
    price: 37.0,
    popular: false,
    image: "/images/menu/breakfast-fassi.webp",
  },
  {
    id: 5,
    name: "فطور سوسي",
    category: "وجبات الفطور",
    description:
      "حسوة، مشروب ساخن، عصير برتقال طازج، أملو، زيت زيتون، جبن بلدي، زيتون أسود وأخضر، عسل، مربى، وماء معدني.",
    price: 38.0,
    popular: true,
    image: "/images/menu/breakfast-soussi.webp",
  },
  {
    id: 6,
    name: "فطور غورماند",
    category: "وجبات الفطور",
    description:
      "حسوة، مشروب ساخن، عصير برتقال طازج، زيت زيتون، أملو، زيتون أسود، عسل، سلة خبز، زبادي، وماء معدني.",
    price: 26.0,
    popular: false,
    image: "/images/menu/breakfast-gourmand.webp",
  },
  {
    id: 7,
    name: "فطور لا مادلين",
    category: "وجبات الفطور",
    description:
      "تشكيلتنا الخاصة: حسوة، مشروب ساخن، عصير برتقال طازج، أومليت (جبن / كاشير / طماطم)، زيت زيتون، زيتون، عسل، جبن بلدي، أملو، سلة خبز، كريب، شوكولاتة دهن، كيك أمريكي، ماء معدني، وزبادي.",
    price: 55.0,
    popular: true,
    image: "/images/menu/breakfast-la-madeleine.webp",
  },
  {
    id: 8,
    name: "فطور الأطفال",
    category: "وجبات الفطور",
    description:
      "حليب بالشوكولاتة، عصير برتقال طازج، خبز صغير، كيك الفانيليا، ماء معدني، وزبادي.",
    price: 25.0,
    popular: false,
    image: "/images/menu/breakfast-kids.webp",
  },
  {
    id: 9,
    name: "أومليت عادي (بيضتان)",
    category: "الأومليت",
    description: "أومليت بسيط من بيضتين، يقدم مع الزيتون وزيت الزيتون.",
    price: 13.0,
    popular: false,
    image: "/images/menu/omelet-nature.webp",
  },
  {
    id: 10,
    name: "أومليت عادي (4 بيضات)",
    category: "الأومليت",
    description: "أومليت وافر من أربع بيضات، يقدم مع الزيتون وزيت الزيتون.",
    price: 18.0,
    popular: false,
    image: "/images/menu/omelet-nature.webp",
  },
  {
    id: 11,
    name: "أومليت بالطماطم (بيضتان)",
    category: "الأومليت",
    description:
      "أومليت من بيضتين مع الطماطم الطازجة، يقدم مع الزيتون وزيت الزيتون.",
    price: 16.0,
    popular: false,
    image: "/images/menu/omelet-tomato.webp",
  },
  {
    id: 12,
    name: "أومليت بالطماطم (4 بيضات)",
    category: "الأومليت",
    description:
      "أومليت من أربع بيضات مع الطماطم الطازجة، يقدم مع الزيتون وزيت الزيتون.",
    price: 20.0,
    popular: false,
    image: "/images/menu/omelet-tomato.webp",
  },
  {
    id: 13,
    name: "أومليت بالجبن (بيضتان)",
    category: "الأومليت",
    description:
      "أومليت شهي من بيضتين محشو بالجبن الذائب، يقدم مع الزيتون وزيت الزيتون.",
    price: 16.0,
    popular: true,
    image: "/images/menu/omelet-cheese.webp",
  },
  {
    id: 14,
    name: "أومليت بالجبن (4 بيضات)",
    category: "الأومليت",
    description:
      "أومليت شهي من أربع بيضات محشو بالجبن الذائب، يقدم مع الزيتون وزيت الزيتون.",
    price: 22.0,
    popular: false,
    image: "/images/menu/omelet-cheese.webp",
  },
  {
    id: 15,
    name: "أومليت بالخليع (بيضتان)",
    category: "الأومليت",
    description:
      "أومليت من بيضتين مع الخليع المغربي التقليدي، يقدم مع الزيتون وزيت الزيتون.",
    price: 18.0,
    popular: false,
    image: "/images/menu/omelet-khlii.webp",
  },
  {
    id: 16,
    name: "أومليت بالخليع (4 بيضات)",
    category: "الأومليت",
    description:
      "أومليت من أربع بيضات مع الخليع المغربي التقليدي، يقدم مع الزيتون وزيت الزيتون.",
    price: 24.0,
    popular: false,
    image: "/images/menu/omelet-khlii.webp",
  },
  {
    id: 17,
    name: "أومليت بالكاشير (بيضتان)",
    category: "الأومليت",
    description: "أومليت من بيضتين مع الكاشير، يقدم مع الزيتون وزيت الزيتون.",
    price: 17.0,
    popular: false,
    image: "/images/menu/omelet-charcuterie.webp",
  },
  {
    id: 18,
    name: "أومليت بالكاشير (4 بيضات)",
    category: "الأومليت",
    description:
      "أومليت من أربع بيضات مع الكاشير، يقدم مع الزيتون وزيت الزيتون.",
    price: 23.0,
    popular: false,
    image: "/images/menu/omelet-charcuterie.webp",
  },
  {
    id: 19,
    name: "أملو",
    category: "إضافات",
    description:
      "مزيج تقليدي من اللوز وزيت الأركان والعسل الحر، يقدم مع الخبز.",
    price: 8.0,
    popular: false,
    image: "/images/menu/amlou.webp",
  },
  {
    id: 20,
    name: "أملو بحبات اللوز",
    category: "إضافات",
    description:
      "أملو تقليدي مغطى بحبات اللوز الكاملة الإضافية، يقدم مع الخبز.",
    price: 12.0,
    popular: false,
    image: "/images/menu/amlou-almonds.webp",
  },
  {
    id: 21,
    name: "عسل",
    category: "إضافات",
    description: "عسل طبيعي نقي، يقدم مع الخبز.",
    price: 6.0,
    popular: false,
    image: "/images/menu/honey.webp",
  },
  {
    id: 22,
    name: "مربى",
    category: "إضافات",
    description: "مربى الفواكه اللذيذ، يقدم مع الخبز.",
    price: 6.0,
    popular: false,
    image: "/images/menu/jam.webp",
  },
  {
    id: 23,
    name: "جبن بلدي",
    category: "إضافات",
    description: "جبن طازج على الطريقة المغربية التقليدية، يقدم مع الخبز.",
    price: 8.0,
    popular: false,
    image: "/images/menu/jben.webp",
  },
  {
    id: 24,
    name: "جبن",
    category: "إضافات",
    description: "حصة من الجبن، تقدم مع الخبز.",
    price: 3.0,
    popular: false,
    image: "/images/menu/cheese.webp",
  },
  {
    id: 25,
    name: "زيت زيتون",
    category: "إضافات",
    description: "حصة إضافية من زيت الزيتون الصافي، تقدم مع الخبز.",
    price: 8.0,
    popular: false,
    image: "/images/menu/olive-oil.webp",
  },
  {
    id: 26,
    name: "زيتون أسود وأخضر",
    category: "إضافات",
    description: "تشكيلة من الزيتون الأسود والأخضر، تقدم مع الخبز.",
    price: 5.0,
    popular: false,
    image: "/images/menu/olives.webp",
  },
  {
    id: 27,
    name: "نوتيلا",
    category: "إضافات",
    description: "حصة وافرة من شوكولاتة نوتيلا، تقدم مع الخبز.",
    price: 10.0,
    popular: false,
    image: "/images/menu/nutella-side.webp",
  },

  // ---------- الحساء ----------
  {
    id: 28,
    name: "حسوة شعير",
    category: "الشوربة والحساء",
    description:
      "حساء دافئ ومغذي من الشعير والحليب على الطريقة المغربية التقليدية.",
    price: 7.0,
    popular: false,
    image: "/images/menu/hesewa.webp",
  },
  {
    id: 29,
    name: "حريرة مغربية",
    category: "الشوربة والحساء",
    description: "شوربة مغربية أصيلة وغنية بالطماطم والعدس والحمص والتوابل.",
    price: 10.0,
    popular: false,
    image: "/images/menu/soup.webp",
  },

  // ---------- القهوة ----------
  {
    id: 30,
    name: "إسبريسو",
    category: "القهوة",
    description:
      "جرعة مركزة من الإسبريسو الكلاسيكي الغني على الطريقة الإيطالية.",
    price: 12.0,
    popular: false,
    image: "/images/menu/espresso.webp",
  },
  {
    id: 31,
    name: "إسبريسو إيلي",
    category: "القهوة",
    description: "إسبريسو فاخر محضر من حبوب قهوة إيلي المميزة.",
    price: 16.0,
    popular: false,
    image: "/images/menu/espresso-illy.webp",
  },
  {
    id: 32,
    name: "كافيه كريم",
    category: "القهوة",
    description: "إسبريسو مغطى برغوة حليب ساخنة وكريمية.",
    price: 12.0,
    popular: false,
    image: "/images/menu/cafe-creme.webp",
  },
  {
    id: 33,
    name: "قهوة نسبريسو",
    category: "القهوة",
    description: "قهوة سلسة ومحضرة من كبسولات نسبريسو المختارة.",
    price: 15.0,
    popular: false,
    image: "/images/menu/cafe-nespresso.webp",
  },
  {
    id: 34,
    name: "أمريكانو",
    category: "القهوة",
    description: "إسبريسو مخفف بالماء الساخن لمذاق قهوة أخف وأهدأ.",
    price: 14.0,
    popular: false,
    image: "/images/menu/cafe-americain.webp",
  },
  {
    id: 35,
    name: "كافيه سيباري",
    category: "القهوة",
    description: "إسبريسو يقدم مع الحليب المبخر جانباً حسب رغبتك.",
    price: 15.0,
    popular: false,
    image: "/images/menu/cafe-separe.webp",
  },
  {
    id: 36,
    name: "دبل إسبريسو",
    category: "القهوة",
    description: "جرعة مضاعفة من قهوة الإسبريسو المركزة والمنعشة.",
    price: 18.0,
    popular: false,
    image: "/images/menu/double-espresso.webp",
  },
  {
    id: 37,
    name: "كابتشينو",
    category: "القهوة",
    description: "إسبريسو غني مع حليب مبخر وطبقة كثيفة من رغوة الحليب.",
    price: 15.0,
    popular: true,
    image: "/images/menu/cappuccino.webp",
  },
  {
    id: 38,
    name: "مورشا",
    category: "القهوة",
    description: "قهوة سوداء مغربية قوية ومتبلة بالنكهات التقليدية.",
    price: 18.0,
    popular: false,
    image: "/images/menu/morcha.webp",
  },
  {
    id: 39,
    name: "كورتادو",
    category: "القهوة",
    description: "إسبريسو مكسور بلمسة خفيفة من الحليب الساخن المبخر.",
    price: 16.0,
    popular: false,
    image: "/images/menu/cortado.webp",
  },
  {
    id: 40,
    name: "لاتيه ماكياتو",
    category: "القهوة",
    description: "حليب ساخن مبخر مع لمسة لطيفة من جرعة الإسبريسو.",
    price: 16.0,
    popular: false,
    image: "/images/menu/latte-macchiato.webp",
  },
  {
    id: 41,
    name: "فلات وايت",
    category: "القهوة",
    description: "إسبريسو مع طبقة ناعمة ومخملية من رغوة الحليب الدقيقة.",
    price: 16.0,
    popular: false,
    image: "/images/menu/flat-white.webp",
  },
  {
    id: 42,
    name: "شوكولاتة فيينواز",
    category: "القهوة",
    description: "شوكولاتة ساخنة غنية تعلوها طبقة وافرة من الكريمة المخفوقة.",
    price: 16.0,
    popular: false,
    image: "/images/menu/chocolat-viennois.webp",
  },

  // ---------- القهوة المثلجة ----------
  {
    id: 43,
    name: "أفوغاتو",
    category: "القهوة المثلجة",
    description:
      "كرة من آيس كريم الفانيليا مغمورة في جرعة إسبريسو ساخنة ولذيذة.",
    price: 18.0,
    popular: false,
    image: "/images/menu/affogato.webp",
  },
  {
    id: 44,
    name: "موكا مثلجة",
    category: "القهوة المثلجة",
    description: "إسبريسو بارد ممزوج بالشوكولاتة الغنية والحليب البارد.",
    price: 19.0,
    popular: false,
    image: "/images/menu/iced-mocha.webp",
  },
  {
    id: 45,
    name: "كراميل ماكياتو مثلج",
    category: "القهوة المثلجة",
    description: "طبقات من الحليب البارد والإسبريسو مع صوص الكراميل اللذيذ.",
    price: 21.0,
    popular: false,
    image: "/images/menu/iced-caramel-macchiato.webp",
  },
  {
    id: 46,
    name: "فرابتشينو مثلج",
    category: "القهوة المثلجة",
    description:
      "مشروب قهوة مثلجة ومخفوقة، متوفرة بالفانيليا أو الشوكولاتة أو الكراميل.",
    price: 21.0,
    popular: true,
    image: "/images/menu/iced-frappuccino.webp",
  },
  {
    id: 47,
    name: "قهوة مثلجة",
    category: "القهوة المثلجة",
    description:
      "قهوة منعشة تقدم مع الثلج، متوفرة عادية أو بنكهة الفانيليا أو الشوكولاتة أو الكراميل أو البندق.",
    price: 18.0,
    popular: false,
    image: "/images/menu/iced-coffee.webp",
  },
  {
    id: 48,
    name: "لاتيه مثلج",
    category: "القهوة المثلجة",
    description:
      "إسبريسو وحليب بارد فوق مكعبات الثلج، متوفر عادي أو بالفانيليا أو الشوكولاتة أو الكراميل أو البندق.",
    price: 19.0,
    popular: false,
    image: "/images/menu/iced-latte.webp",
  },

  // ---------- الحليب والشاي ----------
  {
    id: 49,
    name: "حليب بالشوكولاتة",
    category: "الحليب والشاي",
    description: "حليب دافئ ممزوج بالشوكولاتة اللذيذة.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-chocolat.webp",
  },
  {
    id: 50,
    name: "حليب ساخن",
    category: "الحليب والشاي",
    description: "كوب بسيط ومريح من الحليب الدافئ الطبيعي.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-chaud.webp",
  },
  {
    id: 51,
    name: "حليب باللويزة",
    category: "الحليب والشاي",
    description: "حليب دافئ منقوع بعشبة اللويزة العطرية المهدئة.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-verveine.webp",
  },
  {
    id: 52,
    name: "حليب بالسيروب",
    category: "الحليب والشاي",
    description: "حليب دافئ محلى بشراب السيروب المنكه اللذيذ.",
    price: 11.0,
    popular: false,
    image: "/images/menu/lait-sirop.webp",
  },
  {
    id: 53,
    name: "حليب بليبتون",
    category: "الحليب والشاي",
    description: "حليب دافئ ممتزج بنكهة شاي ليبتون الأصيل.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-lipton.webp",
  },
  {
    id: 54,
    name: "شاي اللويزة",
    category: "الحليب والشاي",
    description: "منقوع مهدئ وطبيعي من أوراق اللويزة العطرية.",
    price: 11.0,
    popular: false,
    image: "/images/menu/verveine-nature.webp",
  },
  {
    id: 55,
    name: "شاي ليبتون",
    category: "الحليب والشاي",
    description: "شاي أسود كلاسيكي من ليبتون.",
    price: 11.0,
    popular: false,
    image: "/images/menu/lipton-nature.webp",
  },
  {
    id: 56,
    name: "أتاي مغربي بالنعناع",
    category: "الحليب والشاي",
    description: "شاي أخضر مغربي تقليدي محلى ومحضر بالنعناع الطازج.",
    price: 11.0,
    popular: true,
    image: "/images/menu/the-marocain.webp",
  },

  // ---------- الوافل، الكريب والبانكيك ----------
  {
    id: 57,
    name: "وافل بالكراميل",
    category: "الوافل، الكريب والبانكيك",
    description: "وافل ذهبي مقرمش ومزين بصوص الكراميل الشهي.",
    price: 16.0,
    popular: false,
    image: "/images/menu/waffle-caramel.webp",
  },
  {
    id: 58,
    name: "وافل بالنوتيلا",
    category: "الوافل، الكريب والبانكيك",
    description: "وافل ذهبي مقرمش مغطى بسخاء بشوكولاتة نوتيلا الذائبة.",
    price: 19.0,
    popular: true,
    image: "/images/menu/waffle-nutella.webp",
  },
  {
    id: 59,
    name: "وافل نوتيلا وموز",
    category: "الوافل، الكريب والبانكيك",
    description: "وافل ذهبي مغطى بالنوتيلا وقطع الموز الطازجة.",
    price: 22.0,
    popular: false,
    image: "/images/menu/waffle-nutella-banane.webp",
  },
  {
    id: 60,
    name: "وافل نوتيلا وفواكه موسمية",
    category: "الوافل، الكريب والبانكيك",
    description:
      "وافل ذهبي مغطى بالنوتيلا وتشكيلة من الفواكه الموسمية الطازجة.",
    price: 27.0,
    popular: false,
    image: "/images/menu/waffle-nutella-fruits.webp",
  },
  {
    id: 61,
    name: "كريب بالكراميل",
    category: "الوافل، الكريب والبانكيك",
    description: "كريب رقيق محشو بصلصة الكراميل الغنية.",
    price: 16.0,
    popular: false,
    image: "/images/menu/crepe-caramel.webp",
  },
  {
    id: 62,
    name: "كريب بالنوتيلا",
    category: "الوافل، الكريب والبانكيك",
    description: "كريب رقيق محشو بسخاء بشوكولاتة نوتيلا اللذيذة.",
    price: 19.0,
    popular: false,
    image: "/images/menu/crepe-nutella.webp",
  },
  {
    id: 63,
    name: "كريب نوتيلا وموز",
    category: "الوافل، الكريب والبانكيك",
    description: "كريب رقيق محشو بالنوتيلا مع شرائح الموز الطازجة.",
    price: 23.0,
    popular: false,
    image: "/images/menu/crepe-nutella-banane.webp",
  },
  {
    id: 64,
    name: "كريب نوتيلا وأوريو",
    category: "الوافل، الكريب والبانكيك",
    description: "كريب رقيق محشو بالنوتيلا مع فتات بسكويت الأوريو المقرمش.",
    price: 25.0,
    popular: false,
    image: "/images/menu/crepe-nutella-oreo.webp",
  },
  {
    id: 65,
    name: "كريب نوتيلا وفواكه موسمية",
    category: "الوافل، الكريب والبانكيك",
    description:
      "كريب رقيق محشو بالنوتيلا ومزين بقطع الفواكه الموسمية الطازجة.",
    price: 29.0,
    popular: false,
    image: "/images/menu/crepe-nutella-fruits.webp",
  },
  {
    id: 66,
    name: "بانكيك بالعسل",
    category: "الوافل، الكريب والبانكيك",
    description: "طبقات من البانكيك الهش والخفيف مسكوب عليها العسل الطبيعي.",
    price: 16.0,
    popular: false,
    image: "/images/menu/pancakes-miel.webp",
  },
  {
    id: 67,
    name: "بانكيك بأملو",
    category: "الوافل، الكريب والبانكيك",
    description: "طبقات من البانكيك الهش مغطاة بأملو المغربي الأصيل.",
    price: 17.0,
    popular: false,
    image: "/images/menu/pancakes-amlou.webp",
  },
  {
    id: 68,
    name: "بانكيك بالنوتيلا",
    category: "الوافل، الكريب والبانكيك",
    description: "طبقات من البانكيك الهش والمغطى بطبقة سخية من النوتيلا.",
    price: 21.0,
    popular: false,
    image: "/images/menu/pancakes-nutella.webp",
  },
  {
    id: 69,
    name: "بانكيك نوتيلا وموز",
    category: "الوافل، الكريب والبانكيك",
    description: "بانكيك هش محلى بالنوتيلا ومزين بشرائح الموز الطازجة.",
    price: 26.0,
    popular: false,
    image: "/images/menu/pancakes-nutella-banane.webp",
  },

  // ---------- المعجنات والحلويات ----------
  {
    id: 70,
    name: "سيكار بفواكه البحر",
    category: "المعجنات والحلويات",
    description:
      "ورقة بسطيلة مقرمشة ملفوفة بحشوة متبلة من فواكه البحر المتنوعة.",
    price: 12.0,
    popular: false,
    image: "/images/menu/cigar.webp",
  },
  {
    id: 71,
    name: "بسطيلة بفواكه البحر",
    category: "المعجنات والحلويات",
    description:
      "فطيرة مغربية مقرمشة ولذيذة محشوة بفواكه البحر المتبلة والشعرية الصينية.",
    price: 12.0,
    popular: false,
    image: "/images/menu/pastilla.webp",
  },
  {
    id: 72,
    name: "ساندويتش",
    category: "المعجنات والحلويات",
    description: "ساندويتش مالح وطازج محضر بأجود المكونات.",
    price: 8.0,
    popular: false,
    image: "/images/menu/sandwich.webp",
  },
  {
    id: 73,
    name: "ميني بيتزا",
    category: "المعجنات والحلويات",
    description: "بيتزا صغيرة فردية مغطاة بصلصة الطماطم الغنية والجبن الذائب.",
    price: 6.0,
    popular: false,
    image: "/images/menu/pizza.webp",
  },
  {
    id: 74,
    name: "فطيرة الهوت دوغ",
    category: "المعجنات والحلويات",
    description: "نقانق شهية ملفوفة ومخبوزة بعجينة لينة وذهبية.",
    price: 9.0,
    popular: false,
    image: "/images/menu/hot-dog.webp",
  },
  {
    id: 75,
    name: "بسطيلة بالدجاج",
    category: "المعجنات والحلويات",
    description:
      "بسطيلة تقليدية بنكهة حلوة ومالحة، محشوة بالدجاج المتبل واللوز المحمص.",
    price: 10.0,
    popular: false,
    image: "/images/menu/pastilla.webp",
  },
  {
    id: 76,
    name: "بريوات بالجبن",
    category: "المعجنات والحلويات",
    description: "مثلثات ورقة البسطيلة المقرمشة والمحشوة بالجبن المتبل اللذيذ.",
    price: 7.0,
    popular: false,
    image: "/images/menu/briouat.webp",
  },
  {
    id: 77,
    name: "تارت اللوز",
    category: "المعجنات والحلويات",
    description: "عجينة تارت هشة ومقرمشة محشوة بكريمة اللوز الغنية.",
    price: 10.0,
    popular: false,
    image: "/images/menu/tart.webp",
  },
  {
    id: 78,
    name: "شوسون بالتفاح",
    category: "المعجنات والحلويات",
    description: "عجينة مورقة ومقرمشة محشوة بحشوة التفاح المكرمل والدافئ.",
    price: 6.0,
    popular: false,
    image: "/images/menu/apple-turnover.webp",
  },
  {
    id: 79,
    name: "بسبوسة بالشوكولاتة",
    category: "المعجنات والحلويات",
    description: "كيكة سميد طرية وغنية بنكهة الشوكولاتة اللذيذة.",
    price: 8.0,
    popular: false,
    image: "/images/menu/basbousa.webp",
  },
  {
    id: 80,
    name: "مادلين بالشوكولاتة",
    category: "المعجنات والحلويات",
    description: "كعكة مادلين إسفنجية تقليدية ولذيذة بنكهة الشوكولاتة.",
    price: 2.5,
    popular: false,
    image: "/images/menu/madeleine.webp",
  },
  {
    id: 81,
    name: "دونات",
    category: "المعجنات والحلويات",
    description: "دونات كلاسيكية مقلية وطرية وذات حلاوة متوازنة.",
    price: 4.0,
    popular: false,
    image: "/images/menu/donut.webp",
  },
  {
    id: 82,
    name: "تارت فرانجيبان",
    category: "المعجنات والحلويات",
    description: "تارت حلو ولذيذ محشو بكريمة اللوز (فرانجيبان) الشهية.",
    price: 8.0,
    popular: false,
    image: "/images/menu/frangipane-tart.webp",
  },
  {
    id: 83,
    name: "بيتيفييه بالفواكه",
    category: "المعجنات والحلويات",
    description: "فطيرة من العجين المورق محشوة بكومبوت الفواكه الحلوة اللذيذة.",
    price: 6.0,
    popular: false,
    image: "/images/menu/pithiviers.webp",
  },
  {
    id: 84,
    name: "تارتليت بالفواكه",
    category: "المعجنات والحلويات",
    description: "تارت صغير ومقرمش محشو بالكريمة ومزين بقطع الفواكه الطازجة.",
    price: 7.0,
    popular: false,
    image: "/images/menu/fruit-tartlet.webp",
  },
  {
    id: 85,
    name: "بسبوسة بالفانيليا",
    category: "المعجنات والحلويات",
    description: "كيكة سميد كلاسيكية وطرية مسقية بشراب الفانيليا الحلو.",
    price: 6.0,
    popular: false,
    image: "/images/menu/basbousa.webp",
  },
  {
    id: 86,
    name: "مادلين بالفانيليا",
    category: "المعجنات والحلويات",
    description:
      "كعكة مادلين فرنسية كلاسيكية زبدية على شكل صدفة بنكهة الفانيليا.",
    price: 1.5,
    popular: false,
    image: "/images/menu/madeleine.webp",
  },
  {
    id: 87,
    name: "كرواسون باللوز",
    category: "المعجنات والحلويات",
    description:
      "كرواسون مورق ومقرمش محشو بكريمة اللوز ومزين برقائق اللوز المحمص.",
    price: 5.0,
    popular: false,
    image: "/images/menu/croissant.webp",
  },
  {
    id: 88,
    name: "مثلث باللوز",
    category: "المعجنات والحلويات",
    description: "معجنات مورقة ومقرمشة على شكل مثلث ومحشوة بعقدة اللوز الحلوة.",
    price: 6.0,
    popular: false,
    image: "/images/menu/triangle.webp",
  },
  {
    id: 89,
    name: "دانيش بالشوكولاتة",
    category: "المعجنات والحلويات",
    description: "معجنات دانيش مورقة وغنية بتموجات الشوكولاتة الذائبة.",
    price: 4.0,
    popular: false,
    image: "/images/menu/danish.webp",
  },
  {
    id: 90,
    name: "معجنات دانيش",
    category: "المعجنات والحلويات",
    description: "معجنات دانيش تقليدية مورقة ومقرمشة محضرة بالزبدة الفاخرة.",
    price: 3.5,
    popular: false,
    image: "/images/menu/danish.webp",
  },
  {
    id: 91,
    name: "حرشة",
    category: "المعجنات والحلويات",
    description: "خبز سميد مغربي تقليدي محضر في المقلاة ومقرمش من الخارج.",
    price: 2.5,
    popular: false,
    image: "/images/menu/harcha.webp",
  },
  {
    id: 92,
    name: "مسمن",
    category: "المعجنات والحلويات",
    description: "رغيف مغربي تقليدي مورق ومقرمش على شكل مربعات ذهبية.",
    price: 4.0,
    popular: false,
    image: "/images/menu/msemmen.webp",
  },
  {
    id: 93,
    name: "حرشة بزيت الزيتون",
    category: "المعجنات والحلويات",
    description: "حرشة سميد تقليدية محضرة بزيت الزيتون البكر الأصيل.",
    price: 3.5,
    popular: false,
    image: "/images/menu/oil-harcha.webp",
  },
  {
    id: 94,
    name: "بان سويس",
    category: "المعجنات والحلويات",
    description:
      "فطيرة مورقة ولذيذة محشوة بكاسترد الفانيليا وحبيبات الشوكولاتة.",
    price: 3.0,
    popular: false,
    image: "/images/menu/pain-suisse.webp",
  },
  {
    id: 95,
    name: "بان أو شوكولا / كرواسون",
    category: "المعجنات والحلويات",
    description: "معجنات فرنسية كلاسيكية مورقة ومقرمشة محضرة بالزبدة الطبيعية.",
    price: 2.5,
    popular: false,
    image: "/images/menu/pain-au-chocolat.webp",
  },
  {
    id: 96,
    name: "بيتيفييه",
    category: "المعجنات والحلويات",
    description: "فطيرة دائرية من العجين المورق المقرمش بحشوة حلوة ولذيذة.",
    price: 5.0,
    popular: false,
    image: "/images/menu/pithiviers.webp",
  },
  {
    id: 97,
    name: "ميني كيك بالتوت",
    category: "المعجنات والحلويات",
    description: "كيك صغير وهش بنكهة التوت الأحمر المنعشة واللذيذة.",
    price: 8.0,
    popular: false,
    image: "/images/menu/minicake.webp",
  },
  {
    id: 98,
    name: "ميل فوي",
    category: "المعجنات والحلويات",
    description:
      "حلوى فرنسية شهيرة مؤلفة من طبقات هشة ومقرمشة محشوة بكريمة الفانيليا الناعمة.",
    price: 8.0,
    popular: false,
    image: "/images/menu/millefeuille.webp",
  },
  {
    id: 99,
    name: "ميني كيك",
    category: "المعجنات والحلويات",
    description: "كيك فردي صغير، طري ولذيذ المذاق.",
    price: 7.0,
    popular: false,
    image: "/images/menu/minicake.webp",
  },
  {
    id: 100,
    name: "ميني كب كيك",
    category: "المعجنات والحلويات",
    description: "كب كيك صغير الحجم هش ومزين بكريمة التزيين الشهية.",
    price: 4.0,
    popular: false,
    image: "/images/menu/cupcake.webp",
  },

  // ---------- السموذي والميلك شيك ----------
  {
    id: 101,
    name: "سموذي الفراولة",
    category: "السموذي والميلك شيك",
    description: "فراولة طازجة مخفوقة في مشروب فاكهي ناعم ومنعش.",
    price: 23.0,
    popular: true,
    image: "/images/menu/smoothie-fraise.webp",
  },
  {
    id: 102,
    name: "سموذي الموز",
    category: "السموذي والميلك شيك",
    description: "سموذي كريمي ولذيذ محضر من الموز الطازج والناضج.",
    price: 23.0,
    popular: false,
    image: "/images/menu/smoothie-banane.webp",
  },
  {
    id: 103,
    name: "سموذي المانجو",
    category: "السموذي والميلك شيك",
    description: "سموذي استوائي سلس وغني بنكهة المانجو الطبيعية.",
    price: 23.0,
    popular: false,
    image: "/images/menu/smoothie-mangue.webp",
  },
  {
    id: 104,
    name: "سموذي إكزوتيك",
    category: "السموذي والميلك شيك",
    description: "مزيج منعش من الفواكه الاستوائية المتنوعة لتجربة منعشة.",
    price: 26.0,
    popular: false,
    image: "/images/menu/smoothie-exotique.webp",
  },
  {
    id: 105,
    name: "ميلك شيك شوكولاتة",
    category: "السموذي والميلك شيك",
    description: "ميلك شيك شوكولاتة كثيف وكريمي فائق اللذة.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milkshake-choco.webp",
  },
  {
    id: 106,
    name: "ميلك شيك فانيليا",
    category: "السموذي والميلك شيك",
    description: "ميلك شيك كثيف وناعم بنكهة الفانيليا الغنية.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milkshake-vanille.webp",
  },
  {
    id: 107,
    name: "ميلك شيك موز",
    category: "السموذي والميلك شيك",
    description: "ميلك شيك كثيف وكريمي محضر من الموز الطبيعي.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milkshake-banane.webp",
  },
  {
    id: 108,
    name: "ميلك شيك فراولة",
    category: "السموذي والميلك شيك",
    description: "ميلك شيك كريمي ولذيذ بنكهة الفراولة الطازجة.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milkshake-fraise.webp",
  },
  {
    id: 109,
    name: "ميلك شيك أوريو",
    category: "السموذي والميلك شيك",
    description: "ميلك شيك كريمي ممزوج بقطع بسكويت الأوريو المقرمشة.",
    price: 26.0,
    popular: false,
    image: "/images/menu/milkshake-oreo.webp",
  },

  // ---------- الموهيتو ----------
  {
    id: 110,
    name: "فيرجن موهيتو",
    category: "الموهيتو",
    description: "موهيتو منعش خالٍ من الكحول بالليمون الأخضر والنعناع الطازج.",
    price: 19.0,
    popular: false,
    image: "/images/menu/mojito-virgin.webp",
  },
  {
    id: 111,
    name: "موهيتو أزرق",
    category: "الموهيتو",
    description: "موهيتو منعش بلون أزرق جذاب مع الليمون والنعناع.",
    price: 22.0,
    popular: false,
    image: "/images/menu/mojito-blue.webp",
  },
  {
    id: 112,
    name: "موهيتو وردي",
    category: "الموهيتو",
    description: "موهيتو منعش بنكهة الورد اللطيفة مع الليمون والنعناع.",
    price: 22.0,
    popular: false,
    image: "/images/menu/mojito-roso.webp",
  },

  // ---------- العصائر الطبيعية ----------
  {
    id: 113,
    name: "عصير برتقال",
    category: "العصائر الطبيعية",
    description: "عصير برتقال طازج معصور فور الطلب.",
    price: 16.0,
    popular: false,
    image: "/images/menu/jus-orange.webp",
  },
  {
    id: 114,
    name: "عصير موز",
    category: "العصائر الطبيعية",
    description: "عصير موز طازج مخفوق بقوام كريمي.",
    price: 16.0,
    popular: false,
    image: "/images/menu/jus-banane.webp",
  },
  {
    id: 115,
    name: "عصير تفاح",
    category: "العصائر الطبيعية",
    description: "عصير تفاح طبيعي معصور وطازج.",
    price: 16.0,
    popular: false,
    image: "/images/menu/jus-pomme.webp",
  },
  {
    id: 116,
    name: "عصير أفوكادو",
    category: "العصائر الطبيعية",
    description: "عصير أفوكادو غني وطبيعي بقوام كثيف ورائع.",
    price: 18.0,
    popular: false,
    image: "/images/menu/jus-avocat.webp",
  },
  {
    id: 117,
    name: "عصير فراولة",
    category: "العصائر الطبيعية",
    description: "عصير فراولة طبيعي طازج ومخفوق بعناية.",
    price: 18.0,
    popular: false,
    image: "/images/menu/jus-fraise.webp",
  },
  {
    id: 118,
    name: "عصير مانجو",
    category: "العصائر الطبيعية",
    description: "عصير مانجو طبيعي حلو وطازج المذاق.",
    price: 20.0,
    popular: false,
    image: "/images/menu/jus-mangue.webp",
  },
  {
    id: 119,
    name: "عصير أناناس",
    category: "العصائر الطبيعية",
    description: "عصير أناناس طبيعي ومنعش وغني بالفيتامينات.",
    price: 23.0,
    popular: false,
    image: "/images/menu/jus-ananas.webp",
  },
  {
    id: 120,
    name: "عصير باناشي بالحليب",
    category: "العصائر الطبيعية",
    description: "تشكيلة من الفواكه الطازجة المخفوقة مع الحليب.",
    price: 18.0,
    popular: false,
    image: "/images/menu/jus-panache-lait.webp",
  },
  {
    id: 121,
    name: "عصير باناشي بالبرتقال",
    category: "العصائر الطبيعية",
    description: "تشكيلة من الفواكه الطازجة المخفوقة مع عصير البرتقال المنعش.",
    price: 23.0,
    popular: true,
    image: "/images/menu/jus-panache-orange.webp",
  },
  {
    id: 122,
    name: "عصير أفوكادو بالفواكه الجافة",
    category: "العصائر الطبيعية",
    description:
      "عصير أفوكادو كريمي فاخر ومزين بتشكيلة غنية من المكسرات والفواكه الجافة.",
    price: 23.0,
    popular: false,
    image: "/images/menu/jus-avocat-fruits-secs.webp",
  },

  // ---------- الكوكتيلات وسلطات الفواكه ----------
  {
    id: 123,
    name: "سلطة فواكه بالزبادي",
    category: "الكوكتيلات وسلطات الفواكه",
    description: "قطع فواكه موسمية طازجة تقدم فوق قاعدة كريمية من الزبادي.",
    price: 18.0,
    popular: false,
    image: "/images/menu/salade-fruits-yaourt.webp",
  },
  {
    id: 124,
    name: "سلطة فواكه بعصير البرتقال",
    category: "الكوكتيلات وسلطات الفواكه",
    description: "قطع فواكه موسمية طازجة ومغمورة في عصير البرتقال الطبيعي.",
    price: 19.0,
    popular: false,
    image: "/images/menu/salade-fruits-orange.webp",
  },
  {
    id: 125,
    name: "كوكتيل تروبيكال",
    category: "الكوكتيلات وسلطات الفواكه",
    description: "مزيج منعش من المانجو والكيوي والأناناس.",
    price: 21.0,
    popular: false,
    image: "/images/menu/cocktail-tropical.webp",
  },
  {
    id: 126,
    name: "كوكتيل أوريونتال",
    category: "الكوكتيلات وسلطات الفواكه",
    description: "مزيج متناغم وكلاسيكي من الموز والتفاح والبرتقال.",
    price: 20.0,
    popular: false,
    image: "/images/menu/cocktail-oriental.webp",
  },
  {
    id: 127,
    name: "كوكتيل إكزوتيك",
    category: "الكوكتيلات وسلطات الفواكه",
    description: "مزيج استوائي رائع من المانجو والبرتقال والأناناس.",
    price: 21.0,
    popular: false,
    image: "/images/menu/cocktail-exotique.webp",
  },

  // ---------- المشروبات الغازية والمياه ----------
  {
    id: 128,
    name: "مشروب غازي (33 سل)",
    category: "المشروبات الغازية والمياه",
    description: "اختيارك من المشروبات الغازية الباردة والمنعشة، علبة 33 سل.",
    price: 12.0,
    popular: false,
    image: "/images/menu/soda.webp",
  },
  {
    id: 129,
    name: "ماء معدني (33 سل)",
    category: "المشروبات الغازية والمياه",
    description: "قنينة ماء معدني صغيرة (طبيعي أو غازي).",
    price: 5.0,
    popular: false,
    image: "/images/menu/eau-minerale-33.webp",
  },
  {
    id: 130,
    name: "ماء معدني (50 سل)",
    category: "المشروبات الغازية والمياه",
    description: "قنينة ماء معدني متوسطة (طبيعي أو غازي).",
    price: 7.0,
    popular: false,
    image: "/images/menu/eau-minerale-50.webp",
  },
];

export const shopProducts = [
  // BREAKFAST & SAVORY
  {
    id: 1,
    name: "حساء الشعير (حسوة)",
    category: "فطور ومملحات",
    description: "حساء الشعير والحليب المغربي التقليدي الدافئ والمريح.",
    price: 7.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/hesewa.webp",
  },
  {
    id: 2,
    name: "أومليت بالجبن",
    category: "فطور ومملحات",
    description:
      "أومليت هشة محشوة بالجبن الذائب، تُقدم مع الزيتون وزيت الزيتون.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 3,
    name: "فطور كونتيننتال",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، أومليت بالجبن، زيت زيتون، زيتون، جبن، خبز، زبادي، وماء.",
    price: 35.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 4,
    name: "أومليت باللحم البارد (كاشير)",
    category: "فطور ومملحات",
    description: "أومليت محشوة باللحم البارد، تُقدم مع الزيتون وزيت الزيتون.",
    price: 17.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 5,
    name: "فطور إكسبريس",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، معجنات، زبادي، وماء معدني.",
    price: 26.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 6,
    name: "فطور فاسي",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، أومليت باللحم المجفف (القديد)، زيت زيتون، زيتون، جبن، خبز، زبادي، وماء.",
    price: 37.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 7,
    name: "فطور الذواقة",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، زيت زيتون، أملو، زيتون، عسل، خبز، زبادي، وماء.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 8,
    name: "حريرة",
    category: "فطور ومملحات",
    description: "الحساء المغربي التقليدي الغني بالطماطم، العدس، والحمص.",
    price: 10.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/soup.webp",
  },
  {
    id: 9,
    name: "أومليت بالخليع",
    category: "فطور ومملحات",
    description:
      "أومليت تقليدية مع اللحم المغربي المحفوظ (الخليع)، تُقدم مع الزيتون وزيت الزيتون.",
    price: 24.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 10,
    name: "فطور الأطفال",
    category: "فطور ومملحات",
    description:
      "حليب بالشوكولاتة، عصير برتقال، خبز بالشوكولاتة، كيك بالفانيليا، زبادي، وماء.",
    price: 25.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 11,
    name: "فطور لامادلين",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، اختيارك من الأومليت، زيت زيتون، زيتون، عسل، جبن، أملو، خبز، كريب، شوكولاتة، كيك، زبادي، وماء.",
    price: 55.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 12,
    name: "أومليت عادية",
    category: "فطور ومملحات",
    description: "أومليت بيض بسيطة وهشة تُقدم مع الزيتون وزيت الزيتون.",
    price: 13.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 13,
    name: "فطور سوسي",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، أملو، زيت زيتون، جبن، زيتون، عسل، مربى، وماء.",
    price: 38.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 14,
    name: "أومليت بالطماطم",
    category: "فطور ومملحات",
    description: "أومليت هشة مع طماطم طازجة، تُقدم مع الزيتون وزيت الزيتون.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 15,
    name: "فطور تقليدي",
    category: "فطور ومملحات",
    description:
      "حساء الشعير، مشروب ساخن، عصير برتقال، بغرير، حرشة، عسل، جبن طازج، وماء.",
    price: 28.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.webp",
  },

  // PASTRIES & DESSERTS
  {
    id: 16,
    name: "سيجار فواكه البحر",
    category: "معجنات وحلويات",
    description: "لفائف مقرمشة محشوة بتشكيلة لذيذة من فواكه البحر.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/cigar.webp",
  },
  {
    id: 17,
    name: "بسطيلة فواكه البحر",
    category: "معجنات وحلويات",
    description: "فطيرة مالحة مورقة محشوة بفواكه البحر المتبلة والشعيرية.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pastilla.webp",
  },
  {
    id: 18,
    name: "سندويش",
    category: "معجنات وحلويات",
    description: "سندويش مالح محضر طازجاً.",
    price: 8.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/sandwich.webp",
  },
  {
    id: 19,
    name: "ميني بيتزا",
    category: "معجنات وحلويات",
    description: "بيتزا مالحة بحجم صغير مغطاة بالجبن وصلصة الطماطم.",
    price: 6.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/pizza.webp",
  },
  {
    id: 20,
    name: "هوت دوج بعجينة مورقة",
    category: "معجنات وحلويات",
    description: "نقانق مالحة ملفوفة ومخبوزة في عجينة طرية.",
    price: 9.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/hot-dog.webp",
  },
  {
    id: 21,
    name: "بسطيلة بالدجاج",
    category: "معجنات وحلويات",
    description: "فطيرة حلوة ومالحة محشوة بالدجاج المتبل واللوز المحمص.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pastilla.webp",
  },
  {
    id: 22,
    name: "بريوات بالجبن",
    category: "معجنات وحلويات",
    description: "مثلثات معجنات مغربية مقرمشة محشوة بالجبن المالح.",
    price: 7.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/briouat.webp",
  },
  {
    id: 23,
    name: "تارت اللوز",
    category: "معجنات وحلويات",
    description: "قشرة معجنات حلوة ومقرمشة محشوة بكريمة اللوز الكثيفة.",
    price: 10.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/tart.webp",
  },
  {
    id: 24,
    name: "بان كيك أملو",
    category: "معجنات وحلويات",
    description: "بان كيك هش مغطى بالأملو المغربي التقليدي.",
    price: 17.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 25,
    name: "شوسون بالتفاح",
    category: "معجنات وحلويات",
    description: "عجينة مورقة محشوة بكومبوت التفاح الحلو المتبل.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/apple-turnover.webp",
  },
  {
    id: 26,
    name: "كريب بالكراميل",
    category: "معجنات وحلويات",
    description: "كريب فرنسي رقيق مطوي مع الكراميل الحلو.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 27,
    name: "وافل بالكراميل",
    category: "معجنات وحلويات",
    description: "وافل ذهبي مغطى بصلصة الكراميل الغنية.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 28,
    name: "بسبوسة بالشوكولاتة",
    category: "معجنات وحلويات",
    description: "كيكة سميد حلوة بنكهة الشوكولاتة الغنية.",
    price: 8.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.webp",
  },
  {
    id: 29,
    name: "مادلين بالشوكولاتة",
    category: "معجنات وحلويات",
    description: "كيكة إسفنجية صغيرة على شكل صدفة بنكهة الشوكولاتة.",
    price: 2.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.webp",
  },
  {
    id: 30,
    name: "كريب كلاسيكي",
    category: "معجنات وحلويات",
    description: "كريب فرنسي بسيط ورقيق وطري.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 31,
    name: "شريحة كيك بالكريمة (10)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 10.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 32,
    name: "شريحة كيك بالكريمة (12)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 33,
    name: "شريحة كيك بالكريمة (13)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 13.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 34,
    name: "شريحة كيك بالكريمة (14)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 14.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 35,
    name: "شريحة كيك بالكريمة (15)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 36,
    name: "شريحة كيك بالكريمة (17)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 17.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 37,
    name: "شريحة كيك بالكريمة (18)",
    category: "معجنات وحلويات",
    description: "شريحة لذيذة من الكيك المحشو بالكريمة.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 38,
    name: "دونات",
    category: "معجنات وحلويات",
    description: "دونات كلاسيكية مقلية طرية وحلوة.",
    price: 4.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/donut.webp",
  },
  {
    id: 39,
    name: "تارت الفرانجيبان",
    category: "معجنات وحلويات",
    description: "تارت معجنات حلوة محشوة بكريمة اللوز الغنية.",
    price: 8.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/frangipane-tart.webp",
  },
  {
    id: 40,
    name: "بيثيفييه فواكه",
    category: "معجنات وحلويات",
    description: "فطيرة من العجين المورق محشوة بكومبوت الفواكه الحلو.",
    price: 6.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pithiviers.webp",
  },
  {
    id: 41,
    name: "سلطة فواكه مع عصير برتقال",
    category: "معجنات وحلويات",
    description: "فواكه موسمية طازجة منقوعة في عصير برتقال طازج.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/fruit-salad.webp",
  },
  {
    id: 42,
    name: "سلطة فواكه مع زبادي",
    category: "معجنات وحلويات",
    description: "فواكه موسمية طازجة ممزوجة بزبادي كريمي.",
    price: 18.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/fruit-salad.webp",
  },
  {
    id: 43,
    name: "تارتليت بالفواكه",
    category: "معجنات وحلويات",
    description: "قشرة تارت حلوة صغيرة محشوة بالكاسترد والفواكه الطازجة.",
    price: 7.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/fruit-tartlet.webp",
  },
  {
    id: 44,
    name: "بان كيك بالعسل",
    category: "معجنات وحلويات",
    description: "بان كيك هش مغطى بعسل نقي.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 45,
    name: "باوند كيك كبير",
    category: "معجنات وحلويات",
    description: "كيكة بحجم كبير، غنية بالزبدة وطرية.",
    price: 30.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 46,
    name: "باوند كيك وسط",
    category: "معجنات وحلويات",
    description: "كيكة كلاسيكية طرية وحلوة.",
    price: 20.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 47,
    name: "ميل فوي",
    category: "معجنات وحلويات",
    description:
      "معجنات فرنسية كلاسيكية بطبقات من العجينة المورقة وكريمة الفانيليا.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/millefeuille.webp",
  },
  {
    id: 48,
    name: "ميني كيك",
    category: "معجنات وحلويات",
    description: "كيكة صغيرة شخصية، طرية وحلوة.",
    price: 7.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/minicake.webp",
  },
  {
    id: 49,
    name: "ميني كب كيك",
    category: "معجنات وحلويات",
    description: "كيكة صغيرة هشة بحجم لقمة مع كريمة تزيين حلوة.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cupcake.webp",
  },
  {
    id: 50,
    name: "كريب نوتيلا وموز",
    category: "معجنات وحلويات",
    description: "كريب محشو بالنوتيلا والموز.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 51,
    name: "بان كيك نوتيلا وموز",
    category: "معجنات وحلويات",
    description: "بان كيك يُقدم مع النوتيلا والموز الطازج.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 52,
    name: "وافل نوتيلا وموز",
    category: "معجنات وحلويات",
    description: "وافل مغطى بالنوتيلا وشرائح الموز الطازجة.",
    price: 22.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 53,
    name: "كريب نوتيلا وأوريو",
    category: "معجنات وحلويات",
    description: "كريب محشو بالنوتيلا وبسكويت الأوريو المطحون.",
    price: 25.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 54,
    name: "كريب نوتيلا وفواكه موسمية",
    category: "معجنات وحلويات",
    description: "كريب محشو بالنوتيلا والفواكه الموسمية الطازجة.",
    price: 29.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 55,
    name: "وافل نوتيلا وفواكه موسمية",
    category: "معجنات وحلويات",
    description: "وافل مع النوتيلا والفواكه الموسمية الطازجة.",
    price: 27.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 56,
    name: "كريب نوتيلا",
    category: "معجنات وحلويات",
    description: "كريب رقيق كلاسيكي محشو بالنوتيلا الدافئة.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 57,
    name: "بان كيك نوتيلا",
    category: "معجنات وحلويات",
    description: "طبقات من البان كيك الهش يتخللها النوتيلا.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 58,
    name: "وافل نوتيلا",
    category: "معجنات وحلويات",
    description: "وافل ذهبي مغطى بسخاء بالنوتيلا.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 59,
    name: "بيثيفييه",
    category: "معجنات وحلويات",
    description: "فطيرة دائرية مغلقة مصنوعة من العجين المورق مع حشوة حلوة.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pithiviers.webp",
  },
  {
    id: 60,
    name: "ميني كيك بالتوت",
    category: "معجنات وحلويات",
    description: "كيكة صغيرة بنكهة التوت الحلو.",
    price: 8.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/minicake.webp",
  },
  {
    id: 61,
    name: "شريحة باوند كيك",
    category: "معجنات وحلويات",
    description: "شريحة شخصية من الباوند كيك الطري.",
    price: 15.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 62,
    name: "بسبوسة بالفانيليا",
    category: "معجنات وحلويات",
    description: "كيكة سميد حلوة كلاسيكية مشربة بشراب الفانيليا.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.webp",
  },
  {
    id: 63,
    name: "مادلين بالفانيليا",
    category: "معجنات وحلويات",
    description: "كيكة إسفنجية فرنسية كلاسيكية غنية بالزبدة على شكل صدفة.",
    price: 1.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.webp",
  },
  {
    id: 64,
    name: "كرواسون باللوز",
    category: "معجنات وحلويات",
    description: "كرواسون مورق محشو بكريمة اللوز ومغطى بشرائح اللوز.",
    price: 5.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/croissant.webp",
  },
  {
    id: 65,
    name: "مثلث اللوز",
    category: "معجنات وحلويات",
    description: "معجنات مورقة على شكل مثلث محشوة بعجينة اللوز الحلوة.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/triangle.webp",
  },
  {
    id: 66,
    name: "دانيش بالشوكولاتة",
    category: "معجنات وحلويات",
    description: "معجنات دانيش مورقة متداخلة مع الشوكولاتة الغنية.",
    price: 4.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/danish.webp",
  },
  {
    id: 67,
    name: "معجنات دانيش",
    category: "معجنات وحلويات",
    description: "معجنات دانيش تقليدية مورقة، غنية بالزبدة وحلوة.",
    price: 3.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/danish.webp",
  },
  {
    id: 68,
    name: "حرشة",
    category: "معجنات وحلويات",
    description: "خبز سميد مغربي تقليدي مقلي بالمقلاة.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/harcha.webp",
  },
  {
    id: 69,
    name: "مسمن",
    category: "معجنات وحلويات",
    description: "خبز مسطح مغربي تقليدي مورق ومربع الشكل.",
    price: 4.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/msemmen.webp",
  },
  {
    id: 70,
    name: "حرشة بزيت الزيتون",
    category: "معجنات وحلويات",
    description: "خبز سميد مالح محضر بزيت الزيتون الغني.",
    price: 3.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/oil-harcha.webp",
  },
  {
    id: 71,
    name: "بان سويس",
    category: "معجنات وحلويات",
    description: "معجنات مورقة ملفوفة مع كاسترد الفانيليا ورقائق الشوكولاتة.",
    price: 3.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pain-suisse.webp",
  },
  {
    id: 72,
    name: "بان أو شوكولا / كرواسون",
    category: "معجنات وحلويات",
    description: "معجنات فطور فرنسية كلاسيكية مورقة وغنية بالزبدة.",
    price: 2.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pain-au-chocolat.webp",
  },

  // BAKERY
  {
    id: 73,
    name: "خبز الشعير",
    category: "مخبزة",
    description: "خبز شعير مغربي صحي ومشبع.",
    price: 2.5,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 74,
    name: "بطبوط",
    category: "مخبزة",
    description: "خبز مغربي طري مطبوخ في المقلاة.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 75,
    name: "بريوش بالشوكولاتة",
    category: "مخبزة",
    description: "خبز حلو طري وهش محشو برقائق الشوكولاتة.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 76,
    name: "باجيت كلاسيكي",
    category: "مخبزة",
    description: "باجيت فرنسي تقليدي مقرمش وطري من الداخل.",
    price: 1.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/bread.webp",
  },
  {
    id: 77,
    name: "خبز كلاسيكي",
    category: "مخبزة",
    description: "خبز مغربي تقليدي دائري وطري.",
    price: 1.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 78,
    name: "بريوش كلاسيكي",
    category: "مخبزة",
    description: "خبز حلو تقليدي غني بالزبدة، طري وهش.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 79,
    name: "خبز الذرة",
    category: "مخبزة",
    description: "خبز دقيق الذرة المغربي الريفي واللذيذ.",
    price: 2.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },
  {
    id: 80,
    name: "خبز الزنجبيل (بان ديبس)",
    category: "مخبزة",
    description: "خبز التوابل الفرنسي التقليدي بالعسل واليانسون.",
    price: 24.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 81,
    name: "باجيت متعدد الحبوب",
    category: "مخبزة",
    description: "باجيت مقرمش مخبوز بمزيج من البذور والحبوب الصحية.",
    price: 4.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 82,
    name: "باجيت بالزيتون",
    category: "مخبزة",
    description: "باجيت مالح مخبوز مع قطع من الزيتون الأسود والأخضر.",
    price: 5.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 83,
    name: "خبز بالزيتون",
    category: "مخبزة",
    description: "خبز دائري تقليدي طري مخبوز مع زيتون مالح.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 84,
    name: "خبز قمح بدون ملح",
    category: "مخبزة",
    description: "خبز قمح كامل صحي محضر بدون ملح مضاف.",
    price: 3.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/bread.webp",
  },
  {
    id: 85,
    name: "باجيت سميد",
    category: "مخبزة",
    description: "باجيت مصنوع من دقيق السميد لقرمشة ريفية.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 86,
    name: "خبز سميد",
    category: "مخبزة",
    description: "خبز دائري مغربي تقليدي مصنوع من السميد.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 87,
    name: "باجيت بالسمسم",
    category: "مخبزة",
    description: "باجيت فرنسي مقرمش طازج مزين ببذور السمسم.",
    price: 2.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 88,
    name: "لفافة بالسمسم",
    category: "مخبزة",
    description: "لفافة خبز طرية مغطاة بسخاء ببذور السمسم.",
    price: 3.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },
  {
    id: 89,
    name: "باجيت فيينوا",
    category: "مخبزة",
    description: "خبز على طراز فيينا، طري وحلو قليلاً وغني.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 90,
    name: "باجيت قمح كامل",
    category: "مخبزة",
    description: "باجيت فرنسي صحي ومشبع من القمح الكامل.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 91,
    name: "خبز قمح كامل",
    category: "مخبزة",
    description: "خبز دائري مغربي تقليدي مغذي من القمح الكامل.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 92,
    name: "لفافة قمح كامل",
    category: "مخبزة",
    description: "لفافة خبز صحية وطرية من القمح الكامل.",
    price: 2.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },

  // HOT DRINKS
  {
    id: 93,
    name: "شاي أسود (ليبتون)",
    category: "مشروبات ساخنة",
    description: "شاي ليبتون الأسود الكلاسيكي.",
    price: 12.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/lipton.webp",
  },
  {
    id: 94,
    name: "شوكولاتة ساخنة",
    category: "مشروبات ساخنة",
    description: "حليب دافئ ومريح مع الشوكولاتة الغنية.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/hot-chocolate.webp",
  },
  {
    id: 95,
    name: "حليب ساخن",
    category: "مشروبات ساخنة",
    description: "حليب مبخر بسيط ومريح.",
    price: 12.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/hot-milk.webp",
  },
  {
    id: 96,
    name: "شاي لويزة",
    category: "مشروبات ساخنة",
    description: "شاي أعشاب محضر من أوراق اللويزة الطبيعية.",
    price: 12.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/lemon-verbena-tea.webp",
  },
  {
    id: 97,
    name: "شاي بالحليب (ليبتون)",
    category: "مشروبات ساخنة",
    description: "شاي ليبتون الأسود الكلاسيكي محضر مع الحليب.",
    price: 12.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/milk-tea.webp",
  },
  {
    id: 98,
    name: "حليب باللويزة",
    category: "مشروبات ساخنة",
    description: "حليب دافئ منقوع باللويزة المهدئة.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-tea.webp",
  },
  {
    id: 99,
    name: "حليب بالسيرو (الشراب)",
    category: "مشروبات ساخنة",
    description: "حليب بارد أو دافئ بنكهة الشراب الحلو.",
    price: 11.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/milk-syrup.webp",
  },
  {
    id: 100,
    name: "شاي مغربي بالنعناع",
    category: "مشروبات ساخنة",
    description: "شاي أخضر تقليدي محضر مع النعناع الطازج.",
    price: 11.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/moroccan-tea.webp",
  },

  // COLD DRINKS
  {
    id: 101,
    name: "أفوغاتو",
    category: "مشروبات باردة",
    description: "كرة من آيس كريم الفانيليا غارقة في إسبريسو ساخن.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/affogato.webp",
  },
  {
    id: 102,
    name: "ميلك شيك موز",
    category: "مشروبات باردة",
    description: "مخفوق الموز الحلو والكريمي.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 103,
    name: "سموثي موز",
    category: "مشروبات باردة",
    description: "سموثي موز ممزوج وكريمي.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 104,
    name: "موهيتو أزرق",
    category: "مشروبات باردة",
    description: "مشروب حمضيات ونعناع مع شراب الكوراكاو الأزرق.",
    price: 22.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/mojito.webp",
  },
  {
    id: 105,
    name: "مشروب غازي (35 سل)",
    category: "مشروبات باردة",
    description: "تشكيلة من المشروبات الغازية المنعشة.",
    price: 12.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/soda.webp",
  },
  {
    id: 106,
    name: "ميلك شيك شوكولاتة",
    category: "مشروبات باردة",
    description: "مخفوق الشوكولاتة الغني والكريمي.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 107,
    name: "كوكتيل استوائي",
    category: "مشروبات باردة",
    description: "مزيج المانجو، البرتقال، والأناناس.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/cocktail.webp",
  },
  {
    id: 108,
    name: "سموثي استوائي",
    category: "مشروبات باردة",
    description: "مزيج منعش من الفواكه الاستوائية.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 109,
    name: "مكياتو كراميل مثلج",
    category: "مشروبات باردة",
    description: "حليب وإسبريسو مثلج، بنكهة الفانيليا والكراميل.",
    price: 21.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/iced-caramel.webp",
  },
  {
    id: 110,
    name: "قهوة مثلجة",
    category: "مشروبات باردة",
    description: "قهوة مبردة بالثلج مع اختيار النكهة.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/iced-coffee.webp",
  },
  {
    id: 111,
    name: "فرابتشينو مثلج",
    category: "مشروبات باردة",
    description:
      "مشروب قهوة مثلج ممزوج مع اختيار الفانيليا، الشوكولاتة، أو الكراميل.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-frappuccino.webp",
  },
  {
    id: 112,
    name: "لاتيه مثلج",
    category: "مشروبات باردة",
    description: "إسبريسو وحليب مبرد على الثلج.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/iced-latte.webp",
  },
  {
    id: 113,
    name: "موكا مثلج",
    category: "مشروبات باردة",
    description: "إسبريسو مثلج مع الشوكولاتة والحليب.",
    price: 19.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-mocha.webp",
  },
  {
    id: 114,
    name: "سموثي مانجو",
    category: "مشروبات باردة",
    description: "سموثي مانجو استوائي ممزوج.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 115,
    name: "مياه معدنية (33 سل)",
    category: "مشروبات باردة",
    description: "قنينة صغيرة من المياه المعدنية بدون غاز.",
    price: 5.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/water.webp",
  },
  {
    id: 116,
    name: "مياه معدنية (50 سل)",
    category: "مشروبات باردة",
    description: "قنينة متوسطة من المياه المعدنية بدون غاز.",
    price: 7.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/water.webp",
  },
  {
    id: 117,
    name: "ميلك شيك أوريو",
    category: "مشروبات باردة",
    description: "مخفوق فانيليا كريمي ممزوج ببسكويت الأوريو.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 118,
    name: "كوكتيل شرقي",
    category: "مشروبات باردة",
    description: "مزيج الموز، التفاح، والبرتقال.",
    price: 20.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cocktail.webp",
  },
  {
    id: 119,
    name: "موهيتو أحمر",
    category: "مشروبات باردة",
    description: "مشروب توت أحمر فاكهي مع نعناع وليمون.",
    price: 22.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/mojito.webp",
  },
  {
    id: 120,
    name: "ميلك شيك فراولة",
    category: "مشروبات باردة",
    description: "مخفوق الفراولة الحلو والكريمي.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 121,
    name: "سموثي فراولة",
    category: "مشروبات باردة",
    description: "فراولة طازجة ممزوجة مع الزبادي.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 122,
    name: "كوكتيل استوائي",
    category: "مشروبات باردة",
    description: "مزيج المانجو، الكيوي، والأناناس.",
    price: 21.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/cocktail.webp",
  },
  {
    id: 123,
    name: "ميلك شيك فانيليا",
    category: "مشروبات باردة",
    description: "مخفوق الفانيليا الكلاسيكي الكريمي.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 124,
    name: "فيرجن موهيتو",
    category: "مشروبات باردة",
    description: "مشروب الليمون والنعناع المنعش.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/mojito.webp",
  },

  // COFFEES
  {
    id: 125,
    name: "أمريكانو",
    category: "قهوة",
    description: "إسبريسو مخفف بالماء الساخن.",
    price: 14.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/americano.webp",
  },
  {
    id: 126,
    name: "كابتشينو",
    category: "قهوة",
    description: "إسبريسو مغطى بمقادير متساوية من الحليب المبخر والرغوة.",
    price: 15.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/cappuccino.webp",
  },
  {
    id: 127,
    name: "قهوة مع حليب جانبي",
    category: "قهوة",
    description: "إسبريسو يُقدم مع حليب جانبي منفصل.",
    price: 15.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/coffee-milk.webp",
  },
  {
    id: 128,
    name: "كورتادو",
    category: "قهوة",
    description: "مقادير متساوية من الإسبريسو والحليب المبخر.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/cortado.webp",
  },
  {
    id: 129,
    name: "قهوة بالكريمة",
    category: "قهوة",
    description: "إسبريسو ممزوج بالكريمة المبخرة.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cream-coffee.webp",
  },
  {
    id: 130,
    name: "إسبريسو مزدوج",
    category: "قهوة",
    description: "جرعتان غنيتان من الإسبريسو المركز.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/double-espresso.webp",
  },
  {
    id: 131,
    name: "إسبريسو",
    category: "قهوة",
    description: "جرعة غنية ومركزة من القهوة.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/espresso.webp",
  },
  {
    id: 132,
    name: "فلات وايت",
    category: "قهوة",
    description: "إسبريسو مع حليب برغوة دقيقة.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/flat-white.webp",
  },
  {
    id: 133,
    name: "إسبريسو إيلي",
    category: "قهوة",
    description: "جرعة إسبريسو إيطالية فاخرة من إيلي.",
    price: 16.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/illy-espresso.webp",
  },
  {
    id: 134,
    name: "لاتيه ماكياتو",
    category: "قهوة",
    description: "حليب مبخر مضاف إليه جرعة من الإسبريسو.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/latte-macchiato.webp",
  },
  {
    id: 135,
    name: "موكا",
    category: "قهوة",
    description: "إسبريسو ممزوج مع الشوكولاتة والحليب المبخر.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/mocha.webp",
  },
  {
    id: 136,
    name: "قهوة نسبريسو",
    category: "قهوة",
    description: "قهوة نسبريسو كلاسيكية.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/nespresso.webp",
  },
  {
    id: 137,
    name: "شوكولاتة فيينوا",
    category: "قهوة",
    description: "شوكولاتة ساخنة مغطاة بكريمة مخفوقة.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/viennese-chocolate.webp",
  },

  // JUICES
  {
    id: 138,
    name: "عصير تفاح",
    category: "عصائر",
    description: "عصير تفاح معصور طازجاً.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/apple-juice.webp",
  },
  {
    id: 139,
    name: "عصير أفوكادو",
    category: "عصائر",
    description: "عصير أفوكادو ممزوج، غني وكريمي.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/avocado-juice.webp",
  },
  {
    id: 140,
    name: "عصير أفوكادو بالفواكه الجافة",
    category: "عصائر",
    description: "عصير أفوكادو كريمي ممزوج بمزيج من الفواكه الجافة.",
    price: 23.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/avocado-juice-with-dried-fruits.webp",
  },
  {
    id: 141,
    name: "عصير موز",
    category: "عصائر",
    description: "عصير موز ممزوج طازجاً.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/banana-juice.webp",
  },
  {
    id: 142,
    name: "عصير مانجو",
    category: "عصائر",
    description: "عصير مانجو استوائي طازج.",
    price: 20.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/mango-juice.webp",
  },
  {
    id: 143,
    name: "عصير فواكه مشكلة بالحليب",
    category: "عصائر",
    description: "مزيج من الفواكه المشكلة مع الحليب.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/mixed-fruit-juice-with-milk.webp",
  },
  {
    id: 144,
    name: "عصير فواكه مشكلة بالبرتقال",
    category: "عصائر",
    description: "مزيج من الفواكه المشكلة مع عصير البرتقال.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/mixed-fruit-juice-with-orange.webp",
  },
  {
    id: 145,
    name: "عصير برتقال",
    category: "عصائر",
    description: "عصير برتقال معصور طازجاً.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/orange-juice.webp",
  },
  {
    id: 146,
    name: "عصير أناناس",
    category: "عصائر",
    description: "عصير أناناس حلو وطازج.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pineapple-juice.webp",
  },
  {
    id: 147,
    name: "عصير فراولة",
    category: "عصائر",
    description: "عصير فراولة ممزوج طازجاً.",
    price: 18.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/strawberry-juice.webp",
  },

  // EXTRAS
  {
    id: 148,
    name: "أملو باللوز",
    category: "إضافات",
    description: "أملو فاخر محضر بلوز محمص إضافي. يُقدم مع الخبز.",
    price: 12.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/almond.webp",
  },
  {
    id: 149,
    name: "أملو بزيت الأركان",
    category: "إضافات",
    description: "تغميسة تقليدية من اللوز والعسل وزيت الأركان. تُقدم مع الخبز.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/argan.webp",
  },
  {
    id: 150,
    name: "زيتون أسود وأخضر",
    category: "إضافات",
    description: "زيتون مشكل متبل. يُقدم مع الخبز.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/olive.webp",
  },
  {
    id: 151,
    name: "جبن للدهن",
    category: "إضافات",
    description: "حصة من الجبن القابل للدهن. تُقدم مع الخبز.",
    price: 3.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cheese.webp",
  },
  {
    id: 152,
    name: "جبن طازج (جُبن)",
    category: "إضافات",
    description: "حصة من الجبن المغربي الطازج التقليدي. تُقدم مع الخبز.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/fresh-cheese.webp",
  },
  {
    id: 153,
    name: "عسل",
    category: "إضافات",
    description: "حصة من العسل النقي. تُقدم مع الخبز.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/honey.webp",
  },
  {
    id: 154,
    name: "مربى",
    category: "إضافات",
    description: "حصة من مربى الفواكه. تُقدم مع الخبز.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/jam.webp",
  },
  {
    id: 155,
    name: "نوتيلا",
    category: "إضافات",
    description: "حصة من دهن البندق والكاكاو الغني. تُقدم مع الخبز.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/nutella.webp",
  },
  {
    id: 156,
    name: "زيت زيتون",
    category: "إضافات",
    description:
      "حصة من زيت الزيتون البكر الممتاز عالي الجودة. تُقدم مع الخبز.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/olive-oil.webp",
  },
];
