export const siteConfig = {
  name: "LaMadeleine Agadir",
  tagline: "Boulangerie Artisanale & Salon de Café",
  description:
    "Pâtisseries faites à la main, pain artisanal et café exceptionnel — une expérience authentique de boulangerie française et marocaine depuis 2019.",
  phone: "05.28.26.43.44",
  email: "contact@lamadeleine.ma",
  address: "Av. Al Oulfa, Tilila, Agadir 80000",
  social: {
    instagram: "https://instagram.com/lamadeleine.agadir",
    facebook: "https://facebook.com/lamadeleine.agadir",
  },
  hours: [{ day: "Lundi — Dimanche", time: "6h00 — 22h00" }],
};

export const heroSlides = [
  {
    id: 1,
    title: "PÂTISSERIE AU CHOCOLAT",
    subtitle: "Délicieux",
    image: "/images/slider/slide-1/slide-1-image.png",
    bgText: "/images/slider/slide-1/slide-1-bg.png",
    bgIcon: "/images/slider/slide-1/slide-1-bg-icon.png",
    products: [
      {
        title: "CHOCOLAT",
        description:
          "Riche pâtisserie au chocolat noir avec du chocolat belge et une pâte feuilletée.",
        icon: "/images/slider/slide-1/slide-1-product-1.png",
      },
      {
        title: "CLASSIQUES SUCRÉS",
        description:
          "Croissants frais, éclairs et tartes cuits tous les jours avec des ingrédients de première qualité.",
        icon: "/images/slider/slide-1/slide-1-product-2.png",
      },
    ],
  },
  {
    id: 2,
    title: "DE BEAUX GROS PAINS.",
    subtitle: "Délicieux",
    image: "/images/slider/slide-2/slide-2-image.png",
    bgText: "/images/slider/slide-2/slide-2-bg.png",
    bgIcon: "/images/slider/slide-2/slide-2-bg-icon.png",
    products: [
      {
        title: "CUIRE LE MEILLEUR",
        description:
          "Cuit frais tous les jours avec une croûte dorée et croustillante.",
        icon: "/images/slider/slide-2/slide-2-product-1.png",
      },
      {
        title: "INCROYABLEMENT BON",
        description:
          "Des pains riches et beurrés avec une texture fondante en bouche.",
        icon: "/images/slider/slide-2/slide-2-product-2.png",
      },
    ],
  },
  {
    id: 3,
    title: "SANDWICHS",
    subtitle: "Délicieux",
    image: "/images/slider/slide-3/slide-3-image.png",
    bgText: "/images/slider/slide-3/slide-3-bg.png",
    bgIcon: "/images/slider/slide-3/slide-3-bg-icon.png",
    products: [
      {
        title: "PETIT-DÉJEUNER",
        description: "Sandwichs salés pour le petit-déjeuner.",
        icon: "/images/slider/slide-3/slide-3-product-1.png",
      },
      {
        title: "COLLATION SAINE",
        description: "Parfaits aux fruits frais et yaourt.",
        icon: "/images/slider/slide-3/slide-3-product-2.png",
      },
    ],
  },
];

export const categories = [
  {
    id: 1,
    name: "Petit-déjeuner",
    description: "Commencez votre journée à la marocaine",
    icon: "sunrise",
    image: "/images/cat-breakfast.jpg",
  },
  {
    id: 2,
    name: "Pain Artisanal",
    description: "Pains traditionnels français et marocains",
    icon: "wheat",
    image: "/images/cat-bread.jpg",
  },
  {
    id: 3,
    name: "Desserts",
    description: "Créations douces et gourmandes",
    icon: "cherry",
    image: "/images/cat-desserts.jpg",
  },
  {
    id: 4,
    name: "Café",
    description: "Torréfié et infusé avec expertise",
    icon: "coffee",
    image: "/images/cat-coffee.jpg",
  },
  {
    id: 5,
    name: "Pâtisseries",
    description: "Délicate pâtisserie française et marocaine",
    icon: "cake",
    image: "/images/cat-pastries.jpg",
  },
  {
    id: 6,
    name: "Sandwichs",
    description: "Frais, faits main et délicieux",
    icon: "sandwich",
    image: "/images/cat-sandwiches.jpg",
  },
];

type TodaysSpecial = {
  id: number;
  name: string;
  category: string;
  description: string;
  price: number;
  image: string;
};

export const todaysSpecials: TodaysSpecial[] = [
  {
    id: 1,
    name: "Pain au Chocolat",
    category: "Pâtisserie",
    description:
      "Couches beurrées et feuilletées enroulées autour de deux barres de chocolat noir de première qualité — la pâtisserie classique du petit-déjeuner français.",
    price: 2.5,
    image: "/images/today-specials/today-3.jpg",
  },
  {
    id: 2,
    name: "Croissant au Beurre",
    category: "Petit-déjeuner",
    description:
      "Croissant doré et incroyablement léger, préparé avec 84 % de beurre normand. 72 heures de fermentation pour un feuilletage parfait.",
    price: 2.5,
    image: "/images/today-specials/today-1.jpg",
  },
  {
    id: 3,
    name: "Croissant Sandwich",
    category: "Petit-déjeuner",
    description:
      "Une pâtisserie de petit-déjeuner français classique remplie d'une crème riche et beurrée et finie avec un léger saupoudrage de sucre glace.",
    price: 5,
    image: "/images/today-specials/today-2.jpg",
  },
  {
    id: 4,
    name: "Tarte aux Fruits",
    category: "Dessert",
    description:
      "Fruits de saison disposés sur une crème pâtissière à la vanille, nichés dans un fond de tarte croustillant et caramélisé.",
    price: 7,
    image: "/images/today-specials/today-4.jpg",
  },
  {
    id: 5,
    name: "Mille-Feuille aux Amandes",
    category: "Dessert",
    description:
      "Trois couches de pâte feuilletée caramélisée alternant avec une crème d'amande légère, garnies d'amandes effilées grillées et d'un saupoudrage de sucre glace.",
    price: 10,
    image: "/images/today-specials/today-5.jpg",
  },
  {
    id: 6,
    name: "Cortado Signature MadLine",
    category: "Café",
    description:
      "À parts égales d'espresso intensément riche et de lait cuit à la vapeur parfaitement texturé, saupoudré d'un soupçon d'épices chaudes.",
    price: 12,
    image: "/images/today-specials/today-6.jpg",
  },
];

export const coffeeMenu = [
  {
    id: 1,
    name: "Moka",
    description:
      "Espresso combiné avec du chocolat et du lait cuit à la vapeur.",
    price: 18.0,
    icon: "Cookie",
  },
  {
    id: 2,
    name: "Cappuccino",
    description:
      "Espresso surmonté de parts égales de lait cuit à la vapeur et de mousse.",
    price: 15.0,
    icon: "Milk",
  },
  {
    id: 3,
    name: "Café au Lait à Part",
    description: "Espresso servi avec un côté séparé de lait.",
    price: 15.0,
    icon: "Coffee",
  },
  {
    id: 4,
    name: "Cortado",
    description: "À parts égales d'espresso et de lait cuit à la vapeur.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 5,
    name: "Café Crème",
    description: "Espresso mélangé avec de la crème cuite à la vapeur.",
    price: 12.0,
    icon: "Cookie",
  },
  {
    id: 6,
    name: "Double Espresso",
    description: "Deux riches shots d'espresso intense.",
    price: 18.0,
    icon: "Droplets",
  },
  {
    id: 7,
    name: "Espresso",
    description: "Shot de café riche et intense.",
    price: 12.0,
    icon: "Coffee",
  },
  {
    id: 8,
    name: "Flat White",
    description: "Espresso avec du lait micro-moussé.",
    price: 16.0,
    icon: "Milk",
  },
  {
    id: 9,
    name: "Espresso Illy",
    description: "Shot d'espresso italien premium Illy.",
    price: 16.0,
    icon: "Sparkles",
  },
  {
    id: 10,
    name: "Latte Macchiato",
    description: "Lait cuit à la vapeur marqué par un shot d'espresso.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 11,
    name: "Americano",
    description: "Espresso dilué avec de l'eau chaude.",
    price: 14.0,
    icon: "Coffee",
  },
  {
    id: 12,
    name: "Café Nespresso",
    description: "Café infusé Nespresso classique.",
    price: 15.0,
    icon: "Coffee",
  },
];

export const menuCategories = [
  "Petit-déjeuner et Salé",
  "Pâtisseries et Desserts",
  "Boulangerie",
  "Boissons Chaudes",
  "Boissons Froides",
  "Cafés",
  "Jus",
  "Suppléments",
];

export const menuItems = [
  // BREAKFAST & SAVORY
  {
    id: 1,
    name: "Soupe d'Orge (Hssoua)",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe traditionnelle marocaine à l'orge et au lait, chaude et réconfortante.",
    price: 7.0,
    popular: false,
    image: "/images/menu/Soup.png",
  },
  {
    id: 2,
    name: "Omelette au Fromage",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette moelleuse garnie de fromage fondu, servie avec des olives et de l'huile d'olive.",
    price: 16.0,
    popular: true,
    image: "/images/menu/Omelet.png",
  },
  {
    id: 3,
    name: "Petit-déjeuner Continental",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, omelette au fromage, huile d'olive, olives, fromage, pain, yaourt et eau.",
    price: 35.0,
    popular: false,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 4,
    name: "Omelette à la Charcuterie",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette garnie de charcuterie, servie avec des olives et de l'huile d'olive.",
    price: 17.0,
    popular: false,
    image: "/images/menu/Omelet.png",
  },
  {
    id: 5,
    name: "Petit-déjeuner Express",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, viennoiseries, yaourt et eau minérale.",
    price: 26.0,
    popular: true,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 6,
    name: "Petit-déjeuner Fassi",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, omelette à la viande séchée, huile d'olive, olives, fromage, pain, yaourt et eau.",
    price: 37.0,
    popular: true,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 7,
    name: "Petit-déjeuner Gourmand",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, huile d'olive, Amlou, olives, miel, pain, yaourt et eau.",
    price: 26.0,
    popular: false,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 8,
    name: "Soupe Harira",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe marocaine traditionnelle consistante aux tomates, lentilles et pois chiches.",
    price: 10.0,
    popular: false,
    image: "/images/menu/Soup.png",
  },
  {
    id: 9,
    name: "Omelette au Khlii",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette traditionnelle avec de la viande confite marocaine, servie avec des olives et de l'huile d'olive.",
    price: 24.0,
    popular: true,
    image: "/images/menu/Omelet.png",
  },
  {
    id: 10,
    name: "Petit-déjeuner Enfant",
    category: "Petit-déjeuner et Salé",
    description:
      "Lait au chocolat, jus d'orange, pain au chocolat, gâteau à la vanille, yaourt et eau.",
    price: 25.0,
    popular: false,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 11,
    name: "Petit-déjeuner La Madeleine",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, choix d'omelette, huile d'olive, olives, miel, fromage, Amlou, pain, crêpe, chocolat, gâteau, yaourt et eau.",
    price: 55.0,
    popular: true,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 12,
    name: "Omelette Nature",
    category: "Petit-déjeuner et Salé",
    description:
      "Simple omelette moelleuse servie avec des olives et de l'huile d'olive.",
    price: 13.0,
    popular: true,
    image: "/images/menu/Omelet.png",
  },
  {
    id: 13,
    name: "Petit-déjeuner Soussi",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, Amlou, huile d'olive, fromage, olives, miel, confiture et eau.",
    price: 38.0,
    popular: true,
    image: "/images/menu/breakfast.png",
  },
  {
    id: 14,
    name: "Omelette aux Tomates",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette moelleuse aux tomates fraîches, servie avec des olives et de l'huile d'olive.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Omelet.png",
  },
  {
    id: 15,
    name: "Petit-déjeuner Traditionnel",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, crêpes marocaines (Baghrir), Harcha, miel, fromage frais et eau.",
    price: 28.0,
    popular: true,
    image: "/images/menu/breakfast.png",
  },

  // PASTRIES & DESSERTS
  {
    id: 16,
    name: "Cigare aux Fruits de Mer",
    category: "Pâtisseries et Desserts",
    description:
      "Pâte croustillante roulée et remplie d'un mélange salé de fruits de mer.",
    price: 12.0,
    popular: false,
    image: "/images/menu/Cigar.png",
  },
  {
    id: 17,
    name: "Pastilla aux Fruits de Mer",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte salée feuilletée garnie de fruits de mer assaisonnés et de vermicelles.",
    price: 12.0,
    popular: false,
    image: "/images/menu/pastilla.png",
  },
  {
    id: 18,
    name: "Sandwich",
    category: "Pâtisseries et Desserts",
    description: "Sandwich salé fraîchement préparé.",
    price: 8.0,
    popular: false,
    image: "/images/menu/sandwich.png",
  },
  {
    id: 19,
    name: "Mini Pizza",
    category: "Pâtisseries et Desserts",
    description:
      "Pizza salée de format individuel garnie de fromage et de sauce tomate.",
    price: 6.0,
    popular: false,
    image: "/images/menu/pizza.png",
  },
  {
    id: 20,
    name: "Friand à la Saucisse",
    category: "Pâtisseries et Desserts",
    description: "Saucisse salée enveloppée et cuite dans une pâte moelleuse.",
    price: 9.0,
    popular: false,
    image: "/images/menu/hot-dog.png",
  },
  {
    id: 21,
    name: "Pastilla au Poulet",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte sucrée-salée garnie de poulet épicé et d'amandes grillées.",
    price: 10.0,
    popular: false,
    image: "/images/menu/pastilla.png",
  },
  {
    id: 22,
    name: "Briouate au Fromage",
    category: "Pâtisseries et Desserts",
    description:
      "Triangles de pâte marocaine croustillante farcis de fromage salé.",
    price: 7.0,
    popular: false,
    image: "/images/menu/Briouat.png",
  },
  {
    id: 23,
    name: "Tarte aux Amandes",
    category: "Pâtisseries et Desserts",
    description:
      "Fond de tarte sucré et croustillant garni d'une crème d'amande dense.",
    price: 10.0,
    popular: false,
    image: "/images/menu/Tart.png",
  },
  {
    id: 24,
    name: "Pancakes à l'Amlou",
    category: "Pâtisseries et Desserts",
    description: "Pancakes moelleux garnis d'Amlou traditionnel marocain.",
    price: 17.0,
    popular: false,
    image: "/images/menu/Pancakes.png",
  },
  {
    id: 25,
    name: "Chausson aux Pommes",
    category: "Pâtisseries et Desserts",
    description:
      "Pâte feuilletée remplie d'une compote de pommes douce et épicée.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Apple-Turnover.png",
  },
  {
    id: 26,
    name: "Crêpe au Caramel",
    category: "Pâtisseries et Desserts",
    description: "Fine crêpe française pliée avec du caramel sucré.",
    price: 16.0,
    popular: false,
    image: "/images/menu/crepe.png",
  },
  {
    id: 27,
    name: "Gaufre au Caramel",
    category: "Pâtisseries et Desserts",
    description: "Gaufre dorée nappée d'une riche sauce au caramel.",
    price: 16.0,
    popular: false,
    image: "/images/menu/waffle.png",
  },
  {
    id: 28,
    name: "Basboussa au Chocolat",
    category: "Pâtisseries et Desserts",
    description: "Gâteau de semoule sucré aromatisé au chocolat riche.",
    price: 8.0,
    popular: false,
    image: "/images/menu/basbousa.png",
  },
  {
    id: 29,
    name: "Madeleine au Chocolat",
    category: "Pâtisseries et Desserts",
    description:
      "Petit gâteau éponge en forme de coquille, aromatisé au chocolat.",
    price: 2.5,
    popular: false,
    image: "/images/menu/madeleine.png",
  },
  {
    id: 30,
    name: "Crêpe Classique",
    category: "Pâtisseries et Desserts",
    description: "Crêpe française simple, fine et moelleuse.",
    price: 4.0,
    popular: false,
    image: "/images/menu/crepe.png",
  },
  {
    id: 31,
    name: "Part de Gâteau à la Crème (10)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 10.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 32,
    name: "Part de Gâteau à la Crème (12)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 12.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 33,
    name: "Part de Gâteau à la Crème (13)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 13.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 34,
    name: "Part de Gâteau à la Crème (14)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 14.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 35,
    name: "Part de Gâteau à la Crème (15)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 15.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 36,
    name: "Part de Gâteau à la Crème (17)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 17.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 37,
    name: "Part de Gâteau à la Crème (18)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 18.0,
    popular: false,
    image: "/images/menu/strawberry-cake.png",
  },
  {
    id: 38,
    name: "Beignet",
    category: "Pâtisseries et Desserts",
    description: "Anneau de pâte frite moelleux, sucré et classique.",
    price: 4.0,
    popular: false,
    image: "/images/menu/donut.png",
  },
  {
    id: 39,
    name: "Tarte Frangipane",
    category: "Pâtisseries et Desserts",
    description: "Tartelette en pâte sucrée garnie de riche crème d'amande.",
    price: 8.0,
    popular: false,
    image: "/images/menu/tart.png",
  },
  {
    id: 40,
    name: "Pithiviers aux Fruits",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte en pâte feuilletée garnie de compote de fruits sucrée.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Pithiviers.png",
  },
  {
    id: 41,
    name: "Salade de Fruits au Jus d'Orange",
    category: "Pâtisseries et Desserts",
    description: "Fruits frais de saison macérés dans du jus d'orange frais.",
    price: 19.0,
    popular: false,
    image: "/images/menu/fruit-salad.png",
  },
  {
    id: 42,
    name: "Salade de Fruits au Yaourt",
    category: "Pâtisseries et Desserts",
    description: "Fruits frais de saison mélangés avec du yaourt crémeux.",
    price: 18.0,
    popular: false,
    image: "/images/menu/fruit-salad.png",
  },
  {
    id: 43,
    name: "Tartelette aux Fruits",
    category: "Pâtisseries et Desserts",
    description:
      "Petite croûte de tarte sucrée garnie de crème anglaise et de fruits frais.",
    price: 7.0,
    popular: false,
    image: "/images/menu/tartlet.png",
  },
  {
    id: 44,
    name: "Pancakes au Miel",
    category: "Pâtisseries et Desserts",
    description: "Pancakes moelleux arrosés de pur miel.",
    price: 16.0,
    popular: false,
    image: "/images/menu/pancakes.png",
  },
  {
    id: 45,
    name: "Grand Quatre-quarts",
    category: "Pâtisseries et Desserts",
    description: "Quatre-quarts généreux, beurré et moelleux.",
    price: 30.0,
    popular: false,
    image: "/images/menu/pound-cake.png",
  },
  {
    id: 46,
    name: "Quatre-quarts Moyen",
    category: "Pâtisseries et Desserts",
    description: "Quatre-quarts classique, moelleux et sucré.",
    price: 20.0,
    popular: false,
    image: "/images/menu/pound-cake.png",
  },
  {
    id: 47,
    name: "Mille-Feuille",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie française classique avec des couches de pâte feuilletée et de crème vanille.",
    price: 8.0,
    popular: false,
    image: "/images/menu/millefeuille.png",
  },
  {
    id: 48,
    name: "Mini Gâteau",
    category: "Pâtisseries et Desserts",
    description: "Petit gâteau personnel, moelleux et sucré.",
    price: 7.0,
    popular: false,
    image: "/images/menu/minicake.png",
  },
  {
    id: 49,
    name: "Mini Cupcake",
    category: "Pâtisseries et Desserts",
    description: "Gâteau moelleux en format bouchée avec glaçage sucré.",
    price: 4.0,
    popular: false,
    image: "/images/menu/cupcake.png",
  },
  {
    id: 50,
    name: "Crêpe Nutella & Banane",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fourrée au Nutella et aux bananes tranchées.",
    price: 23.0,
    popular: true,
    image: "/images/menu/crepe.png",
  },
  {
    id: 51,
    name: "Pancakes Nutella & Banane",
    category: "Pâtisseries et Desserts",
    description: "Pancakes servis avec du Nutella et des bananes fraîches.",
    price: 26.0,
    popular: true,
    image: "/images/menu/pancakes.png",
  },
  {
    id: 52,
    name: "Gaufre Nutella & Banane",
    category: "Pâtisseries et Desserts",
    description: "Gaufre garnie de Nutella et de tranches de banane fraîche.",
    price: 22.0,
    popular: true,
    image: "/images/menu/waffle.png",
  },
  {
    id: 53,
    name: "Crêpe Nutella & Oreo",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fourrée au Nutella et aux biscuits Oreo concassés.",
    price: 25.0,
    popular: true,
    image: "/images/menu/crepe.png",
  },
  {
    id: 54,
    name: "Crêpe Nutella & Fruits de Saison",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fourrée au Nutella et aux fruits de saison frais.",
    price: 29.0,
    popular: false,
    image: "/images/menu/crepe.png",
  },
  {
    id: 55,
    name: "Gaufre Nutella & Fruits de Saison",
    category: "Pâtisseries et Desserts",
    description: "Gaufre au Nutella et aux fruits de saison frais.",
    price: 27.0,
    popular: false,
    image: "/images/menu/waffle.png",
  },
  {
    id: 56,
    name: "Crêpe au Nutella",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fine classique fourrée au Nutella chaud.",
    price: 19.0,
    popular: true,
    image: "/images/menu/crepe.png",
  },
  {
    id: 57,
    name: "Pancakes au Nutella",
    category: "Pâtisseries et Desserts",
    description: "Pile de pancakes moelleux étagés avec du Nutella.",
    price: 21.0,
    popular: true,
    image: "/images/menu/pancakes.png",
  },
  {
    id: 58,
    name: "Gaufre au Nutella",
    category: "Pâtisseries et Desserts",
    description: "Gaufre dorée généreusement garnie de Nutella.",
    price: 19.0,
    popular: true,
    image: "/images/menu/waffle.png",
  },
  {
    id: 59,
    name: "Pithiviers",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte ronde fermée en pâte feuilletée avec une garniture sucrée.",
    price: 5.0,
    popular: false,
    image: "/images/menu/Pithiviers.png",
  },
  {
    id: 60,
    name: "Mini Gâteau à la Framboise",
    category: "Pâtisseries et Desserts",
    description: "Petit gâteau infusé avec une douce saveur de framboise.",
    price: 8.0,
    popular: false,
    image: "/images/menu/minicake.png",
  },
  {
    id: 61,
    name: "Petit Quatre-quarts",
    category: "Pâtisseries et Desserts",
    description: "Tranche de quatre-quarts moelleux au format individuel.",
    price: 15.0,
    popular: false,
    image: "/images/menu/pound-cake.png",
  },
  {
    id: 62,
    name: "Basboussa à la Vanille",
    category: "Pâtisseries et Desserts",
    description:
      "Gâteau de semoule sucré classique imbibé de sirop à la vanille.",
    price: 6.0,
    popular: false,
    image: "/images/menu/basbousa.png",
  },
  {
    id: 63,
    name: "Madeleine à la Vanille",
    category: "Pâtisseries et Desserts",
    description:
      "Gâteau éponge français classique, beurré et en forme de coquille.",
    price: 1.5,
    popular: false,
    image: "/images/menu/madeleine.png",
  },
  {
    id: 64,
    name: "Croissant aux Amandes",
    category: "Pâtisseries et Desserts",
    description:
      "Croissant feuilleté garni de crème d'amande et surmonté d'amandes effilées.",
    price: 5.0,
    popular: false,
    image: "/images/menu/croissant.png",
  },
  {
    id: 65,
    name: "Triangle aux Amandes",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie feuilletée en forme de triangle garnie de pâte d'amande sucrée.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Triangle.png",
  },
  {
    id: 66,
    name: "Danoise au Chocolat",
    category: "Pâtisseries et Desserts",
    description: "Pâtisserie danoise feuilletée marbrée de chocolat riche.",
    price: 4.0,
    popular: false,
    image: "/images/menu/Danish.webp",
  },
  {
    id: 67,
    name: "Pâtisserie Danoise",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie danoise traditionnelle feuilletée, beurrée et sucrée.",
    price: 3.5,
    popular: false,
    image: "/images/menu/Danish.webp",
  },
  {
    id: 68,
    name: "Harcha",
    category: "Pâtisseries et Desserts",
    description:
      "Pain plat marocain traditionnel à la semoule cuit à la poêle.",
    price: 2.5,
    popular: false,
    image: "/images/menu/harcha.png",
  },
  {
    id: 69,
    name: "Msemmen",
    category: "Pâtisseries et Desserts",
    description: "Pain plat carré marocain traditionnel, feuilleté et étagé.",
    price: 4.0,
    popular: false,
    image: "/images/menu/msemmen.png",
  },
  {
    id: 70,
    name: "Harcha à l'Huile d'Olive",
    category: "Pâtisseries et Desserts",
    description:
      "Pain plat salé à la semoule préparé avec de la riche huile d'olive.",
    price: 3.5,
    popular: false,
    image: "/images/menu/harcha.png",
  },
  {
    id: 71,
    name: "Pain Suisse",
    category: "Pâtisseries et Desserts",
    description:
      "Pâte feuilletée roulée avec de la crème pâtissière à la vanille et des pépites de chocolat.",
    price: 3.0,
    popular: false,
    image: "/images/menu/pain-suisse.png",
  },
  {
    id: 72,
    name: "Pain au Chocolat / Croissant",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie de petit-déjeuner française classique, feuilletée et beurrée.",
    price: 2.5,
    popular: false,
    image: "/images/menu/croissant.png",
  },

  // BAKERY
  {
    id: 73,
    name: "Pain d'Orge",
    category: "Boulangerie",
    description: "Pain d'orge marocain consistant et sain.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 74,
    name: "Batbout",
    category: "Boulangerie",
    description: "Pain plat marocain moelleux cuit à la poêle.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 75,
    name: "Brioche au Chocolat",
    category: "Boulangerie",
    description: "Pain sucré moelleux et gonflé rempli de pépites de chocolat.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 76,
    name: "Baguette Classique",
    category: "Boulangerie",
    description:
      "Baguette française traditionnelle croustillante et moelleuse.",
    price: 1.5,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 77,
    name: "Pain Classique",
    category: "Boulangerie",
    description: "Pain rond blanc moelleux traditionnel marocain.",
    price: 1.5,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 78,
    name: "Brioche Classique",
    category: "Boulangerie",
    description: "Pain sucré traditionnel beurré, moelleux et gonflé.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 79,
    name: "Pain de Maïs",
    category: "Boulangerie",
    description: "Pain de semoule de maïs marocain rustique et savoureux.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 80,
    name: "Pain d'Épices",
    category: "Boulangerie",
    description: "Pain épicé français traditionnel avec du miel et de l'anis.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 81,
    name: "Baguette Multicéréales",
    category: "Boulangerie",
    description:
      "Baguette croustillante cuite avec un mélange de graines et de céréales saines.",
    price: 4.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 82,
    name: "Baguette aux Olives",
    category: "Boulangerie",
    description:
      "Baguette salée cuite avec des morceaux d'olives noires et vertes.",
    price: 5.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 83,
    name: "Pain aux Olives",
    category: "Boulangerie",
    description: "Pain rond traditionnel moelleux cuit avec des olives salées.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 84,
    name: "Pain de Blé Sans Sel",
    category: "Boulangerie",
    description: "Pain au blé complet sain préparé sans sel ajouté.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 85,
    name: "Baguette de Semoule",
    category: "Boulangerie",
    description:
      "Baguette faite avec de la farine de semoule pour un croquant rustique.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 86,
    name: "Pain de Semoule",
    category: "Boulangerie",
    description: "Pain rond traditionnel marocain fait avec de la semoule.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 87,
    name: "Baguette au Sésame",
    category: "Boulangerie",
    description:
      "Baguette française croustillante fraîchement cuite et garnie de graines de sésame.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 88,
    name: "Petit Pain au Sésame",
    category: "Boulangerie",
    description:
      "Petit pain moelleux généreusement garni de graines de sésame.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 89,
    name: "Baguette Viennoise",
    category: "Boulangerie",
    description: "Pain de style viennois, moelleux, légèrement sucré et riche.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 90,
    name: "Baguette Complète",
    category: "Boulangerie",
    description: "Baguette française au blé complet saine et consistante.",
    price: 3.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 91,
    name: "Pain Complet",
    category: "Boulangerie",
    description: "Pain rond traditionnel marocain au blé complet nutritif.",
    price: 2.0,
    popular: false,
    image: "/images/menu/bread.png",
  },
  {
    id: 92,
    name: "Petit Pain Complet",
    category: "Boulangerie",
    description: "Petit pain au blé complet sain et moelleux.",
    price: 2.5,
    popular: false,
    image: "/images/menu/bread.png",
  },

  // HOT DRINKS
  {
    id: 93,
    name: "Thé Noir (Lipton)",
    category: "Boissons Chaudes",
    description: "Thé noir classique Lipton.",
    price: 12.0,
    popular: false,
    image: "/images/menu/tea.png",
  },
  {
    id: 94,
    name: "Chocolat Chaud",
    category: "Boissons Chaudes",
    description: "Lait chaud et réconfortant avec du chocolat riche.",
    price: 12.0,
    popular: true,
    image: "/images/menu/hot-chocolate.png",
  },
  {
    id: 95,
    name: "Lait Chaud",
    category: "Boissons Chaudes",
    description: "Lait cuit à la vapeur simple et réconfortant.",
    price: 12.0,
    popular: false,
    image: "/images/menu/hot-milk.png",
  },
  {
    id: 96,
    name: "Verveine",
    category: "Boissons Chaudes",
    description:
      "Tisane faite avec des feuilles de verveine citronnée naturelles.",
    price: 12.0,
    popular: false,
    image: "/images/menu/tea.png",
  },
  {
    id: 97,
    name: "Thé au Lait (Lipton)",
    category: "Boissons Chaudes",
    description: "Thé noir classique Lipton infusé avec du lait.",
    price: 12.0,
    popular: false,
    image: "/images/menu/milk-tea.png",
  },
  {
    id: 98,
    name: "Lait à la Verveine",
    category: "Boissons Chaudes",
    description: "Lait chaud infusé avec de la verveine citronnée apaisante.",
    price: 12.0,
    popular: false,
    image: "/images/menu/milk-tea.png",
  },
  {
    id: 99,
    name: "Lait au Sirop",
    category: "Boissons Chaudes",
    description: "Lait froid ou chaud aromatisé avec du sirop sucré.",
    price: 11.0,
    popular: false,
    image: "/images/menu/hot-milk.png",
  },
  {
    id: 100,
    name: "Thé à la Menthe Marocain",
    category: "Boissons Chaudes",
    description: "Thé vert traditionnel infusé avec de la menthe fraîche.",
    price: 11.0,
    popular: true,
    image: "/images/menu/teapot.png",
  },

  // COLD DRINKS
  {
    id: 101,
    name: "Affogato",
    category: "Boissons Froides",
    description:
      "Une boule de glace à la vanille noyée dans un espresso chaud.",
    price: 18.0,
    popular: false,
    image: "/images/menu/Affogato.png",
  },
  {
    id: 102,
    name: "Milkshake Banane",
    category: "Boissons Froides",
    description: "Milkshake à la banane doux et crémeux.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milk-shake.png",
  },
  {
    id: 103,
    name: "Smoothie Banane",
    category: "Boissons Froides",
    description: "Smoothie crémeux mixé à la banane.",
    price: 23.0,
    popular: false,
    image: "/images/menu/Smoothie.png",
  },
  {
    id: 104,
    name: "Mojito Bleu",
    category: "Boissons Froides",
    description:
      "Mocktail aux agrumes et à la menthe avec sirop de curaçao bleu.",
    price: 22.0,
    popular: false,
    image: "/images/menu/Mojito.png",
  },
  {
    id: 105,
    name: "Choix de Soda (35cl)",
    category: "Boissons Froides",
    description: "Sélection de boissons gazeuses rafraîchissantes.",
    price: 12.0,
    popular: true,
    image: "/images/menu/Soda.png",
  },
  {
    id: 106,
    name: "Milkshake Chocolat",
    category: "Boissons Froides",
    description: "Milkshake au chocolat riche et crémeux.",
    price: 23.0,
    popular: true,
    image: "/images/menu/milk-shake.png",
  },
  {
    id: 107,
    name: "Cocktail Exotique",
    category: "Boissons Froides",
    description: "Mangue, orange et ananas mixés.",
    price: 21.0,
    popular: true,
    image: "/images/menu/Cocktail.png",
  },
  {
    id: 108,
    name: "Smoothie Exotique",
    category: "Boissons Froides",
    description: "Mélange rafraîchissant de fruits tropicaux.",
    price: 26.0,
    popular: false,
    image: "/images/menu/Smoothie.png",
  },
  {
    id: 109,
    name: "Macchiato Glacé au Caramel",
    category: "Boissons Froides",
    description:
      "Lait et espresso glacés, aromatisés à la vanille et au caramel.",
    price: 21.0,
    popular: true,
    image: "/images/menu/iced-caramel.png",
  },
  {
    id: 110,
    name: "Café Glacé",
    category: "Boissons Froides",
    description: "Café refroidi sur des glaçons avec un choix de saveur.",
    price: 18.0,
    popular: false,
    image: "/images/menu/iced-coffee.png",
  },
  {
    id: 111,
    name: "Frappuccino Glacé",
    category: "Boissons Froides",
    description:
      "Boisson au café glacé mixée avec un choix de vanille, chocolat ou caramel.",
    price: 21.0,
    popular: true,
    image: "/images/menu/iced-frappuccino.png",
  },
  {
    id: 112,
    name: "Latte Glacé",
    category: "Boissons Froides",
    description: "Espresso et lait refroidi sur des glaçons.",
    price: 19.0,
    popular: true,
    image: "/images/menu/Iced-Latte.png",
  },
  {
    id: 113,
    name: "Moka Glacé",
    category: "Boissons Froides",
    description: "Espresso glacé avec du chocolat et du lait.",
    price: 19.0,
    popular: true,
    image: "/images/menu/iced-mocha.png",
  },
  {
    id: 114,
    name: "Smoothie Mangue",
    category: "Boissons Froides",
    description: "Smoothie tropical à la mangue mixée.",
    price: 23.0,
    popular: true,
    image: "/images/menu/smoothie.png",
  },
  {
    id: 115,
    name: "Eau Minérale (33cl)",
    category: "Boissons Froides",
    description: "Petite bouteille d'eau minérale plate.",
    price: 5.0,
    popular: false,
    image: "/images/menu/Water.png",
  },
  {
    id: 116,
    name: "Eau Minérale (50cl)",
    category: "Boissons Froides",
    description: "Bouteille moyenne d'eau minérale plate.",
    price: 7.0,
    popular: true,
    image: "/images/menu/Water.png",
  },
  {
    id: 117,
    name: "Milkshake Oreo",
    category: "Boissons Froides",
    description: "Milkshake onctueux à la vanille mixé avec des biscuits Oreo.",
    price: 26.0,
    popular: true,
    image: "/images/menu/milk-shake.png",
  },
  {
    id: 118,
    name: "Cocktail Oriental",
    category: "Boissons Froides",
    description: "Banane, pomme et orange mixées.",
    price: 20.0,
    popular: false,
    image: "/images/menu/Cocktail.png",
  },
  {
    id: 119,
    name: "Mojito Rouge",
    category: "Boissons Froides",
    description:
      "Mocktail fruité aux fruits rouges avec menthe et citron vert.",
    price: 22.0,
    popular: false,
    image: "/images/menu/Mojito.png",
  },
  {
    id: 120,
    name: "Milkshake Fraise",
    category: "Boissons Froides",
    description: "Milkshake doux et crémeux à la fraise.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milk-shake.png",
  },
  {
    id: 121,
    name: "Smoothie Fraise",
    category: "Boissons Froides",
    description: "Fraises fraîches et yaourt mixés.",
    price: 23.0,
    popular: true,
    image: "/images/menu/Smoothie.png",
  },
  {
    id: 122,
    name: "Cocktail Tropical",
    category: "Boissons Froides",
    description: "Mangue, kiwi et ananas mixés.",
    price: 21.0,
    popular: false,
    image: "/images/menu/Cocktail.png",
  },
  {
    id: 123,
    name: "Milkshake Vanille",
    category: "Boissons Froides",
    description: "Milkshake classique crémeux à la vanille.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milk-shake.png",
  },
  {
    id: 124,
    name: "Virgin Mojito",
    category: "Boissons Froides",
    description: "Mocktail rafraîchissant au citron vert et à la menthe.",
    price: 19.0,
    popular: true,
    image: "/images/menu/Mojito.png",
  },

  // COFFEES
  {
    id: 125,
    name: "Americano",
    category: "Cafés",
    description: "Espresso dilué avec de l'eau chaude.",
    price: 14.0,
    popular: false,
    image: "/images/menu/Americano.png",
  },
  {
    id: 126,
    name: "Cappuccino",
    category: "Cafés",
    description:
      "Espresso surmonté de parts égales de lait cuit à la vapeur et de mousse.",
    price: 15.0,
    popular: true,
    image: "/images/menu/Cappuccino.png",
  },
  {
    id: 127,
    name: "Café au Lait à Part",
    category: "Cafés",
    description: "Espresso servi avec un côté séparé de lait.",
    price: 15.0,
    popular: false,
    image: "/images/menu/coffee-milk.png",
  },
  {
    id: 128,
    name: "Cortado",
    category: "Cafés",
    description: "À parts égales d'espresso et de lait cuit à la vapeur.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Cortado.png",
  },
  {
    id: 129,
    name: "Café Crème",
    category: "Cafés",
    description: "Espresso mélangé avec de la crème cuite à la vapeur.",
    price: 12.0,
    popular: true,
    image: "/images/menu/Cream-Coffee.png",
  },
  {
    id: 130,
    name: "Double Espresso",
    category: "Cafés",
    description: "Deux riches shots d'espresso intense.",
    price: 18.0,
    popular: true,
    image: "/images/menu/double-espresso.png",
  },
  {
    id: 131,
    name: "Espresso",
    category: "Cafés",
    description: "Shot de café riche et intense.",
    price: 12.0,
    popular: true,
    image: "/images/menu/Espresso.png",
  },
  {
    id: 132,
    name: "Flat White",
    category: "Cafés",
    description: "Espresso avec du lait micro-moussé.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Flat-White.png",
  },
  {
    id: 133,
    name: "Espresso Illy",
    category: "Cafés",
    description: "Shot d'espresso italien premium Illy.",
    price: 16.0,
    popular: false,
    image: "/images/menu/Illy-Espresso.png",
  },
  {
    id: 134,
    name: "Latte Macchiato",
    category: "Cafés",
    description: "Lait cuit à la vapeur marqué par un shot d'espresso.",
    price: 16.0,
    popular: true,
    image: "/images/menu/Latte-Macchiato.png",
  },
  {
    id: 135,
    name: "Moka",
    category: "Cafés",
    description:
      "Espresso combiné avec du chocolat et du lait cuit à la vapeur.",
    price: 18.0,
    popular: false,
    image: "/images/menu/mocha.png",
  },
  {
    id: 136,
    name: "Café Nespresso",
    category: "Cafés",
    description: "Café infusé Nespresso classique.",
    price: 15.0,
    popular: false,
    image: "/images/menu/Nespresso.png",
  },
  {
    id: 137,
    name: "Viennois au Chocolat",
    category: "Cafés",
    description: "Chocolat chaud garni de crème fouettée.",
    price: 16.0,
    popular: true,
    image: "/images/menu/Viennese-Chocolate.png",
  },

  // JUICES
  {
    id: 138,
    name: "Jus de Pomme",
    category: "Jus",
    description: "Jus de pomme fraîchement pressé.",
    price: 16.0,
    popular: false,
    image: "/images/menu/juices.png",
  },
  {
    id: 139,
    name: "Jus d'Avocat",
    category: "Jus",
    description: "Jus d'avocat mixé riche et crémeux.",
    price: 18.0,
    popular: true,
    image: "/images/menu/juices.png",
  },
  {
    id: 140,
    name: "Jus d'Avocat aux Fruits Secs",
    category: "Jus",
    description: "Jus d'avocat crémeux mixé avec un mélange de fruits secs.",
    price: 23.0,
    popular: true,
    image: "/images/menu/juices.png",
  },
  {
    id: 141,
    name: "Jus de Banane",
    category: "Jus",
    description: "Jus de banane fraîchement mixé.",
    price: 16.0,
    popular: false,
    image: "/images/menu/juices.png",
  },
  {
    id: 142,
    name: "Jus de Mangue",
    category: "Jus",
    description: "Jus de mangue tropical frais.",
    price: 20.0,
    popular: false,
    image: "/images/menu/juices.png",
  },
  {
    id: 143,
    name: "Jus de Fruits Mixtes au Lait",
    category: "Jus",
    description: "Mélange de fruits mixtes avec du lait.",
    price: 18.0,
    popular: true,
    image: "/images/menu/juices.png",
  },
  {
    id: 144,
    name: "Jus de Fruits Mixtes à l'Orange",
    category: "Jus",
    description: "Mélange de fruits mixtes avec du jus d'orange.",
    price: 23.0,
    popular: false,
    image: "/images/menu/juices.png",
  },
  {
    id: 145,
    name: "Jus d'Orange",
    category: "Jus",
    description: "Jus d'orange fraîchement pressé.",
    price: 16.0,
    popular: true,
    image: "/images/menu/juices.png",
  },
  {
    id: 146,
    name: "Jus d'Ananas",
    category: "Jus",
    description: "Jus d'ananas frais et sucré.",
    price: 23.0,
    popular: false,
    image: "/images/menu/juices.png",
  },
  {
    id: 147,
    name: "Jus de Fraise",
    category: "Jus",
    description: "Jus de fraise fraîchement mixé.",
    price: 18.0,
    popular: true,
    image: "/images/menu/juices.png",
  },

  // EXTRAS
  {
    id: 148,
    name: "Amlou aux Amandes",
    category: "Suppléments",
    description:
      "Amlou premium fait avec des amandes extra grillées. Servi avec du pain.",
    price: 12.0,
    popular: false,
    image: "/images/menu/Almond.png",
  },
  {
    id: 149,
    name: "Amlou à l'Huile d'Argan",
    category: "Suppléments",
    description:
      "Trempette traditionnelle aux amandes, miel et huile d'argan. Servie avec du pain.",
    price: 8.0,
    popular: true,
    image: "/images/menu/argan.png",
  },
  {
    id: 150,
    name: "Olives Noires et Vertes",
    category: "Suppléments",
    description: "Olives mixtes marinées. Servies avec du pain.",
    price: 5.0,
    popular: false,
    image: "/images/menu/olive.png",
  },
  {
    id: 151,
    name: "Fromage à Tartiner",
    category: "Suppléments",
    description: "Portion de fromage à tartiner. Servi avec du pain.",
    price: 3.0,
    popular: true,
    image: "/images/menu/cheese.png",
  },
  {
    id: 152,
    name: "Fromage Frais (Jben)",
    category: "Suppléments",
    description:
      "Portion de fromage frais marocain traditionnel. Servi avec du pain.",
    price: 8.0,
    popular: true,
    image: "/images/menu/Fresh-Cheese.png",
  },
  {
    id: 153,
    name: "Miel",
    category: "Suppléments",
    description: "Portion de pur miel. Servi avec du pain.",
    price: 6.0,
    popular: true,
    image: "/images/menu/Honey.png",
  },
  {
    id: 154,
    name: "Confiture",
    category: "Suppléments",
    description: "Portion de confiture de fruits. Servie avec du pain.",
    price: 6.0,
    popular: false,
    image: "/images/menu/Jam.png",
  },
  {
    id: 155,
    name: "Nutella",
    category: "Suppléments",
    description:
      "Portion de riche pâte à tartiner noisettes cacao. Servie avec du pain.",
    price: 10.0,
    popular: true,
    image: "/images/menu/Nutella.png",
  },
  {
    id: 156,
    name: "Huile d'Olive",
    category: "Suppléments",
    description:
      "Portion d'huile d'olive extra vierge de haute qualité. Servie avec du pain.",
    price: 8.0,
    popular: true,
    image: "/images/menu/Olive-Oil.png",
  },
];

export const shopProducts = [
  // BREAKFAST & SAVORY
  {
    id: 1,
    name: "Soupe d'Orge (Hssoua)",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe traditionnelle marocaine à l'orge et au lait, chaude et réconfortante.",
    price: 7.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Hesewa.jpg",
  },
  {
    id: 2,
    name: "Omelette au Fromage",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette moelleuse garnie de fromage fondu, servie avec des olives et de l'huile d'olive.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Omelet.jpg",
  },
  {
    id: 3,
    name: "Petit-déjeuner Continental",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, omelette au fromage, huile d'olive, olives, fromage, pain, yaourt et eau.",
    price: 35.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 4,
    name: "Omelette à la Charcuterie",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette garnie de charcuterie, servie avec des olives et de l'huile d'olive.",
    price: 17.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/Omelet.jpg",
  },
  {
    id: 5,
    name: "Petit-déjeuner Express",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, viennoiseries, yaourt et eau minérale.",
    price: 26.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 6,
    name: "Petit-déjeuner Fassi",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, omelette à la viande séchée, huile d'olive, olives, fromage, pain, yaourt et eau.",
    price: 37.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 7,
    name: "Petit-déjeuner Gourmand",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, huile d'olive, Amlou, olives, miel, pain, yaourt et eau.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 8,
    name: "Soupe Harira",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe marocaine traditionnelle consistante aux tomates, lentilles et pois chiches.",
    price: 10.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Soup.jpg",
  },
  {
    id: 9,
    name: "Omelette au Khlii",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette traditionnelle avec de la viande confite marocaine, servie avec des olives et de l'huile d'olive.",
    price: 24.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Omelet.jpg",
  },
  {
    id: 10,
    name: "Petit-déjeuner Enfant",
    category: "Petit-déjeuner et Salé",
    description:
      "Lait au chocolat, jus d'orange, pain au chocolat, gâteau à la vanille, yaourt et eau.",
    price: 25.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 11,
    name: "Petit-déjeuner La Madeleine",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, choix d'omelette, huile d'olive, olives, miel, fromage, Amlou, pain, crêpe, chocolat, gâteau, yaourt et eau.",
    price: 55.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 12,
    name: "Omelette Nature",
    category: "Petit-déjeuner et Salé",
    description:
      "Simple omelette moelleuse servie avec des olives et de l'huile d'olive.",
    price: 13.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/Omelet.jpg",
  },
  {
    id: 13,
    name: "Petit-déjeuner Soussi",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, Amlou, huile d'olive, fromage, olives, miel, confiture et eau.",
    price: 38.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.jpg",
  },
  {
    id: 14,
    name: "Omelette aux Tomates",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette moelleuse aux tomates fraîches, servie avec des olives et de l'huile d'olive.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Omelet.jpg",
  },
  {
    id: 15,
    name: "Petit-déjeuner Traditionnel",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, crêpes marocaines (Baghrir), Harcha, miel, fromage frais et eau.",
    price: 28.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.jpg",
  },

  // PASTRIES & DESSERTS
  {
    id: 16,
    name: "Cigare aux Fruits de Mer",
    category: "Pâtisseries et Desserts",
    description:
      "Pâte croustillante roulée et remplie d'un mélange salé de fruits de mer.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Cigar.webp",
  },
  {
    id: 17,
    name: "Pastilla aux Fruits de Mer",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte salée feuilletée garnie de fruits de mer assaisonnés et de vermicelles.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pastilla.png",
  },
  {
    id: 18,
    name: "Sandwich",
    category: "Pâtisseries et Desserts",
    description: "Sandwich salé fraîchement préparé.",
    price: 8.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/sandwich.jpg",
  },
  {
    id: 19,
    name: "Mini Pizza",
    category: "Pâtisseries et Desserts",
    description:
      "Pizza salée de format individuel garnie de fromage et de sauce tomate.",
    price: 6.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/pizza.jpeg",
  },
  {
    id: 20,
    name: "Friand à la Saucisse",
    category: "Pâtisseries et Desserts",
    description: "Saucisse salée enveloppée et cuite dans une pâte moelleuse.",
    price: 9.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/hot-dog.jpg",
  },
  {
    id: 21,
    name: "Pastilla au Poulet",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte sucrée-salée garnie de poulet épicé et d'amandes grillées.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pastilla.png",
  },
  {
    id: 22,
    name: "Briouate au Fromage",
    category: "Pâtisseries et Desserts",
    description:
      "Triangles de pâte marocaine croustillante farcis de fromage salé.",
    price: 7.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Briouat.jpeg",
  },
  {
    id: 23,
    name: "Tarte aux Amandes",
    category: "Pâtisseries et Desserts",
    description:
      "Fond de tarte sucré et croustillant garni d'une crème d'amande dense.",
    price: 10.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Tart.jpg",
  },
  {
    id: 24,
    name: "Pancakes à l'Amlou",
    category: "Pâtisseries et Desserts",
    description: "Pancakes moelleux garnis d'Amlou traditionnel marocain.",
    price: 17.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Pancakes.jpg",
  },
  {
    id: 25,
    name: "Chausson aux Pommes",
    category: "Pâtisseries et Desserts",
    description:
      "Pâte feuilletée remplie d'une compote de pommes douce et épicée.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Apple-Turnover.jpg",
  },
  {
    id: 26,
    name: "Crêpe au Caramel",
    category: "Pâtisseries et Desserts",
    description: "Fine crêpe française pliée avec du caramel sucré.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 27,
    name: "Gaufre au Caramel",
    category: "Pâtisseries et Desserts",
    description: "Gaufre dorée nappée d'une riche sauce au caramel.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/waffle.jpg",
  },
  {
    id: 28,
    name: "Basboussa au Chocolat",
    category: "Pâtisseries et Desserts",
    description: "Gâteau de semoule sucré aromatisé au chocolat riche.",
    price: 8.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.jpg",
  },
  {
    id: 29,
    name: "Madeleine au Chocolat",
    category: "Pâtisseries et Desserts",
    description:
      "Petit gâteau éponge en forme de coquille, aromatisé au chocolat.",
    price: 2.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.jpg",
  },
  {
    id: 30,
    name: "Crêpe Classique",
    category: "Pâtisseries et Desserts",
    description: "Crêpe française simple, fine et moelleuse.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 31,
    name: "Part de Gâteau à la Crème (10)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 10.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 32,
    name: "Part de Gâteau à la Crème (12)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 33,
    name: "Part de Gâteau à la Crème (13)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 13.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 34,
    name: "Part de Gâteau à la Crème (14)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 14.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 35,
    name: "Part de Gâteau à la Crème (15)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 36,
    name: "Part de Gâteau à la Crème (17)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 17.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 37,
    name: "Part de Gâteau à la Crème (18)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Cream-Cake-Slice.webp",
  },
  {
    id: 38,
    name: "Beignet",
    category: "Pâtisseries et Desserts",
    description: "Anneau de pâte frite moelleux, sucré et classique.",
    price: 4.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/donut.jpg",
  },
  {
    id: 39,
    name: "Tarte Frangipane",
    category: "Pâtisseries et Desserts",
    description: "Tartelette en pâte sucrée garnie de riche crème d'amande.",
    price: 8.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Frangipane-Tart.jpg",
  },
  {
    id: 40,
    name: "Pithiviers aux Fruits",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte en pâte feuilletée garnie de compote de fruits sucrée.",
    price: 6.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Pithiviers.jpg",
  },
  {
    id: 41,
    name: "Salade de Fruits au Jus d'Orange",
    category: "Pâtisseries et Desserts",
    description: "Fruits frais de saison macérés dans du jus d'orange frais.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/fruit-salad.jpeg",
  },
  {
    id: 42,
    name: "Salade de Fruits au Yaourt",
    category: "Pâtisseries et Desserts",
    description: "Fruits frais de saison mélangés avec du yaourt crémeux.",
    price: 18.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/fruit-salad.jpeg",
  },
  {
    id: 43,
    name: "Tartelette aux Fruits",
    category: "Pâtisseries et Desserts",
    description:
      "Petite croûte de tarte sucrée garnie de crème anglaise et de fruits frais.",
    price: 7.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Fruit-Tartlet.jpg",
  },
  {
    id: 44,
    name: "Pancakes au Miel",
    category: "Pâtisseries et Desserts",
    description: "Pancakes moelleux arrosés de pur miel.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pancakes.jpg",
  },
  {
    id: 45,
    name: "Grand Quatre-quarts",
    category: "Pâtisseries et Desserts",
    description: "Quatre-quarts généreux, beurré et moelleux.",
    price: 30.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pound-cake.jpg",
  },
  {
    id: 46,
    name: "Quatre-quarts Moyen",
    category: "Pâtisseries et Desserts",
    description: "Quatre-quarts classique, moelleux et sucré.",
    price: 20.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pound-cake.jpg",
  },
  {
    id: 47,
    name: "Mille-Feuille",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie française classique avec des couches de pâte feuilletée et de crème vanille.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/millefeuille.jpg",
  },
  {
    id: 48,
    name: "Mini Gâteau",
    category: "Pâtisseries et Desserts",
    description: "Petit gâteau personnel, moelleux et sucré.",
    price: 7.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/minicake.png",
  },
  {
    id: 49,
    name: "Mini Cupcake",
    category: "Pâtisseries et Desserts",
    description: "Gâteau moelleux en format bouchée avec glaçage sucré.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cupcake.png",
  },
  {
    id: 50,
    name: "Crêpe Nutella & Banane",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fourrée au Nutella et aux bananes tranchées.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 51,
    name: "Pancakes Nutella & Banane",
    category: "Pâtisseries et Desserts",
    description: "Pancakes servis avec du Nutella et des bananes fraîches.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pancakes.jpg",
  },
  {
    id: 52,
    name: "Gaufre Nutella & Banane",
    category: "Pâtisseries et Desserts",
    description: "Gaufre garnie de Nutella et de tranches de banane fraîche.",
    price: 22.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.jpg",
  },
  {
    id: 53,
    name: "Crêpe Nutella & Oreo",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fourrée au Nutella et aux biscuits Oreo concassés.",
    price: 25.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 54,
    name: "Crêpe Nutella & Fruits de Saison",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fourrée au Nutella et aux fruits de saison frais.",
    price: 29.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 55,
    name: "Gaufre Nutella & Fruits de Saison",
    category: "Pâtisseries et Desserts",
    description: "Gaufre au Nutella et aux fruits de saison frais.",
    price: 27.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.jpg",
  },
  {
    id: 56,
    name: "Crêpe au Nutella",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fine classique fourrée au Nutella chaud.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.jpg",
  },
  {
    id: 57,
    name: "Pancakes au Nutella",
    category: "Pâtisseries et Desserts",
    description: "Pile de pancakes moelleux étagés avec du Nutella.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pancakes.jpg",
  },
  {
    id: 58,
    name: "Gaufre au Nutella",
    category: "Pâtisseries et Desserts",
    description: "Gaufre dorée généreusement garnie de Nutella.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/waffle.jpg",
  },
  {
    id: 59,
    name: "Pithiviers",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte ronde fermée en pâte feuilletée avec une garniture sucrée.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Pithiviers.jpg",
  },
  {
    id: 60,
    name: "Mini Gâteau à la Framboise",
    category: "Pâtisseries et Desserts",
    description: "Petit gâteau infusé avec une douce saveur de framboise.",
    price: 8.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/minicake.png",
  },
  {
    id: 61,
    name: "Petit Quatre-quarts",
    category: "Pâtisseries et Desserts",
    description: "Tranche de quatre-quarts moelleux au format individuel.",
    price: 15.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pound-cake.jpg",
  },
  {
    id: 62,
    name: "Basboussa à la Vanille",
    category: "Pâtisseries et Desserts",
    description:
      "Gâteau de semoule sucré classique imbibé de sirop à la vanille.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.jpg",
  },
  {
    id: 63,
    name: "Madeleine à la Vanille",
    category: "Pâtisseries et Desserts",
    description:
      "Gâteau éponge français classique, beurré et en forme de coquille.",
    price: 1.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.jpg",
  },
  {
    id: 64,
    name: "Croissant aux Amandes",
    category: "Pâtisseries et Desserts",
    description:
      "Croissant feuilleté garni de crème d'amande et surmonté d'amandes effilées.",
    price: 5.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/croissant.jpg",
  },
  {
    id: 65,
    name: "Triangle aux Amandes",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie feuilletée en forme de triangle garnie de pâte d'amande sucrée.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Triangle.jpg",
  },
  {
    id: 66,
    name: "Danoise au Chocolat",
    category: "Pâtisseries et Desserts",
    description: "Pâtisserie danoise feuilletée marbrée de chocolat riche.",
    price: 4.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Danish.jpg",
  },
  {
    id: 67,
    name: "Pâtisserie Danoise",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie danoise traditionnelle feuilletée, beurrée et sucrée.",
    price: 3.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Danish.jpg",
  },
  {
    id: 68,
    name: "Harcha",
    category: "Pâtisseries et Desserts",
    description:
      "Pain plat marocain traditionnel à la semoule cuit à la poêle.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/harcha.jpg",
  },
  {
    id: 69,
    name: "Msemmen",
    category: "Pâtisseries et Desserts",
    description: "Pain plat carré marocain traditionnel, feuilleté et étagé.",
    price: 4.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/msemmen.jpg",
  },
  {
    id: 70,
    name: "Harcha à l'Huile d'Olive",
    category: "Pâtisseries et Desserts",
    description:
      "Pain plat salé à la semoule préparé avec de la riche huile d'olive.",
    price: 3.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Oil-Harcha.jpg",
  },
  {
    id: 71,
    name: "Pain Suisse",
    category: "Pâtisseries et Desserts",
    description:
      "Pâte feuilletée roulée avec de la crème pâtissière à la vanille et des pépites de chocolat.",
    price: 3.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pain-suisse.jpg",
  },
  {
    id: 72,
    name: "Pain au Chocolat / Croissant",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie de petit-déjeuner française classique, feuilletée et beurrée.",
    price: 2.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Pain-au-Chocolat.jpg",
  },

  // BAKERY
  {
    id: 73,
    name: "Pain d'Orge",
    category: "Boulangerie",
    description: "Pain d'orge marocain consistant et sain.",
    price: 2.5,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 74,
    name: "Batbout",
    category: "Boulangerie",
    description: "Pain plat marocain moelleux cuit à la poêle.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 75,
    name: "Brioche au Chocolat",
    category: "Boulangerie",
    description: "Pain sucré moelleux et gonflé rempli de pépites de chocolat.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 76,
    name: "Baguette Classique",
    category: "Boulangerie",
    description:
      "Baguette française traditionnelle croustillante et moelleuse.",
    price: 1.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 77,
    name: "Pain Classique",
    category: "Boulangerie",
    description: "Pain rond blanc moelleux traditionnel marocain.",
    price: 1.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 78,
    name: "Brioche Classique",
    category: "Boulangerie",
    description: "Pain sucré traditionnel beurré, moelleux et gonflé.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 79,
    name: "Pain de Maïs",
    category: "Boulangerie",
    description: "Pain de semoule de maïs marocain rustique et savoureux.",
    price: 2.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 80,
    name: "Pain d'Épices",
    category: "Boulangerie",
    description: "Pain épicé français traditionnel avec du miel et de l'anis.",
    price: 24.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 81,
    name: "Baguette Multicéréales",
    category: "Boulangerie",
    description:
      "Baguette croustillante cuite avec un mélange de graines et de céréales saines.",
    price: 4.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 82,
    name: "Baguette aux Olives",
    category: "Boulangerie",
    description:
      "Baguette salée cuite avec des morceaux d'olives noires et vertes.",
    price: 5.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 83,
    name: "Pain aux Olives",
    category: "Boulangerie",
    description: "Pain rond traditionnel moelleux cuit avec des olives salées.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 84,
    name: "Pain de Blé Sans Sel",
    category: "Boulangerie",
    description: "Pain au blé complet sain préparé sans sel ajouté.",
    price: 3.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 85,
    name: "Baguette de Semoule",
    category: "Boulangerie",
    description:
      "Baguette faite avec de la farine de semoule pour un croquant rustique.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 86,
    name: "Pain de Semoule",
    category: "Boulangerie",
    description: "Pain rond traditionnel marocain fait avec de la semoule.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 87,
    name: "Baguette au Sésame",
    category: "Boulangerie",
    description:
      "Baguette française croustillante fraîchement cuite et garnie de graines de sésame.",
    price: 2.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 88,
    name: "Petit Pain au Sésame",
    category: "Boulangerie",
    description:
      "Petit pain moelleux généreusement garni de graines de sésame.",
    price: 3.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 89,
    name: "Baguette Viennoise",
    category: "Boulangerie",
    description: "Pain de style viennois, moelleux, légèrement sucré et riche.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 90,
    name: "Baguette Complète",
    category: "Boulangerie",
    description: "Baguette française au blé complet saine et consistante.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 91,
    name: "Pain Complet",
    category: "Boulangerie",
    description: "Pain rond traditionnel marocain au blé complet nutritif.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.jpg",
  },
  {
    id: 92,
    name: "Petit Pain Complet",
    category: "Boulangerie",
    description: "Petit pain au blé complet sain et moelleux.",
    price: 2.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.jpg",
  },

  // HOT DRINKS
  {
    id: 93,
    name: "Thé Noir (Lipton)",
    category: "Boissons Chaudes",
    description: "Thé noir classique Lipton.",
    price: 12.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/Lipton.jpg",
  },
  {
    id: 94,
    name: "Chocolat Chaud",
    category: "Boissons Chaudes",
    description: "Lait chaud et réconfortant avec du chocolat riche.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/hot-chocolate.jpg",
  },
  {
    id: 95,
    name: "Lait Chaud",
    category: "Boissons Chaudes",
    description: "Lait cuit à la vapeur simple et réconfortant.",
    price: 12.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/hot-milk.webp",
  },
  {
    id: 96,
    name: "Verveine",
    category: "Boissons Chaudes",
    description:
      "Tisane faite avec des feuilles de verveine citronnée naturelles.",
    price: 12.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Lemon-Verbena-Tea.jpg",
  },
  {
    id: 97,
    name: "Thé au Lait (Lipton)",
    category: "Boissons Chaudes",
    description: "Thé noir classique Lipton infusé avec du lait.",
    price: 12.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Milk-Tea.jpg",
  },
  {
    id: 98,
    name: "Lait à la Verveine",
    category: "Boissons Chaudes",
    description: "Lait chaud infusé avec de la verveine citronnée apaisante.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-tea.jpg",
  },
  {
    id: 99,
    name: "Lait au Sirop",
    category: "Boissons Chaudes",
    description: "Lait froid ou chaud aromatisé avec du sirop sucré.",
    price: 11.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/Milk-Syrup.jpg",
  },
  {
    id: 100,
    name: "Thé à la Menthe Marocain",
    category: "Boissons Chaudes",
    description: "Thé vert traditionnel infusé avec de la menthe fraîche.",
    price: 11.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Moroccan-Tea.jpg",
  },

  // COLD DRINKS
  {
    id: 101,
    name: "Affogato",
    category: "Boissons Froides",
    description:
      "Une boule de glace à la vanille noyée dans un espresso chaud.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Affogato.jpg",
  },
  {
    id: 102,
    name: "Milkshake Banane",
    category: "Boissons Froides",
    description: "Milkshake à la banane doux et crémeux.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-shake.jpg",
  },
  {
    id: 103,
    name: "Smoothie Banane",
    category: "Boissons Froides",
    description: "Smoothie crémeux mixé à la banane.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Smoothie.jpg",
  },
  {
    id: 104,
    name: "Mojito Bleu",
    category: "Boissons Froides",
    description:
      "Mocktail aux agrumes et à la menthe avec sirop de curaçao bleu.",
    price: 22.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Mojito.jpg",
  },
  {
    id: 105,
    name: "Choix de Soda (35cl)",
    category: "Boissons Froides",
    description: "Sélection de boissons gazeuses rafraîchissantes.",
    price: 12.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/Soda.jpg",
  },
  {
    id: 106,
    name: "Milkshake Chocolat",
    category: "Boissons Froides",
    description: "Milkshake au chocolat riche et crémeux.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/milk-shake.jpg",
  },
  {
    id: 107,
    name: "Cocktail Exotique",
    category: "Boissons Froides",
    description: "Mangue, orange et ananas mixés.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Cocktail.jpg",
  },
  {
    id: 108,
    name: "Smoothie Exotique",
    category: "Boissons Froides",
    description: "Mélange rafraîchissant de fruits tropicaux.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Smoothie.jpg",
  },
  {
    id: 109,
    name: "Macchiato Glacé au Caramel",
    category: "Boissons Froides",
    description:
      "Lait et espresso glacés, aromatisés à la vanille et au caramel.",
    price: 21.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/iced-caramel.jpg",
  },
  {
    id: 110,
    name: "Café Glacé",
    category: "Boissons Froides",
    description: "Café refroidi sur des glaçons avec un choix de saveur.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/iced-coffee.jpg",
  },
  {
    id: 111,
    name: "Frappuccino Glacé",
    category: "Boissons Froides",
    description:
      "Boisson au café glacé mixée avec un choix de vanille, chocolat ou caramel.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-frappuccino.jpg",
  },
  {
    id: 112,
    name: "Latte Glacé",
    category: "Boissons Froides",
    description: "Espresso et lait refroidi sur des glaçons.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Iced-Latte.jpg",
  },
  {
    id: 113,
    name: "Moka Glacé",
    category: "Boissons Froides",
    description: "Espresso glacé avec du chocolat et du lait.",
    price: 19.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-mocha.jpg",
  },
  {
    id: 114,
    name: "Smoothie Mangue",
    category: "Boissons Froides",
    description: "Smoothie tropical à la mangue mixée.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/smoothie.jpg",
  },
  {
    id: 115,
    name: "Eau Minérale (33cl)",
    category: "Boissons Froides",
    description: "Petite bouteille d'eau minérale plate.",
    price: 5.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/Water.webp",
  },
  {
    id: 116,
    name: "Eau Minérale (50cl)",
    category: "Boissons Froides",
    description: "Bouteille moyenne d'eau minérale plate.",
    price: 7.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/Water.webp",
  },
  {
    id: 117,
    name: "Milkshake Oreo",
    category: "Boissons Froides",
    description: "Milkshake onctueux à la vanille mixé avec des biscuits Oreo.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/milk-shake.jpg",
  },
  {
    id: 118,
    name: "Cocktail Oriental",
    category: "Boissons Froides",
    description: "Banane, pomme et orange mixées.",
    price: 20.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cocktail.jpg",
  },
  {
    id: 119,
    name: "Mojito Rouge",
    category: "Boissons Froides",
    description:
      "Mocktail fruité aux fruits rouges avec menthe et citron vert.",
    price: 22.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Mojito.jpg",
  },
  {
    id: 120,
    name: "Milkshake Fraise",
    category: "Boissons Froides",
    description: "Milkshake doux et crémeux à la fraise.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/milk-shake.jpg",
  },
  {
    id: 121,
    name: "Smoothie Fraise",
    category: "Boissons Froides",
    description: "Fraises fraîches et yaourt mixés.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Smoothie.jpg",
  },
  {
    id: 122,
    name: "Cocktail Tropical",
    category: "Boissons Froides",
    description: "Mangue, kiwi et ananas mixés.",
    price: 21.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Cocktail.jpg",
  },
  {
    id: 123,
    name: "Milkshake Vanille",
    category: "Boissons Froides",
    description: "Milkshake classique crémeux à la vanille.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/milk-shake.jpg",
  },
  {
    id: 124,
    name: "Virgin Mojito",
    category: "Boissons Froides",
    description: "Mocktail rafraîchissant au citron vert et à la menthe.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Mojito.jpg",
  },

  // COFFEES
  {
    id: 125,
    name: "Americano",
    category: "Cafés",
    description: "Espresso dilué avec de l'eau chaude.",
    price: 14.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/Americano.jpg",
  },
  {
    id: 126,
    name: "Cappuccino",
    category: "Cafés",
    description:
      "Espresso surmonté de parts égales de lait cuit à la vapeur et de mousse.",
    price: 15.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Cappuccino.jpg",
  },
  {
    id: 127,
    name: "Café au Lait à Part",
    category: "Cafés",
    description: "Espresso servi avec un côté séparé de lait.",
    price: 15.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/coffee-milk.jpg",
  },
  {
    id: 128,
    name: "Cortado",
    category: "Cafés",
    description: "À parts égales d'espresso et de lait cuit à la vapeur.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Cortado.jpg",
  },
  {
    id: 129,
    name: "Café Crème",
    category: "Cafés",
    description: "Espresso mélangé avec de la crème cuite à la vapeur.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Cream-Coffee.jpg",
  },
  {
    id: 130,
    name: "Double Espresso",
    category: "Cafés",
    description: "Deux riches shots d'espresso intense.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/double-espresso.jpg",
  },
  {
    id: 131,
    name: "Espresso",
    category: "Cafés",
    description: "Shot de café riche et intense.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Espresso.jpg",
  },
  {
    id: 132,
    name: "Flat White",
    category: "Cafés",
    description: "Espresso avec du lait micro-moussé.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Flat-White.png",
  },
  {
    id: 133,
    name: "Espresso Illy",
    category: "Cafés",
    description: "Shot d'espresso italien premium Illy.",
    price: 16.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Illy-Espresso.jpg",
  },
  {
    id: 134,
    name: "Latte Macchiato",
    category: "Cafés",
    description: "Lait cuit à la vapeur marqué par un shot d'espresso.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Latte-Macchiato.jpg",
  },
  {
    id: 135,
    name: "Moka",
    category: "Cafés",
    description:
      "Espresso combiné avec du chocolat et du lait cuit à la vapeur.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/mocha.png",
  },
  {
    id: 136,
    name: "Café Nespresso",
    category: "Cafés",
    description: "Café infusé Nespresso classique.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Nespresso.jpg",
  },
  {
    id: 137,
    name: "Viennois au Chocolat",
    category: "Cafés",
    description: "Chocolat chaud garni de crème fouettée.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Viennese-Chocolate.jpg",
  },

  // JUICES
  {
    id: 138,
    name: "Jus de Pomme",
    category: "Jus",
    description: "Jus de pomme fraîchement pressé.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/Apple-Juice.jpg",
  },
  {
    id: 139,
    name: "Jus d'Avocat",
    category: "Jus",
    description: "Jus d'avocat mixé riche et crémeux.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Avocado-Juice.jpg",
  },
  {
    id: 140,
    name: "Jus d'Avocat aux Fruits Secs",
    category: "Jus",
    description: "Jus d'avocat crémeux mixé avec un mélange de fruits secs.",
    price: 23.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Avocado-Juice-with-Dried-Fruits.jpg",
  },
  {
    id: 141,
    name: "Jus de Banane",
    category: "Jus",
    description: "Jus de banane fraîchement mixé.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Banana-Juice.jpg",
  },
  {
    id: 142,
    name: "Jus de Mangue",
    category: "Jus",
    description: "Jus de mangue tropical frais.",
    price: 20.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Mango-Juice.jpg",
  },
  {
    id: 143,
    name: "Jus de Fruits Mixtes au Lait",
    category: "Jus",
    description: "Mélange de fruits mixtes avec du lait.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Mixed-Fruit-Juice-with-Milk.jpg",
  },
  {
    id: 144,
    name: "Jus de Fruits Mixtes à l'Orange",
    category: "Jus",
    description: "Mélange de fruits mixtes avec du jus d'orange.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Mixed-Fruit-Juice-with-Orange.jpg",
  },
  {
    id: 145,
    name: "Jus d'Orange",
    category: "Jus",
    description: "Jus d'orange fraîchement pressé.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Orange-Juice.jpg",
  },
  {
    id: 146,
    name: "Jus d'Ananas",
    category: "Jus",
    description: "Jus d'ananas frais et sucré.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/Pineapple-Juice.jpg",
  },
  {
    id: 147,
    name: "Jus de Fraise",
    category: "Jus",
    description: "Jus de fraise fraîchement mixé.",
    price: 18.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Strawberry-Juice.jpg",
  },

  // EXTRAS
  {
    id: 148,
    name: "Amlou aux Amandes",
    category: "Suppléments",
    description:
      "Amlou premium fait avec des amandes extra grillées. Servi avec du pain.",
    price: 12.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Almond.jpeg",
  },
  {
    id: 149,
    name: "Amlou à l'Huile d'Argan",
    category: "Suppléments",
    description:
      "Trempette traditionnelle aux amandes, miel et huile d'argan. Servie avec du pain.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/argan.jpg",
  },
  {
    id: 150,
    name: "Olives Noires et Vertes",
    category: "Suppléments",
    description: "Olives mixtes marinées. Servies avec du pain.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/olive.jpg",
  },
  {
    id: 151,
    name: "Fromage à Tartiner",
    category: "Suppléments",
    description: "Portion de fromage à tartiner. Servi avec du pain.",
    price: 3.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cheese.jpg",
  },
  {
    id: 152,
    name: "Fromage Frais (Jben)",
    category: "Suppléments",
    description:
      "Portion de fromage frais marocain traditionnel. Servi avec du pain.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Fresh-Cheese.jpg",
  },
  {
    id: 153,
    name: "Miel",
    category: "Suppléments",
    description: "Portion de pur miel. Servi avec du pain.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/Honey.jpg",
  },
  {
    id: 154,
    name: "Confiture",
    category: "Suppléments",
    description: "Portion de confiture de fruits. Servie avec du pain.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/Jam.jpg",
  },
  {
    id: 155,
    name: "Nutella",
    category: "Suppléments",
    description:
      "Portion de riche pâte à tartiner noisettes cacao. Servie avec du pain.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/Nutella.jpg",
  },
  {
    id: 156,
    name: "Huile d'Olive",
    category: "Suppléments",
    description:
      "Portion d'huile d'olive extra vierge de haute qualité. Servie avec du pain.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/Olive-Oil.jpg",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Ryu Zaki",
    role: "Client Régulier",
    quote:
      "Un charmant salon de thé servant de très bonnes pâtisseries et viennoiseries. Les jus de fruits sont excellents.",
    rating: 5,
  },
  {
    id: 2,
    name: "Halima Elmkiess",
    role: "Client Régulier",
    quote:
      "Un endroit génial où vous pouvez trouver tout ce que vous voulez. Le personnel est merveilleux 😊 Établissement très propre. La nourriture est absolument délicieuse. J'adore vraiment, vraiment ça. Merci beaucoup pour votre service ! ☺️",
    rating: 5,
  },
  {
    id: 3,
    name: "Soufiane Driver",
    role: "Client Régulier",
    quote:
      "Un endroit très calme avec un bon service et des gens sympathiques !",
    rating: 4,
  },
];

export const locations = [
  {
    id: 1,
    name: "La Madeleine — Tilila",
    address: "Av. Al Oulfa, Tilila, Agadir 80000",
    phone: "05.28.26.43.44",
    hours: "Lun–Dim 6h00–22h00",
    mapUrl: "https://maps.app.goo.gl/Z5memQUhJrBtShyx7",
  },
];

export const faqData = [
  {
    id: 1,
    category: "Général",
    question: "Quelles sont vos heures d'ouverture ?",
    answer: "Nous sommes ouverts du lundi au dimanche de 06h00 à 22h00.",
  },
  {
    id: 2,
    category: "Général",
    question: "Proposez-vous un service sur place ou seulement à emporter ?",
    answer:
      "Les deux ! Nous avons un bel espace pour s'asseoir avec des tables à l'intérieur et à l'extérieur. Dégustez vos pâtisseries fraîchement cuites et votre café dans notre espace chaleureux et accueillant.",
  },
  {
    id: 3,
    category: "Produits",
    question: "Vos produits sont-ils faits avec des ingrédients bio ?",
    answer:
      "Nous nous approvisionnons avec les meilleurs ingrédients disponibles. Bien que tout ne soit pas certifié bio, nous accordons la priorité à la qualité et à la durabilité.",
  },
  {
    id: 4,
    category: "Commandes",
    question: "Quels moyens de paiement acceptez-vous ?",
    answer: "Nous n'acceptons actuellement que les paiements en espèces.",
  },
  {
    id: 5,
    category: "Commandes",
    question: "Puis-je passer une commande pour la livraison ?",
    answer:
      "Pour le moment, nous ne proposons pas de livraison ni de commande en ligne. Pour passer une commande, appelez-nous directement ou visitez notre boulangerie, et notre équipe se fera un plaisir de vous aider.",
  },
  {
    id: 6,
    category: "Commandes",
    question:
      "Assurez-vous le service traiteur pour les événements et mariages ?",
    answer:
      "Nous serions ravis de faire partie de votre jour spécial ! Nous proposons des formules traiteur sur mesure pour les mariages, événements d'entreprise et fêtes privées. Contactez-nous au moins une semaine à l'avance pour les commandes personnalisées.",
  },
  {
    id: 7,
    category: "Général",
    question: "Y a-t-il un parking près de votre boulangerie ?",
    answer:
      "Un parking est disponible à proximité, et notre boulangerie est facilement accessible en transports en commun ou en voiture.",
  },
];
