export const siteConfig = {
  name: "LaMadeleine Agadir",
  tagline: "Boulangerie Artisanale & Salon de Café",
  description:
    "Pâtisseries faites à la main, pain artisanal et café exceptionnel — une expérience authentique de boulangerie française et marocaine depuis 2018.",
  phone: "05.28.26.43.44",
  email: "contact@lamadeleine.ma",
  address: "Av. Al Oulfa, Tilila, Agadir 80000",
  social: {
    instagram: "https://instagram.com/lamadeleine.agadir",
    facebook: "https://facebook.com/lamadeleine.agadir",
  },
  hours: [{ day: "Lundi — Dimanche", time: "6h00 — 22h00" }],
  science: 2018,
  mapLink: "https://maps.app.goo.gl/Z5memQUhJrBtShyx7",
};

type TodaysSpecial = {
  id: number;
  name: string;
  category: string;
  description: string;
  price: number;
  image: string;
};

export const todaysSpecials: TodaysSpecial[] = [
  {
    id: 1,
    name: "Pain au Chocolat",
    category: "Pâtisserie",
    description:
      "Couches beurrées et feuilletées enroulées autour de deux barres de chocolat noir de première qualité — la pâtisserie classique du petit-déjeuner français.",
    price: 2.5,
    image: "/images/today-specials/today-3.webp",
  },
  {
    id: 2,
    name: "Croissant au Beurre",
    category: "Petit-déjeuner",
    description:
      "Croissant doré et incroyablement léger, préparé avec 84 % de beurre normand. 72 heures de fermentation pour un feuilletage parfait.",
    price: 2.5,
    image: "/images/today-specials/today-1.webp",
  },
  {
    id: 3,
    name: "Croissant Sandwich",
    category: "Petit-déjeuner",
    description:
      "Une pâtisserie de petit-déjeuner français classique remplie d'une crème riche et beurrée et finie avec un léger saupoudrage de sucre glace.",
    price: 5,
    image: "/images/today-specials/today-2.webp",
  },
  {
    id: 4,
    name: "Tarte aux Fruits",
    category: "Dessert",
    description:
      "Fruits de saison disposés sur une crème pâtissière à la vanille, nichés dans un fond de tarte croustillant et caramélisé.",
    price: 7,
    image: "/images/today-specials/today-4.webp",
  },
  {
    id: 5,
    name: "Mille-Feuille aux Amandes",
    category: "Dessert",
    description:
      "Trois couches de pâte feuilletée caramélisée alternant avec une crème d'amande légère, garnies d'amandes effilées grillées et d'un saupoudrage de sucre glace.",
    price: 10,
    image: "/images/today-specials/today-5.webp",
  },
  {
    id: 6,
    name: "Cortado Signature MadLine",
    category: "Café",
    description:
      "À parts égales d'espresso intensément riche et de lait cuit à la vapeur parfaitement texturé, saupoudré d'un soupçon d'épices chaudes.",
    price: 12,
    image: "/images/today-specials/today-6.webp",
  },
];

export const coffeeMenu = [
  {
    id: 1,
    name: "Moka",
    description:
      "Espresso combiné avec du chocolat et du lait cuit à la vapeur.",
    price: 18.0,
    icon: "Cookie",
  },
  {
    id: 2,
    name: "Cappuccino",
    description:
      "Espresso surmonté de parts égales de lait cuit à la vapeur et de mousse.",
    price: 15.0,
    icon: "Milk",
  },
  {
    id: 3,
    name: "Café au Lait à Part",
    description: "Espresso servi avec un côté séparé de lait.",
    price: 15.0,
    icon: "Coffee",
  },
  {
    id: 4,
    name: "Cortado",
    description: "À parts égales d'espresso et de lait cuit à la vapeur.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 5,
    name: "Café Crème",
    description: "Espresso mélangé avec de la crème cuite à la vapeur.",
    price: 12.0,
    icon: "Cookie",
  },
  {
    id: 6,
    name: "Double Espresso",
    description: "Deux riches shots d'espresso intense.",
    price: 18.0,
    icon: "Droplets",
  },
  {
    id: 7,
    name: "Espresso",
    description: "Shot de café riche et intense.",
    price: 12.0,
    icon: "Coffee",
  },
  {
    id: 8,
    name: "Flat White",
    description: "Espresso avec du lait micro-moussé.",
    price: 16.0,
    icon: "Milk",
  },
  {
    id: 9,
    name: "Espresso Illy",
    description: "Shot d'espresso italien premium Illy.",
    price: 16.0,
    icon: "Sparkles",
  },
  {
    id: 10,
    name: "Americano",
    description: "Espresso dilué avec de l'eau chaude.",
    price: 14.0,
    icon: "Coffee",
  },
  {
    id: 11,
    name: "Latte Macchiato",
    description: "Lait cuit à la vapeur marqué par un shot d'espresso.",
    price: 16.0,
    icon: "Wine",
  },
  {
    id: 12,
    name: "Café Nespresso",
    description: "Café infusé Nespresso classique.",
    price: 15.0,
    icon: "Coffee",
  },
];

export const menuCategories = [
  "Petit-Déjeuner",
  "Pâtisserie",
  "Cafés",
  "Laits & Thés",
  "Boissons Fraîches",
];

export const menuItems = [
  {
    id: 1,
    name: "Petit-Déjeuner Express",
    category: "Petit-Déjeuner",
    description:
      "Hssoua, une boisson chaude, jus d'orange frais, panier de viennoiseries, yaourt et eau minérale.",
    price: 26.0,
    popular: false,
    image: "/images/menu/breakfast-express.webp",
  },
  {
    id: 2,
    name: "Petit-Déjeuner Beldi",
    category: "Petit-Déjeuner",
    description:
      "Hssoua, une boisson chaude, jus d'orange frais, msemen ou meloui, harcha, miel, jben et eau minérale.",
    price: 28.0,
    popular: true,
    image: "/images/menu/breakfast-beldi.webp",
  },
  {
    id: 3,
    name: "Petit-Déjeuner Continental",
    category: "Petit-Déjeuner",
    description:
      "Hssoua, une boisson chaude, jus d'orange frais, omelette au fromage, huile d'olive, olives, jben, corbeille de pain, eau minérale et yaourt.",
    price: 35.0,
    popular: false,
    image: "/images/menu/breakfast-continental.webp",
  },
  {
    id: 4,
    name: "Petit-Déjeuner Fassi",
    category: "Petit-Déjeuner",
    description:
      "Hssoua, une boisson chaude, jus d'orange frais, omelette au khliî, huile d'olive, olives, jben, corbeille de pain, eau minérale et yaourt.",
    price: 37.0,
    popular: false,
    image: "/images/menu/breakfast-fassi.webp",
  },
  {
    id: 5,
    name: "Petit-Déjeuner Soussi",
    category: "Petit-Déjeuner",
    description:
      "Hssoua, une boisson chaude, jus d'orange frais, amlou, huile d'olive, jben, olives noires et vertes, miel, confiture et eau minérale.",
    price: 38.0,
    popular: true,
    image: "/images/menu/breakfast-soussi.webp",
  },
  {
    id: 6,
    name: "Petit-Déjeuner Gourmand",
    category: "Petit-Déjeuner",
    description:
      "Hssoua, une boisson chaude, jus d'orange frais, huile d'olive, amlou, olives noires, miel, corbeille de pain, yaourt et eau minérale.",
    price: 26.0,
    popular: false,
    image: "/images/menu/breakfast-gourmand.webp",
  },
  {
    id: 7,
    name: "Petit-Déjeuner La Madeleine",
    category: "Petit-Déjeuner",
    description:
      "Notre formule signature : hssoua, une boisson chaude, jus d'orange frais, omelette (fromage / charcuterie / tomate), huile d'olive, olives, miel, jben, amlou, corbeille de pain, crêpe, pâte à tartiner chocolatée, gâteau américain, eau minérale et yaourt.",
    price: 55.0,
    popular: true,
    image: "/images/menu/breakfast-la-madeleine.webp",
  },
  {
    id: 8,
    name: "Petit-Déjeuner Enfant",
    category: "Petit-Déjeuner",
    description:
      "Lait au chocolat, jus d'orange frais, petit pain, gâteau à la vanille, eau minérale et yaourt.",
    price: 25.0,
    popular: false,
    image: "/images/menu/breakfast-kids.webp",
  },
  {
    id: 9,
    name: "Omelette Nature (2 œufs)",
    category: "Omelettes",
    description:
      "Simple omelette de deux œufs, servie avec olives et huile d'olive.",
    price: 13.0,
    popular: false,
    image: "/images/menu/omelet-nature.webp",
  },
  {
    id: 10,
    name: "Omelette Nature (4 œufs)",
    category: "Omelettes",
    description:
      "Généreuse omelette de quatre œufs, servie avec olives et huile d'olive.",
    price: 18.0,
    popular: false,
    image: "/images/menu/omelet-nature.webp",
  },
  {
    id: 11,
    name: "Omelette Tomate (2 œufs)",
    category: "Omelettes",
    description:
      "Omelette de deux œufs aux tomates fraîches, servie avec olives et huile d'olive.",
    price: 16.0,
    popular: false,
    image: "/images/menu/omelet-tomato.webp",
  },
  {
    id: 12,
    name: "Omelette Tomate (4 œufs)",
    category: "Omelettes",
    description:
      "Omelette de quatre œufs aux tomates fraîches, servie avec olives et huile d'olive.",
    price: 20.0,
    popular: false,
    image: "/images/menu/omelet-tomato.webp",
  },
  {
    id: 13,
    name: "Omelette Fromage (2 œufs)",
    category: "Omelettes",
    description:
      "Omelette moelleuse de deux œufs garnie de fromage fondu, servie avec olives et huile d'olive.",
    price: 16.0,
    popular: true,
    image: "/images/menu/omelet-cheese.webp",
  },
  {
    id: 14,
    name: "Omelette Fromage (4 œufs)",
    category: "Omelettes",
    description:
      "Omelette moelleuse de quatre œufs garnie de fromage fondu, servie avec olives et huile d'olive.",
    price: 22.0,
    popular: false,
    image: "/images/menu/omelet-cheese.webp",
  },
  {
    id: 15,
    name: "Omelette Khliî (2 œufs)",
    category: "Omelettes",
    description:
      "Omelette de deux œufs au khliî (viande séchée et épicée marocaine), servie avec olives et huile d'olive.",
    price: 18.0,
    popular: false,
    image: "/images/menu/omelet-khlii.webp",
  },
  {
    id: 16,
    name: "Omelette Khliî (4 œufs)",
    category: "Omelettes",
    description:
      "Omelette de quatre œufs au khliî (viande séchée et épicée marocaine), servie avec olives et huile d'olive.",
    price: 24.0,
    popular: false,
    image: "/images/menu/omelet-khlii.webp",
  },
  {
    id: 17,
    name: "Omelette Charcuterie (2 œufs)",
    category: "Omelettes",
    description:
      "Omelette de deux œufs à la charcuterie, servie avec olives et huile d'olive.",
    price: 17.0,
    popular: false,
    image: "/images/menu/omelet-charcuterie.webp",
  },
  {
    id: 18,
    name: "Omelette Charcuterie (4 œufs)",
    category: "Omelettes",
    description:
      "Omelette de quatre œufs à la charcuterie, servie avec olives et huile d'olive.",
    price: 23.0,
    popular: false,
    image: "/images/menu/omelet-charcuterie.webp",
  },
  {
    id: 19,
    name: "Amlou",
    category: "Suppléments",
    description:
      "Pâte à tartiner traditionnelle aux amandes, huile d'argan et miel, servie avec du pain.",
    price: 8.0,
    popular: false,
    image: "/images/menu/amlou.webp",
  },
  {
    id: 20,
    name: "Amlou aux Amandes",
    category: "Suppléments",
    description:
      "Pâte d'amlou garnie d'amandes entières supplémentaires, servie avec du pain.",
    price: 12.0,
    popular: false,
    image: "/images/menu/amlou-almonds.webp",
  },
  {
    id: 21,
    name: "Miel",
    category: "Suppléments",
    description: "Miel naturel, servi avec du pain.",
    price: 6.0,
    popular: false,
    image: "/images/menu/honey.webp",
  },
  {
    id: 22,
    name: "Confiture",
    category: "Suppléments",
    description: "Confiture de fruits, servie avec du pain.",
    price: 6.0,
    popular: false,
    image: "/images/menu/jam.webp",
  },
  {
    id: 23,
    name: "Jben (Fromage Frais)",
    category: "Suppléments",
    description: "Fromage frais traditionnel marocain, servi avec du pain.",
    price: 8.0,
    popular: false,
    image: "/images/menu/jben.webp",
  },
  {
    id: 24,
    name: "Fromage",
    category: "Suppléments",
    description: "Portion de fromage, servie avec du pain.",
    price: 3.0,
    popular: false,
    image: "/images/menu/cheese.webp",
  },
  {
    id: 25,
    name: "Huile d'Olive",
    category: "Suppléments",
    description: "Portion supplémentaire d'huile d'olive, servie avec du pain.",
    price: 8.0,
    popular: false,
    image: "/images/menu/olive-oil.webp",
  },
  {
    id: 26,
    name: "Olives Noires & Vertes",
    category: "Suppléments",
    description: "Mélange d'olives noires et vertes, servi avec du pain.",
    price: 5.0,
    popular: false,
    image: "/images/menu/olives.webp",
  },
  {
    id: 27,
    name: "Nutella",
    category: "Suppléments",
    description: "Généreuse portion de Nutella, servie avec du pain.",
    price: 10.0,
    popular: false,
    image: "/images/menu/nutella-side.webp",
  },

  // ---------- Soupes ----------
  {
    id: 28,
    name: "Soupe d'Orge (Hssoua)",
    category: "Soupes",
    description:
      "Soupe marocaine traditionnelle et réconfortante à l'orge et au lait.",
    price: 7.0,
    popular: false,
    image: "/images/menu/hesewa.webp",
  },
  {
    id: 29,
    name: "Harira",
    category: "Soupes",
    description:
      "Soupe traditionnelle marocaine consistante aux tomates, lentilles et pois chiches.",
    price: 10.0,
    popular: false,
    image: "/images/menu/soup.webp",
  },

  // ---------- Cafés ----------
  {
    id: 30,
    name: "Espresso",
    category: "Cafés",
    description: "Court espresso classique à l'italienne, riche en arômes.",
    price: 12.0,
    popular: false,
    image: "/images/menu/espresso.webp",
  },
  {
    id: 31,
    name: "Espresso illy",
    category: "Cafés",
    description:
      "Espresso de qualité supérieure préparé avec des grains de café illy.",
    price: 16.0,
    popular: false,
    image: "/images/menu/espresso-illy.webp",
  },
  {
    id: 32,
    name: "Café Crème",
    category: "Cafés",
    description: "Espresso surmonté d'une mousse de lait chaude et crémeuse.",
    price: 12.0,
    popular: false,
    image: "/images/menu/cafe-creme.webp",
  },
  {
    id: 33,
    name: "Café Nespresso",
    category: "Cafés",
    description: "Café doux préparé à partir de capsules Nespresso.",
    price: 15.0,
    popular: false,
    image: "/images/menu/cafe-nespresso.webp",
  },
  {
    id: 34,
    name: "Café Américain",
    category: "Cafés",
    description:
      "Espresso allongé à l'eau chaude pour une dégustation plus douce.",
    price: 14.0,
    popular: false,
    image: "/images/menu/cafe-americain.webp",
  },
  {
    id: 35,
    name: "Café Séparé",
    category: "Cafés",
    description:
      "Espresso servi séparément avec du lait chaud émulsionné à part.",
    price: 15.0,
    popular: false,
    image: "/images/menu/cafe-separe.webp",
  },
  {
    id: 36,
    name: "Double Espresso",
    category: "Cafés",
    description: "Double dose d'espresso bien corsé.",
    price: 18.0,
    popular: false,
    image: "/images/menu/double-espresso.webp",
  },
  {
    id: 37,
    name: "Cappuccino",
    category: "Cafés",
    description:
      "Espresso avec lait chaud et une épaisse couche de mousse de lait.",
    price: 15.0,
    popular: true,
    image: "/images/menu/cappuccino.webp",
  },
  {
    id: 38,
    name: "Morcha",
    category: "Cafés",
    description: "Café noir traditionnel marocain bien corsé et épicé.",
    price: 18.0,
    popular: false,
    image: "/images/menu/morcha.webp",
  },
  {
    id: 39,
    name: "Cortado",
    category: "Cafés",
    description: "Espresso coupé avec une petite touche de lait chaud.",
    price: 16.0,
    popular: false,
    image: "/images/menu/cortado.webp",
  },
  {
    id: 40,
    name: "Latte Macchiato",
    category: "Cafés",
    description: "Lait chaud délicatement marqué d'un shot d'espresso.",
    price: 16.0,
    popular: false,
    image: "/images/menu/latte-macchiato.webp",
  },
  {
    id: 41,
    name: "Flat White",
    category: "Cafés",
    description:
      "Espresso avec une fine couche de micromousse de lait veloutée.",
    price: 16.0,
    popular: false,
    image: "/images/menu/flat-white.webp",
  },
  {
    id: 42,
    name: "Chocolat Viennois",
    category: "Cafés",
    description:
      "Chocolat chaud onctueux garni d'une généreuse crème chantilly.",
    price: 16.0,
    popular: false,
    image: "/images/menu/chocolat-viennois.webp",
  },

  // ---------- Cafés Glacés ----------
  {
    id: 43,
    name: "Café Affogato",
    category: "Cafés Glacés",
    description:
      "Une boule de glace vanille « noyée » dans un shot d'espresso brûlant.",
    price: 18.0,
    popular: true,
    image: "/images/menu/affogato.webp",
  },
  {
    id: 44,
    name: "Mocha Glacé",
    category: "Cafés Glacés",
    description: "Espresso frappé mélangé avec du chocolat et du lait froid.",
    price: 19.0,
    popular: false,
    image: "/images/menu/iced-mocha.webp",
  },
  {
    id: 45,
    name: "Macchiato Caramel Glacé",
    category: "Cafés Glacés",
    description:
      "Lait frais et espresso étagés avec un nappage de caramel gourmand.",
    price: 21.0,
    popular: false,
    image: "/images/menu/iced-caramel-macchiato.webp",
  },
  {
    id: 46,
    name: "Frappuccino Glacé",
    category: "Cafés Glacés",
    description:
      "Boisson glacée au café mixé, disponible à la vanille, au chocolat ou au caramel.",
    price: 21.0,
    popular: true,
    image: "/images/menu/iced-frappuccino.webp",
  },
  {
    id: 47,
    name: "Café Glacé",
    category: "Cafés Glacés",
    description:
      "Café frais servi sur glaçons, disponible nature, vanille, chocolat, caramel ou noisette.",
    price: 18.0,
    popular: false,
    image: "/images/menu/iced-coffee.webp",
  },
  {
    id: 48,
    name: "Latte Glacé",
    category: "Cafés Glacés",
    description:
      "Espresso et lait froid sur glaçons, disponible nature, vanille, chocolat, caramel ou noisette.",
    price: 19.0,
    popular: false,
    image: "/images/menu/iced-latte.webp",
  },

  // ---------- Laits & Thés ----------
  {
    id: 49,
    name: "Lait au Chocolat",
    category: "Laits & Thés",
    description: "Lait chaud mélangé à du chocolat gourmand.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-chocolat.webp",
  },
  {
    id: 50,
    name: "Lait Chaud",
    category: "Laits & Thés",
    description: "Un simple verre de lait chaud bien doux.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-chaud.webp",
  },
  {
    id: 51,
    name: "Lait à la Verveine",
    category: "Laits & Thés",
    description: "Lait chaud infusé à la verveine parfumée.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-verveine.webp",
  },
  {
    id: 52,
    name: "Lait au Sirop",
    category: "Laits & Thés",
    description: "Lait chaud sucré au sirop parfumé.",
    price: 11.0,
    popular: false,
    image: "/images/menu/lait-sirop.webp",
  },
  {
    id: 53,
    name: "Lait Lipton",
    category: "Laits & Thés",
    description: "Lait chaud délicatement infusé au thé Lipton.",
    price: 12.0,
    popular: false,
    image: "/images/menu/lait-lipton.webp",
  },
  {
    id: 54,
    name: "Infusion Verveine",
    category: "Laits & Thés",
    description: "Infusion apaisante de feuilles naturelles de verveine.",
    price: 11.0,
    popular: false,
    image: "/images/menu/verveine-nature.webp",
  },
  {
    id: 55,
    name: "Thé Lipton",
    category: "Laits & Thés",
    description: "Thé noir classique Lipton.",
    price: 11.0,
    popular: false,
    image: "/images/menu/lipton-nature.webp",
  },
  {
    id: 56,
    name: "Thé Marocain à la Menthe",
    category: "Laits & Thés",
    description:
      "Thé vert traditionnel marocain sucré et parfumé à la menthe fraîche.",
    price: 11.0,
    popular: true,
    image: "/images/menu/the-marocain.webp",
  },

  // ---------- Gaufres, Crêpes & Pancakes ----------
  {
    id: 57,
    name: "Gaufre au Caramel",
    category: "Gaufres, Crêpes & Pancakes",
    description: "Gaufre dorée et croustillante nappée d'une sauce caramel.",
    price: 16.0,
    popular: false,
    image: "/images/menu/waffle-caramel.webp",
  },
  {
    id: 58,
    name: "Gaufre au Nutella",
    category: "Gaufres, Crêpes & Pancakes",
    description: "Gaufre dorée croustillante généreusement nappée de Nutella.",
    price: 19.0,
    popular: true,
    image: "/images/menu/waffle-nutella.webp",
  },
  {
    id: 59,
    name: "Gaufre Nutella Banane",
    category: "Gaufres, Crêpes & Pancakes",
    description:
      "Gaufre dorée garnie de Nutella et de rondelles de banane fraîche.",
    price: 22.0,
    popular: false,
    image: "/images/menu/waffle-nutella-banane.webp",
  },
  {
    id: 60,
    name: "Gaufre Nutella Fruits de Saison",
    category: "Gaufres, Crêpes & Pancakes",
    description:
      "Gaufre dorée surmontée de Nutella et de fruits frais de saison.",
    price: 27.0,
    popular: false,
    image: "/images/menu/waffle-nutella-fruits.webp",
  },
  {
    id: 61,
    name: "Crêpe au Caramel",
    category: "Gaufres, Crêpes & Pancakes",
    description: "Fine crêpe pliée avec une délicieuse sauce caramel.",
    price: 16.0,
    popular: false,
    image: "/images/menu/crepe-caramel.webp",
  },
  {
    id: 62,
    name: "Crêpe au Nutella",
    category: "Gaufres, Crêpes & Pancakes",
    description: "Fine crêpe généreusement fourrée au Nutella fondant.",
    price: 19.0,
    popular: true,
    image: "/images/menu/crepe-nutella.webp",
  },
  {
    id: 63,
    name: "Crêpe Nutella Banane",
    category: "Gaufres, Crêpes & Pancakes",
    description:
      "Fine crêpe garnie de Nutella et de tranches de banane fraîche.",
    price: 23.0,
    popular: false,
    image: "/images/menu/crepe-nutella-banane.webp",
  },
  {
    id: 64,
    name: "Crêpe Nutella Oreo",
    category: "Gaufres, Crêpes & Pancakes",
    description:
      "Fine crêpe fourrée au Nutella et aux éclats de biscuits Oreo.",
    price: 25.0,
    popular: false,
    image: "/images/menu/crepe-nutella-oreo.webp",
  },
  {
    id: 65,
    name: "Crêpe Nutella Fruits de Saison",
    category: "Gaufres, Crêpes & Pancakes",
    description: "Fine crêpe garnie de Nutella et de fruits frais de saison.",
    price: 29.0,
    popular: false,
    image: "/images/menu/crepe-nutella-fruits.webp",
  },
  {
    id: 66,
    name: "Pancakes au Miel",
    category: "Gaufres, Crêpes & Pancakes",
    description: "Pancakes moelleux et épais arrosés de miel naturel.",
    price: 16.0,
    popular: false,
    image: "/images/menu/pancakes-miel.webp",
  },
  {
    id: 67,
    name: "Pancakes à l'Amlou",
    category: "Gaufres, Crêpes & Pancakes",
    description: "Pancakes moelleux nappés d'amlou traditionnel marocain.",
    price: 17.0,
    popular: false,
    image: "/images/menu/pancakes-amlou.webp",
  },
  {
    id: 68,
    name: "Pancakes au Nutella",
    category: "Gaufres, Crêpes & Pancakes",
    description: "Pancakes moelleux et épais recouverts de Nutella.",
    price: 21.0,
    popular: false,
    image: "/images/menu/pancakes-nutella.webp",
  },
  {
    id: 69,
    name: "Pancakes Nutella Banane",
    category: "Gaufres, Crêpes & Pancakes",
    description:
      "Pancakes moelleux garnis de Nutella et de rondelles de banane.",
    price: 26.0,
    popular: false,
    image: "/images/menu/pancakes-nutella-banane.webp",
  },

  // ---------- Pâtisseries & Desserts -----------
  {
    id: 70,
    name: "Cigare aux Fruits de Mer",
    category: "Pâtisseries & Desserts",
    description:
      "Rouleau croustillant farci d'un savoureux mélange de fruits de mer.",
    price: 12.0,
    popular: false,
    image: "/images/menu/cigar.webp",
  },
  {
    id: 71,
    name: "Pastilla aux Fruits de Mer",
    category: "Pâtisseries & Desserts",
    description:
      "Tourte feuilletée salée garnie de fruits de mer assaisonnés et de vermicelle.",
    price: 12.0,
    popular: false,
    image: "/images/menu/pastilla.webp",
  },
  {
    id: 72,
    name: "Sandwich",
    category: "Pâtisseries & Desserts",
    description: "Sandwich salé fraîchement préparé.",
    price: 8.0,
    popular: false,
    image: "/images/menu/sandwich.webp",
  },
  {
    id: 73,
    name: "Mini Pizza",
    category: "Pâtisseries & Desserts",
    description:
      "Mini pizza individuelle garnie de fromage et de sauce tomate.",
    price: 6.0,
    popular: false,
    image: "/images/menu/pizza.webp",
  },
  {
    id: 74,
    name: "Feuilleté Hot-Dog",
    category: "Pâtisseries & Desserts",
    description:
      "Saucisse savoureuse enroulée et dorée dans une pâte moelleuse.",
    price: 9.0,
    popular: false,
    image: "/images/menu/hot-dog.webp",
  },
  {
    id: 75,
    name: "Pastilla au Poulet",
    category: "Pâtisseries & Desserts",
    description:
      "Tourte sucrée-salée croustillante garnie de poulet épicé et d'amandes grillées.",
    price: 10.0,
    popular: false,
    image: "/images/menu/pastilla.webp",
  },
  {
    id: 76,
    name: "Briouate au Fromage",
    category: "Pâtisseries & Desserts",
    description:
      "Triangles de pâte filo croustillants farcis au fromage savoureux.",
    price: 7.0,
    popular: false,
    image: "/images/menu/briouat.webp",
  },
  {
    id: 77,
    name: "Tartelette aux Amandes",
    category: "Pâtisseries & Desserts",
    description:
      "Pâte sablée croustillante garnie d'une crème d'amandes onctueuse.",
    price: 10.0,
    popular: false,
    image: "/images/menu/tart.webp",
  },
  {
    id: 78,
    name: "Chausson aux Pommes",
    category: "Pâtisseries & Desserts",
    description:
      "Pâte feuilletée croustillante garnie d'une douce compote de pommes épicée.",
    price: 6.0,
    popular: false,
    image: "/images/menu/apple-turnover.webp",
  },
  {
    id: 79,
    name: "Basboussa au Chocolat",
    category: "Pâtisseries & Desserts",
    description:
      "Gâteau de semoule moelleux délicatement parfumé au chocolat riche.",
    price: 8.0,
    popular: false,
    image: "/images/menu/basbousa.webp",
  },
  {
    id: 80,
    name: "Madeleine au Chocolat",
    category: "Pâtisseries & Desserts",
    description:
      "Petite madeleine pur beurre traditionnelle au bon goût de chocolat.",
    price: 2.5,
    popular: false,
    image: "/images/menu/madeleine.webp",
  },
  {
    id: 81,
    name: "Donut",
    category: "Pâtisseries & Desserts",
    description: "Beignet sucré classique, tendre et moelleux.",
    price: 4.0,
    popular: false,
    image: "/images/menu/donut.webp",
  },
  {
    id: 82,
    name: "Tarte Frangipane",
    category: "Pâtisseries & Desserts",
    description:
      "Tarte pâtissière douce fourrée d'une généreuse crème frangipane.",
    price: 8.0,
    popular: false,
    image: "/images/menu/frangipane-tart.webp",
  },
  {
    id: 83,
    name: "Pithiviers aux Fruits",
    category: "Pâtisseries & Desserts",
    description:
      "Pâtisserie feuilletée garnie d'une délicieuse compotée de fruits.",
    price: 6.0,
    popular: false,
    image: "/images/menu/pithiviers.webp",
  },
  {
    id: 84,
    name: "Tartelette aux Fruits",
    category: "Pâtisseries & Desserts",
    description:
      "Fond de tarte croustillant garni de crème pâtissière et de fruits frais.",
    price: 7.0,
    popular: false,
    image: "/images/menu/fruit-tartlet.webp",
  },
  {
    id: 85,
    name: "Basboussa à la Vanille",
    category: "Pâtisseries & Desserts",
    description:
      "Gâteau traditionnel de semoule imbibé de sirop aromatisé à la vanille.",
    price: 6.0,
    popular: false,
    image: "/images/menu/basbousa.webp",
  },
  {
    id: 86,
    name: "Madeleine à la Vanille",
    category: "Pâtisseries & Desserts",
    description:
      "Véritable madeleine pur beurre française délicatement parfumée à la vanille.",
    price: 1.5,
    popular: false,
    image: "/images/menu/madeleine.webp",
  },
  {
    id: 87,
    name: "Croissant aux Amandes",
    category: "Pâtisseries & Desserts",
    description:
      "Croissant feuilleté garni de crème d'amandes et parsemé d'amandes effilées.",
    price: 5.0,
    popular: false,
    image: "/images/menu/croissant.webp",
  },
  {
    id: 88,
    name: "Triangle aux Amandes",
    category: "Pâtisseries & Desserts",
    description:
      "Pâtisserie feuilletée triangulaire garnie d'une douce pâte d'amandes.",
    price: 6.0,
    popular: false,
    image: "/images/menu/triangle.webp",
  },
  {
    id: 89,
    name: "Danoise au Chocolat",
    category: "Pâtisseries & Desserts",
    description:
      "Viennoiserie danoise feuilletée marbrée d'un chocolat onctueux.",
    price: 4.0,
    popular: false,
    image: "/images/menu/danish.webp",
  },
  {
    id: 90,
    name: "Viennoiserie Danoise",
    category: "Pâtisseries & Desserts",
    description:
      "Pâtisserie feuilletée danoise traditionnelle, croustillante et pur beurre.",
    price: 3.5,
    popular: false,
    image: "/images/menu/danish.webp",
  },
  {
    id: 91,
    name: "Harcha",
    category: "Pâtisseries & Desserts",
    description:
      "Galette traditionnelle marocaine de semoule cuite à la poêle.",
    price: 2.5,
    popular: false,
    image: "/images/menu/harcha.webp",
  },
  {
    id: 92,
    name: "Msemen",
    category: "Pâtisseries & Desserts",
    description:
      "Crêpe feuilletée carrée traditionnelle marocaine, croustillante et moelleuse.",
    price: 4.0,
    popular: false,
    image: "/images/menu/msemmen.webp",
  },
  {
    id: 93,
    name: "Harcha à l'Huile d'Olive",
    category: "Pâtisseries & Desserts",
    description:
      "Galette de semoule savoureuse préparée à l'huile d'olive authentique.",
    price: 3.5,
    popular: false,
    image: "/images/menu/oil-harcha.webp",
  },
  {
    id: 94,
    name: "Pain Suisse",
    category: "Pâtisseries & Desserts",
    description:
      "Viennoiserie feuilletée garnie de crème pâtissière à la vanille et pépites de chocolat.",
    price: 3.0,
    popular: false,
    image: "/images/menu/pain-suisse.webp",
  },
  {
    id: 95,
    name: "Pain au Chocolat / Croissant",
    category: "Pâtisseries & Desserts",
    description:
      "Viennoiseries françaises classiques, pur beurre et croustillantes.",
    price: 2.5,
    popular: false,
    image: "/images/menu/pain-au-chocolat.webp",
  },
  {
    id: 96,
    name: "Pithiviers",
    category: "Pâtisseries & Desserts",
    description: "Tourte feuilletée ronde dorée avec une garniture gourmande.",
    price: 5.0,
    popular: false,
    image: "/images/menu/pithiviers.webp",
  },
  {
    id: 97,
    name: "Mini Cake Framboise",
    category: "Pâtisseries & Desserts",
    description:
      "Gâteau individuel moelleux infusé aux saveurs douces de framboise.",
    price: 8.0,
    popular: false,
    image: "/images/menu/minicake.webp",
  },
  {
    id: 98,
    name: "Mille-Feuille",
    category: "Pâtisseries & Desserts",
    description:
      "Grand classique de la pâtisserie française : fines couches feuilletées et crème vanille.",
    price: 8.0,
    popular: false,
    image: "/images/menu/millefeuille.webp",
  },
  {
    id: 99,
    name: "Mini Cake",
    category: "Pâtisseries & Desserts",
    description: "Petit gâteau individuel moelleux et savoureux.",
    price: 7.0,
    popular: false,
    image: "/images/menu/minicake.webp",
  },
  {
    id: 100,
    name: "Mini Cupcake",
    category: "Pâtisseries & Desserts",
    description: "Bouchée de gâteau aéré surmontée d'un glaçage gourmand.",
    price: 4.0,
    popular: false,
    image: "/images/menu/cupcake.webp",
  },

  // ---------- Smoothies & Milkshakes ----------
  {
    id: 101,
    name: "Smoothie Fraise",
    category: "Smoothies & Milkshakes",
    description: "Fraises fraîches mixées en une boisson douce et fruitée.",
    price: 23.0,
    popular: false,
    image: "/images/menu/smoothie-fraise.webp",
  },
  {
    id: 102,
    name: "Smoothie Banane",
    category: "Smoothies & Milkshakes",
    description: "Smoothie onctueux préparé avec des bananes bien mûres.",
    price: 23.0,
    popular: false,
    image: "/images/menu/smoothie-banane.webp",
  },
  {
    id: 103,
    name: "Smoothie Mangue",
    category: "Smoothies & Milkshakes",
    description: "Smoothie tropical onctueux à la mangue fraîche.",
    price: 23.0,
    popular: false,
    image: "/images/menu/smoothie-mangue.webp",
  },
  {
    id: 104,
    name: "Smoothie Exotique",
    category: "Smoothies & Milkshakes",
    description:
      "Un assortiment de fruits exotiques pour un smoothie tropical rafraîchissant.",
    price: 26.0,
    popular: false,
    image: "/images/menu/smoothie-exotique.webp",
  },
  {
    id: 105,
    name: "Milkshake Chocolat",
    category: "Smoothies & Milkshakes",
    description: "Milkshake épais et très crémeux au chocolat gourmand.",
    price: 23.0,
    popular: true,
    image: "/images/menu/milkshake-choco.webp",
  },
  {
    id: 106,
    name: "Milkshake Vanille",
    category: "Smoothies & Milkshakes",
    description: "Milkshake onctueux et richement parfumé à la vanille.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milkshake-vanille.webp",
  },
  {
    id: 107,
    name: "Milkshake Banane",
    category: "Smoothies & Milkshakes",
    description: "Milkshake gourmand et onctueux à la banane fraîche.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milkshake-banane.webp",
  },
  {
    id: 108,
    name: "Milkshake Fraise",
    category: "Smoothies & Milkshakes",
    description: "Milkshake velouté et savoureux aux fraises.",
    price: 23.0,
    popular: false,
    image: "/images/menu/milkshake-fraise.webp",
  },
  {
    id: 109,
    name: "Milkshake Oreo",
    category: "Smoothies & Milkshakes",
    description: "Milkshake crémeux mixé avec des brisures de biscuits Oreo.",
    price: 26.0,
    popular: true,
    image: "/images/menu/milkshake-oreo.webp",
  },

  // ---------- Mojitos ----------
  {
    id: 110,
    name: "Virgin Mojito",
    category: "Mojitos",
    description:
      "Mojito sans alcool ultra-rafraîchissant au citron vert et à la menthe.",
    price: 19.0,
    popular: false,
    image: "/images/menu/mojito-virgin.webp",
  },
  {
    id: 111,
    name: "Mojito Bleu",
    category: "Mojitos",
    description:
      "Mojito rafraîchissant aux teintes bleues avec citron vert et menthe.",
    price: 22.0,
    popular: false,
    image: "/images/menu/mojito-blue.webp",
  },
  {
    id: 112,
    name: "Mojito Rose",
    category: "Mojitos",
    description:
      "Mojito rafraîchissant subtilement aromatisé à la rose, citron vert et menthe.",
    price: 22.0,
    popular: false,
    image: "/images/menu/mojito-roso.webp",
  },

  // ---------- Jus Frais ----------
  {
    id: 113,
    name: "Jus d'Orange",
    category: "Jus Frais",
    description: "Jus d'oranges fraîches pressées à la commande.",
    price: 16.0,
    popular: true,
    image: "/images/menu/jus-orange.webp",
  },
  {
    id: 114,
    name: "Jus de Banane",
    category: "Jus Frais",
    description: "Jus onctueux préparé avec des bananes fraîches.",
    price: 16.0,
    popular: false,
    image: "/images/menu/jus-banane.webp",
  },
  {
    id: 115,
    name: "Jus de Pomme",
    category: "Jus Frais",
    description: "Pur jus de pommes fraîches pressées.",
    price: 16.0,
    popular: false,
    image: "/images/menu/jus-pomme.webp",
  },
  {
    id: 116,
    name: "Jus d'Avocat",
    category: "Jus Frais",
    description: "Jus onctueux et crémeux à l'avocat frais.",
    price: 18.0,
    popular: false,
    image: "/images/menu/jus-avocat.webp",
  },
  {
    id: 117,
    name: "Jus de Fraise",
    category: "Jus Frais",
    description: "Jus velouté aux fraises fraîches mixées.",
    price: 18.0,
    popular: false,
    image: "/images/menu/jus-fraise.webp",
  },
  {
    id: 118,
    name: "Jus de Mangue",
    category: "Jus Frais",
    description: "Jus doux et généreux à la mangue fraîche.",
    price: 20.0,
    popular: false,
    image: "/images/menu/jus-mangue.webp",
  },
  {
    id: 119,
    name: "Jus d'Ananas",
    category: "Jus Frais",
    description: "Jus vitaminé d'ananas frais mixé.",
    price: 23.0,
    popular: false,
    image: "/images/menu/jus-ananas.webp",
  },
  {
    id: 120,
    name: "Jus Panaché au Lait",
    category: "Jus Frais",
    description: "Mélange gourmand de fruits frais mixés avec du lait.",
    price: 18.0,
    popular: false,
    image: "/images/menu/jus-panache-lait.webp",
  },
  {
    id: 121,
    name: "Jus Panaché à l'Orange",
    category: "Jus Frais",
    description: "Mélange de fruits frais mixés avec du jus d'orange pressé.",
    price: 23.0,
    popular: false,
    image: "/images/menu/jus-panache-orange.webp",
  },
  {
    id: 122,
    name: "Jus d'Avocat aux Fruits Secs",
    category: "Jus Frais",
    description:
      "Jus onctueux d'avocat garni d'un délicieux mélange de fruits secs.",
    price: 23.0,
    popular: false,
    image: "/images/menu/jus-avocat-fruits-secs.webp",
  },

  // ---------- Cocktails & Salades de Fruits ----------
  {
    id: 123,
    name: "Salade de Fruits au Yaourt",
    category: "Cocktails & Salades de Fruits",
    description:
      "Assortiment de fruits frais découpés servis sur un lit de yaourt.",
    price: 18.0,
    popular: false,
    image: "/images/menu/salade-fruits-yaourt.webp",
  },
  {
    id: 124,
    name: "Salade de Fruits à l'Orange",
    category: "Cocktails & Salades de Fruits",
    description:
      "Assortiment de fruits frais servi dans un jus d'orange pressé.",
    price: 19.0,
    popular: false,
    image: "/images/menu/salade-fruits-orange.webp",
  },
  {
    id: 125,
    name: "Cocktail Tropical",
    category: "Cocktails & Salades de Fruits",
    description: "Un délicieux cocktail associant mangue, kiwi et ananas.",
    price: 21.0,
    popular: false,
    image: "/images/menu/cocktail-tropical.webp",
  },
  {
    id: 126,
    name: "Cocktail Oriental",
    category: "Cocktails & Salades de Fruits",
    description: "Un mélange classique et doux de banane, pomme et orange.",
    price: 20.0,
    popular: false,
    image: "/images/menu/cocktail-oriental.webp",
  },
  {
    id: 127,
    name: "Cocktail Exotique",
    category: "Cocktails & Salades de Fruits",
    description:
      "Un cocktail rafraîchissant combinant mangue, orange et ananas.",
    price: 21.0,
    popular: false,
    image: "/images/menu/cocktail-exotique.webp",
  },

  // ---------- Boissons Gazeuses & Eaux ----------
  {
    id: 128,
    name: "Soda (33cl)",
    category: "Boissons Gazeuses & Eaux",
    description: "Choix de boisson gazeuse fraîche, canette 33cl.",
    price: 12.0,
    popular: false,
    image: "/images/menu/soda.webp",
  },
  {
    id: 129,
    name: "Eau Minérale (33cl)",
    category: "Boissons Gazeuses & Eaux",
    description: "Petite bouteille d'eau minérale plate ou gazeuse.",
    price: 5.0,
    popular: false,
    image: "/images/menu/eau-minerale-33.webp",
  },
  {
    id: 130,
    name: "Eau Minérale (50cl)",
    category: "Boissons Gazeuses & Eaux",
    description: "Moyenne bouteille d'eau minérale plate ou gazeuse.",
    price: 7.0,
    popular: false,
    image: "/images/menu/eau-minerale-50.webp",
  },
];

export const shopProducts = [
  // BREAKFAST & SAVORY
  {
    id: 1,
    name: "Soupe d'Orge (Hssoua)",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe traditionnelle marocaine à l'orge et au lait, chaude et réconfortante.",
    price: 7.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/hesewa.webp",
  },
  {
    id: 2,
    name: "Omelette au Fromage",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette moelleuse garnie de fromage fondu, servie avec des olives et de l'huile d'olive.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 3,
    name: "Petit-déjeuner Continental",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, omelette au fromage, huile d'olive, olives, fromage, pain, yaourt et eau.",
    price: 35.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 4,
    name: "Omelette à la Charcuterie",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette garnie de charcuterie, servie avec des olives et de l'huile d'olive.",
    price: 17.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 5,
    name: "Petit-déjeuner Express",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, viennoiseries, yaourt et eau minérale.",
    price: 26.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 6,
    name: "Petit-déjeuner Fassi",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, omelette à la viande séchée, huile d'olive, olives, fromage, pain, yaourt et eau.",
    price: 37.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 7,
    name: "Petit-déjeuner Gourmand",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, huile d'olive, Amlou, olives, miel, pain, yaourt et eau.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 8,
    name: "Soupe Harira",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe marocaine traditionnelle consistante aux tomates, lentilles et pois chiches.",
    price: 10.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/soup.webp",
  },
  {
    id: 9,
    name: "Omelette au Khlii",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette traditionnelle avec de la viande confite marocaine, servie avec des olives et de l'huile d'olive.",
    price: 24.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 10,
    name: "Petit-déjeuner Enfant",
    category: "Petit-déjeuner et Salé",
    description:
      "Lait au chocolat, jus d'orange, pain au chocolat, gâteau à la vanille, yaourt et eau.",
    price: 25.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 11,
    name: "Petit-déjeuner La Madeleine",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, choix d'omelette, huile d'olive, olives, miel, fromage, Amlou, pain, crêpe, chocolat, gâteau, yaourt et eau.",
    price: 55.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 12,
    name: "Omelette Nature",
    category: "Petit-déjeuner et Salé",
    description:
      "Simple omelette moelleuse servie avec des olives et de l'huile d'olive.",
    price: 13.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 13,
    name: "Petit-déjeuner Soussi",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, Amlou, huile d'olive, fromage, olives, miel, confiture et eau.",
    price: 38.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/breakfast.webp",
  },
  {
    id: 14,
    name: "Omelette aux Tomates",
    category: "Petit-déjeuner et Salé",
    description:
      "Omelette moelleuse aux tomates fraîches, servie avec des olives et de l'huile d'olive.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/omelet.webp",
  },
  {
    id: 15,
    name: "Petit-déjeuner Traditionnel",
    category: "Petit-déjeuner et Salé",
    description:
      "Soupe d'orge, boisson chaude, jus d'orange, crêpes marocaines (Baghrir), Harcha, miel, fromage frais et eau.",
    price: 28.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/breakfast.webp",
  },

  // PASTRIES & DESSERTS
  {
    id: 16,
    name: "Cigare aux Fruits de Mer",
    category: "Pâtisseries et Desserts",
    description:
      "Pâte croustillante roulée et remplie d'un mélange salé de fruits de mer.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/cigar.webp",
  },
  {
    id: 17,
    name: "Pastilla aux Fruits de Mer",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte salée feuilletée garnie de fruits de mer assaisonnés et de vermicelles.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pastilla.webp",
  },
  {
    id: 18,
    name: "Sandwich",
    category: "Pâtisseries et Desserts",
    description: "Sandwich salé fraîchement préparé.",
    price: 8.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/sandwich.webp",
  },
  {
    id: 19,
    name: "Mini Pizza",
    category: "Pâtisseries et Desserts",
    description:
      "Pizza salée de format individuel garnie de fromage et de sauce tomate.",
    price: 6.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/pizza.webp",
  },
  {
    id: 20,
    name: "Friand à la Saucisse",
    category: "Pâtisseries et Desserts",
    description: "Saucisse salée enveloppée et cuite dans une pâte moelleuse.",
    price: 9.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/hot-dog.webp",
  },
  {
    id: 21,
    name: "Pastilla au Poulet",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte sucrée-salée garnie de poulet épicé et d'amandes grillées.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pastilla.webp",
  },
  {
    id: 22,
    name: "Briouate au Fromage",
    category: "Pâtisseries et Desserts",
    description:
      "Triangles de pâte marocaine croustillante farcis de fromage salé.",
    price: 7.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/briouat.webp",
  },
  {
    id: 23,
    name: "Tarte aux Amandes",
    category: "Pâtisseries et Desserts",
    description:
      "Fond de tarte sucré et croustillant garni d'une crème d'amande dense.",
    price: 10.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/tart.webp",
  },
  {
    id: 24,
    name: "Pancakes à l'Amlou",
    category: "Pâtisseries et Desserts",
    description: "Pancakes moelleux garnis d'Amlou traditionnel marocain.",
    price: 17.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 25,
    name: "Chausson aux Pommes",
    category: "Pâtisseries et Desserts",
    description:
      "Pâte feuilletée remplie d'une compote de pommes douce et épicée.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/apple-turnover.webp",
  },
  {
    id: 26,
    name: "Crêpe au Caramel",
    category: "Pâtisseries et Desserts",
    description: "Fine crêpe française pliée avec du caramel sucré.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 27,
    name: "Gaufre au Caramel",
    category: "Pâtisseries et Desserts",
    description: "Gaufre dorée nappée d'une riche sauce au caramel.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 28,
    name: "Basboussa au Chocolat",
    category: "Pâtisseries et Desserts",
    description: "Gâteau de semoule sucré aromatisé au chocolat riche.",
    price: 8.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.webp",
  },
  {
    id: 29,
    name: "Madeleine au Chocolat",
    category: "Pâtisseries et Desserts",
    description:
      "Petit gâteau éponge en forme de coquille, aromatisé au chocolat.",
    price: 2.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.webp",
  },
  {
    id: 30,
    name: "Crêpe Classique",
    category: "Pâtisseries et Desserts",
    description: "Crêpe française simple, fine et moelleuse.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 31,
    name: "Part de Gâteau à la Crème (10)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 10.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 32,
    name: "Part de Gâteau à la Crème (12)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 33,
    name: "Part de Gâteau à la Crème (13)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 13.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 34,
    name: "Part de Gâteau à la Crème (14)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 14.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 35,
    name: "Part de Gâteau à la Crème (15)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 36,
    name: "Part de Gâteau à la Crème (17)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 17.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 37,
    name: "Part de Gâteau à la Crème (18)",
    category: "Pâtisseries et Desserts",
    description: "Délicieuse part de gâteau à étages fourré à la crème.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/cream-cake-slice.webp",
  },
  {
    id: 38,
    name: "Beignet",
    category: "Pâtisseries et Desserts",
    description: "Anneau de pâte frite moelleux, sucré et classique.",
    price: 4.0,
    inStock: true,
    rating: 4.1,
    image: "/images/shop/donut.webp",
  },
  {
    id: 39,
    name: "Tarte Frangipane",
    category: "Pâtisseries et Desserts",
    description: "Tartelette en pâte sucrée garnie de riche crème d'amande.",
    price: 8.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/frangipane-tart.webp",
  },
  {
    id: 40,
    name: "Pithiviers aux Fruits",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte en pâte feuilletée garnie de compote de fruits sucrée.",
    price: 6.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pithiviers.webp",
  },
  {
    id: 41,
    name: "Salade de Fruits au Jus d'Orange",
    category: "Pâtisseries et Desserts",
    description: "Fruits frais de saison macérés dans du jus d'orange frais.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/fruit-salad.webp",
  },
  {
    id: 42,
    name: "Salade de Fruits au Yaourt",
    category: "Pâtisseries et Desserts",
    description: "Fruits frais de saison mélangés avec du yaourt crémeux.",
    price: 18.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/fruit-salad.webp",
  },
  {
    id: 43,
    name: "Tartelette aux Fruits",
    category: "Pâtisseries et Desserts",
    description:
      "Petite croûte de tarte sucrée garnie de crème anglaise et de fruits frais.",
    price: 7.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/fruit-tartlet.webp",
  },
  {
    id: 44,
    name: "Pancakes au Miel",
    category: "Pâtisseries et Desserts",
    description: "Pancakes moelleux arrosés de pur miel.",
    price: 16.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 45,
    name: "Grand Quatre-quarts",
    category: "Pâtisseries et Desserts",
    description: "Quatre-quarts généreux, beurré et moelleux.",
    price: 30.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 46,
    name: "Quatre-quarts Moyen",
    category: "Pâtisseries et Desserts",
    description: "Quatre-quarts classique, moelleux et sucré.",
    price: 20.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 47,
    name: "Mille-Feuille",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie française classique avec des couches de pâte feuilletée et de crème vanille.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/millefeuille.webp",
  },
  {
    id: 48,
    name: "Mini Gâteau",
    category: "Pâtisseries et Desserts",
    description: "Petit gâteau personnel, moelleux et sucré.",
    price: 7.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/minicake.webp",
  },
  {
    id: 49,
    name: "Mini Cupcake",
    category: "Pâtisseries et Desserts",
    description: "Gâteau moelleux en format bouchée avec glaçage sucré.",
    price: 4.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cupcake.webp",
  },
  {
    id: 50,
    name: "Crêpe Nutella & Banane",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fourrée au Nutella et aux bananes tranchées.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 51,
    name: "Pancakes Nutella & Banane",
    category: "Pâtisseries et Desserts",
    description: "Pancakes servis avec du Nutella et des bananes fraîches.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 52,
    name: "Gaufre Nutella & Banane",
    category: "Pâtisseries et Desserts",
    description: "Gaufre garnie de Nutella et de tranches de banane fraîche.",
    price: 22.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 53,
    name: "Crêpe Nutella & Oreo",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fourrée au Nutella et aux biscuits Oreo concassés.",
    price: 25.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 54,
    name: "Crêpe Nutella & Fruits de Saison",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fourrée au Nutella et aux fruits de saison frais.",
    price: 29.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 55,
    name: "Gaufre Nutella & Fruits de Saison",
    category: "Pâtisseries et Desserts",
    description: "Gaufre au Nutella et aux fruits de saison frais.",
    price: 27.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 56,
    name: "Crêpe au Nutella",
    category: "Pâtisseries et Desserts",
    description: "Crêpe fine classique fourrée au Nutella chaud.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/crepe.webp",
  },
  {
    id: 57,
    name: "Pancakes au Nutella",
    category: "Pâtisseries et Desserts",
    description: "Pile de pancakes moelleux étagés avec du Nutella.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/pancakes.webp",
  },
  {
    id: 58,
    name: "Gaufre au Nutella",
    category: "Pâtisseries et Desserts",
    description: "Gaufre dorée généreusement garnie de Nutella.",
    price: 19.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/waffle.webp",
  },
  {
    id: 59,
    name: "Pithiviers",
    category: "Pâtisseries et Desserts",
    description:
      "Tourte ronde fermée en pâte feuilletée avec une garniture sucrée.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pithiviers.webp",
  },
  {
    id: 60,
    name: "Mini Gâteau à la Framboise",
    category: "Pâtisseries et Desserts",
    description: "Petit gâteau infusé avec une douce saveur de framboise.",
    price: 8.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/minicake.webp",
  },
  {
    id: 61,
    name: "Petit Quatre-quarts",
    category: "Pâtisseries et Desserts",
    description: "Tranche de quatre-quarts moelleux au format individuel.",
    price: 15.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/pound-cake.webp",
  },
  {
    id: 62,
    name: "Basboussa à la Vanille",
    category: "Pâtisseries et Desserts",
    description:
      "Gâteau de semoule sucré classique imbibé de sirop à la vanille.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/basbousa.webp",
  },
  {
    id: 63,
    name: "Madeleine à la Vanille",
    category: "Pâtisseries et Desserts",
    description:
      "Gâteau éponge français classique, beurré et en forme de coquille.",
    price: 1.5,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/madeleine.webp",
  },
  {
    id: 64,
    name: "Croissant aux Amandes",
    category: "Pâtisseries et Desserts",
    description:
      "Croissant feuilleté garni de crème d'amande et surmonté d'amandes effilées.",
    price: 5.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/croissant.webp",
  },
  {
    id: 65,
    name: "Triangle aux Amandes",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie feuilletée en forme de triangle garnie de pâte d'amande sucrée.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/triangle.webp",
  },
  {
    id: 66,
    name: "Danoise au Chocolat",
    category: "Pâtisseries et Desserts",
    description: "Pâtisserie danoise feuilletée marbrée de chocolat riche.",
    price: 4.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/danish.webp",
  },
  {
    id: 67,
    name: "Pâtisserie Danoise",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie danoise traditionnelle feuilletée, beurrée et sucrée.",
    price: 3.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/danish.webp",
  },
  {
    id: 68,
    name: "Harcha",
    category: "Pâtisseries et Desserts",
    description:
      "Pain plat marocain traditionnel à la semoule cuit à la poêle.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/harcha.webp",
  },
  {
    id: 69,
    name: "Msemmen",
    category: "Pâtisseries et Desserts",
    description: "Pain plat carré marocain traditionnel, feuilleté et étagé.",
    price: 4.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/msemmen.webp",
  },
  {
    id: 70,
    name: "Harcha à l'Huile d'Olive",
    category: "Pâtisseries et Desserts",
    description:
      "Pain plat salé à la semoule préparé avec de la riche huile d'olive.",
    price: 3.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/oil-harcha.webp",
  },
  {
    id: 71,
    name: "Pain Suisse",
    category: "Pâtisseries et Desserts",
    description:
      "Pâte feuilletée roulée avec de la crème pâtissière à la vanille et des pépites de chocolat.",
    price: 3.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/pain-suisse.webp",
  },
  {
    id: 72,
    name: "Pain au Chocolat / Croissant",
    category: "Pâtisseries et Desserts",
    description:
      "Pâtisserie de petit-déjeuner française classique, feuilletée et beurrée.",
    price: 2.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/pain-au-chocolat.webp",
  },

  // BAKERY
  {
    id: 73,
    name: "Pain d'Orge",
    category: "Boulangerie",
    description: "Pain d'orge marocain consistant et sain.",
    price: 2.5,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 74,
    name: "Batbout",
    category: "Boulangerie",
    description: "Pain plat marocain moelleux cuit à la poêle.",
    price: 2.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 75,
    name: "Brioche au Chocolat",
    category: "Boulangerie",
    description: "Pain sucré moelleux et gonflé rempli de pépites de chocolat.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 76,
    name: "Baguette Classique",
    category: "Boulangerie",
    description:
      "Baguette française traditionnelle croustillante et moelleuse.",
    price: 1.5,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/bread.webp",
  },
  {
    id: 77,
    name: "Pain Classique",
    category: "Boulangerie",
    description: "Pain rond blanc moelleux traditionnel marocain.",
    price: 1.5,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 78,
    name: "Brioche Classique",
    category: "Boulangerie",
    description: "Pain sucré traditionnel beurré, moelleux et gonflé.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 79,
    name: "Pain de Maïs",
    category: "Boulangerie",
    description: "Pain de semoule de maïs marocain rustique et savoureux.",
    price: 2.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },
  {
    id: 80,
    name: "Pain d'Épices",
    category: "Boulangerie",
    description: "Pain épicé français traditionnel avec du miel et de l'anis.",
    price: 24.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 81,
    name: "Baguette Multicéréales",
    category: "Boulangerie",
    description:
      "Baguette croustillante cuite avec un mélange de graines et de céréales saines.",
    price: 4.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 82,
    name: "Baguette aux Olives",
    category: "Boulangerie",
    description:
      "Baguette salée cuite avec des morceaux d'olives noires et vertes.",
    price: 5.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 83,
    name: "Pain aux Olives",
    category: "Boulangerie",
    description: "Pain rond traditionnel moelleux cuit avec des olives salées.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 84,
    name: "Pain de Blé Sans Sel",
    category: "Boulangerie",
    description: "Pain au blé complet sain préparé sans sel ajouté.",
    price: 3.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/bread.webp",
  },
  {
    id: 85,
    name: "Baguette de Semoule",
    category: "Boulangerie",
    description:
      "Baguette faite avec de la farine de semoule pour un croquant rustique.",
    price: 3.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 86,
    name: "Pain de Semoule",
    category: "Boulangerie",
    description: "Pain rond traditionnel marocain fait avec de la semoule.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 87,
    name: "Baguette au Sésame",
    category: "Boulangerie",
    description:
      "Baguette française croustillante fraîchement cuite et garnie de graines de sésame.",
    price: 2.5,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 88,
    name: "Petit Pain au Sésame",
    category: "Boulangerie",
    description:
      "Petit pain moelleux généreusement garni de graines de sésame.",
    price: 3.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },
  {
    id: 89,
    name: "Baguette Viennoise",
    category: "Boulangerie",
    description: "Pain de style viennois, moelleux, légèrement sucré et riche.",
    price: 2.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/bread.webp",
  },
  {
    id: 90,
    name: "Baguette Complète",
    category: "Boulangerie",
    description: "Baguette française au blé complet saine et consistante.",
    price: 3.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/bread.webp",
  },
  {
    id: 91,
    name: "Pain Complet",
    category: "Boulangerie",
    description: "Pain rond traditionnel marocain au blé complet nutritif.",
    price: 2.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/bread.webp",
  },
  {
    id: 92,
    name: "Petit Pain Complet",
    category: "Boulangerie",
    description: "Petit pain au blé complet sain et moelleux.",
    price: 2.5,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/bread.webp",
  },

  // HOT DRINKS
  {
    id: 93,
    name: "Thé Noir (Lipton)",
    category: "Boissons Chaudes",
    description: "Thé noir classique Lipton.",
    price: 12.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/lipton.webp",
  },
  {
    id: 94,
    name: "Chocolat Chaud",
    category: "Boissons Chaudes",
    description: "Lait chaud et réconfortant avec du chocolat riche.",
    price: 12.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/hot-chocolate.webp",
  },
  {
    id: 95,
    name: "Lait Chaud",
    category: "Boissons Chaudes",
    description: "Lait cuit à la vapeur simple et réconfortant.",
    price: 12.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/hot-milk.webp",
  },
  {
    id: 96,
    name: "Verveine",
    category: "Boissons Chaudes",
    description:
      "Tisane faite avec des feuilles de verveine citronnée naturelles.",
    price: 12.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/lemon-verbena-tea.webp",
  },
  {
    id: 97,
    name: "Thé au Lait (Lipton)",
    category: "Boissons Chaudes",
    description: "Thé noir classique Lipton infusé avec du lait.",
    price: 12.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/milk-tea.webp",
  },
  {
    id: 98,
    name: "Lait à la Verveine",
    category: "Boissons Chaudes",
    description: "Lait chaud infusé avec de la verveine citronnée apaisante.",
    price: 12.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-tea.webp",
  },
  {
    id: 99,
    name: "Lait au Sirop",
    category: "Boissons Chaudes",
    description: "Lait froid ou chaud aromatisé avec du sirop sucré.",
    price: 11.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/milk-syrup.webp",
  },
  {
    id: 100,
    name: "Thé à la Menthe Marocain",
    category: "Boissons Chaudes",
    description: "Thé vert traditionnel infusé avec de la menthe fraîche.",
    price: 11.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/moroccan-tea.webp",
  },

  // COLD DRINKS
  {
    id: 101,
    name: "Affogato",
    category: "Boissons Froides",
    description:
      "Une boule de glace à la vanille noyée dans un espresso chaud.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/affogato.webp",
  },
  {
    id: 102,
    name: "Milkshake Banane",
    category: "Boissons Froides",
    description: "Milkshake à la banane doux et crémeux.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 103,
    name: "Smoothie Banane",
    category: "Boissons Froides",
    description: "Smoothie crémeux mixé à la banane.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 104,
    name: "Mojito Bleu",
    category: "Boissons Froides",
    description:
      "Mocktail aux agrumes et à la menthe avec sirop de curaçao bleu.",
    price: 22.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/mojito.webp",
  },
  {
    id: 105,
    name: "Choix de Soda (35cl)",
    category: "Boissons Froides",
    description: "Sélection de boissons gazeuses rafraîchissantes.",
    price: 12.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/soda.webp",
  },
  {
    id: 106,
    name: "Milkshake Chocolat",
    category: "Boissons Froides",
    description: "Milkshake au chocolat riche et crémeux.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 107,
    name: "Cocktail Exotique",
    category: "Boissons Froides",
    description: "Mangue, orange et ananas mixés.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/cocktail.webp",
  },
  {
    id: 108,
    name: "Smoothie Exotique",
    category: "Boissons Froides",
    description: "Mélange rafraîchissant de fruits tropicaux.",
    price: 26.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 109,
    name: "Macchiato Glacé au Caramel",
    category: "Boissons Froides",
    description:
      "Lait et espresso glacés, aromatisés à la vanille et au caramel.",
    price: 21.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/iced-caramel.webp",
  },
  {
    id: 110,
    name: "Café Glacé",
    category: "Boissons Froides",
    description: "Café refroidi sur des glaçons avec un choix de saveur.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/iced-coffee.webp",
  },
  {
    id: 111,
    name: "Frappuccino Glacé",
    category: "Boissons Froides",
    description:
      "Boisson au café glacé mixée avec un choix de vanille, chocolat ou caramel.",
    price: 21.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-frappuccino.webp",
  },
  {
    id: 112,
    name: "Latte Glacé",
    category: "Boissons Froides",
    description: "Espresso et lait refroidi sur des glaçons.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/iced-latte.webp",
  },
  {
    id: 113,
    name: "Moka Glacé",
    category: "Boissons Froides",
    description: "Espresso glacé avec du chocolat et du lait.",
    price: 19.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/iced-mocha.webp",
  },
  {
    id: 114,
    name: "Smoothie Mangue",
    category: "Boissons Froides",
    description: "Smoothie tropical à la mangue mixée.",
    price: 23.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 115,
    name: "Eau Minérale (33cl)",
    category: "Boissons Froides",
    description: "Petite bouteille d'eau minérale plate.",
    price: 5.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/water.webp",
  },
  {
    id: 116,
    name: "Eau Minérale (50cl)",
    category: "Boissons Froides",
    description: "Bouteille moyenne d'eau minérale plate.",
    price: 7.0,
    inStock: true,
    rating: 4.0,
    image: "/images/shop/water.webp",
  },
  {
    id: 117,
    name: "Milkshake Oreo",
    category: "Boissons Froides",
    description: "Milkshake onctueux à la vanille mixé avec des biscuits Oreo.",
    price: 26.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 118,
    name: "Cocktail Oriental",
    category: "Boissons Froides",
    description: "Banane, pomme et orange mixées.",
    price: 20.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cocktail.webp",
  },
  {
    id: 119,
    name: "Mojito Rouge",
    category: "Boissons Froides",
    description:
      "Mocktail fruité aux fruits rouges avec menthe et citron vert.",
    price: 22.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/mojito.webp",
  },
  {
    id: 120,
    name: "Milkshake Fraise",
    category: "Boissons Froides",
    description: "Milkshake doux et crémeux à la fraise.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 121,
    name: "Smoothie Fraise",
    category: "Boissons Froides",
    description: "Fraises fraîches et yaourt mixés.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/smoothie.webp",
  },
  {
    id: 122,
    name: "Cocktail Tropical",
    category: "Boissons Froides",
    description: "Mangue, kiwi et ananas mixés.",
    price: 21.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/cocktail.webp",
  },
  {
    id: 123,
    name: "Milkshake Vanille",
    category: "Boissons Froides",
    description: "Milkshake classique crémeux à la vanille.",
    price: 23.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/milk-shake.webp",
  },
  {
    id: 124,
    name: "Virgin Mojito",
    category: "Boissons Froides",
    description: "Mocktail rafraîchissant au citron vert et à la menthe.",
    price: 19.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/mojito.webp",
  },

  // COFFEES
  {
    id: 125,
    name: "Americano",
    category: "Cafés",
    description: "Espresso dilué avec de l'eau chaude.",
    price: 14.0,
    inStock: true,
    rating: 4.3,
    image: "/images/shop/americano.webp",
  },
  {
    id: 126,
    name: "Cappuccino",
    category: "Cafés",
    description:
      "Espresso surmonté de parts égales de lait cuit à la vapeur et de mousse.",
    price: 15.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/cappuccino.webp",
  },
  {
    id: 127,
    name: "Café au Lait à Part",
    category: "Cafés",
    description: "Espresso servi avec un côté séparé de lait.",
    price: 15.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/coffee-milk.webp",
  },
  {
    id: 128,
    name: "Cortado",
    category: "Cafés",
    description: "À parts égales d'espresso et de lait cuit à la vapeur.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/cortado.webp",
  },
  {
    id: 129,
    name: "Café Crème",
    category: "Cafés",
    description: "Espresso mélangé avec de la crème cuite à la vapeur.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/cream-coffee.webp",
  },
  {
    id: 130,
    name: "Double Espresso",
    category: "Cafés",
    description: "Deux riches shots d'espresso intense.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/double-espresso.webp",
  },
  {
    id: 131,
    name: "Espresso",
    category: "Cafés",
    description: "Shot de café riche et intense.",
    price: 12.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/espresso.webp",
  },
  {
    id: 132,
    name: "Flat White",
    category: "Cafés",
    description: "Espresso avec du lait micro-moussé.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/flat-white.webp",
  },
  {
    id: 133,
    name: "Espresso Illy",
    category: "Cafés",
    description: "Shot d'espresso italien premium Illy.",
    price: 16.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/illy-espresso.webp",
  },
  {
    id: 134,
    name: "Latte Macchiato",
    category: "Cafés",
    description: "Lait cuit à la vapeur marqué par un shot d'espresso.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/latte-macchiato.webp",
  },
  {
    id: 135,
    name: "Moka",
    category: "Cafés",
    description:
      "Espresso combiné avec du chocolat et du lait cuit à la vapeur.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/mocha.webp",
  },
  {
    id: 136,
    name: "Café Nespresso",
    category: "Cafés",
    description: "Café infusé Nespresso classique.",
    price: 15.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/nespresso.webp",
  },
  {
    id: 137,
    name: "Viennois au Chocolat",
    category: "Cafés",
    description: "Chocolat chaud garni de crème fouettée.",
    price: 16.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/viennese-chocolate.webp",
  },

  // JUICES
  {
    id: 138,
    name: "Jus de Pomme",
    category: "Jus",
    description: "Jus de pomme fraîchement pressé.",
    price: 16.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/apple-juice.webp",
  },
  {
    id: 139,
    name: "Jus d'Avocat",
    category: "Jus",
    description: "Jus d'avocat mixé riche et crémeux.",
    price: 18.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/avocado-juice.webp",
  },
  {
    id: 140,
    name: "Jus d'Avocat aux Fruits Secs",
    category: "Jus",
    description: "Jus d'avocat crémeux mixé avec un mélange de fruits secs.",
    price: 23.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/avocado-juice-with-dried-fruits.webp",
  },
  {
    id: 141,
    name: "Jus de Banane",
    category: "Jus",
    description: "Jus de banane fraîchement mixé.",
    price: 16.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/banana-juice.webp",
  },
  {
    id: 142,
    name: "Jus de Mangue",
    category: "Jus",
    description: "Jus de mangue tropical frais.",
    price: 20.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/mango-juice.webp",
  },
  {
    id: 143,
    name: "Jus de Fruits Mixtes au Lait",
    category: "Jus",
    description: "Mélange de fruits mixtes avec du lait.",
    price: 18.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/mixed-fruit-juice-with-milk.webp",
  },
  {
    id: 144,
    name: "Jus de Fruits Mixtes à l'Orange",
    category: "Jus",
    description: "Mélange de fruits mixtes avec du jus d'orange.",
    price: 23.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/mixed-fruit-juice-with-orange.webp",
  },
  {
    id: 145,
    name: "Jus d'Orange",
    category: "Jus",
    description: "Jus d'orange fraîchement pressé.",
    price: 16.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/orange-juice.webp",
  },
  {
    id: 146,
    name: "Jus d'Ananas",
    category: "Jus",
    description: "Jus d'ananas frais et sucré.",
    price: 23.0,
    inStock: true,
    rating: 4.6,
    image: "/images/shop/pineapple-juice.webp",
  },
  {
    id: 147,
    name: "Jus de Fraise",
    category: "Jus",
    description: "Jus de fraise fraîchement mixé.",
    price: 18.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/strawberry-juice.webp",
  },

  // EXTRAS
  {
    id: 148,
    name: "Amlou aux Amandes",
    category: "Suppléments",
    description:
      "Amlou premium fait avec des amandes extra grillées. Servi avec du pain.",
    price: 12.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/almond.webp",
  },
  {
    id: 149,
    name: "Amlou à l'Huile d'Argan",
    category: "Suppléments",
    description:
      "Trempette traditionnelle aux amandes, miel et huile d'argan. Servie avec du pain.",
    price: 8.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/argan.webp",
  },
  {
    id: 150,
    name: "Olives Noires et Vertes",
    category: "Suppléments",
    description: "Olives mixtes marinées. Servies avec du pain.",
    price: 5.0,
    inStock: true,
    rating: 4.5,
    image: "/images/shop/olive.webp",
  },
  {
    id: 151,
    name: "Fromage à Tartiner",
    category: "Suppléments",
    description: "Portion de fromage à tartiner. Servi avec du pain.",
    price: 3.0,
    inStock: true,
    rating: 4.2,
    image: "/images/shop/cheese.webp",
  },
  {
    id: 152,
    name: "Fromage Frais (Jben)",
    category: "Suppléments",
    description:
      "Portion de fromage frais marocain traditionnel. Servi avec du pain.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/fresh-cheese.webp",
  },
  {
    id: 153,
    name: "Miel",
    category: "Suppléments",
    description: "Portion de pur miel. Servi avec du pain.",
    price: 6.0,
    inStock: true,
    rating: 4.7,
    image: "/images/shop/honey.webp",
  },
  {
    id: 154,
    name: "Confiture",
    category: "Suppléments",
    description: "Portion de confiture de fruits. Servie avec du pain.",
    price: 6.0,
    inStock: true,
    rating: 4.4,
    image: "/images/shop/jam.webp",
  },
  {
    id: 155,
    name: "Nutella",
    category: "Suppléments",
    description:
      "Portion de riche pâte à tartiner noisettes cacao. Servie avec du pain.",
    price: 10.0,
    inStock: true,
    rating: 4.9,
    image: "/images/shop/nutella.webp",
  },
  {
    id: 156,
    name: "Huile d'Olive",
    category: "Suppléments",
    description:
      "Portion d'huile d'olive extra vierge de haute qualité. Servie avec du pain.",
    price: 8.0,
    inStock: true,
    rating: 4.8,
    image: "/images/shop/olive-oil.webp",
  },
];